---
permalink: protect-scsql/concept_snapcenter_plug_in_for_microsoft_sql_server_features.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for Microsoft SQL Server 
summary: SQL Server용 플러그인은 Windows 호스트의 Microsoft SQL Server와 통합되고 스토리지 시스템의 NetApp Snapshot 기술과 통합됩니다.  SQL Server용 플러그인을 사용하려면 SnapCenter 인터페이스를 사용합니다. 
---
= Microsoft SQL Server용 SnapCenter 플러그인 기능
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SQL Server용 플러그인은 Windows 호스트의 Microsoft SQL Server와 통합되고 스토리지 시스템의 NetApp Snapshot 기술과 통합됩니다.  SQL Server용 플러그인을 사용하려면 SnapCenter 인터페이스를 사용합니다.

SQL Server용 플러그인에는 다음과 같은 주요 기능이 포함되어 있습니다.

* * SnapCenter 가 지원하는 통합 그래픽 사용자 인터페이스*
+
SnapCenter 인터페이스는 플러그인과 환경 전반에 걸쳐 표준화와 일관성을 제공합니다.  SnapCenter 인터페이스를 사용하면 플러그인 전반에 걸쳐 일관된 백업 및 복원 프로세스를 완료하고, 중앙 집중식 보고를 사용하고, 한눈에 볼 수 있는 대시보드 보기를 사용하고, 역할 기반 액세스 제어(RBAC)를 설정하고, 모든 플러그인에서 작업을 모니터링할 수 있습니다.  SnapCenter 백업 및 복제 작업을 지원하기 위해 중앙 집중식 스케줄링 및 정책 관리 기능도 제공합니다.

* *자동화된 중앙 관리*
+
정기적인 SQL Server 백업을 예약하고, 정책 기반 백업 보존을 구성하고, 특정 시점 및 최신 복원 작업을 설정할 수 있습니다.  SnapCenter 구성하여 이메일 알림을 보내면 SQL Server 환경을 사전에 모니터링할 수도 있습니다.

* *중단 없는 NetApp 스냅샷 기술*
+
SQL Server용 플러그인은 Microsoft Windows용 NetApp SnapCenter 플러그인과 함께 NetApp Snapshot 기술을 사용합니다.  이를 통해 몇 초 안에 데이터베이스를 백업하고 SQL Server를 오프라인으로 전환하지 않고도 빠르게 복원할 수 있습니다.  스냅샷은 최소한의 저장 공간을 차지합니다.



이러한 주요 기능 외에도 SQL Server 플러그인은 다음과 같은 이점을 제공합니다.

* 백업, 복원, 복제 및 검증 워크플로 지원
* RBAC 지원 보안 및 중앙 집중식 역할 위임
* NetApp FlexClone 기술을 사용하여 테스트 또는 데이터 추출을 위한 프로덕션 데이터베이스의 공간 효율적인 특정 시점 복사본 생성
+
복제본을 보관하는 스토리지 시스템에는 FlexClone 라이선스가 필요합니다.

* 중단 없는 자동 백업 검증
* 여러 서버에서 동시에 여러 백업을 실행할 수 있는 기능
* 백업, 확인, 복원 및 복제 작업 스크립팅을 위한 PowerShell cmdlet
* SQL Server에서 AlwaysOn 가용성 그룹(AG)을 지원하여 AG 설정, 백업 및 복원 작업을 가속화합니다.
* SQL Server 2014의 일부인 메모리 내 데이터베이스 및 버퍼 풀 확장(BPE)
* LUN 및 가상 머신 디스크(VMDK) 백업 지원
* 물리적 및 가상화된 인프라 지원
* NFS 및 VMFS를 통한 iSCSI, 파이버 채널, FCoE, 원시 장치 매핑(RDM), VMDK 지원
+

NOTE: NAS 볼륨에는 스토리지 가상 머신(SVM)에 기본 내보내기 정책이 있어야 합니다.

* SQL Server 독립 실행형 데이터베이스에서 FileStream 및 파일 그룹을 지원합니다.
* Windows Server 2022에서 NVMe(Non-Volatile Memory Express) 지원
+
** TCP/IP를 통한 NVMe에서 생성된 VMDK 레이아웃에 대한 백업, 복원, 복제 및 검증 워크플로.
** ESX 8.0 업데이트 2부터 NVMe 펌웨어 버전 1.3을 지원하고 가상 하드웨어 버전 21이 필요합니다.
** Windows Server 장애 조치(Failover) 클러스터링(WSFC)은 TCP/IP를 통한 NVMe의 VMDK를 통한 애플리케이션에서 지원되지 않습니다.


* 사이트 전체에 장애가 발생해도 비즈니스 서비스가 계속 운영될 수 있도록 하는 SnapMirror Active Sync(처음에는 SnapMirror Business Continuity[SM-BC]로 출시)를 지원하며, 보조 복사본을 사용하여 애플리케이션이 투명하게 장애 조치되도록 지원합니다.  SnapMirror Active Sync를 사용하면 장애 조치를 트리거하는 데 수동 개입이나 추가 스크립팅이 필요하지 않습니다.

