---
permalink: protect-scsql/concept_prerequisites_for_using_snapcenter_plug_in_for_microsoft_sql_server.html 
sidebar: sidebar 
keywords: credential 
summary: SQL Server용 플러그인을 사용하기 전에 SnapCenter 관리자는 SnapCenter Server를 설치 및 구성하고 필수 작업을 수행해야 합니다. 
---
= Microsoft SQL Server용 SnapCenter 플러그인을 사용하기 위한 전제 조건
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SQL Server용 플러그인을 사용하기 전에 SnapCenter 관리자는 SnapCenter Server를 설치 및 구성하고 필수 작업을 수행해야 합니다.

* SnapCenter 서버를 설치하고 구성합니다.
* SnapCenter 에 로그인하세요.
* 스토리지 시스템 연결을 추가하거나 할당하고 자격 증명을 생성하여 SnapCenter 환경을 구성합니다.
+

NOTE: SnapCenter 서로 다른 클러스터에서 동일한 이름을 가진 여러 SVM을 지원하지 않습니다.  SnapCenter 가 지원하는 각 SVM에는 고유한 이름이 있어야 합니다.

* 호스트를 추가하고, 플러그인을 설치하고, 리소스를 검색(새로 고침)하고, 플러그인을 구성합니다.
* Invoke-SmConfigureResources를 실행하여 기존 Microsoft SQL Server 데이터베이스를 로컬 디스크에서 NetApp LUN으로 이동하거나 그 반대로 이동합니다.
+
cmdlet을 실행하기 위한 정보는 다음을 참조하세요. https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter 소프트웨어 Cmdlet 참조 가이드"]

* VMware RDM LUN이나 VMDK에 있는 SQL 데이터베이스를 보호하기 위해 SnapCenter Server를 사용하는 경우 SnapCenter Plug-in for VMware vSphere 배포하고 SnapCenter 에 플러그인을 등록해야 합니다.  SnapCenter Plug-in for VMware vSphere 대한 자세한 내용은 설명서를 참조하세요.
+
https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/["SnapCenter Plug-in for VMware vSphere 설명서"]

* Microsoft Windows용 SnapCenter 플러그인을 사용하여 호스트 측 스토리지 프로비저닝을 수행합니다.
* 백업 복제가 필요한 경우 SnapMirror 와 SnapVault 관계를 설정합니다.


자세한 내용은 SnapCenter 설치 정보를 참조하세요.

SnapCenter 4.1.1 사용자의 경우 SnapCenter Plug-in for VMware vSphere 설명서에는 가상화된 데이터베이스와 파일 시스템을 보호하는 방법에 대한 정보가 있습니다.  SnapCenter 4.2.x 사용자, NetApp Data Broker 1.0 및 1.0.1의 경우, Linux 기반 NetApp Data Broker 가상 어플라이언스(Open Virtual Appliance 형식)에서 제공하는 SnapCenter Plug-in for VMware vSphere 사용하여 가상화된 데이터베이스와 파일 시스템을 보호하는 방법에 대한 정보가 설명서에 나와 있습니다.  SnapCenter 4.3.x 사용자의 경우, SnapCenter Plug-in for VMware vSphere 설명서에는 Linux 기반 SnapCenter Plug-in for VMware vSphere (Open Virtual Appliance 형식)을 사용하여 가상화된 데이터베이스와 파일 시스템을 보호하는 방법에 대한 정보가 있습니다.

https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/["SnapCenter Plug-in for VMware vSphere 설명서"]
