---
permalink: protect-scsql/concept_what_you_can_do_with_the_snapcenter_plug_in_for_microsoft_sql_server.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for Microsoft SQL Server 
summary: Microsoft SQL Server용 SnapCenter 플러그인이 사용자 환경에 설치되면 SnapCenter 사용하여 SQL Server 데이터베이스를 백업, 복원 및 복제할 수 있습니다. 
---
= Microsoft SQL Server용 SnapCenter 플러그인으로 할 수 있는 작업
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Microsoft SQL Server용 SnapCenter 플러그인이 사용자 환경에 설치되면 SnapCenter 사용하여 SQL Server 데이터베이스를 백업, 복원 및 복제할 수 있습니다.

SQL Server 데이터베이스와 데이터베이스 리소스의 백업 작업, 복원 작업 및 복제 작업을 지원하는 다음 작업을 수행할 수 있습니다.

* SQL Server 데이터베이스 및 관련 트랜잭션 로그 백업
+
마스터 및 msdb 시스템 데이터베이스에 대한 로그 백업을 생성할 수 없습니다.  하지만 모델 시스템 데이터베이스에 대한 로그 백업을 생성할 수 있습니다.

* 데이터베이스 리소스 복원
+
** 마스터 시스템 데이터베이스, msdb 시스템 데이터베이스, 모델 시스템 데이터베이스를 복원할 수 있습니다.
** 여러 개의 데이터베이스, 인스턴스 및 가용성 그룹을 복원할 수 없습니다.
** 시스템 데이터베이스를 대체 경로로 복원할 수 없습니다.


* 프로덕션 데이터베이스의 특정 시점 복제본 생성
+
tempdb 시스템 데이터베이스에서는 백업, 복원, 복제 및 복제 수명 주기 작업을 수행할 수 없습니다.

* 백업 작업을 즉시 확인하거나 나중에 확인을 연기합니다.
+
SQL Server 시스템 데이터베이스 검증이 지원되지 않습니다.  SnapCenter 데이터베이스를 복제하여 검증 작업을 수행합니다.  SnapCenter SQL Server 시스템 데이터베이스를 복제할 수 없으므로 이러한 데이터베이스의 검증은 지원되지 않습니다.

* 백업 작업 및 복제 작업 예약
* 백업 작업, 복원 작업 및 복제 작업 모니터링



NOTE: SQL Server용 플러그인은 SMB 공유에서 SQL Server 데이터베이스의 백업 및 복구를 지원하지 않습니다.
