---
permalink: protect-scsql/concept_snapcenter_plug_in_for_microsoft_sql_server_overview.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for Microsoft SQL Server 
summary: Microsoft SQL Server용 SnapCenter 플러그인은 Microsoft SQL Server 데이터베이스의 애플리케이션 인식 데이터 보호 관리를 지원하는 NetApp SnapCenter 소프트웨어의 호스트 측 구성 요소입니다.  SQL Server용 플러그인은 SnapCenter 환경에서 SQL Server 데이터베이스 백업, 검증, 복원 및 복제 작업을 자동화합니다. 
---
= Microsoft SQL Server용 SnapCenter 플러그인 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Microsoft SQL Server용 SnapCenter 플러그인은 Microsoft SQL Server 데이터베이스의 애플리케이션 인식 데이터 보호 관리를 지원하는 NetApp SnapCenter 소프트웨어의 호스트 측 구성 요소입니다.  SQL Server용 플러그인은 SnapCenter 환경에서 SQL Server 데이터베이스 백업, 검증, 복원 및 복제 작업을 자동화합니다.

SQL Server용 플러그인을 설치하면 NetApp SnapMirror 기술과 함께 SnapCenter 사용하여 다른 볼륨에 백업 세트의 미러 복사본을 만들고 NetApp SnapVault 기술을 사용하여 표준 준수 또는 보관 목적으로 디스크 간 백업 복제를 수행할 수 있습니다.

* SnapCenter 환경에서 Microsoft SQL Server 데이터베이스에 대한 애플리케이션 인식 백업, 복원 및 복제 작업을 자동화합니다.
* SnapCenter Plug-in for VMware vSphere 배포하고 SnapCenter 에 플러그인을 등록하면 VMDK 및 RDM(원시 장치 매핑) LUN에서 Microsoft SQL Server 데이터베이스를 지원합니다.
* SMB 공유 프로비저닝만 지원합니다.  SMB 공유에서 SQL Server 데이터베이스를 백업하는 기능은 제공되지 않습니다.
* Microsoft SQL Server용 SnapManager 에서 SnapCenter 로 백업을 가져오는 기능을 지원합니다.

