---
permalink: protect-scsql/concept_type_of_backups_supported.html 
sidebar: sidebar 
keywords: Type of backups 
summary: 'SnapCenter 사용하여 SQL Server 시스템 및 사용자 데이터베이스를 백업하려면 데이터베이스, SQL Server 인스턴스, 가용성 그룹(AG) 등의 리소스 유형을 선택해야 합니다.  스냅샷 기술은 리소스가 있는 볼륨의 온라인, 읽기 전용 복사본을 만드는 데 활용됩니다.' 
---
= 지원되는 백업 유형
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 사용하여 SQL Server 시스템 및 사용자 데이터베이스를 백업하려면 데이터베이스, SQL Server 인스턴스, 가용성 그룹(AG) 등의 리소스 유형을 선택해야 합니다.  스냅샷 기술은 리소스가 있는 볼륨의 온라인, 읽기 전용 복사본을 만드는 데 활용됩니다.

복사 전용 옵션을 선택하면 SQL Server가 트랜잭션 로그를 잘라내지 않도록 지정할 수 있습니다.  다른 백업 애플리케이션과 함께 SQL Server를 관리하는 경우 이 옵션을 사용해야 합니다.  거래 로그를 그대로 유지하면 모든 백업 애플리케이션이 시스템 데이터베이스를 복원할 수 있습니다.  복사 전용 백업은 예약된 백업 순서와 무관하며, 데이터베이스의 백업 및 복원 절차에 영향을 미치지 않습니다.

|===
| 백업 유형 | 설명 | 백업 유형이 있는 복사 전용 옵션 


 a| 
전체 백업 및 로그 백업
 a| 
시스템 데이터베이스를 백업하고 트랜잭션 로그를 잘라냅니다.

SQL Server는 이미 데이터베이스에 커밋된 항목을 제거하여 트랜잭션 로그를 잘라냅니다.

전체 백업이 완료되면 이 옵션은 트랜잭션 정보를 캡처하는 트랜잭션 로그를 생성합니다.  일반적으로 이 옵션을 선택하는 것이 좋습니다.  하지만 백업 시간이 짧다면 전체 백업과 함께 트랜잭션 로그 백업을 실행하지 않도록 선택할 수 있습니다.

마스터 및 msdb 시스템 데이터베이스에 대한 로그 백업을 생성할 수 없습니다.  하지만 모델 시스템 데이터베이스에 대한 로그 백업을 생성할 수 있습니다.
 a| 
로그를 잘라내지 않고 시스템 데이터베이스 파일과 트랜잭션 로그를 백업합니다.

복사 전용 백업은 차등 기반이나 차등 백업으로 사용할 수 없으며, 차등 기반에 영향을 미치지 않습니다.  복사 전용 전체 백업을 복원하는 것은 다른 전체 백업을 복원하는 것과 같습니다.



 a| 
전체 데이터베이스 백업
 a| 
시스템 데이터베이스 파일을 백업합니다.

마스터, 모델, msdb 시스템 데이터베이스에 대한 전체 데이터베이스 백업을 생성할 수 있습니다.
 a| 
시스템 데이터베이스 파일을 백업합니다.



 a| 
트랜잭션 로그 백업
 a| 
가장 최근의 트랜잭션 로그가 백업된 이후 커밋된 트랜잭션만 복사하여 잘린 트랜잭션 로그를 백업합니다.

전체 데이터베이스 백업과 함께 자주 트랜잭션 로그 백업을 예약하면 세분화된 복구 지점을 선택할 수 있습니다.
 a| 
트랜잭션 로그를 잘라내지 않고 백업합니다.

이 백업 유형은 정기적인 로그 백업의 순서에 영향을 미치지 않습니다.  복사 전용 로그 백업은 온라인 복원 작업을 수행하는 데 유용합니다.

|===