---
permalink: protect-scsql/task-install-snapcenter-server-for-sql-server.html 
sidebar: sidebar 
keywords: credentials 
summary: Microsoft SQL Server용 SnapCenter Server를 설치하는 방법에 대한 지침을 제공합니다. 
---
= Microsoft SQL Server용 SnapCenter 서버 설치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Microsoft SQL Server용 SnapCenter Server를 설치하기 위한 간략한 설치 지침을 제공합니다.



== 1단계: SnapCenter 서버 다운로드 및 설치

. SnapCenter 서버 설치 패키지를 다운로드하세요. https://mysupport.netapp.com/site/products/all/details/snapcenter/downloads-tab["NetApp 지원 사이트"^] 그런 다음 exe를 두 번 클릭합니다.
+
설치를 시작하면 모든 사전 검사가 수행되고 최소 요구 사항을 충족하지 못하면 해당 오류나 경고 메시지가 표시됩니다.  경고 메시지를 무시하고 설치를 진행할 수 있습니다. 그러나 오류는 수정되어야 합니다.

. SnapCenter 서버 설치에 필요한 미리 채워진 값을 검토하고 필요한 경우 수정합니다.
+
MySQL 서버 저장소 데이터베이스에 대한 비밀번호를 지정할 필요는 없습니다.  SnapCenter 서버를 설치하는 동안 비밀번호가 자동으로 생성됩니다.

+

NOTE: 사용자 지정 설치 경로에서는 특수 문자 "%"가 지원되지 않습니다.  경로에 "%"를 포함하면 설치가 실패합니다.

. *지금 설치*를 클릭하세요.




== 2단계: SnapCenter 에 로그인

. 호스트 데스크톱의 바로가기나 설치 프로그램에서 제공하는 URL( SnapCenter 서버가 설치된 기본 포트 8146의 경우 _\https://server:8146_)에서 SnapCenter 실행합니다.
. 자격 증명을 입력하세요.
+
기본 제공 도메인 관리자 사용자 이름 형식의 경우 _NetBIOS\<사용자 이름>_ 또는 _<사용자 이름>@<도메인>_ 또는 _<도메인 FQDN>\<사용자 이름>_을 사용합니다.

+
기본 로컬 관리자 사용자 이름 형식의 경우 _<username>_을 사용합니다.

. *로그인*을 클릭하세요.




== 3단계: SnapCenter Standard 컨트롤러 기반 라이선스 추가

. ONTAP 명령줄을 사용하여 컨트롤러에 로그인하고 다음을 입력합니다.
+
`system license add -license-code <license_key>`

. 라이센스를 확인하세요:
+
`license show`





== 4단계: 스토리지 시스템 연결 설정

. 왼쪽 창에서 *스토리지 시스템 > 새로 만들기*를 클릭합니다.
. 스토리지 시스템 추가 페이지에서 다음을 수행합니다.
+
.. 저장 시스템의 이름이나 IP 주소를 입력하세요.
.. 스토리지 시스템에 액세스하는 데 사용되는 자격 증명을 입력하세요.
.. 이벤트 관리 시스템(EMS) 및 AutoSupport 활성화하려면 확인란을 선택하세요.


. 플랫폼, 프로토콜, 포트 및 시간 초과에 할당된 기본값을 수정하려면 *추가 옵션*을 클릭하세요.
. *제출*을 클릭하세요.

