---
permalink: protect-scsql/task_perform_clone_lifecycle_management.html 
sidebar: sidebar 
keywords:  
summary: SnapCenter 사용하면 리소스 그룹이나 데이터베이스에서 복제본을 만들 수 있습니다.  주문형 복제를 수행하거나 리소스 그룹이나 데이터베이스의 반복 복제 작업을 예약할 수 있습니다.  백업을 주기적으로 복제하면 복제본을 사용하여 애플리케이션을 개발하고, 데이터를 채우거나, 데이터를 복구할 수 있습니다. 
---
= 복제 수명 주기 수행
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 사용하면 리소스 그룹이나 데이터베이스에서 복제본을 만들 수 있습니다.  주문형 복제를 수행하거나 리소스 그룹이나 데이터베이스의 반복 복제 작업을 예약할 수 있습니다.  백업을 주기적으로 복제하면 복제본을 사용하여 애플리케이션을 개발하고, 데이터를 채우거나, 데이터를 복구할 수 있습니다.

SnapCenter 사용하면 여러 서버에서 동시에 여러 복제 작업을 실행하도록 예약할 수 있습니다.

.시작하기 전에
* 독립 실행형 데이터베이스 인스턴스에 복제하는 동안 마운트 지점 경로가 존재하고 전용 디스크인지 확인하세요.
* FCI(장애 조치 클러스터 인스턴스)에 복제하는 동안 마운트 지점이 있는지, 공유 디스크인지, 경로와 FCI가 동일한 SQL 리소스 그룹에 속해야 하는지 확인하세요.
* 소스 데이터베이스 또는 대상 인스턴스가 클러스터 공유 볼륨(CSV)에 있는 경우 복제된 데이터베이스는 CSV에 있습니다.



NOTE: 가상 환경(VMDK/RDM)의 경우 마운트 지점이 전용 디스크인지 확인하세요.

.이 작업에 관하여
* SCRIPTS_PATH는 플러그인 호스트의 SMCoreServiceHost.exe.Config 파일에 있는 PredefinedWindowsScriptsDirectory 키를 사용하여 정의됩니다.
+
필요한 경우 이 경로를 변경하고 SMcore 서비스를 다시 시작할 수 있습니다.  보안을 위해 기본 경로를 사용하는 것이 좋습니다.

+
키 값은 API를 통해 swagger에서 표시될 수 있습니다: API /4.7/configsettings

+
GET API를 사용하여 키 값을 표시할 수 있습니다.  SET API는 지원되지 않습니다.

* 복제 수명 주기 마법사 페이지의 대부분 필드는 설명이 필요 없습니다.  다음 정보는 귀하에게 지침이 필요할 수 있는 분야에 대한 설명입니다.
* ONTAP 9.12.1 이하 버전의 경우 스냅샷 잠금 기간을 지정하면 변조 방지 스냅샷에서 생성된 복제본은 SnapLock 만료 시간을 상속받습니다. 스토리지 관리자는 SnapLock 만료 시간 이후에 복제본을 수동으로 정리해야 합니다.


.단계
. 왼쪽 탐색 창에서 *리소스*를 클릭한 다음 목록에서 적절한 플러그인을 선택합니다.
. 리소스 페이지에서 *보기* 목록에서 *데이터베이스* 또는 *리소스 그룹*을 선택합니다.
. 리소스 그룹이나 데이터베이스를 선택한 다음 *라이프사이클 복제*를 클릭합니다.
. 옵션 페이지에서 다음 작업을 수행합니다.
+
|===
| 이 분야에서는... | 이렇게 하세요... 


 a| 
복제 작업 이름
 a| 
복제 수명 주기 작업을 모니터링하고 수정하는 데 도움이 되는 복제 수명 주기 작업 이름을 지정합니다.



 a| 
복제 서버
 a| 
복제본을 배치할 호스트를 선택하세요.



 a| 
인스턴스 복제
 a| 
데이터베이스를 복제할 복제 인스턴스를 선택합니다.  이 SQL 인스턴스는 지정된 복제 서버에 있어야 합니다.



 a| 
클론 접미사
 a| 
복제본임을 식별하기 위해 복제본 데이터베이스에 추가될 접미사를 입력하세요.  복제 리소스 그룹을 만드는 데 사용되는 각 SQL 인스턴스에는 고유한 데이터베이스 이름이 있어야 합니다.  예를 들어, 복제 리소스 그룹에 SQL 인스턴스 "inst1"의 소스 데이터베이스 "db1"이 포함되어 있고, "db1"이 "inst1"에 복제된 경우, 복제 데이터베이스 이름은 "db1__clone"이어야 합니다.  "__clone`"은 데이터베이스가 동일한 인스턴스에 복제되므로 필수 사용자 정의 접미사입니다.  "`db1`"이 SQL 인스턴스 "`inst2`"에 복제되면 복제 데이터베이스 이름은 "`db1`"(접미사는 선택 사항)로 유지될 수 있습니다. 데이터베이스가 다른 인스턴스에 복제되기 때문입니다.



 a| 
경로 아래에 마운트 지점 자동 할당 또는 볼륨 마운트 지점 자동 할당
 a| 
경로 아래에 마운트 지점이나 볼륨 마운트 지점을 자동으로 할당할지 여부를 선택합니다.  경로 아래에 볼륨 마운트 지점을 자동으로 할당하도록 선택하면 특정 디렉터리를 제공할 수 있습니다.  해당 디렉토리 내에 마운트 지점이 생성됩니다.  이 옵션을 선택하기 전에 디렉토리가 비어 있는지 확인해야 합니다.  디렉토리에 데이터베이스가 있는 경우 마운트 작업 후 데이터베이스는 유효하지 않은 상태가 됩니다.

|===
. 위치 페이지에서 복제본을 만들 저장 위치를 선택합니다.
. 스크립트 페이지에서 복제 작업 전이나 후에 실행해야 하는 프리스크립트나 포스트스크립트의 경로와 인수를 각각 입력합니다.
+
예를 들어, SNMP 트랩을 업데이트하고, 알림을 자동화하고, 로그를 보내는 등의 작업을 수행하는 스크립트를 실행할 수 있습니다.

+

NOTE: prescripts 또는 postscripts 경로에는 드라이브나 공유가 포함되어서는 안 됩니다.  경로는 SCRIPTS_PATH를 기준으로 해야 합니다.

+
기본 스크립트 시간 초과는 60초입니다.

. 일정 페이지에서 다음 작업 중 하나를 수행합니다.
+
** 복제 작업을 즉시 실행하려면 *지금 실행*을 선택하세요.
** 복제 작업이 얼마나 자주 발생해야 하는지, 복제 일정을 언제 시작해야 하는지, 복제 작업이 어느 요일에 발생해야 하는지, 일정이 언제 만료되어야 하는지, 일정이 만료된 후 복제본을 삭제해야 하는지 여부를 결정하려면 *일정 구성*을 선택합니다.


. 알림 페이지의 *이메일 환경 설정* 드롭다운 목록에서 이메일을 보낼 시나리오를 선택합니다.
+
또한 발신자와 수신자의 이메일 주소와 이메일 제목을 지정해야 합니다.  수행된 복제 작업의 보고서를 첨부하려면 *작업 보고서 첨부*를 선택하세요.

+

NOTE: 이메일 알림을 받으려면 GUI나 PowerShell 명령 Set-SmSmtpServer를 사용하여 SMTP 서버 세부 정보를 지정해야 합니다.

+
EMS의 경우 다음을 참조하세요. https://docs.netapp.com/us-en/snapcenter/admin/concept_manage_ems_data_collection.html["EMS 데이터 수집 관리"]

. 요약을 검토한 후 *마침*을 클릭하세요.


*모니터* > *작업* 페이지를 사용하여 복제 프로세스를 모니터링해야 합니다.
