---
permalink: protect-scsql/task_create_backup_policies_for_sql_server_databases.html 
sidebar: sidebar 
keywords: backup policy 
summary: SnapCenter 사용하여 SQL Server 리소스를 백업하기 전에 리소스 또는 리소스 그룹에 대한 백업 정책을 만들거나, 리소스 그룹을 만들거나 단일 리소스를 백업할 때 백업 정책을 만들 수 있습니다. 
---
= SQL Server 데이터베이스에 대한 백업 정책 만들기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 사용하여 SQL Server 리소스를 백업하기 전에 리소스 또는 리소스 그룹에 대한 백업 정책을 만들거나, 리소스 그룹을 만들거나 단일 리소스를 백업할 때 백업 정책을 만들 수 있습니다.

.시작하기 전에
* 데이터 보호 전략을 정의해야 합니다.
* SnapCenter 설치, 호스트 추가, 리소스 식별, 스토리지 시스템 연결 생성 등의 작업을 완료하여 데이터 보호를 준비했어야 합니다.
* 로그 백업을 위해 호스트 로그 디렉토리를 구성해야 합니다.
* SQL Server 리소스를 새로 고침(검색)했어야 합니다.
* 스냅샷을 미러 또는 볼트에 복제하는 경우 SnapCenter 관리자가 소스 볼륨과 대상 볼륨 모두에 대한 스토리지 가상 머신(SVM)을 할당해야 합니다.
+
관리자가 사용자에게 리소스를 할당하는 방법에 대한 자세한 내용은 SnapCenter 설치 정보를 참조하세요.

* PowerShell 스크립트를 prescripts 및 postscripts로 실행하려면 web.config 파일에서 usePowershellProcessforScripts 매개변수 값을 true로 설정해야 합니다.
+
기본값은 false입니다.

* SnapMirror Active Sync의 특정 전제 조건과 제한 사항을 검토하세요. 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["SnapMirror Active Sync에 대한 개체 제한"] .


.이 작업에 관하여
* 백업 정책은 백업을 관리하고 보관하는 방법과 리소스 또는 리소스 그룹을 백업하는 빈도를 제어하는 일련의 규칙입니다.  또한 복제 및 스크립트 설정을 지정할 수 있습니다.  정책에서 옵션을 지정하면 다른 리소스 그룹에 정책을 재사용할 때 시간을 절약할 수 있습니다.
+
SCRIPTS_PATH는 플러그인 호스트의 SMCoreServiceHost.exe.Config 파일에 있는 PredefinedWindowsScriptsDirectory 키를 사용하여 정의됩니다.

+
필요한 경우 이 경로를 변경하고 SMcore 서비스를 다시 시작할 수 있습니다.  보안을 위해 기본 경로를 사용하는 것이 좋습니다.

+
키 값은 API를 통해 swagger에서 표시될 수 있습니다: API /4.7/configsettings

+
GET API를 사용하여 키 값을 표시할 수 있습니다.  SET API는 지원되지 않습니다.

* SnapLock
+
** '특정 기간 동안 백업 사본을 보관합니다' 옵션을 선택한 경우 SnapLock 보관 기간은 언급된 보관 기간보다 짧거나 같아야 합니다.
+
스냅샷 잠금 기간을 지정하면 보존 기간이 만료될 때까지 스냅샷이 삭제되지 않습니다. 이를 통해 정책에 지정된 수보다 더 많은 수의 스냅샷을 보존할 수 있습니다.

+
ONTAP 9.12.1 이하 버전의 경우 복원의 일부로 SnapLock Vault 스냅샷에서 생성된 복제본은 SnapLock Vault 만료 시간을 상속받습니다. 스토리지 관리자는 SnapLock 만료 시간 이후에 복제본을 수동으로 정리해야 합니다.







== 1단계: 정책 이름 만들기

. 왼쪽 탐색 창에서 *설정*을 선택합니다.
. 설정 페이지에서 *정책*을 선택합니다.
. *새로 만들기*를 선택하세요.
. *이름* 페이지에서 정책 이름과 세부 정보를 입력합니다.




== 2단계: 정책 옵션 구성

. 정책 유형 페이지에서 다음 단계를 수행합니다.
+
.. 저장 유형을 선택하세요.
.. 보험 범위를 선택하세요.
+
[role="tabbed-block"]
====
.전체 백업 및 로그 백업
--
데이터베이스 파일과 트랜잭션 로그를 백업하고 트랜잭션 로그를 잘라냅니다.

... *전체 백업 및 로그 백업*을 선택하세요.
... 각 스냅샷에 대해 백업해야 하는 데이터베이스의 최대 개수를 입력하세요.
+

NOTE: 여러 백업 작업을 동시에 실행하려면 이 값을 늘려야 합니다.



--
.전체 백업
--
데이터베이스 파일을 백업하세요.

... *전체 백업*을 선택하세요.
... 각 스냅샷에 대해 백업해야 하는 데이터베이스의 최대 개수를 입력하세요.  기본값은 100입니다
+

NOTE: 여러 백업 작업을 동시에 실행하려면 이 값을 늘려야 합니다.



--
.로그 백업
--
... 거래 로그를 백업하세요.
... *로그 백업*을 선택하세요.


--
.복사 전용 백업
--
... 다른 백업 애플리케이션을 사용하여 리소스를 백업하는 경우 *백업만 복사*를 선택하세요.


트랜잭션 로그를 그대로 유지하면 모든 백업 애플리케이션이 데이터베이스를 복원할 수 있습니다.  일반적으로 다른 상황에서는 복사 전용 옵션을 사용해서는 안 됩니다.


NOTE: Microsoft SQL에서는 보조 저장소에 대한 *전체 백업 및 로그 백업* 옵션과 함께 *복사 전용 백업* 옵션을 지원하지 않습니다.

--
====






== 3단계: 가용성 그룹 설정 구성

. 가용성 그룹 설정 섹션에서 다음 작업을 수행합니다.
+
.. 선호하는 백업 복제본에만 백업합니다.
+
선호하는 백업 복제본에만 백업하려면 이 옵션을 선택하세요.  선호하는 백업 복제본은 SQL Server에서 AG에 대해 구성된 백업 기본 설정에 따라 결정됩니다.

.. 백업할 복제본을 선택하세요.
+
백업을 위해 기본 AG 복제본이나 보조 AG 복제본을 선택합니다.

.. 백업 우선순위 선택(최소 및 최대 백업 우선순위)
+
백업할 AG 복제본을 결정하는 최소 백업 우선 순위 번호와 최대 백업 우선 순위 번호를 지정합니다.  예를 들어, 최소 우선순위를 10으로, 최대 우선순위를 50으로 지정할 수 있습니다.  이 경우, 우선순위가 10보다 크고 50보다 작은 모든 AG 복제본이 백업 대상으로 고려됩니다.

+
기본적으로 최소 우선순위는 1이고 최대 우선순위는 100입니다.



+

NOTE: 클러스터 구성에서 백업은 정책에 설정된 보존 설정에 따라 클러스터의 각 노드에 보존됩니다.  AG의 소유자 노드가 변경되면 보존 설정에 따라 백업이 수행되고 이전 소유자 노드의 백업이 보존됩니다.  AG에 대한 보존은 노드 수준에서만 적용됩니다.





== 4단계: 스냅샷 및 복제 설정 구성

. 스냅샷 및 복제 페이지에서 다음 단계를 수행합니다.
+
.. *주문형*, *시간별*, *일별*, *주별* 또는 *월별*을 선택하여 일정 유형을 지정합니다.
+
정책에 대해 하나의 일정 유형만 선택할 수 있습니다.

+

NOTE: 리소스 그룹을 생성하는 동안 백업 작업에 대한 일정(시작 날짜, 종료 날짜, 빈도)을 지정할 수 있습니다.  이를 통해 동일한 정책과 백업 빈도를 공유하는 리소스 그룹을 만들 수 있지만, 각 정책에 다른 백업 일정을 할당할 수 있습니다.

+

NOTE: 오전 2시로 예약한 경우, 일광 절약 시간제(DST) 기간에는 일정이 실행되지 않습니다.







== 5단계: 최신 보존 설정 구성

. 최신 보존 설정 섹션에서 백업 유형 페이지에서 선택한 백업 유형에 따라 다음 작업 중 하나 이상을 수행합니다.


[role="tabbed-block"]
====
.특정 사본 수
--
특정 수의 스냅샷만 보관합니다.

. *지난 <숫자>일 동안 로그 백업을 적용합니다* 옵션을 선택하고 보관할 일수를 지정합니다.  이 한도에 가까워지면 이전 사본을 삭제하는 것이 좋습니다.


--
.특정 일수
--
백업 사본을 특정 일수 동안 보관합니다.

. *전체 백업의 마지막 <숫자>일에 적용되는 로그 백업 유지* 옵션을 선택하고 로그 백업 사본을 보관할 일 수를 지정합니다.


--
====


== 6단계: 스냅샷 설정 구성

. 전체 백업 보존 설정의 경우 다음 작업을 수행합니다.
+
.. 보관할 스냅샷의 총 수를 지정하세요
+
... 보관할 스냅샷 수를 지정하려면 *보관할 사본*을 선택하세요.
... 스냅샷 수가 지정된 수를 초과하면 스냅샷이 삭제되고 가장 오래된 사본이 먼저 삭제됩니다.
+

IMPORTANT: 기본적으로 보존 횟수 값은 2로 설정됩니다.  보존 횟수를 1로 설정하면 새 스냅샷이 대상에 복제될 때까지 첫 번째 스냅샷이 SnapVault 관계에 대한 참조 스냅샷이기 때문에 보존 작업이 실패할 수 있습니다.

+

NOTE: 최대 보존 값은 1018입니다. 보존 기간이 기본 NetApp ONTAP 버전에서 지원하는 것보다 높은 값으로 설정된 경우 백업이 실패합니다.







. 스냅샷을 보관하는 기간
+
.. 스냅샷을 삭제하기 전에 보관할 일수를 지정하려면 *사본 보관 기간*을 선택하세요.


. *스냅샷 복사 잠금 기간*을 선택하고 기간을 일, 월 또는 년 단위로 지정합니다.
+
스냅락 보관 기간은 100년 미만이어야 합니다.

. 정책 라벨을 선택하세요.
+

NOTE: 원격 복제를 위해 기본 스냅샷에 SnapMirror 레이블을 할당하면 기본 스냅샷이 SnapCenter 에서 ONTAP 보조 시스템으로 스냅샷 복제 작업을 오프로드할 수 있습니다. 정책 페이지에서 SnapMirror 또는 SnapVault 옵션을 활성화하지 않고도 이 작업을 수행할 수 있습니다.





== 7단계: 보조 복제 옵션 구성

. 보조 복제 옵션 선택 섹션에서 다음 보조 복제 옵션 중 하나 또는 둘 다를 선택합니다.


[role="tabbed-block"]
====
.SnapMirror 업데이트
--
로컬 스냅샷 복사본을 만든 후 SnapMirror 업데이트합니다.

. 다른 볼륨에 백업 세트의 미러 복사본을 생성하려면 이 옵션을 선택하세요(SnapMirror).
+
SnapMirror Active Sync의 경우 이 옵션을 활성화해야 합니다.

+
2차 복제 중에 SnapLock 만료 시간은 기본 SnapLock 만료 시간을 로드합니다.  토폴로지 페이지에서 *새로 고침* 버튼을 클릭하면 ONTAP 에서 검색된 보조 및 기본 SnapLock 만료 시간이 새로 고침됩니다.

+
보다 link:../protect-scsql/task_view_sql_server_backups_and_clones_in_the_topology_page.html["토폴로지 페이지에서 SQL Server 백업 및 복제본 보기"] .



--
.SnapVault 업데이트
--
스냅샷 사본을 만든 후 SnapVault 업데이트합니다.

. 디스크 간 백업 복제를 수행하려면 이 옵션을 선택하세요.
+
2차 복제 중에 SnapLock 만료 시간은 기본 SnapLock 만료 시간을 로드합니다.  토폴로지 페이지에서 *새로 고침* 버튼을 클릭하면 ONTAP 에서 검색된 보조 및 기본 SnapLock 만료 시간이 새로 고침됩니다.

+
ONTAP 에서 SnapLock Vault로 알려진 보조 노드에만 SnapLock 구성된 경우 토폴로지 페이지에서 *새로 고침* 버튼을 클릭하면 ONTAP 에서 검색된 보조 노드의 잠금 기간이 새로 고침됩니다.

+
SnapLock Vault에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/ontap/snaplock/commit-snapshot-copies-worm-concept.html["볼트 대상의 WORM에 스냅샷 복사본 커밋"]

+
보다 link:../protect-scsql/task_view_sql_server_backups_and_clones_in_the_topology_page.html["토폴로지 페이지에서 SQL Server 백업 및 복제본 보기"] .



--
.오류 재시도 횟수
--
. 프로세스가 중단되기 전에 발생해야 하는 복제 시도 횟수를 입력합니다.


--
====


== 8단계: 스크립트 설정 구성

. 스크립트 페이지에서 백업 작업 전이나 후에 실행해야 하는 프리스크립트나 포스트스크립트의 경로와 인수를 각각 입력합니다.
+
예를 들어, SNMP 트랩을 업데이트하고, 알림을 자동화하고, 로그를 보내는 스크립트를 실행할 수 있습니다.

+

NOTE: prescripts 또는 postscripts 경로에는 드라이브나 공유가 포함되어서는 안 됩니다.  경로는 SCRIPTS_PATH를 기준으로 해야 합니다.

+

NOTE: ONTAP 에서 SnapMirror 보존 정책을 구성하여 보조 저장소가 스냅샷의 최대 한도에 도달하지 않도록 해야 합니다.





== 9단계: 확인 설정 구성

확인 페이지에서 다음 단계를 수행하세요.

. 다음 백업 일정에 대한 검증 실행 섹션에서 일정 빈도를 선택합니다.
. 데이터베이스 일관성 검사 옵션 섹션에서 다음 작업을 수행합니다.
+
.. 무결성 구조를 데이터베이스의 물리적 구조로 제한합니다(PHYSICAL_ONLY)
+
... 무결성 검사를 데이터베이스의 물리적 구조로 제한하고 찢어진 페이지, 체크섬 오류, 데이터베이스에 영향을 미치는 일반적인 하드웨어 오류를 감지하려면 *데이터베이스의 물리적 구조로 무결성 구조 제한(PHYSICAL_ONLY)*을 선택합니다.


.. 모든 정보 메시지 표시 안 함(NO INFOMSGS)
+
... 모든 정보 메시지를 억제하려면 *모든 정보 메시지 억제(NO_INFOMSGS)*를 선택하세요.  기본적으로 선택됨.


.. 개체별로 보고된 모든 오류 메시지를 표시합니다(ALL_ERRORMSGS)
+
... 보고된 모든 오류를 개체별로 표시하려면 *개체별로 보고된 모든 오류 메시지 표시(ALL_ERRORMSGS)*를 선택합니다.


.. 비클러스터형 인덱스(NOINDEX)를 검사하지 마십시오.
+
... 비클러스터형 인덱스를 검사하지 않으려면 *비클러스터형 인덱스를 검사하지 않음(NOINDEX)*을 선택합니다.  SQL Server 데이터베이스는 Microsoft SQL Server 데이터베이스 일관성 검사기(DBCC)를 사용하여 데이터베이스에 있는 개체의 논리적 및 물리적 무결성을 검사합니다.


.. 내부 데이터베이스 스냅샷(TABLOCK)을 사용하는 대신 검사를 제한하고 잠금을 획득합니다.
+
... 내부 데이터베이스 스냅샷을 사용하는 대신 검사를 제한하고 잠금을 획득하려면 *검사를 제한하고 내부 데이터베이스 스냅샷 복사본을 사용하는 대신 잠금을 획득(TABLOCK)*을 선택합니다.




. *로그 백업* 섹션에서 *완료 시 로그 백업 확인*을 선택하여 완료 시 로그 백업을 확인합니다.
. *확인 스크립트 설정* 섹션에서는 각각 확인 작업 전이나 후에 실행해야 하는 프리스크립트나 포스트스크립트의 경로와 인수를 입력합니다.
+

NOTE: prescripts 또는 postscripts 경로에는 드라이브나 공유가 포함되어서는 안 됩니다.  경로는 SCRIPTS_PATH를 기준으로 해야 합니다.





== 10단계: 요약 검토

. 요약을 검토한 후 *마침*을 선택하세요.

