---
permalink: protect-scsql/task_set_up_credentials_for_snapcenter_plug_ins_package_for_windows.html 
sidebar: sidebar 
keywords: credentials 
summary: SnapCenter SnapCenter 작업을 위해 사용자를 인증하기 위해 자격 증명을 사용합니다.  SnapCenter 플러그인을 설치하기 위한 자격 증명과 데이터베이스나 Windows 파일 시스템에서 데이터 보호 작업을 수행하기 위한 추가 자격 증명을 만들어야 합니다. 
---
= Windows용 SnapCenter 플러그인 패키지에 대한 자격 증명 설정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter SnapCenter 작업을 위해 사용자를 인증하기 위해 자격 증명을 사용합니다.  SnapCenter 플러그인을 설치하기 위한 자격 증명과 데이터베이스나 Windows 파일 시스템에서 데이터 보호 작업을 수행하기 위한 추가 자격 증명을 만들어야 합니다.

.시작하기 전에
* 플러그인을 설치하기 전에 Windows 자격 증명을 설정해야 합니다.
* 원격 호스트의 관리자 권한을 포함하여 관리자 권한으로 자격 증명을 설정해야 합니다.
* Windows 호스트의 SQL 인증
+
플러그인을 설치한 후 SQL 자격 증명을 설정해야 합니다.

+
Microsoft SQL Server용 SnapCenter 플러그인을 배포하는 경우 플러그인을 설치한 후 SQL 자격 증명을 설정해야 합니다.  SQL Server sysadmin 권한이 있는 사용자에 대한 자격 증명을 설정합니다.

+
SQL 인증 방법은 SQL Server 인스턴스를 대상으로 인증합니다.  즉, SQL Server 인스턴스는 SnapCenter 에서 검색되어야 합니다.  따라서 SQL 자격 증명을 추가하기 전에 호스트를 추가하고, 플러그인 패키지를 설치하고, 리소스를 새로 고쳐야 합니다.  일정 예약이나 리소스 검색 등의 작업을 수행하려면 SQL Server 인증이 필요합니다.



.단계
. 왼쪽 탐색 창에서 *설정*을 클릭합니다.
. 설정 페이지에서 *자격 증명*을 클릭합니다.
. *새로 만들기*를 클릭합니다.
. 자격 증명 페이지에서 자격 증명을 구성하는 데 필요한 정보를 지정합니다.
+
|===
| 이 분야에서는... | 이렇게 하세요... 


 a| 
자격 증명 이름
 a| 
자격 증명의 이름을 입력하세요.



 a| 
사용자 이름/비밀번호
 a| 
인증에 사용할 사용자 이름과 비밀번호를 입력하세요.

** 도메인 관리자
+
SnapCenter 플러그인을 설치할 시스템의 도메인 관리자를 지정하세요. 사용자 이름 필드에 사용할 수 있는 형식은 다음과 같습니다.

+
*** `NetBIOS\UserName`
*** `Domain FQDN\UserName`


** 로컬 관리자(작업 그룹에만 해당)
+
작업 그룹에 속한 시스템의 경우, SnapCenter 플러그인을 설치할 시스템에 기본 제공되는 로컬 관리자를 지정하십시오. 사용자 계정에 승격된 권한이 있거나 호스트 시스템에서 사용자 액세스 제어 기능이 비활성화된 경우, 로컬 관리자 그룹에 속하는 로컬 사용자 계정을 지정할 수 있습니다.  사용자 이름 필드의 유효한 형식은 다음과 같습니다. `UserName`

+
비밀번호에 큰따옴표(")나 백틱(`)을 사용하지 마세요.  비밀번호에 '<' 기호와 '!)' 기호를 함께 사용하면 안 됩니다.  예를 들어, lessthan<!10, lessthan10<!, backtick`12.





 a| 
인증 모드
 a| 
사용할 인증 모드를 선택하세요.  SQL 인증 모드를 선택하는 경우 SQL 서버 인스턴스와 SQL 인스턴스가 있는 호스트도 지정해야 합니다.

|===
. *확인*을 클릭합니다.


자격 증명 설정을 마친 후 사용자 및 액세스 페이지에서 사용자 또는 사용자 그룹에 자격 증명 유지 관리를 할당할 수 있습니다.
