---
permalink: protect-scsql/task_install_the_snapcenter_plug_in_for_sql_server_silently.html 
sidebar: sidebar 
keywords: install, snapcenter 
summary: SnapCenter 사용자 인터페이스 내에서 Microsoft SQL Server용 SnapCenter 플러그인을 설치해야 합니다.  하지만 어떤 이유로든 실행할 수 없다면 Windows 명령줄에서 자동 모드로 SQL Server 플러그인 설치 프로그램을 무인으로 실행할 수 있습니다. 
---
= 명령줄에서 Microsoft SQL Server용 SnapCenter 플러그인을 자동으로 설치합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 사용자 인터페이스 내에서 Microsoft SQL Server용 SnapCenter 플러그인을 설치해야 합니다.  하지만 어떤 이유로든 실행할 수 없다면 Windows 명령줄에서 자동 모드로 SQL Server 플러그인 설치 프로그램을 무인으로 실행할 수 있습니다.

.시작하기 전에
* Microsoft SQL Server용 SnapCenter 플러그인을 설치하기 전에 이전 버전을 삭제해야 합니다.
+
자세한 내용은 다음을 참조하세요.  https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_Install_a_SnapCenter_Plug-In_manually_and_directly_from_thePlug-In_Host["플러그인 호스트에서 SnapCenter 플러그인을 수동으로 직접 설치하는 방법"^] .



.단계
. 플러그인 호스트에 C:\temp 폴더가 있는지, 로그인한 사용자가 해당 폴더에 대한 전체 액세스 권한이 있는지 확인합니다.
. C:\ProgramData\ NetApp\ SnapCenter\Package Repository에서 SQL Server 소프트웨어 플러그인을 다운로드합니다.
+
이 경로는 SnapCenter 서버가 설치된 호스트에서 접근할 수 있습니다.

. 플러그인을 설치하려는 호스트에 설치 파일을 복사합니다.
. 로컬 호스트의 Windows 명령 프롬프트에서 플러그인 설치 파일을 저장한 디렉토리로 이동합니다.
. SQL Server 소프트웨어용 플러그인을 설치하세요:
+
`"snapcenter_windows_host_plugin.exe"/silent /debuglog"Debug_Log_Path" /log"Log_Path" BI_SNAPCENTER_PORT=Num SUITE_INSTALLDIR="Install_Directory_Path" BI_SERVICEACCOUNT=domain\\administrator BI_SERVICEPWD=password ISFeatureInstall=SCW,SCSQL`

+
플레이스홀더 값을 데이터로 바꾸세요

+
** Debug_Log_Path는 제품군 설치 프로그램 로그 파일의 이름과 위치입니다.
** Log_Path는 플러그인 구성 요소(SCW, SCSQL, SMCore)의 설치 로그 위치입니다.
** Num은 SnapCenter SMCore와 통신하는 포트입니다.
** Install_Directory_Path는 호스트 플러그인 패키지 설치 디렉토리입니다.
** domain\administrator는 Microsoft Windows 웹 서비스 계정용 SnapCenter 플러그인입니다.
** password는 Microsoft Windows 웹 서비스 계정용 SnapCenter 플러그인의 비밀번호입니다. + 
`"snapcenter_windows_host_plugin.exe"/silent /debuglog"C:\HPPW_SCSQL_Install.log" /log"C:\" BI_SNAPCENTER_PORT=8145 SUITE_INSTALLDIR="C:\Program Files\NetApp\SnapCenter" BI_SERVICEACCOUNT=domain\administrator BI_SERVICEPWD=password ISFeatureInstall=SCW,SCSQL`


+

NOTE: SQL Server 플러그인을 설치하는 동안 전달되는 모든 매개변수는 대소문자를 구분합니다.

. Windows 작업 스케줄러, 기본 설치 로그 파일 C:\Installdebug.log 및 C:\Temp에 있는 추가 설치 파일을 모니터링합니다.
. %temp% 디렉터리를 모니터링하여 msiexe.exe 설치 프로그램이 오류 없이 소프트웨어를 설치하는지 확인합니다.
+

NOTE: SQL Server용 플러그인을 설치하면 플러그인이 SnapCenter 서버가 아닌 호스트에 등록됩니다.  SnapCenter GUI 또는 PowerShell cmdlet을 사용하여 호스트를 추가하여 SnapCenter 서버에 플러그인을 등록할 수 있습니다.  호스트가 추가되면 플러그인이 자동으로 검색됩니다.


