---
permalink: protect-scsql/task_migrate_resources_to_netapp_storage.html 
sidebar: sidebar 
keywords: migrate resources 
summary: 'Microsoft Windows용 SnapCenter 플러그인을 사용하여 NetApp 스토리지 시스템을 프로비저닝한 후에는 SnapCenter 그래픽 사용자 인터페이스 \(GUI\) 또는 PowerShell cmdlet을 사용하여 리소스를 NetApp 스토리지 시스템으로 마이그레이션하거나 한 NetApp LUN에서 다른 NetApp LUN으로 마이그레이션할 수 있습니다.' 
---
= NetApp 스토리지 시스템으로 리소스 마이그레이션
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Microsoft Windows용 SnapCenter 플러그인을 사용하여 NetApp 스토리지 시스템을 프로비저닝한 후에는 SnapCenter 그래픽 사용자 인터페이스(GUI)나 PowerShell cmdlet을 사용하여 리소스를 NetApp 스토리지 시스템으로 마이그레이션하거나 한 NetApp LUN에서 다른 NetApp LUN으로 마이그레이션할 수 있습니다.

.시작하기 전에
* SnapCenter 서버에 스토리지 시스템을 추가했어야 합니다.
* SQL Server 리소스를 새로 고침(검색)했어야 합니다.


이 마법사 페이지의 대부분 필드는 설명이 필요 없습니다.  다음 정보는 귀하에게 지침이 필요할 수 있는 몇몇 분야에 대해 설명합니다.

.단계
. 왼쪽 탐색 창에서 *리소스*를 클릭한 다음 목록에서 적절한 플러그인을 선택합니다.
. 리소스 페이지에서 *보기* 드롭다운 목록에서 *데이터베이스* 또는 *인스턴스*를 선택합니다.
. 목록에서 데이터베이스나 인스턴스를 선택하고 *마이그레이션*을 클릭합니다.
. 리소스 페이지에서 다음 작업을 수행합니다.
+
|===
| 이 분야에서는... | 이렇게 하세요... 


 a| 
*데이터베이스 이름* (선택 사항)
 a| 
마이그레이션할 인스턴스를 선택한 경우, *데이터베이스* 드롭다운 목록에서 해당 인스턴스의 데이터베이스를 선택해야 합니다.



 a| 
*목적지 선택*
 a| 
데이터 및 로그 파일의 대상 위치를 선택합니다.

데이터 및 로그 파일은 각각 선택된 NetApp 드라이브 아래의 Data 및 Log 폴더로 이동됩니다.  폴더 구조에 폴더가 하나도 없으면 폴더가 생성되고 리소스가 마이그레이션됩니다.



 a| 
*데이터베이스 파일 세부 정보 표시* (선택 사항)
 a| 
단일 데이터베이스의 여러 파일을 마이그레이션하려면 이 옵션을 선택하세요.


NOTE: *인스턴스* 리소스를 선택하면 이 옵션이 표시되지 않습니다.



 a| 
*옵션*
 a| 
원본에서 데이터베이스 복사본을 삭제하려면 *원래 위치에서 마이그레이션된 데이터베이스 복사본 삭제*를 선택합니다.

선택 사항: *데이터베이스를 분리하기 전에 테이블에서 UPDATE STATISTICS를 실행합니다*.

|===
. 확인 페이지에서 다음 작업을 수행합니다.
+
|===
| 이 분야에서는... | 이렇게 하세요... 


 a| 
*데이터베이스 일관성 검사 옵션*
 a| 
마이그레이션 전에 데이터베이스의 무결성을 확인하려면 *실행 전*을 선택하세요.  마이그레이션 후 데이터베이스의 무결성을 확인하려면 *실행 후*를 선택하세요.



 a| 
*DBCC CHECKDB 옵션*
 a| 
** *PHYSICAL_ONLY* 옵션을 선택하면 무결성 검사를 데이터베이스의 물리적 구조로 제한하고 찢어진 페이지, 체크섬 오류, 데이터베이스에 영향을 미치는 일반적인 하드웨어 오류를 감지합니다.
** 모든 정보 메시지를 표시하지 않으려면 *NO_INFOMSGS* 옵션을 선택하세요.
** *ALL_ERRORMSGS* 옵션을 선택하면 개체별로 보고된 모든 오류가 표시됩니다.
** 비클러스터형 인덱스를 확인하지 않으려면 *NOINDEX* 옵션을 선택하세요.
+
SQL Server 데이터베이스는 Microsoft SQL Server 데이터베이스 일관성 검사기(DBCC)를 사용하여 데이터베이스에 있는 개체의 논리적 및 물리적 무결성을 검사합니다.

+

NOTE: 실행 시간을 줄이려면 이 옵션을 선택하는 것이 좋습니다.

** 내부 데이터베이스 스냅샷을 사용하는 대신, 검사를 제한하고 잠금을 얻으려면 **TABLOCK** 옵션을 선택하세요.


|===
. 요약을 검토한 후 **마침**을 클릭합니다.

