---
permalink: protect-scsql/task-install-snapcenter-plug-in-for-sql-server.html 
sidebar: sidebar 
keywords: credentials 
summary: Microsoft SQL Server용 SnapCenter 플러그인을 설치하는 방법에 대한 지침을 제공합니다. 
---
= Microsoft SQL Server용 SnapCenter 플러그인 설치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Microsoft SQL Server용 SnapCenter 플러그인에 대한 간략한 설치 지침을 제공합니다.



== 1단계: Microsoft SQL Server용 플러그인을 설치하기 위해 Run As Credentials 설정

. 왼쪽 창에서 *설정 > 자격 증명 > 새로 만들기*를 클릭합니다.
. 자격 증명을 입력하세요.
+
기본 제공 도메인 관리자 사용자 이름 형식의 경우 _NetBIOS\<사용자 이름>_ 또는 _<사용자 이름>@<도메인>_ 또는 _<도메인 FQDN>\<사용자 이름>_을 사용합니다.

+
기본 로컬 관리자 사용자 이름 형식의 경우 _<username>_을 사용합니다.





== 2단계: 호스트를 추가하고 Microsoft SQL Server용 플러그인을 설치합니다.

. SnapCenter GUI 왼쪽 창에서 *호스트 > 관리 호스트 > 추가*를 클릭합니다.
. 마법사의 호스트 페이지에서 다음을 수행합니다.
+
.. 호스트 유형: Windows 호스트 유형을 선택하세요.
.. 호스트 이름: SQL 호스트를 사용하거나 전용 Windows 호스트의 FQDN을 지정합니다.
.. 자격 증명: 생성한 호스트의 유효한 자격 증명 이름을 선택하거나 새 자격 증명을 만듭니다.


. 설치할 플러그인 선택 섹션에서 *Microsoft SQL Server*를 선택합니다.
. *추가 옵션*을 클릭하여 다음 세부 정보를 지정하세요.
+
.. 포트: 기본 포트 번호를 유지하거나 포트 번호를 지정합니다.
.. 설치 경로: 기본 경로는 _C:\Program Files\ NetApp\SnapCenter_입니다.  선택적으로 경로를 사용자 정의할 수 있습니다.
.. 클러스터에 있는 모든 호스트 추가: WSFC에서 SQL을 사용하는 경우 이 확인란을 선택합니다.
.. 사전 설치 확인 건너뛰기: 플러그인을 수동으로 설치한 경우 또는 호스트가 플러그인 설치 요구 사항을 충족하는지 확인하지 않으려는 경우 이 확인란을 선택합니다.


. *제출*을 클릭하세요.

