---
permalink: protect-scsql/task_storage_disaster_recovery_for_scsql.html 
sidebar: sidebar 
keywords: disaster recovery 
summary: 글로벌 설정 페이지에서 저장소에 대한 DR 모드를 활성화하여 SQL Server 저장소용 SnapCenter 플러그인을 복구할 수 있습니다. 
---
= SQL Server용 SnapCenter 플러그인을 위한 스토리지 재해 복구(DR)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
글로벌 설정 페이지에서 저장소에 대한 DR 모드를 활성화하여 SQL Server 저장소용 SnapCenter 플러그인을 복구할 수 있습니다.

.시작하기 전에
* 플러그인이 유지 관리 모드인지 확인하세요.
* SnapMirror/ SnapVault 관계를 끊습니다.link:https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-950/GUID-8A3F828F-CD3D-48E8-A171-393581FEB2ED.html["SnapMirror 관계 끊기"]
* 보조 머신의 LUN을 동일한 드라이브 문자로 호스트 머신에 연결합니다.
* 모든 디스크가 DR 이전에 사용된 것과 동일한 드라이브 문자를 사용하여 연결되었는지 확인하세요.
* MSSQL 서버 서비스를 다시 시작합니다.
* SQL 리소스가 다시 온라인 상태인지 확인하세요.


.이 작업에 관하여
VMDK 및 RDM 구성에서는 재해 복구(DR)가 지원되지 않습니다.

.단계
. 설정 페이지에서 *설정* > *전역 설정* > *재해 복구*로 이동합니다.
. *재해 복구 활성화*를 선택합니다.
. *적용*을 클릭하세요.
. *모니터* > *작업*을 클릭하여 DR 작업이 활성화되어 있는지 확인하세요.


.당신이 완료한 후
* 장애 조치 후 새 데이터베이스가 생성되면 해당 데이터베이스는 DR 모드가 아닙니다.
+
새로운 데이터베이스는 장애 조치 이전과 마찬가지로 계속 작동합니다.

* DR 모드에서 생성된 새 백업은 토폴로지 페이지의 SnapMirror 또는 SnapVault (보조)에 나열됩니다.
+
새 백업 옆에는 "i" 아이콘이 표시되어 해당 백업이 DR 모드 중에 생성되었음을 나타냅니다.

* UI나 다음 cmdlet을 사용하여 장애 조치 중에 생성된 SQL Server 백업용 SnapCenter 플러그인을 삭제할 수 있습니다. `Remove-SmBackup`
* 장애 조치 후 일부 리소스를 DR 모드가 아닌 모드로 전환하려면 다음 cmdlet을 사용하세요. `Remove-SmResourceDRMode`
+
자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter 소프트웨어 Cmdlet 참조 가이드"^] .

* SnapCenter Server는 DR 모드 또는 비 DR 모드에 있는 개별 스토리지 리소스(SQL 데이터베이스)를 관리하지만, DR 모드 또는 비 DR 모드에 있는 스토리지 리소스가 있는 리소스 그룹은 관리하지 않습니다.

