---
permalink: protect-sco/predefined-environment-variables-prescript-postscript-clone.html 
sidebar: sidebar 
keywords: environment variable, predefined, prescript, postscript, clone 
summary: SnapCenter 사용하면 데이터베이스를 복제하는 동안 프리스크립트와 포스트스크립트를 실행할 때 미리 정의된 환경 변수를 사용할 수 있습니다. 
---
= 클론별 Prescript 및 Postscript에 대한 미리 정의된 환경 변수
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 사용하면 데이터베이스를 복제하는 동안 프리스크립트와 포스트스크립트를 실행할 때 미리 정의된 환경 변수를 사용할 수 있습니다.

*데이터베이스 복제를 위한 지원되는 미리 정의된 환경 변수*

* *SC_ORIGINAL_SID*는 소스 데이터베이스의 SID를 지정합니다.
+
이 매개변수는 애플리케이션 볼륨에 대해 채워집니다.

+
예: NFSB32

* *SC_ORIGINAL_HOST*는 소스 호스트의 이름을 지정합니다.
+
이 매개변수는 애플리케이션 볼륨에 대해 채워집니다.

+
예: asmrac1.gdl.englab.netapp.com

* *SC_ORACLE_HOME*은 대상 데이터베이스의 Oracle 홈 디렉토리 경로를 지정합니다.
+
예: /ora01/app/oracle/product/18.1.0/db_1

* *SC_BACKUP_NAME*"은 백업의 이름을 지정합니다.
+
이 매개변수는 애플리케이션 볼륨에 대해 채워집니다.

+
예:

+
** 데이터베이스가 ARCHIVELOG 모드로 실행되지 않는 경우: DATA@RG2_scspr2417819002_07-20-2021_12.16.48.9267_0|LOG@RG2_scspr2417819002_07-20-2021_12.16.48.9267_1
** 데이터베이스가 ARCHIVELOG 모드에서 실행되는 경우: DATA@RG2_scspr2417819002_07-20-2021_12.16.48.9267_0|LOG:RG2_scspr2417819002_07-20-2021_12.16.48.9267_1,RG2_scspr2417819002_07-21-2021_12.16.48.9267_1,RG2_scspr2417819002_07-22-2021_12.16.48.9267_1


* *SC_AV_NAME*은 애플리케이션 볼륨의 이름을 지정합니다.
+
예: AV1|AV2

* *SC_ORIGINAL_OS_USER*는 소스 데이터베이스의 운영 체제 소유자를 지정합니다.
+
예: 오라클

* *SC_ORIGINAL_OS_GROUP*은 소스 데이터베이스의 운영 체제 그룹을 지정합니다.
+
예: oinstall

* *SC_TARGET_SID*"는 복제된 데이터베이스의 SID를 지정합니다.
+
PDB 복제 워크플로의 경우 이 매개변수 값은 미리 정의되지 않습니다.

+
이 매개변수는 애플리케이션 볼륨에 대해 채워집니다.

+
예: clonedb

* *SC_TARGET_HOST*는 데이터베이스가 복제될 호스트의 이름을 지정합니다.
+
이 매개변수는 애플리케이션 볼륨에 대해 채워집니다.

+
예: asmrac1.gdl.englab.netapp.com

* *SC_TARGET_OS_USER*는 복제된 데이터베이스의 운영 체제 소유자를 지정합니다.
+
PDB 복제 워크플로의 경우 이 매개변수 값은 미리 정의되지 않습니다.

+
예: 오라클

* *SC_TARGET_OS_GROUP*은 복제된 데이터베이스의 운영 체제 그룹을 지정합니다.
+
PDB 복제 워크플로의 경우 이 매개변수 값은 미리 정의되지 않습니다.

+
예: oinstall

* *SC_TARGET_DB_PORT*는 복제된 데이터베이스의 데이터베이스 포트를 지정합니다.
+
PDB 복제 워크플로의 경우 이 매개변수 값은 미리 정의되지 않습니다.

+
예: 1521



구분 기호에 대한 정보는 다음을 참조하세요.link:../protect-sco/predefined-environment-variables-prescript-postscript-backup.html#supported-delimiters["지원되는 구분 기호"^] .
