---
permalink: protect-sco/predefined-environment-variables-prescript-postscript-restore.html 
sidebar: sidebar 
keywords: environment variable, predefined, prescript, postscript, restore 
summary: SnapCenter 사용하면 데이터베이스를 복원하는 동안 프리스크립트와 포스트스크립트를 실행할 때 미리 정의된 환경 변수를 사용할 수 있습니다. 
---
= 특정 사전 스크립트 및 사후 스크립트를 복원하기 위한 사전 정의된 환경 변수
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 사용하면 데이터베이스를 복원하는 동안 프리스크립트와 포스트스크립트를 실행할 때 미리 정의된 환경 변수를 사용할 수 있습니다.

*데이터베이스 복원을 위한 지원되는 사전 정의된 환경 변수*

* *SC_JOB_ID*는 작업의 작업 ID를 지정합니다.
+
예: 257

* *SC_ORACLE_SID*는 데이터베이스의 시스템 식별자를 지정합니다.
+
작업에 여러 데이터베이스가 관련된 경우 파이프로 구분된 데이터베이스 이름이 포함됩니다.

+
예: NFSB31

* *SC_HOST*는 데이터베이스의 호스트 이름을 지정합니다.
+
이 매개변수는 애플리케이션 볼륨에 대해 채워집니다.

+
예: scsmohost2.gdl.englabe.netapp.com

* *SC_OS_USER*는 데이터베이스의 운영 체제 소유자를 지정합니다.
+
예: 오라클

* *SC_OS_GROUP*은 데이터베이스의 운영 체제 그룹을 지정합니다.
+
예: oinstall

* *SC_BACKUP_NAME*은 백업의 이름을 지정합니다.
+
이 매개변수는 애플리케이션 볼륨에 대해 채워집니다.

+
예:

+
** 데이터베이스가 ARCHIVELOG 모드로 실행되지 않는 경우: DATA@RG2_scspr2417819002_07-20-2021_12.16.48.9267_0|LOG@RG2_scspr2417819002_07-20-2021_12.16.48.9267_1
** 데이터베이스가 ARCHIVELOG 모드에서 실행되는 경우: DATA@RG2_scspr2417819002_07-20-2021_12.16.48.9267_0|LOG@RG2_scspr2417819002_07-20-2021_12.16.48.9267_1,RG2_scspr2417819002_07-21-2021_12.16.48.9267_1,RG2_scspr2417819002_07-22-2021_12.16.48.9267_1


* *SC_BACKUP_ID*는 백업의 ID를 지정합니다.
+
이 매개변수는 애플리케이션 볼륨에 대해 채워집니다.

+
예:

+
** 데이터베이스가 ARCHIVELOG 모드로 실행되지 않는 경우: DATA@203|LOG@205
** 데이터베이스가 ARCHIVELOG 모드에서 실행되는 경우: DATA@203|LOG@205,206,207


* *SC_RESOURCE_GROUP_NAME*은 리소스 그룹의 이름을 지정합니다.
+
예: RG1

* *SC_ORACLE_HOME*은 Oracle 홈 디렉토리의 경로를 지정합니다.
+
예: /ora01/app/oracle/product/18.1.0/db_1

* *SC_RECOVERY_TYPE*은 복구되는 파일과 복구 범위를 지정합니다.
+
예: RESTORESCOPE:usingBackupControlfile=false|RECOVERYSCOPE:allLogs=true,noLogs=false,untiltime=false,untilscn=false.



구분 기호에 대한 정보는 다음을 참조하세요.link:../protect-sco/predefined-environment-variables-prescript-postscript-backup.html#supported-delimiters["지원되는 구분 기호"^] .
