---
permalink: protect-sco/predefined-environment-variables-prescript-postscript-backup.html 
sidebar: sidebar 
keywords: environment variable, predefined, prescript, postscript, backup, policy 
summary: SnapCenter 사용하면 백업 정책을 생성하는 동안 프리스크립트와 포스트스크립트를 실행할 때 미리 정의된 환경 변수를 사용할 수 있습니다. 
---
= 백업 특정 사전 스크립트 및 사후 스크립트를 위한 사전 정의된 환경 변수
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 사용하면 백업 정책을 생성하는 동안 프리스크립트와 포스트스크립트를 실행할 때 미리 정의된 환경 변수를 사용할 수 있습니다.  이 기능은 VMDK를 제외한 모든 Oracle 구성에서 지원됩니다.

SnapCenter 셸 스크립트가 실행되는 환경에서 직접 액세스할 수 있는 매개변수 값을 미리 정의합니다.  스크립트를 실행할 때 이러한 매개변수의 값을 수동으로 지정할 필요는 없습니다.



== 백업 정책 생성을 위한 사전 정의된 환경 변수 지원

* *SC_JOB_ID*는 작업의 작업 ID를 지정합니다.
+
예: 256

* *SC_ORACLE_SID*는 데이터베이스의 시스템 식별자를 지정합니다.
+
작업에 여러 데이터베이스가 관련된 경우 매개변수에는 파이프로 구분된 데이터베이스 이름이 포함됩니다.

+
이 매개변수는 애플리케이션 볼륨에 대해 채워집니다.

+
예: NFSB32|NFSB31

* *SC_HOST*는 데이터베이스의 호스트 이름을 지정합니다.
+
RAC의 경우 호스트 이름은 백업이 수행되는 호스트의 이름이 됩니다.

+
이 매개변수는 애플리케이션 볼륨에 대해 채워집니다.

+
예: scsmohost2.gdl.englabe.netapp.com

* *SC_OS_USER*는 데이터베이스의 운영 체제 소유자를 지정합니다.
+
데이터는 <db1>@<osuser1>|<db2>@<osuser2> 형식으로 지정됩니다.

+
예: NFSB31@oracle|NFSB32@oracle

* *SC_OS_GROUP*은 데이터베이스의 운영 체제 그룹을 지정합니다.
+
데이터는 <db1>@<osgroup1>|<db2>@<osgroup2> 형식으로 지정됩니다.

+
예: NFSB31@install|NFSB32@oinstall

* *SC_BACKUP_TYPE*"은 백업 유형(온라인 전체, 온라인 데이터, 온라인 로그, 오프라인 종료, 오프라인 마운트)을 지정합니다.
+
예:

+
** 전체 백업의 경우: ONLINEFULL
** 데이터 전용 백업: ONLINEDATA
** 로그 전용 백업의 경우: ONLINELOG


* *SC_BACKUP_NAME*은 백업의 이름을 지정합니다.
+
이 매개변수는 애플리케이션 볼륨에 대해 채워집니다.

+
예: DATA@RG2_scspr2417819002_07-20-2021_12.16.48.9267_0|LOG@RG2_scspr2417819002_07-20-2021_12.16.48.9267_1|AV@RG2_scspr2417819002_07-20-2021_12.16.48.9267

* *SC_BACKUP_ID*는 백업 ID를 지정합니다.
+
이 매개변수는 애플리케이션 볼륨에 대해 채워집니다.

+
예: DATA@203|LOG@205|AV@207

* *SC_ORACLE_HOME*은 Oracle 홈 디렉토리의 경로를 지정합니다.
+
예: NFSB32@/ora01/app/oracle/product/18.1.0/db_1|NFSB31@/ora01/app/oracle/product/18.1.0/db_1

* *SC_BACKUP_RETENTION*은 정책에 정의된 보존 기간을 지정합니다.
+
예:

+
** 전체 백업의 경우: 시간별|DATA@DAYS:3|LOG@COUNT:4
** 주문형 데이터 전용 백업의 경우: Ondemand|DATA@COUNT:2
** 주문형 로그 전용 백업의 경우: Ondemand|LOG@COUNT:2


* *SC_RESOURCE_GROUP_NAME*은 리소스 그룹의 이름을 지정합니다.
+
예: RG1

* *SC_BACKUP_POLICY_NAME*은 백업 정책의 이름을 지정합니다.
+
예: backup_policy

* *SC_AV_NAME*은 애플리케이션 볼륨의 이름을 지정합니다.
+
예: AV1|AV2

* *SC_PRIMARY_DATA_VOLUME_FULL_PATH*는 데이터 파일 디렉토리의 볼륨에 대한 SVM의 스토리지 매핑을 지정합니다.  이는 LUN과 QTree의 부모 볼륨 이름이 됩니다.
+
데이터는 <db1>@<SVM1:volume1>|<db2>@<SVM2:volume2> 형식으로 지정됩니다.

+
예:

+
** 동일한 리소스 그룹에 있는 2개의 데이터베이스의 경우: NFSB32@buck:/vol/scspr2417819002_NFS_CDB_NFSB32_DATA|NFSB31@buck:/vol/scspr2417819002_NFS_CDB_NFSB31_DATA
** 여러 볼륨에 걸쳐 데이터 파일이 분산된 단일 데이터베이스의 경우: buck:/vol/scspr2417819002_NFS_CDB_NFSB31_DATA,herculus:/vol/scspr2417819002_NFS


* *SC_PRIMARY_ARCHIVELOGS_VOLUME_FULL_PATH*는 로그 파일 디렉토리의 볼륨에 대한 SVM의 스토리지 매핑을 지정합니다.  이는 LUN과 QTree의 부모 볼륨 이름이 됩니다.
+
예:

+
** 단일 데이터베이스 인스턴스의 경우: buck:/vol/scspr2417819002_NFS_CDB_NFSB31_REDO
** 여러 데이터베이스 인스턴스의 경우: NFSB31@buck:/vol/scspr2417819002_NFS_CDB_NFSB31_REDO|NFSB32@buck:/vol/scspr2417819002_NFS_CDB_NFSB32_REDO


* *SC_PRIMARY_FULL_SNAPSHOT_NAME_FOR_TAG*는 스토리지 시스템 이름과 볼륨 이름을 포함하는 스냅샷 목록을 지정합니다.
+
예:

+
** 단일 데이터베이스 인스턴스의 경우: buck:/vol/scspr2417819002_NFS_CDB_NFSB32_DATA/RG2_scspr2417819002_07-21-2021_02.28.26.3973_0,buck:/vol/scspr2417819002_NFS_CDB_NFSB32_REDO/RG2_scspr2417819002_07-21-2021_02.28.26.3973_1
** 여러 데이터베이스 인스턴스의 경우: NFSB32@buck:/vol/scspr2417819002_NFS_CDB_NFSB32_DATA/RG2_scspr2417819002_07-21-2021_02.28.26.3973_0,buck:/vol/scspr2417819002_NFS_CDB_NFSB32_REDO/RG2_scspr2417819002_07-21-2021_02.28.26.3973_1 |NFSB31@buck:/vol/scspr2417819002_NFS_CDB_NFSB31_DATA/RG2_scspr2417819002_07-21-2021_02.28.26.3973_0,buck:/vol/scspr2417819002_NFS_CDB_NFSB31_REDO/RG2_scspr2417819002_07-21-2021_02.28.26.3973_1


* *SC_PRIMARY_SNAPSHOT_NAMES*는 백업 중에 생성된 기본 스냅샷의 이름을 지정합니다.
+
예:

+
** 단일 데이터베이스 인스턴스의 경우: RG2_scspr2417819002_07-21-2021_02.28.26.3973_0,RG2_scspr2417819002_07-21-2021_02.28.26.3973_1
** 여러 데이터베이스 인스턴스의 경우: NFSB32@RG2_scspr2417819002_07-21-2021_02.28.26.3973_0,RG2_scspr2417819002_07-21-2021_02.28.26.3973_1|NFSB31@RG2_scspr2417819002_07-21-2021_02.28.26.3973_0,RG2_scspr2417819002_07-21-2021_02.28.26.3973_1
** 일관성을 위해 2개의 볼륨을 포함하는 그룹 스냅샷: cg3_R80404CBEF5V1_04-05-2021_03.08.03.4945_0_bfc279cc-28ad-465c-9d60-5487ac17b25d_2021_4_5_3_8_58_350


* *SC_PRIMARY_MOUNT_POINTS*는 백업의 일부인 마운트 지점 세부 정보를 지정합니다.
+
세부 정보에는 볼륨이 마운트된 디렉토리가 포함되지만 백업 중인 파일의 직접적인 부모는 포함되지 않습니다.  ASM 구성의 경우 디스크 그룹의 이름입니다.

+
데이터는 <db1>@<mountpoint1,mountpoint2>|<db2>@<mountpoint1,mountpoint2> 형식으로 지정됩니다.

+
예:

+
** 단일 데이터베이스 인스턴스의 경우: /mnt/nfsdb3_data,/mnt/nfsdb3_log,/mnt/nfsdb3_data1
** 여러 데이터베이스 인스턴스의 경우: NFSB31@/mnt/nfsdb31_data,/mnt/nfsdb31_log,/mnt/nfsdb31_data1|NFSB32@/mnt/nfsdb32_data,/mnt/nfsdb32_log,/mnt/nfsdb32_data1
** ASM의 경우: +DATA2DG,+LOG2DG


* *SC_PRIMARY_SNAPSHOTS_AND_MOUNT_POINTS*는 각 마운트 지점의 백업 중에 생성된 스냅샷의 이름을 지정합니다.
+
예:

+
** 단일 데이터베이스 인스턴스의 경우: RG2_scspr2417819002_07-21-2021_02.28.26.3973_0:/mnt/nfsb32_data,RG2_scspr2417819002_07-21-2021_02.28.26.3973_1:/mnt/nfsb31_log
** 여러 데이터베이스 인스턴스의 경우: NFSB32@RG2_scspr2417819002_07-21-2021_02.28.26.3973_0:/mnt/nfsb32_data,RG2_scspr2417819002_07-21-2021_02.28.26.3973_1:/mnt/nfsb31_log|NFSB31@RG2_scspr2417819002_07-21-2021_02.28.26.3973_0:/mnt/nfsb31_data,RG2_scspr2417819002_07-21-2021_02.28.26.3973_1:/mnt/nfsb32_log


* *SC_ARCHIVELOGS_LOCATIONS*는 보관 로그 디렉토리의 위치를 지정합니다.
+
디렉토리 이름은 보관 로그 파일의 바로 상위가 됩니다.  보관 로그가 두 개 이상의 위치에 저장되면 모든 위치가 캡처됩니다.  여기에는 FRA 시나리오도 포함됩니다.  디렉토리에 소프트링크가 사용되면 동일한 내용이 채워집니다.

+
예:

+
** NFS의 단일 데이터베이스의 경우: /mnt/nfsdb2_log
** NFS의 여러 데이터베이스와 두 개의 다른 위치에 배치된 NFSB31 데이터베이스 아카이브 로그의 경우: NFSB31@/mnt/nfsdb31_log1,/mnt/nfsdb31_log2|NFSB32@/mnt/nfsdb32_log
** ASM의 경우: +LOG2DG/ASMDB2/ARCHIVELOG/2021_07_15


* *SC_REDO_LOGS_LOCATIONS*는 리두 로그 디렉토리의 위치를 지정합니다.
+
디렉토리 이름은 리두 로그 파일의 바로 상위 파일이 됩니다.  디렉토리에 소프트링크가 사용되면 동일한 내용이 채워집니다.

+
예:

+
** NFS의 단일 데이터베이스의 경우: /mnt/nfsdb2_data/newdb1
** NFS에 있는 여러 데이터베이스의 경우: NFSB31@/mnt/nfsdb31_data/newdb31|NFSB32@/mnt/nfsdb32_data/newdb32
** ASM의 경우: +LOG2DG/ASMDB2/ONLINELOG


* *SC_CONTROL_FILES_LOCATIONS*는 제어 파일 디렉토리의 위치를 지정합니다.
+
디렉토리 이름은 제어 파일의 바로 상위가 됩니다.  디렉토리에 소프트링크가 사용되면 동일한 내용이 채워집니다.

+
예:

+
** NFS의 단일 데이터베이스의 경우: /mnt/nfsdb2_data/fra/newdb1,/mnt/nfsdb2_data/newdb1
** NFS에 있는 여러 데이터베이스의 경우: NFSB31@/mnt/nfsdb31_data/fra/newdb31,/mnt/nfsdb31_data/newdb31|NFSB32@/mnt/nfsdb32_data/fra/newdb32,/mnt/nfsdb32_data/newdb32
** ASM의 경우: +LOG2DG/ASMDB2/CONTROLFILE


* *SC_DATA_FILES_LOCATIONS*"는 데이터 파일 디렉토리의 위치를 지정합니다.
+
디렉토리 이름은 데이터 파일의 바로 상위 이름이 됩니다.  디렉토리에 소프트링크가 사용되면 동일한 내용이 채워집니다.

+
예:

+
** NFS의 단일 데이터베이스의 경우: /mnt/nfsdb3_data1,/mnt/nfsdb3_data/NEWDB3/datafile
** NFS에 있는 여러 데이터베이스의 경우: NFSB31@/mnt/nfsdb31_data1,/mnt/nfsdb31_data/NEWDB31/datafile|NFSB32@/mnt/nfsdb32_data1,/mnt/nfsdb32_data/NEWDB32/datafile
** ASM의 경우: +DATA2DG/ASMDB2/DATAFILE,+DATA2DG/ASMDB2/TEMPFILE


* *SC_SNAPSHOT_LABEL*은 보조 레이블의 이름을 지정합니다.
+
예: 시간별, 일별, 주별, 월별 또는 사용자 정의 라벨.





== 지원되는 구분 기호

* *:*는 SVM 이름과 볼륨 이름을 구분하는 데 사용됩니다.
+
예: buck:/vol/scspr2417819002_NFS_CDB_NFSB32_DATA/RG2_scspr2417819002_07-21-2021_02.28.26.3973_0,buck:/vol/scspr2417819002_NFS_CDB_NFSB32_REDO/RG2_scspr2417819002_07-21-2021_02.28.26.3973_1

* *@*는 데이터베이스 이름과 데이터를 구분하고 키와 값을 구분하는 데 사용됩니다.
+
예:

+
** NFSB32@buck:/vol/scspr2417819002_NFS_CDB_NFSB32_DATA/RG2_scspr2417819002_07-21-2021_02.28.26.3973_0,buck:/vol/scspr2417819002_NFS_CDB_NFSB32_REDO/RG2_scspr2417819002_07-21-2021_02.28.26.3973_1 |NFSB31@buck:/vol/scspr2417819002_NFS_CDB_NFSB31_DATA/RG2_scspr2417819002_07-21-2021_02.28.26.3973_0,buck:/vol/scspr2417819002_NFS_CDB_NFSB31_REDO/RG2_scspr2417819002_07-21-2021_02.28.26.3973_1
** NFSB31@오라클|NFSB32@오라클


* *|*는 두 개의 서로 다른 데이터베이스 간의 데이터를 구분하고 SC_BACKUP_ID, SC_BACKUP_RETENTION 및 SC_BACKUP_NAME 매개변수에 대한 두 개의 서로 다른 엔터티 간의 데이터를 구분하는 데 사용됩니다.
+
예:

+
** 데이터@203|로그@205
** 시간별|데이터@일:3|로그@카운트:4
** 데이터@RG2_scspr2417819002_07-20-2021_12.16.48.9267_0|로그@RG2_scspr2417819002_07-20-2021_12.16.48.9267_1


* */*는 SC_PRIMARY_SNAPSHOT_NAMES 및 SC_PRIMARY_FULL_SNAPSHOT_NAME_FOR_TAG 매개변수에 대한 볼륨 이름과 스냅샷을 구분하는 데 사용됩니다.
+
예: NFSB32@buck:/vol/scspr2417819002_NFS_CDB_NFSB32_DATA/RG2_scspr2417819002_07-21-2021_02.28.26.3973_0,buck:/vol/scspr2417819002_NFS_CDB_NFSB32_REDO/RG2_scspr2417819002_07-21-2021_02.28.26.3973_1

* *,*는 동일한 DB에 대한 변수 집합을 구분하는 데 사용됩니다.
+
예: NFSB32@buck:/vol/scspr2417819002_NFS_CDB_NFSB32_DATA/RG2_scspr2417819002_07-21-2021_02.28.26.3973_0,buck:/vol/scspr2417819002_NFS_CDB_NFSB32_REDO/RG2_scspr2417819002_07-21-2021_02.28.26.3973_1 |NFSB31@buck:/vol/scspr2417819002_NFS_CDB_NFSB31_DATA/RG2_scspr2417819002_07-21-2021_02.28.26.3973_0,buck:/vol/scspr2417819002_NFS_CDB_NFSB31_REDO/RG2_scspr2417819002_07-21-2021_02.28.26.3973_1


