---
permalink: protect-sco/preferred-nodes.html 
sidebar: sidebar 
keywords: oracle databases discover 
summary: SnapCenter Oracle 데이터베이스를 검색하는 방법. 
---
= RAC 설정에서 선호하는 노드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Oracle Real Application Clusters(RAC) 설정에서 SnapCenter 백업 작업을 수행하는 데 사용하는 기본 노드를 지정할 수 있습니다.  기본 노드를 지정하지 않으면 SnapCenter 자동으로 노드를 기본 노드로 지정하고 해당 노드에 백업이 생성됩니다.

선호되는 노드는 RAC 데이터베이스 인스턴스가 있는 클러스터 노드 중 하나 또는 전체일 수 있습니다.  백업 작업은 선호도 순서대로 이러한 선호 노드에서만 실행됩니다.

.예
RAC 데이터베이스 cdbrac에는 세 개의 인스턴스가 있습니다. 노드 1에 cdbrac1, 노드 2에 cdbrac2, 노드 3에 cdbrac3입니다.

node1과 node2 인스턴스는 기본 노드로 구성되며, node2는 첫 번째 기본 설정이고 node1은 두 번째 기본 설정입니다.  백업 작업을 수행할 때 작업은 우선적으로 노드2에서 시도됩니다. 이는 노드2가 첫 번째 기본 노드이기 때문입니다.

플러그인 에이전트가 호스트에서 실행되지 않거나, 호스트의 데이터베이스 인스턴스가 지정된 백업 유형에 필요한 상태가 아니거나, FlexASM 구성에서 node2의 데이터베이스 인스턴스가 로컬 ASM 인스턴스에서 제공되지 않는 등 여러 가지 이유로 node2가 백업할 수 없는 상태가 되면, 작업은 node1에서 시도됩니다.

node3은 선호 노드 목록에 없으므로 백업에 사용되지 않습니다.



== Flex ASM 설정

Flex ASM 설정에서 RAC 클러스터의 노드 수보다 기수가 적으면 Leaf 노드는 기본 노드로 나열되지 않습니다.  Flex ASM 클러스터 노드 역할에 변경 사항이 있는 경우 수동으로 검색하여 기본 노드가 새로 고쳐지도록 해야 합니다.



== 필수 데이터베이스 상태

백업이 성공적으로 완료되려면 기본 노드의 RAC 데이터베이스 인스턴스가 필요한 상태여야 합니다.

* 구성된 기본 노드의 RAC 데이터베이스 인스턴스 중 하나는 온라인 백업을 생성하기 위해 열린 상태여야 합니다.
* 구성된 기본 노드의 RAC 데이터베이스 인스턴스 중 하나는 마운트 상태여야 하며, 다른 기본 노드를 포함한 다른 모든 인스턴스는 오프라인 마운트 백업을 생성하려면 마운트 상태 이하여야 합니다.
* RAC 데이터베이스 인스턴스는 어떤 상태든 될 수 있지만 오프라인 종료 백업을 만들려면 기본 노드를 지정해야 합니다.

