---
permalink: protect-sco/reference_requirements_for_cloning_an_oracle_database.html 
sidebar: sidebar 
keywords:  
summary: Oracle 데이터베이스를 복제하기 전에 필수 구성 요소가 모두 완료되었는지 확인해야 합니다. 
---
= Oracle 데이터베이스 복제를 위한 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Oracle 데이터베이스를 복제하기 전에 필수 구성 요소가 모두 완료되었는지 확인해야 합니다.

* SnapCenter 사용하여 데이터베이스 백업을 만들어야 합니다.
+
복제 작업을 성공적으로 수행하려면 온라인 데이터 및 로그 백업이나 오프라인(마운트 또는 종료) 백업을 성공적으로 만들어야 합니다.

* 제어 파일이나 리두 로그 파일 경로를 사용자 지정하려면 필요한 파일 시스템이나 ASM(자동 스토리지 관리) 디스크 그룹을 미리 프로비저닝해야 합니다.
+
기본적으로 복제된 데이터베이스의 리두 로그와 제어 파일은 SnapCenter 에서 복제 데이터베이스의 데이터 파일을 위해 프로비저닝한 ASM 디스크 그룹이나 파일 시스템에 생성됩니다.

* NFS를 통해 ASM을 사용하는 경우 asm_diskstring 매개변수에 정의된 기존 경로에 _/var/opt/snapcenter/scu/clones/*/*_를 추가해야 합니다.
* asm_diskstring 매개변수에서 ASMFD를 사용하는 경우 _AFD:*_를 구성해야 하고, ASMLIB를 사용하는 경우 _ORCL:*_를 구성해야 합니다.
+
asm_diskstring 매개변수를 편집하는 방법에 대한 자세한 내용은 다음을 참조하세요. https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/Disk_paths_are_not_added_to_the_asm_diskstring_database_parameter["asm_diskstring에 디스크 경로를 추가하는 방법"^] .

* 대체 호스트에서 복제본을 생성하는 경우 대체 호스트는 다음 요구 사항을 충족해야 합니다.
+
** Oracle Database용 SnapCenter 플러그인은 대체 호스트에 설치해야 합니다.
** 복제 호스트는 기본 또는 보조 스토리지에서 LUN을 검색할 수 있어야 합니다.
+
*** 기본 스토리지 또는 보조(Vault 또는 Mirror) 스토리지에서 대체 호스트로 복제하는 경우 보조 스토리지와 대체 호스트 간에 iSCSI 세션이 설정되었거나 FC에 대해 적절하게 구역 지정되었는지 확인하세요.
*** Vault 또는 Mirror 스토리지에서 동일한 호스트로 복제하는 경우 Vault 또는 Mirror 스토리지와 호스트 간에 iSCSI 세션이 설정되었는지 또는 FC에 대해 적절하게 구역 지정되었는지 확인하세요.
*** 가상화된 환경에서 복제하는 경우 기본 또는 보조 스토리지와 대체 호스트를 호스팅하는 ESX 서버 간에 iSCSI 세션이 설정되었는지 또는 FC에 대해 적절하게 구역 지정되었는지 확인하세요.
+
자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/ontap-sanhost/["호스트 유틸리티 문서"] .



** 소스 데이터베이스가 ASM 데이터베이스인 경우:
+
*** 복제가 수행될 호스트에서 ASM 인스턴스가 실행 중이어야 합니다.
*** 복제된 데이터베이스의 보관 로그 파일을 전용 ASM 디스크 그룹에 배치하려면 복제 작업 전에 ASM 디스크 그룹을 프로비저닝해야 합니다.
*** 데이터 디스크 그룹의 이름은 구성할 수 있지만, 복제가 수행될 호스트의 다른 ASM 디스크 그룹에서 해당 이름이 사용되지 않는지 확인하세요.
+
ASM 디스크 그룹에 있는 데이터 파일은 SnapCenter 복제 워크플로의 일부로 프로비저닝됩니다.



** NVMe의 경우 NVMe util을 설치해야 합니다.


* 로그 백업을 사용하여 대체 호스트에 복제하는 동안 보조 로케이터를 검색하려면 데이터 LUN과 로그 LUN에 대한 보호 유형(예: 미러, 볼트 또는 미러-볼트)이 동일해야 합니다.
* 12_c_ 데이터베이스 백업을 복제하기 위해 시드 PDB 관련 정보를 검색하려면 소스 데이터베이스 매개변수 파일에서 exclude_seed_cdb_view 값을 FALSE로 설정해야 합니다.
+
시드 PDB는 CDB가 PDB를 생성하는 데 사용할 수 있는 시스템 제공 템플릿입니다.  시드 PDB의 이름은 PDB$SEED입니다.  PDB$SEED에 대한 자세한 내용은 Oracle Doc ID 1940806.1을 참조하세요.

+

NOTE: 12_c_ 데이터베이스를 백업하기 전에 값을 설정해야 합니다.

* SnapCenter autofs 하위 시스템에서 관리하는 파일 시스템의 백업을 지원합니다.  데이터베이스를 복제하는 경우 플러그인 호스트의 루트 사용자는 autofs 마운트 지점의 루트 아래에 디렉토리를 생성할 권한이 없으므로 데이터 마운트 지점이 autofs 마운트 지점의 루트 아래에 있지 않은지 확인하세요.
+
제어 및 리두 로그 파일이 데이터 마운트 지점에 있는 경우 제어 파일 경로를 수정한 다음, 그에 따라 리두 로그 파일 경로를 수정해야 합니다.

+

NOTE: 새로 복제된 마운트 포인트를 autofs 하위 시스템에 수동으로 등록할 수 있습니다.  새로 복제된 마운트 포인트는 자동으로 등록되지 않습니다.

* TDE(자동 로그인)가 있고 동일하거나 다른 호스트에서 데이터베이스를 복제하려는 경우 소스 데이터베이스에서 _/etc/ORACLE/WALLET/$ORACLE_SID_ 아래의 지갑(키 파일)을 복제된 데이터베이스로 복사해야 합니다.
* Oracle Linux 7 이상 또는 Red Hat Enterprise Linux(RHEL) 7 이상의 SAN(Storage Area Network) 환경에서 복제를 성공적으로 수행하려면 _/etc/lvm/lvm.conf_에서 use_lvmetad = 0 값을 설정하고 lvm2-lvmetad 서비스를 중지해야 합니다.
* Oracle 데이터베이스 11.2.0.3 이상을 사용하고 NID 스크립트를 사용하여 보조 인스턴스의 데이터베이스 ID를 변경하는 경우 13366202 Oracle 패치를 설치해야 합니다.
* 볼륨을 호스팅하는 집계가 스토리지 가상 머신(SVM)의 할당된 집계 목록에 있는지 확인해야 합니다.
* NVMe의 경우 연결에서 대상 포트를 제외해야 하는 경우 /var/opt/snapcenter/scu/etc/nvme.conf 파일에 대상 노드 이름과 포트 이름을 추가해야 합니다.
+
해당 파일이 존재하지 않으면 아래 예시와 같이 파일을 생성해야 합니다.

+
....
blacklist {
nn-0x<target_node_name_1>:pn-0x<target_port_name_1>
nn-0x<target_node_name_2>:pn-0x<target_port_name_2>
}
....
* LUN이 iSCSI와 FC의 혼합 프로토콜로 구성된 iGroup을 사용하여 AIX 호스트에 매핑되지 않았는지 확인해야 합니다. 자세한 내용은 다음을 참조하세요.  https://kb.netapp.com/mgmt/SnapCenter/SnapCenter_Plug-in_for_Oracle_operations_fail_with_error_Unable_to_discover_the_device_for_LUN_LUN_PATH["LUN에 대한 장치를 검색할 수 없습니다. 오류가 발생하여 작업이 실패합니다."^] .

