---
permalink: protect-sco/reference_storage_types_supported_by_snapcenter_plug_in_for_oracle_database.html 
sidebar: sidebar 
keywords: storage types, iSCSI, NFS, RDM, VMDK, NFS, LVM, ASM, SAN filesystem 
summary: SnapCenter 물리적 머신과 가상 머신 모두에서 다양한 스토리지 유형을 지원합니다.  Linux용 SnapCenter 플러그인 패키지 또는 AIX용 SnapCenter 플러그인 패키지를 설치하기 전에 스토리지 유형에 대한 지원을 확인해야 합니다. 
---
= Oracle Database용 플러그인이 지원하는 저장 유형
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 물리적 머신과 가상 머신 모두에서 다양한 스토리지 유형을 지원합니다.  Linux용 SnapCenter 플러그인 패키지 또는 AIX용 SnapCenter 플러그인 패키지를 설치하기 전에 스토리지 유형에 대한 지원을 확인해야 합니다.

SnapCenter Linux 및 AIX에 대한 스토리지 프로비저닝을 지원하지 않습니다.



== Linux에서 지원되는 스토리지 유형

다음 표는 Linux에서 지원되는 저장 유형을 나열합니다.

|===
| 기계 | 저장 유형 


 a| 
물리적 서버
 a| 
* FC 연결 LUN
* iSCSI로 연결된 LUN
* NFS 연결 볼륨
* NVMe-FC
* NVMe/TCP




 a| 
VMware ESXi
 a| 
* FC 또는 iSCSI ESXi HBA로 연결된 RDM LUN 호스트 버스 어댑터(HBA) 스캐닝은 SnapCenter 호스트에 있는 모든 호스트 버스 어댑터를 스캔하기 때문에 완료하는 데 오랜 시간이 걸릴 수 있습니다.
+
_/opt/ NetApp/snapcenter/spl/plugins/scu/scucore/modules/SCU/Config_에 있는 *LinuxConfig.pm* 파일을 편집하여 *SCSI_HOSTS_OPTIMIZED_RESCAN* 매개변수 값을 1로 설정하면 HBA_DRIVER_NAMES에 나열된 HBA만 다시 스캔합니다.

* iSCSI 이니시에이터에 의해 게스트 시스템에 직접 연결된 iSCSI LUN
* NFS 데이터 저장소의 VMDK
* NVMe/TCP를 통해 생성된 VMFS의 VMDK
+

NOTE: RAC는 공유 VMDK를 지원하는 ESX 8.0U2에서 지원됩니다.

* 게스트 시스템에 직접 연결된 NFS 볼륨
* NFS와 SAN 모두에 있는 vVol 데이터 저장소
+
vVol 데이터스토어는 VMware vSphere용 ONTAP 도구를 사용해서만 프로비저닝할 수 있습니다.



|===


== AIX에서 지원되는 스토리지 유형

다음 표는 AIX에서 지원되는 스토리지 유형을 나열합니다.

|===
| 기계 | 저장 유형 


 a| 
물리적 서버
 a| 
* FC 연결 및 iSCSI 연결 LUN.
+
SAN 환경에서는 ASM, LVM, SAN 파일 시스템이 지원됩니다.

+

NOTE: AIX 및 파일 시스템에서는 NFS가 지원되지 않습니다.

* 향상된 저널링 파일 시스템(JFS2)
+
SAN 파일 시스템과 LVM 레이아웃에 대한 인라인 로깅을 지원합니다.



|===
그만큼 https://imt.netapp.com/matrix/imt.jsp?components=121071;&solution=1259&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 도구"] 지원되는 버전에 대한 최신 정보가 포함되어 있습니다.
