---
permalink: protect-sco/schedule-backups.html 
sidebar: sidebar 
keywords: oracle databases discover 
summary: SnapCenter Oracle 데이터베이스를 검색하는 방법. 
---
= 백업 일정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
백업 빈도(일정 유형)는 정책에 지정되고, 백업 일정은 리소스 그룹 구성에 지정됩니다.  백업 빈도나 일정을 결정하는 가장 중요한 요소는 리소스의 변화율과 데이터의 중요도입니다.  자주 사용되는 리소스는 매시간 백업하고, 거의 사용되지 않는 리소스는 하루에 한 번 백업할 수도 있습니다.  기타 요소로는 조직에 대한 리소스의 중요성, 서비스 수준 계약(SLA), 복구 지점 목표(RPO) 등이 있습니다.

SLA는 기대되는 서비스 수준을 정의하고 서비스 가용성과 성능을 포함한 많은 서비스 관련 문제를 해결합니다.  RPO는 장애 발생 후 정상적인 작업을 재개하기 위해 백업 저장소에서 복구해야 하는 파일의 수명에 대한 전략을 정의합니다.  SLA와 RPO는 데이터 보호 전략에 기여합니다.

많이 사용되는 리소스의 경우에도 하루에 한두 번 이상 전체 백업을 실행할 필요는 없습니다.  예를 들어, 정기적인 트랜잭션 로그 백업을 통해 필요한 백업을 확보하는 데 충분할 수 있습니다.  데이터베이스를 더 자주 백업할수록 SnapCenter 복원 시 사용해야 하는 트랜잭션 로그가 줄어들어 복원 작업이 더 빨라질 수 있습니다.

백업 일정은 다음과 같이 두 부분으로 구성됩니다.

* 백업 주파수
+
일부 플러그인의 경우 _스케줄 유형_이라고 하는 백업 빈도(백업을 수행하는 빈도)는 정책 구성의 일부입니다.  정책의 백업 빈도를 시간별, 일별, 주별 또는 월별로 선택할 수 있습니다.  이러한 주파수를 선택하지 않으면 생성된 정책은 주문형 정책만입니다.  *설정* > *정책*을 클릭하면 정책에 액세스할 수 있습니다.

* 백업 일정
+
백업 일정(백업을 정확히 언제 수행해야 하는지)은 리소스 그룹 구성의 일부입니다.  예를 들어, 주간 백업에 대한 정책이 구성된 리소스 그룹이 있는 경우 매주 목요일 오후 10시에 백업하도록 일정을 구성할 수 있습니다.  *리소스* > *리소스 그룹*을 클릭하면 리소스 그룹 일정에 액세스할 수 있습니다.


