---
permalink: protect-sco/task_define_a_clone_strategy_for_oracle_databases.html 
sidebar: sidebar 
keywords: backup types, cloning type, clone name, limitations 
summary: 데이터베이스를 복제하기 전에 전략을 정의하면 복제 작업이 성공할 수 있습니다. 
---
= Oracle 데이터베이스에 대한 복제 전략 정의
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터베이스를 복제하기 전에 전략을 정의하면 복제 작업이 성공할 수 있습니다.



== 복제에 지원되는 백업 유형

SnapCenter 다양한 유형의 Oracle 데이터베이스 백업 복제를 지원합니다.

* 온라인 데이터 백업
* 온라인 전체 백업
* 오프라인 마운트 백업
* 오프라인 종료 백업
* Data Guard 대기 데이터베이스 및 Active Data Guard 대기 데이터베이스 백업
* RAC(Real Application Clusters) 구성에서의 온라인 데이터 백업, 온라인 전체 백업, 오프라인 마운트 백업 및 오프라인 종료 백업
* ASM(자동 스토리지 관리) 구성의 온라인 데이터 백업, 온라인 전체 백업, 오프라인 마운트 백업 및 오프라인 종료 백업
+

IMPORTANT: 멀티패스 구성 파일의 user_friendly_names 옵션이 yes로 설정된 경우 SAN 구성은 지원되지 않습니다.




NOTE: 보관 로그 백업 복제는 지원되지 않습니다.



== Oracle 데이터베이스에서 지원되는 복제 유형

Oracle 데이터베이스 환경에서 SnapCenter 데이터베이스 백업 복제를 지원합니다.  기본 및 보조 저장 시스템에서 백업을 복제할 수 있습니다.

SnapCenter 서버는 NetApp FlexClone 기술을 사용하여 백업을 복제합니다.

"Refresh-SmClone" 명령을 실행하여 복제본을 새로 고칠 수 있습니다.  이 명령은 데이터베이스의 백업을 생성하고, 기존 복제본을 삭제하고, 같은 이름의 복제본을 생성합니다.


NOTE: 복제 새로 고침 작업은 UNIX 명령을 사용해서만 수행할 수 있습니다.



== Oracle 데이터베이스의 복제 명명 규칙

SnapCenter 3.0부터 파일 시스템 복제본에 사용되는 명명 규칙이 ASM 디스크 그룹 복제본과 다릅니다.

* SAN 또는 NFS 파일 시스템의 명명 규칙은 FileSystemNameofsourcedatabase_CLONESID입니다.
* ASM 디스크 그룹의 명명 규칙은 SC_HASHCODEofDISKGROUP_CLONESID입니다.
+
HASHCODEofDISKGROUP은 각 ASM 디스크 그룹에 대해 고유한 자동 생성 숫자(2~10자리)입니다.





== Oracle 데이터베이스 복제의 한계

데이터베이스를 복제하기 전에 복제 작업의 제한 사항을 알고 있어야 합니다.

* 11.2.0.4에서 12.1.0.1까지의 Oracle 버전을 사용하는 경우 _renamedg_ 명령을 실행하면 복제 작업이 중단됩니다.  이 문제를 해결하려면 Oracle 패치 19544733을 적용하세요.
* 호스트에 직접 연결된 LUN(예: Windows 호스트에서 Microsoft iSCSI Initiator 사용)에서 동일한 Windows 호스트의 VMDK 또는 RDM LUN이나 다른 Windows 호스트로 데이터베이스를 복제하는 것은 지원되지 않습니다.
* 볼륨 마운트 지점의 루트 디렉토리는 공유 디렉토리가 될 수 없습니다.
* 복제본이 포함된 LUN을 새 볼륨으로 이동하면 복제본을 삭제할 수 없습니다.

