---
permalink: protect-sco/task_define_a_backup_strategy_for_oracle_databases.html 
sidebar: sidebar 
keywords: backup type, preferred nodes, catalog backups, schedules, backup name format, retention, verification 
summary: 백업 전략을 정의하면 데이터베이스를 성공적으로 복원하거나 복제할 수 있는 수단이 확보됩니다. 
---
= Oracle 데이터베이스에 대한 백업 전략 정의
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터베이스를 성공적으로 복원하거나 복제할 수 있는 수단을 확보하기 위해 백업 전략을 정의하세요.

백업 전략은 주로 서비스 수준 계약(SLA), 복구 시간 목표(RTO), 복구 지점 목표(RPO)에 따라 결정됩니다.

* SLA는 기대되는 서비스 수준을 정의하고 서비스의 가용성과 성능과 같은 서비스 관련 문제를 해결합니다.
* RTO는 서비스가 중단된 후 비즈니스 프로세스를 복구해야 하는 시간을 정의합니다.
* RPO는 장애 발생 후 정상적인 작업을 재개하기 위해 백업 저장소에서 복구해야 하는 파일의 기간을 정의합니다.




== 백업을 위한 지원되는 Oracle 데이터베이스 구성

SnapCenter 다양한 Oracle 데이터베이스 구성의 백업을 지원합니다.

* Oracle Standalone
* Oracle Real Application Clusters(RAC)
* Oracle Standalone 레거시
* Oracle 독립형 컨테이너 데이터베이스(CDB)
* Oracle Data Guard 대기
+
Data Guard 대기 데이터베이스의 오프라인 마운트 백업만 생성할 수 있습니다.  오프라인 종료 백업, 보관 로그 전용 백업 및 전체 백업은 지원되지 않습니다.

* Oracle Active Data Guard 대기
+
Active Data Guard 대기 데이터베이스의 온라인 백업만 생성할 수 있습니다.  아카이브 로그만 백업하고 전체 백업은 지원되지 않습니다.

+

NOTE: Data Guard 대기 또는 Active Data Guard 대기 데이터베이스의 백업을 생성하기 전에 관리형 복구 프로세스(MRP)가 중지되고 백업이 생성되면 MRP가 시작됩니다.

* 자동 스토리지 관리(ASM)
+
** 가상 머신 디스크(VMDK)의 ASM 독립형 및 ASM RAC
+

NOTE: Oracle 데이터베이스에 지원되는 모든 복원 방법 중에서 VMDK에서는 ASM RAC 데이터베이스에 대한 연결 및 복사 복원만 수행할 수 있습니다.

** ASM 독립형 및 원시 장치 매핑(RDM)의 ASM RAC ASMLib을 사용하거나 사용하지 않고 ASM에서 Oracle 데이터베이스에 대한 백업, 복원 및 복제 작업을 수행할 수 있습니다.
** Oracle ASM 필터 드라이버(ASMFD)
+

NOTE: PDB 마이그레이션 및 PDB 복제 작업은 지원되지 않습니다.

** 오라클 플렉스 ASM




지원되는 Oracle 버전에 대한 최신 정보는 다음을 참조하세요. https://imt.netapp.com/matrix/imt.jsp?components=121071;&solution=1259&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 도구"^] .



== Oracle 데이터베이스에서 지원되는 백업 유형

백업 유형은 생성하려는 백업 유형을 지정합니다.  SnapCenter Oracle 데이터베이스에 대한 온라인 및 오프라인 백업 유형을 지원합니다.



=== 온라인 백업

데이터베이스가 온라인 상태일 때 생성되는 백업을 온라인 백업이라고 합니다.  핫 백업이라고도 하는 온라인 백업을 사용하면 데이터베이스를 종료하지 않고도 백업을 만들 수 있습니다.

온라인 백업의 일부로 다음 파일의 백업을 만들 수 있습니다.

* 데이터 파일과 제어 파일만
* 아카이브 로그 파일만(이 시나리오에서는 데이터베이스가 백업 모드로 전환되지 않음)
* 데이터 파일, 제어 파일 및 보관 로그 파일을 포함하는 전체 데이터베이스




=== 오프라인 백업

데이터베이스가 마운트되거나 종료된 상태일 때 생성된 백업을 오프라인 백업이라고 합니다.  오프라인 백업은 콜드 백업이라고도 합니다.  오프라인 백업에는 데이터 파일과 제어 파일만 포함할 수 있습니다.  오프라인 마운트 또는 오프라인 종료 백업을 만들 수 있습니다.

* 오프라인 마운트 백업을 생성할 때 데이터베이스가 마운트된 상태인지 확인해야 합니다.
+
데이터베이스가 다른 상태에 있으면 백업 작업이 실패합니다.

* 오프라인 종료 백업을 생성할 때 데이터베이스는 어떤 상태든 될 수 있습니다.
+
백업을 생성하기 위해 데이터베이스 상태가 필요한 상태로 변경됩니다.  백업을 만든 후 데이터베이스 상태가 원래 상태로 돌아갑니다.





== SnapCenter Oracle 데이터베이스를 검색하는 방법

"리소스"는 SnapCenter 에서 유지 관리하는 호스트의 Oracle 데이터베이스입니다.  사용 가능한 데이터베이스를 발견한 후 이러한 데이터베이스를 리소스 그룹에 추가하여 데이터 보호 작업을 수행할 수 있습니다.  SnapCenter Oracle 데이터베이스의 다양한 유형과 버전을 검색하는 프로세스를 알고 있어야 합니다.

|===
| Oracle 버전 11__g__ ~ 12__c__R1의 경우 | Oracle 버전 12__c__R2 ~ 18__c__의 경우 


 a| 
*RAC 데이터베이스*: RAC 데이터베이스는 /etc/oratab 항목을 기반으로만 검색됩니다.

/etc/oratab 파일에 데이터베이스 항목이 있어야 합니다.
 a| 
*RAC 데이터베이스*: RAC 데이터베이스는 srvctl config 명령을 사용하여 검색됩니다.



 a| 
*독립형*: 독립형 데이터베이스는 /etc/oratab 항목을 기반으로만 검색됩니다.

/etc/oratab 파일에 데이터베이스 항목이 있어야 합니다.
 a| 
*독립형*: 독립형 데이터베이스는 /etc/oratab 파일의 항목과 srvctl config 명령의 출력을 기반으로 검색됩니다.



 a| 
*ASM*: ASM 인스턴스 항목은 /etc/oratab 파일에서 사용할 수 있어야 합니다.
 a| 
*ASM*: ASM 인스턴스 항목은 /etc/oratab 파일에 있을 필요가 없습니다.



 a| 
*RAC One Node*: RAC One Node 데이터베이스는 /etc/oratab 항목을 기반으로만 검색됩니다.

데이터베이스는 _nomount_, _mount_ 또는 _open_ 상태여야 합니다.  /etc/oratab 파일에 데이터베이스 항목이 있어야 합니다.

데이터베이스가 이미 검색되었고 백업이 데이터베이스와 연결되어 있는 경우 RAC One Node 데이터베이스 상태는 이름이 변경됨 또는 삭제됨으로 표시됩니다.

데이터베이스가 이전된 경우 다음 단계를 수행해야 합니다.

. 장애 조치된 RAC 노드의 /etc/oratab 파일에 재배치된 데이터베이스 항목을 수동으로 추가합니다.
. 리소스를 수동으로 새로 고칩니다.
. 리소스 페이지에서 RAC One Node 데이터베이스를 선택한 다음 *데이터베이스 설정*을 클릭합니다.
. 데이터베이스를 구성하여 현재 데이터베이스를 호스팅하는 RAC 노드를 기본 클러스터 노드로 설정합니다.
. SnapCenter 작업을 수행합니다.



NOTE: 한 노드에서 다른 노드로 데이터베이스를 이전했고 이전 노드의 oratab 항목이 삭제되지 않은 경우, 동일한 데이터베이스가 두 번 표시되는 것을 방지하려면 oratab 항목을 수동으로 삭제해야 합니다.
 a| 
*RAC One Node*: RAC One Node 데이터베이스는 srvctl config 명령을 사용해서만 검색됩니다.

데이터베이스는 _nomount_, _mount_ 또는 _open_ 상태여야 합니다.  데이터베이스가 이미 검색되었고 백업이 데이터베이스와 연결되어 있는 경우 RAC One Node 데이터베이스 상태는 이름이 변경됨 또는 삭제됨으로 표시됩니다.

데이터베이스가 이전된 경우 다음 단계를 수행해야 합니다.

. 리소스를 수동으로 새로 고칩니다.
. 리소스 페이지에서 RAC One Node 데이터베이스를 선택한 다음 **데이터베이스 설정**을 클릭합니다.
. 데이터베이스를 구성하여 현재 데이터베이스를 호스팅하는 RAC 노드를 기본 클러스터 노드로 설정합니다.
. SnapCenter 작업을 수행합니다.


|===

NOTE: /etc/oratab 파일에 Oracle 12__c__R2 및 18__c__ 데이터베이스 항목이 있고 동일한 데이터베이스가 srvctl config 명령으로 등록된 경우 SnapCenter 중복된 데이터베이스 항목을 제거합니다.  오래된 데이터베이스 항목이 있는 경우 데이터베이스는 발견되지만 데이터베이스에 접근할 수 없게 되고 상태는 오프라인이 됩니다.



== RAC 설정에서 선호하는 노드

Oracle Real Application Clusters(RAC) 설정에서 백업 작업을 수행할 기본 노드를 지정할 수 있습니다.  기본 노드를 지정하지 않으면 SnapCenter 자동으로 노드를 기본 노드로 지정하고 해당 노드에 백업이 생성됩니다.

선호되는 노드는 RAC 데이터베이스 인스턴스가 있는 클러스터 노드 중 하나 또는 전체일 수 있습니다.  백업 작업은 선호도 순서대로 이러한 선호 노드에서만 실행됩니다.

예: RAC 데이터베이스 cdbrac에는 세 개의 인스턴스가 있습니다. 노드 1에 cdbrac1, 노드 2에 cdbrac2, 노드 3에 cdbrac3입니다.  node1과 node2 인스턴스는 기본 노드로 구성되며, node2는 첫 번째 기본 설정이고 node1은 두 번째 기본 설정입니다.  백업 작업을 수행할 때 작업은 우선적으로 노드2에서 시도됩니다. 이는 노드2가 첫 번째 기본 노드이기 때문입니다.  플러그인 에이전트가 호스트에서 실행되지 않거나, 호스트의 데이터베이스 인스턴스가 지정된 백업 유형에 필요한 상태가 아니거나, FlexASM 구성에서 node2의 데이터베이스 인스턴스가 로컬 ASM 인스턴스에서 제공되지 않는 등 여러 가지 이유로 node2가 백업할 수 없는 상태가 되면, 작업은 node1에서 시도됩니다.  node3은 선호 노드 목록에 없으므로 백업에 사용되지 않습니다.

Flex ASM 설정에서 RAC 클러스터의 노드 수보다 기수가 적으면 Leaf 노드는 기본 노드로 나열되지 않습니다.  Flex ASM 클러스터 노드 역할에 변경 사항이 있는 경우 수동으로 검색하여 기본 노드가 새로 고쳐지도록 해야 합니다.



=== 필수 데이터베이스 상태

백업이 성공적으로 완료되려면 기본 노드의 RAC 데이터베이스 인스턴스가 필요한 상태여야 합니다.

* 구성된 기본 노드의 RAC 데이터베이스 인스턴스 중 하나는 온라인 백업을 생성하기 위해 열린 상태여야 합니다.
* 구성된 기본 노드의 RAC 데이터베이스 인스턴스 중 하나는 마운트 상태여야 하며, 다른 기본 노드를 포함한 다른 모든 인스턴스는 오프라인 마운트 백업을 생성하려면 마운트 상태 이하여야 합니다.
* RAC 데이터베이스 인스턴스는 어떤 상태든 될 수 있지만 오프라인 종료 백업을 만들려면 기본 노드를 지정해야 합니다.




== Oracle Recovery Manager를 사용하여 백업을 카탈로그화하는 방법

Oracle 데이터베이스의 백업은 Oracle Recovery Manager(RMAN)를 사용하여 카탈로그화하여 Oracle RMAN 저장소에 백업 정보를 저장할 수 있습니다.

카탈로그화된 백업은 나중에 블록 수준 복원이나 테이블스페이스 지정 시점 복구 작업에 사용할 수 있습니다.  이러한 카탈로그화된 백업이 필요하지 않으면 카탈로그 정보를 제거할 수 있습니다.

카탈로그화를 위해서는 데이터베이스가 마운트된 상태 이상이어야 합니다.  데이터 백업, 보관 로그 백업 및 전체 백업에 대한 카탈로그 작성을 수행할 수 있습니다.  여러 데이터베이스가 있는 리소스 그룹의 백업에 대해 카탈로그화가 활성화된 경우 각 데이터베이스에 대해 카탈로그화가 수행됩니다.  Oracle RAC 데이터베이스의 경우 카탈로그화는 데이터베이스가 최소한 마운트된 상태인 기본 노드에서 수행됩니다.


NOTE: RAC 데이터베이스의 백업을 카탈로그화하려면 해당 데이터베이스에 대해 다른 작업이 실행되고 있지 않은지 확인하세요.  다른 작업이 실행 중이면 카탈로그 작업은 대기열에 추가되지 않고 실패합니다.

기본적으로 대상 데이터베이스 제어 파일은 카탈로그화에 사용됩니다.  외부 카탈로그 데이터베이스를 추가하려면 SnapCenter 그래픽 사용자 인터페이스(GUI)의 데이터베이스 설정 마법사를 사용하여 외부 카탈로그의 자격 증명과 TNS(Transparent Network Substrate) 이름을 지정하여 구성할 수 있습니다.  -OracleRmanCatalogCredentialName 및 -OracleRmanCatalogTnsName 옵션과 함께 Configure-SmOracleDatabase 명령을 실행하여 CLI에서 외부 카탈로그 데이터베이스를 구성할 수도 있습니다.

SnapCenter GUI에서 Oracle 백업 정책을 생성하는 동안 카탈로그화 옵션을 활성화한 경우 백업은 백업 작업의 일부로 Oracle RMAN을 사용하여 카탈로그화됩니다.  Catalog-SmBackupWithOracleRMAN 명령을 실행하여 백업의 지연 카탈로그화를 수행할 수도 있습니다.  백업을 카탈로그화한 후 Get-SmBackupDetails 명령을 실행하여 카탈로그화된 데이터 파일의 태그, 제어 파일 카탈로그 경로, 카탈로그화된 보관 로그 위치와 같은 카탈로그화된 백업 정보를 얻을 수 있습니다.

ASM 디스크 그룹 이름이 16자 이상이면 SnapCenter 3.0부터 백업에 사용되는 명명 형식은 SC_HASHCODEofDISKGROUP_DBSID_BACKUPID입니다.  그러나 디스크 그룹 이름이 16자 미만이면 백업에 사용되는 명명 형식은 DISKGROUPNAME_DBSID_BACKUPID입니다. 이는 SnapCenter 2.0에서 사용되는 형식과 동일합니다.


NOTE: HASHCODEofDISKGROUP은 각 ASM 디스크 그룹에 대해 자동으로 생성되는 고유한 숫자(2~10자리)입니다.

저장소 레코드가 물리적 상태와 일치하지 않는 백업에 대한 오래된 RMAN 저장소 정보를 업데이트하기 위해 교차 검사를 수행할 수 있습니다.  예를 들어, 사용자가 운영 체제 명령을 사용하여 디스크에서 보관된 로그를 제거하는 경우, 제어 파일은 실제로는 로그가 디스크에 있지 않더라도 여전히 로그가 디스크에 있다고 표시합니다.  교차 검사 작업을 통해 제어 파일을 해당 정보로 업데이트할 수 있습니다.  Set-SmConfigSettings 명령을 실행하고 ENABLE_CROSSCHECK 매개변수에 TRUE 값을 할당하여 교차 검사를 활성화할 수 있습니다.  기본값은 FALSE로 설정됩니다.

`sccli Set-SmConfigSettings-ConfigSettingsTypePlugin-PluginCodeSCO-ConfigSettings "KEY=ENABLE_CROSSCHECK, VALUE=TRUE"`

Uncatalog-SmBackupWithOracleRMAN 명령을 실행하면 카탈로그 정보를 제거할 수 있습니다.  SnapCenter GUI를 사용하여 카탈로그 정보를 제거할 수 없습니다.  그러나 카탈로그화된 백업의 정보는 백업을 삭제하거나 해당 카탈로그화된 백업과 연관된 보존 및 리소스 그룹을 삭제하는 동안 제거됩니다.


NOTE: SnapCenter 호스트를 강제로 삭제하는 경우 해당 호스트와 연관된 카탈로그화된 백업 정보는 제거되지 않습니다.  호스트를 강제로 삭제하기 전에 해당 호스트에 대한 모든 카탈로그 백업 정보를 제거해야 합니다.

작업 시간이 ORACLE_PLUGIN_RMAN_CATALOG_TIMEOUT 매개변수에 지정된 시간 초과 값을 초과하여 카탈로그화 및 카탈로그 해제가 실패하는 경우 다음 명령을 실행하여 매개변수 값을 수정해야 합니다.

`/opt/Netapp/snapcenter/spl/bin/sccli Set-SmConfigSettings-ConfigSettingsType Plugin -PluginCode SCO-ConfigSettings "KEY=ORACLE_PLUGIN_RMAN_CATALOG_TIMEOUT,VALUE=user_defined_value"`

매개변수 값을 수정한 후 다음 명령을 실행하여 SnapCenter 플러그인 Loader (SPL) 서비스를 다시 시작합니다.

`/opt/NetApp/snapcenter/spl/bin/spl restart`

명령과 함께 사용할 수 있는 매개변수와 해당 설명에 대한 정보는 Get-Help command_name을 실행하면 얻을 수 있습니다. 또는 다음을 참조할 수도 있습니다. https://library.netapp.com/ecm/ecm_download_file/ECMLP3337666["SnapCenter 소프트웨어 명령 참조 가이드"^] .



== 백업 일정

백업 빈도(일정 유형)는 정책에 지정되고, 백업 일정은 리소스 그룹 구성에 지정됩니다.  백업 빈도나 일정을 결정하는 가장 중요한 요소는 리소스의 변화율과 데이터의 중요도입니다.  자주 사용되는 리소스는 매시간 백업하고, 거의 사용되지 않는 리소스는 하루에 한 번 백업할 수도 있습니다.  기타 요소로는 조직에 대한 리소스의 중요성, 서비스 수준 계약(SLA), 복구 지점 목표(RPO) 등이 있습니다.

SLA는 기대되는 서비스 수준을 정의하고 서비스 가용성과 성능을 포함한 많은 서비스 관련 문제를 해결합니다.  RPO는 장애 발생 후 정상적인 작업을 재개하기 위해 백업 저장소에서 복구해야 하는 파일의 수명에 대한 전략을 정의합니다.  SLA와 RPO는 데이터 보호 전략에 기여합니다.

많이 사용되는 리소스의 경우에도 하루에 한두 번 이상 전체 백업을 실행할 필요는 없습니다.  예를 들어, 정기적인 트랜잭션 로그 백업을 통해 필요한 백업을 확보하는 데 충분할 수 있습니다.  데이터베이스를 더 자주 백업할수록 SnapCenter 복원 시 사용해야 하는 트랜잭션 로그가 줄어들어 복원 작업이 더 빨라질 수 있습니다.

백업 일정은 다음과 같이 두 부분으로 구성됩니다.

* 백업 주파수
+
일부 플러그인의 경우 _스케줄 유형_이라고 하는 백업 빈도(백업을 수행하는 빈도)는 정책 구성의 일부입니다.  정책의 백업 빈도를 시간별, 일별, 주별 또는 월별로 선택할 수 있습니다.  이러한 주파수를 선택하지 않으면 생성된 정책은 주문형 정책만입니다.  *설정* > *정책*을 클릭하면 정책에 액세스할 수 있습니다.

* 백업 일정
+
백업 일정(백업을 정확히 언제 수행해야 하는지)은 리소스 그룹 구성의 일부입니다.  예를 들어, 주간 백업에 대한 정책이 구성된 리소스 그룹이 있는 경우 매주 목요일 오후 10시에 백업하도록 일정을 구성할 수 있습니다.  *리소스* > *리소스 그룹*을 클릭하면 리소스 그룹 일정에 액세스할 수 있습니다.





== 백업 명명 규칙

기본 스냅샷 명명 규칙을 사용하거나 사용자 지정 명명 규칙을 사용할 수 있습니다.  기본 백업 명명 규칙은 스냅샷 이름에 타임스탬프를 추가하여 복사본이 생성된 시기를 식별하는 데 도움이 됩니다.

스냅샷은 다음과 같은 기본 명명 규칙을 사용합니다.

`resourcegroupname_hostname_timestamp`

다음 예와 같이 논리적으로 백업 리소스 그룹의 이름을 지정해야 합니다.

[listing]
----
dts1_mach1x88_03-12-2015_23.17.26
----
이 예에서 구문 요소는 다음과 같은 의미를 갖습니다.

* _dts1_은 리소스 그룹 이름입니다.
* _mach1x88_은 호스트 이름입니다.
* _03-12-2015_23.17.26_은 날짜와 타임스탬프입니다.


또는, *스냅샷 복사에 사용자 지정 이름 형식 사용*을 선택하여 리소스나 리소스 그룹을 보호하는 동안 스냅샷 이름 형식을 지정할 수 있습니다.  예를 들어, customtext_resourcegroup_policy_hostname 또는 resourcegroup_hostname입니다.  기본적으로 타임스탬프 접미사는 스냅샷 이름에 추가됩니다.



== 백업 보존 옵션

백업 사본을 보관할 일수를 선택하거나 보관할 백업 사본 수를 지정할 수 있으며, ONTAP 최대 255개 사본까지 보관할 수 있습니다.  예를 들어, 귀하의 조직에서는 10일 분의 백업 사본이나 130개의 백업 사본을 보관하도록 요구할 수 있습니다.

정책을 생성하는 동안 백업 유형과 일정 유형에 대한 보존 옵션을 지정할 수 있습니다.

SnapMirror 복제를 설정하면 보존 정책이 대상 볼륨에 미러링됩니다.

SnapCenter 일정 유형과 일치하는 보존 레이블이 있는 보관된 백업을 삭제합니다.  리소스 또는 리소스 그룹의 일정 유형이 변경된 경우 이전 일정 유형 레이블이 지정된 백업이 시스템에 남아 있을 수 있습니다.


NOTE: 백업 사본을 장기간 보관하려면 SnapVault 백업을 사용해야 합니다.



== 기본 또는 보조 스토리지 볼륨을 사용하여 백업 사본을 확인합니다.

기본 저장소 볼륨이나 SnapMirror 또는 SnapVault 보조 저장소 볼륨에서 백업 사본을 확인할 수 있습니다.  보조 저장 볼륨을 사용하여 검증하면 기본 저장 볼륨의 부하가 줄어듭니다.

기본 또는 보조 스토리지 볼륨에 있는 백업을 검증하면 모든 기본 및 보조 스냅샷이 검증됨으로 표시됩니다.

SnapMirror 및 SnapVault 보조 스토리지 볼륨의 백업 사본을 확인하려면 SnapRestore 라이선스가 필요합니다.
