---
permalink: protect-sco/task_clone_oracle_database_backups_using_unix_commands.html 
sidebar: sidebar 
keywords: clone, CLI, commands 
summary: 복제 워크플로에는 계획, 복제 작업 수행, 작업 모니터링이 포함됩니다. 
---
= UNIX 명령을 사용하여 Oracle 데이터베이스 백업 복제
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
복제 워크플로에는 계획, 복제 작업 수행, 작업 모니터링이 포함됩니다.

*이 작업에 관하여*

Oracle 데이터베이스 복제 사양 파일을 만들고 복제 작업을 시작하려면 다음 명령을 실행해야 합니다.

명령과 함께 사용할 수 있는 매개변수와 해당 설명에 대한 정보는 Get-Help _command_name_을 실행하면 얻을 수 있습니다. 또는 다음을 참조할 수도 있습니다. https://library.netapp.com/ecm/ecm_download_file/ECMLP3337666["SnapCenter 소프트웨어 명령 참조 가이드"^] .

*단계*

. 지정된 백업에서 Oracle 데이터베이스 복제 사양을 만듭니다: _New-SmOracleCloneSpecification_
+

NOTE: 2차 데이터 보호 정책이 통합 미러 볼트인 경우 -IncludeSecondaryDetails만 지정합니다.  -SecondaryStorageType을 지정할 필요는 없습니다.

+
이 명령은 지정된 소스 데이터베이스와 해당 백업에 대한 Oracle 데이터베이스 복제 사양 파일을 자동으로 생성합니다.  또한 복제 데이터베이스 SID를 제공해야 합니다. 그래야 생성될 복제 데이터베이스에 대해 자동으로 생성된 값이 사양 파일에 저장됩니다.

+

NOTE: 클론 사양 파일은 _/var/opt/snapcenter/sco/clone_specs_에 생성됩니다.

. 복제 리소스 그룹 또는 기존 백업에서 복제 작업을 시작합니다: _New-SmClone_
+
이 명령은 복제 작업을 시작합니다.  복제 작업을 위해 Oracle 복제 사양 파일 경로도 제공해야 합니다.  또한 복구 옵션, 복제 작업을 수행할 호스트, 사전 스크립트, 사후 스크립트 및 기타 세부 정보를 지정할 수 있습니다.

+
기본적으로 복제 데이터베이스의 아카이브 로그 대상 파일은 _$ORACLE_HOME/CLONE_SIDs_에 자동으로 채워집니다.


