---
permalink: protect-sco/task_configure_snapcenter_plug_in_loader_service.html 
sidebar: sidebar 
keywords: SPL, plug-in loader service 
summary: SnapCenter 플러그인 Loader 서비스는 Linux 또는 AIX용 플러그인 패키지를 로드하여 SnapCenter 서버와 상호 작용합니다.  SnapCenter 플러그인 Loader 서비스는 Linux용 SnapCenter 플러그인 패키지 또는 AIX용 SnapCenter 플러그인 패키지를 설치할 때 설치됩니다. 
---
= SnapCenter 플러그인 Loader 서비스 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 플러그인 Loader 서비스는 Linux 또는 AIX용 플러그인 패키지를 로드하여 SnapCenter 서버와 상호 작용합니다.  SnapCenter 플러그인 Loader 서비스는 Linux용 SnapCenter 플러그인 패키지 또는 AIX용 SnapCenter 플러그인 패키지를 설치할 때 설치됩니다.

*이 작업에 관하여*

Linux용 SnapCenter 플러그인 패키지 또는 AIX용 SnapCenter 플러그인 패키지를 설치하면 SnapCenter 플러그인 Loader 서비스가 자동으로 시작됩니다.  SnapCenter 플러그인 Loader 서비스가 자동으로 시작되지 않으면 다음을 수행해야 합니다.

* 플러그인이 작동 중인 디렉토리가 삭제되지 않았는지 확인하세요.
* Java Virtual Machine에 할당된 메모리 공간을 늘리세요


_/custom_location/ NetApp/snapcenter/spl/etc/_에 있는 spl.properties 파일에는 다음 매개변수가 포함되어 있습니다.  이러한 매개변수에는 기본값이 할당됩니다.

|===
| 매개변수 이름 | 설명 


 a| 
로그 레벨
 a| 
지원되는 로그 수준을 표시합니다.

가능한 값은 TRACE, DEBUG, INFO, WARN, ERROR, FATAL입니다.



 a| 
SPL_프로토콜
 a| 
SnapCenter 플러그인 Loader 가 지원하는 프로토콜을 표시합니다.

HTTPS 프로토콜만 지원됩니다.  기본값이 없는 경우 값을 추가할 수 있습니다.



 a| 
SNAPCENTER_SERVER_프로토콜
 a| 
SnapCenter Server에서 지원하는 프로토콜을 표시합니다.

HTTPS 프로토콜만 지원됩니다.  기본값이 없는 경우 값을 추가할 수 있습니다.



 a| 
자바 홈 업데이트 건너뛰기
 a| 
기본적으로 SPL 서비스는 Java 경로를 감지하고 JAVA_HOME 매개변수를 업데이트합니다.

따라서 기본값은 FALSE로 설정됩니다.  기본 동작을 비활성화하고 Java 경로를 수동으로 수정하려면 TRUE로 설정하면 됩니다.



 a| 
SPL_키스토어_패스
 a| 
키스토어 파일의 비밀번호를 표시합니다.

비밀번호를 변경하거나 새로운 키스토어 파일을 만드는 경우에만 이 값을 변경할 수 있습니다.



 a| 
SPL_PORT
 a| 
SnapCenter 플러그인 Loader 서비스가 실행 중인 포트 번호를 표시합니다.

기본값이 없는 경우 값을 추가할 수 있습니다.


NOTE: 플러그인을 설치한 후에는 값을 변경하지 마세요.



 a| 
SNAPCENTER_SERVER_HOST
 a| 
SnapCenter 서버의 IP 주소 또는 호스트 이름을 표시합니다.



 a| 
SPL_키스토어_경로
 a| 
키스토어 파일의 절대 경로를 표시합니다.



 a| 
SNAPCENTER_SERVER_PORT
 a| 
SnapCenter 서버가 실행 중인 포트 번호를 표시합니다.



 a| 
LOGS_MAX_COUNT
 a| 
_/custom_location/snapcenter/spl/logs_ 폴더에 보관된 SnapCenter 플러그인 Loader 로그 파일의 수를 표시합니다.

기본값은 5000으로 설정되어 있습니다.  개수가 지정된 값보다 많으면 마지막으로 수정된 5000개의 파일이 보존됩니다.  SnapCenter 플러그인 Loader 서비스가 시작된 후 24시간마다 파일 개수 확인이 자동으로 수행됩니다.


NOTE: spl.properties 파일을 수동으로 삭제하면 보존되는 파일 수가 9999로 설정됩니다.



 a| 
자바 홈
 a| 
SPL 서비스를 시작하는 데 사용되는 JAVA_HOME의 절대 디렉토리 경로를 표시합니다.

이 경로는 설치 중 및 SPL 시작의 일부로 결정됩니다.



 a| 
로그 최대 크기
 a| 
작업 로그 파일의 최대 크기를 표시합니다.

최대 크기에 도달하면 로그 파일이 압축되고 로그는 해당 작업의 새 파일에 기록됩니다.



 a| 
지난 며칠 동안의 로그 보관
 a| 
로그가 보관되는 일수를 표시합니다.



 a| 
인증서 검증 활성화
 a| 
호스트에 대해 CA 인증서 검증이 활성화된 경우 true로 표시됩니다.

spl.properties를 편집하거나 SnapCenter GUI 또는 cmdlet을 사용하여 이 매개변수를 활성화하거나 비활성화할 수 있습니다.

|===
이러한 매개변수 중 하나라도 기본값에 할당되지 않았거나 값을 할당하거나 변경하려는 경우 spl.properties 파일을 수정할 수 있습니다.  spl.properties 파일을 확인하고 파일을 편집하여 매개변수에 할당된 값과 관련된 문제를 해결할 수도 있습니다.  spl.properties 파일을 수정한 후에는 SnapCenter 플러그인 Loader 서비스를 다시 시작해야 합니다.

*단계*

. 필요에 따라 다음 작업 중 하나를 수행합니다.
+
** SnapCenter 플러그인 Loader 서비스를 시작합니다.
+
*** 루트 사용자로 다음을 실행합니다. `/custom_location/NetApp/snapcenter/spl/bin/spl start`
*** 루트가 아닌 사용자로 다음을 실행합니다. `sudo /custom_location/NetApp/snapcenter/spl/bin/spl start`


** SnapCenter 플러그인 Loader 서비스를 중지합니다.
+
*** 루트 사용자로 다음을 실행합니다. `/custom_location/NetApp/snapcenter/spl/bin/spl stop`
*** 루트가 아닌 사용자로 다음을 실행합니다. `sudo /custom_location/NetApp/snapcenter/spl/bin/spl stop`
+

NOTE: stop 명령과 함께 -force 옵션을 사용하면 SnapCenter 플러그인 Loader 서비스를 강제로 중지할 수 있습니다.  하지만 그렇게 하면 기존 작업도 종료되므로 주의해서 작업해야 합니다.



** SnapCenter 플러그인 Loader 서비스를 다시 시작합니다.
+
*** 루트 사용자로 다음을 실행합니다. `/custom_location/NetApp/snapcenter/spl/bin/spl restart`
*** 루트가 아닌 사용자로 다음을 실행합니다. `sudo /custom_location/NetApp/snapcenter/spl/bin/spl restart`


** SnapCenter 플러그인 Loader 서비스의 상태를 확인하세요.
+
*** 루트 사용자로 다음을 실행합니다. `/custom_location/NetApp/snapcenter/spl/bin/spl status`
*** 루트 사용자가 아닌 경우 다음을 실행합니다. `sudo /custom_location/NetApp/snapcenter/spl/bin/spl status`


** SnapCenter 플러그인 Loader 서비스에서 변경 사항을 찾으세요.
+
*** 루트 사용자로 다음을 실행합니다. `/custom_location/NetApp/snapcenter/spl/bin/spl change`
*** 루트가 아닌 사용자로 다음을 실행합니다. `sudo /custom_location/NetApp/snapcenter/spl/bin/spl change`





