---
permalink: protect-sco/task_refresh_a_clone.html 
sidebar: sidebar 
keywords: refresh clone, clone 
summary: '"Refresh-SmClone" 명령을 실행하여 복제본을 새로 고칠 수 있습니다.  이 명령은 데이터베이스의 백업을 생성하고, 기존 복제본을 삭제하고, 같은 이름의 복제본을 생성합니다.' 
---
= 클론 새로 고침
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
_Refresh-SmClone_ 명령을 실행하여 복제본을 새로 고칠 수 있습니다.  이 명령은 데이터베이스의 백업을 생성하고, 기존 복제본을 삭제하고, 같은 이름의 복제본을 생성합니다.


NOTE: PDB 복제본을 새로 고칠 수 없습니다.

*필요한 것*

* 예약된 백업이 활성화되지 않은 상태에서 온라인 전체 백업이나 오프라인 데이터 백업 정책을 만듭니다.
* 백업 실패에 대해서만 정책에서 이메일 알림을 구성합니다.
* 원치 않는 백업이 발생하지 않도록 주문형 백업의 보존 횟수를 적절히 정의합니다.
* 새로 고침 복제 작업을 위해 식별된 리소스 그룹에는 온라인 전체 백업 또는 오프라인 데이터 백업 정책만 연결되어 있는지 확인하세요.
* 데이터베이스가 하나만 있는 리소스 그룹을 만듭니다.
* 클론 새로 고침 명령에 대한 Cron 작업이 생성되는 경우 SnapCenter 일정과 Cron 일정이 데이터베이스 리소스 그룹에 대해 겹치지 않는지 확인하세요.
+
복제 새로 고침 명령에 대해 생성된 크론 작업의 경우 24시간마다 Open-SmConnection을 실행해야 합니다.

* 복제본 SID가 호스트에 대해 고유한지 확인하세요.
+
여러 개의 새로 고침 복제 작업에서 동일한 복제 사양 파일을 사용하거나 동일한 복제 SID를 가진 복제 사양 파일을 사용하는 경우 호스트에서 해당 SID를 가진 기존 복제본이 삭제된 다음 복제본이 생성됩니다.

* 백업 정책이 보조 보호와 함께 활성화되어 있는지 확인하고, 보조 백업을 사용하여 복제본을 생성하기 위해 "`-IncludeSecondaryDetails`"로 복제 사양 파일을 생성하세요.
+
** 기본 복제 사양 파일이 지정되었지만 정책에 보조 업데이트 옵션이 선택된 경우 백업이 생성되고 업데이트가 보조로 전송됩니다.  하지만 복제본은 기본 백업에서 생성됩니다.
** 기본 복제 사양 파일이 지정되고 정책에 보조 업데이트 옵션이 선택되지 않은 경우 백업은 기본에 생성되고 복제본은 기본에서 생성됩니다.




*단계*

. 지정된 사용자에 대해 SnapCenter 서버와의 연결 세션을 시작합니다: _Open-SmConnection_
. 지정된 백업에서 Oracle 데이터베이스 복제 사양을 만듭니다: _New-SmOracleCloneSpecification_
+

NOTE: 2차 데이터 보호 정책이 통합 미러 볼트인 경우 -IncludeSecondaryDetails만 지정합니다.  -SecondaryStorageType을 지정할 필요는 없습니다.

+
이 명령은 지정된 소스 데이터베이스와 해당 백업에 대한 Oracle 데이터베이스 복제 사양 파일을 자동으로 생성합니다.  또한 복제 데이터베이스 SID를 제공해야 합니다. 그래야 생성될 복제 데이터베이스에 대해 자동으로 생성된 값이 사양 파일에 저장됩니다.

+

NOTE: 클론 사양 파일은 _/var/opt/snapcenter/sco/clone_specs_에 생성됩니다.

. _Refresh-SmClone_을 실행합니다.
+
"PL-SCO-20032: canExecute 작업이 오류로 인해 실패했습니다: PL-SCO-30031: Redo 로그 파일 +SC_2959770772_clmdb/clmdb/redolog/redo01_01.log가 있습니다" 오류 메시지와 함께 작업이 실패하는 경우 _-WaitToTriggerClone_에 더 높은 값을 지정하세요.

+
UNIX 명령에 대한 자세한 내용은 다음을 참조하세요. https://library.netapp.com/ecm/ecm_download_file/ECMLP3337666["SnapCenter 소프트웨어 명령 참조 가이드"^] .


