---
permalink: protect-sco/task_back_up_oracle_databases_using_unix_commands.html 
sidebar: sidebar 
keywords: backup, cli, commands 
summary: 백업 워크플로에는 계획, 백업 리소스 식별, 백업 정책 생성, 리소스 그룹 생성 및 정책 연결, 백업 생성, 작업 모니터링이 포함됩니다. 
---
= UNIX 명령을 사용하여 Oracle 데이터베이스 백업
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
백업 워크플로에는 계획, 백업 리소스 식별, 백업 정책 생성, 리소스 그룹 생성 및 정책 연결, 백업 생성, 작업 모니터링이 포함됩니다.

*필요한 것*

* _Add-SmStorageConnection_ 및 _Add-SmCredential_ 명령을 사용하여 스토리지 시스템 연결을 추가하고 자격 증명을 생성했어야 합니다.
* _Open-SmConnection_ 명령을 사용하여 SnapCenter 서버와의 연결 세션을 설정했어야 합니다.
+
SnapCenter 계정 로그인 세션은 하나만 가질 수 있으며 토큰은 사용자 홈 디렉토리에 저장됩니다.

+

NOTE: 연결 세션은 24시간 동안만 유효합니다.  하지만 TokenNeverExpires 옵션을 사용하여 토큰을 생성하면 만료되지 않는 토큰을 생성할 수 있으며 세션은 항상 유효합니다.



*이 작업에 관하여*

SnapCenter 서버와의 연결을 설정하고, Oracle 데이터베이스 인스턴스를 검색하고, 정책과 리소스 그룹을 추가하고, 백업하고, 백업을 확인하려면 다음 명령을 실행해야 합니다.

명령과 함께 사용할 수 있는 매개변수와 해당 설명에 대한 정보는 Get-Help _command_name_을 실행하면 얻을 수 있습니다. 또는 다음을 참조할 수도 있습니다. https://library.netapp.com/ecm/ecm_download_file/ECMLP3337666["SnapCenter 소프트웨어 명령 참조 가이드"^] .

*단계*

. 지정된 사용자에 대해 SnapCenter 서버와의 연결 세션을 시작합니다: _Open-SmConnection_
. 호스트 리소스 검색 작업 수행: _Get-SmResources_
. RAC(Real Application Cluster) 데이터베이스의 백업 작업을 위해 Oracle 데이터베이스 자격 증명 및 기본 노드를 구성합니다: _Configure-SmOracleDatabase_
. 백업 정책 만들기: _Add-SmPolicy_
. 보조(SnapVault 또는 SnapMirror) 저장소 위치에 대한 정보를 검색합니다: _Get-SmSecondaryDetails_
+
이 명령은 지정된 리소스의 기본 저장소와 보조 저장소 간의 매핑 세부 정보를 검색합니다.  백업 리소스 그룹을 생성하는 동안 매핑 세부 정보를 사용하여 보조 검증 설정을 구성할 수 있습니다.

. SnapCenter 에 리소스 그룹 추가: _Add-SmResourceGroup_
. 백업 만들기: _New-SmBackup_
+
WaitForCompletion 옵션을 사용하여 작업을 폴링할 수 있습니다.  이 옵션이 지정되면 명령은 백업 작업이 완료될 때까지 서버를 계속 폴링합니다.

. SnapCenter 에서 로그 검색: _Get-SmLogs_

