---
permalink: protect-sco/task_define_a_restore_and_recovery_strategy_for_oracle_databases.html 
sidebar: sidebar 
keywords: backup types, restore methods, connect-and-copy restore, full restore, partial restore, in-place restore, recovery type, limitations 
summary: 데이터베이스를 복원하고 복구하기 전에 전략을 정의해야 복원 및 복구 작업을 성공적으로 수행할 수 있습니다. 
---
= Oracle 데이터베이스에 대한 복원 및 복구 전략 정의
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터베이스를 복원하고 복구하기 전에 전략을 정의해야 복원 및 복구 작업을 성공적으로 수행할 수 있습니다.



== 복원 및 복구 작업에 지원되는 백업 유형

SnapCenter 다양한 유형의 Oracle 데이터베이스 백업의 복원 및 복구를 지원합니다.

* 온라인 데이터 백업
* 오프라인 종료 데이터 백업
* 오프라인 마운트 데이터 백업
+

NOTE: 오프라인 종료 또는 오프라인 마운트 데이터 백업을 복원하는 경우 SnapCenter 데이터베이스를 오프라인 상태로 둡니다.  데이터베이스를 수동으로 복구하고 로그를 재설정해야 합니다.

* 전체 백업
* Data Guard 대기 데이터베이스의 오프라인 마운트 백업
* Active Data Guard 대기 데이터베이스의 데이터 전용 온라인 백업
+

NOTE: Active Data Guard 대기 데이터베이스의 복구를 수행할 수 없습니다.

* RAC(Real Application Clusters) 구성에서의 온라인 데이터 백업, 온라인 전체 백업, 오프라인 마운트 백업 및 오프라인 종료 백업
* ASM(자동 스토리지 관리) 구성의 온라인 데이터 백업, 온라인 전체 백업, 오프라인 마운트 백업 및 오프라인 종료 백업




== Oracle 데이터베이스에 지원되는 복원 방법 유형

SnapCenter Oracle 데이터베이스에 대한 연결 및 복사 또는 제자리 복원을 지원합니다.  복원 작업 중에 SnapCenter 데이터 손실 없이 복원하는 데 사용할 파일 시스템에 적합한 복원 방법을 결정합니다.


NOTE: SnapCenter 볼륨 기반 SnapRestore 지원하지 않습니다.



=== 연결 및 복사 복원

데이터베이스 레이아웃이 백업과 다르거나 백업이 생성된 후 새 파일이 있는 경우 연결 및 복사 복원이 수행됩니다.  연결 및 복사 복원 방법에서는 다음 작업이 수행됩니다.

*단계*

. 볼륨은 스냅샷에서 복제되고 파일 시스템 스택은 복제된 LUN이나 볼륨을 사용하여 호스트에 구축됩니다.
. 파일은 복제된 파일 시스템에서 원본 파일 시스템으로 복사됩니다.
. 복제된 파일 시스템은 호스트에서 마운트 해제되고 복제된 볼륨은 ONTAP 에서 삭제됩니다.



NOTE: Flex ASM 설정(카디널리티가 RAC 클러스터의 노드 수보다 작은 경우) 또는 VMDK 또는 RDM의 ASM RAC 데이터베이스의 경우 연결 및 복사 복원 방법만 지원됩니다.

강제로 제자리 복원을 활성화한 경우에도 SnapCenter 다음과 같은 시나리오에서 연결 및 복사 복원을 수행합니다.

* 보조 저장 시스템에서 복원
* 데이터베이스 인스턴스가 구성되지 않은 Oracle RAC 설정의 노드에 있는 ASM 디스크 그룹 복원
* Oracle RAC 설정에서 ASM 인스턴스 또는 클러스터 인스턴스가 실행 중이 아니거나 피어 노드가 다운된 경우 피어 노드 중 하나에서
* 제어 파일만 복원
* ASM 디스크 그룹에 있는 테이블스페이스 하위 집합 복원
* 디스크 그룹은 데이터 파일, sp 파일 및 암호 파일 간에 공유됩니다.
* RAC 환경의 원격 노드에 SnapCenter 플러그인 Loader (SPL) 서비스가 설치되지 않았거나 실행되지 않습니다.
* Oracle RAC에 새 노드가 추가되고 SnapCenter Server는 새로 추가된 노드를 인식하지 못합니다.




=== 제자리 복원

데이터베이스 레이아웃이 백업과 유사하고 저장소 및 데이터베이스 스택에서 구성이 변경되지 않은 경우, 파일이나 LUN의 복원이 ONTAP 에서 수행되는 제자리 복원이 수행됩니다.  SnapCenter 제자리 복원 방법의 일부로 SFSR(단일 파일 SnapRestore )만 지원합니다.


NOTE: NetApp ONTAP 보조 위치에서의 원위치 복원을 지원합니다.

데이터베이스에서 제자리 복원을 수행하려면 ASM 디스크 그룹에 데이터 파일만 있는지 확인하세요.  ASM 디스크 그룹이나 데이터베이스의 물리적 구조가 변경된 후에는 백업을 만들어야 합니다.  제자리 복원을 수행한 후에는 디스크 그룹에 백업 시점과 동일한 수의 데이터 파일이 포함됩니다.

디스크 그룹 또는 마운트 지점이 다음 기준과 일치하면 제자리 복원이 자동으로 적용됩니다.

* 백업 후 새로운 데이터 파일이 추가되지 않습니다(외부 파일 검사)
* 백업 후 ASM 디스크 또는 LUN 추가, 삭제 또는 재생성 없음(ASM 디스크 그룹 구조 변경 확인)
* LVM 디스크 그룹에 LUN 추가, 삭제 또는 재생성 없음(LVM 디스크 그룹 구조 변경 확인)



NOTE: GUI, SnapCenter CLI 또는 PowerShell cmdlet을 사용하여 강제로 제자리 복원을 활성화하여 외부 파일 검사 및 LVM 디스크 그룹 구조 변경 검사를 재정의할 수도 있습니다.



==== ASM RAC에서 제자리 복원 수행

SnapCenter 에서 복원을 수행하는 노드를 기본 노드라고 하며, ASM 디스크 그룹이 있는 RAC의 다른 모든 노드를 피어 노드라고 합니다.  SnapCenter 스토리지 복원 작업을 수행하기 전에 ASM 디스크 그룹이 마운트 상태인 모든 노드에서 ASM 디스크 그룹의 상태를 마운트 해제로 변경합니다.  저장소 복원이 완료되면 SnapCenter ASM 디스크 그룹의 상태를 복원 작업 전 상태로 변경합니다.

SAN 환경에서 SnapCenter 모든 피어 노드에서 장치를 제거하고 스토리지 복원 작업 전에 LUN 매핑 해제 작업을 수행합니다.  저장소 복구 작업 후 SnapCenter LUN 맵 작업을 수행하고 모든 피어 노드에 장치를 구성합니다.  SAN 환경에서 Oracle RAC ASM 레이아웃이 LUN에 상주하는 경우 SnapCenter 복원하는 동안 ASM 디스크 그룹이 있는 RAC 클러스터의 모든 노드에서 LUN 매핑 해제, LUN 복원 및 LUN 매핑 작업을 수행합니다.  RAC 노드의 모든 이니시에이터가 LUN에 사용되지 않았더라도 복원하기 전에 SnapCenter 복원 후 모든 RAC 노드의 모든 이니시에이터로 새 iGroup을 생성합니다.

* 피어 노드에서 사전 복구 작업 중에 오류가 발생하면 SnapCenter 사전 복구 작업이 성공한 피어 노드에서 복구를 수행하기 전의 ASM 디스크 그룹 상태를 자동으로 롤백합니다.  작업이 실패한 기본 노드와 피어 노드에 대한 롤백은 지원되지 않습니다.  다른 복원을 시도하기 전에 피어 노드에서 문제를 수동으로 해결하고 기본 노드의 ASM 디스크 그룹을 마운트 상태로 되돌려야 합니다.
* 복구 작업 중에 오류가 발생하면 복구 작업이 실패하고 롤백이 수행되지 않습니다.  다른 복원을 시도하기 전에 스토리지 복원 문제를 수동으로 해결하고 기본 노드의 ASM 디스크 그룹을 마운트 상태로 되돌려야 합니다.
* 피어 노드 중 하나에서 복원 후 작업 중에 오류가 발생하면 SnapCenter 다른 피어 노드에서 복원 작업을 계속합니다.  피어 노드에서 복원 후 문제를 수동으로 해결해야 합니다.




== Oracle 데이터베이스에서 지원되는 복원 작업 유형

SnapCenter 사용하면 Oracle 데이터베이스에 대해 다양한 유형의 복원 작업을 수행할 수 있습니다.

데이터베이스를 복원하기 전에 백업을 검증하여 실제 데이터베이스 파일과 비교했을 때 누락된 파일이 있는지 확인합니다.



=== 전체 복원

* 데이터 파일만 복원합니다.
* 제어 파일만 복원합니다.
* 데이터 파일과 제어 파일을 복원합니다.
* Data Guard 대기 및 Active Data Guard 대기 데이터베이스에서 데이터 파일, 제어 파일 및 리두 로그 파일을 복원합니다.




=== 부분 복원

* 선택된 테이블스페이스만 복원합니다.
* 선택된 플러그형 데이터베이스(PDB)만 복원합니다.
* PDB의 선택된 테이블스페이스만 복원합니다.




== Oracle 데이터베이스에서 지원되는 복구 작업 유형

SnapCenter 사용하면 Oracle 데이터베이스에 대해 다양한 유형의 복구 작업을 수행할 수 있습니다.

* 마지막 트랜잭션까지의 데이터베이스(모든 로그)
* 특정 시스템 변경 번호(SCN)까지의 데이터베이스
* 특정 날짜 및 시간까지의 데이터베이스
+
데이터베이스 호스트의 표준 시간대를 기준으로 복구 날짜와 시간을 지정해야 합니다.

+
SnapCenter Oracle 데이터베이스에 대한 복구 불가 옵션도 제공합니다.




NOTE: Oracle 데이터베이스용 플러그인은 데이터베이스 역할을 대기로 설정하여 생성된 백업을 사용하여 복원한 경우 복구를 지원하지 않습니다.  물리적 대기 데이터베이스에 대해서는 항상 수동 복구를 수행해야 합니다.



== Oracle 데이터베이스 복원 및 복구와 관련된 제한 사항

복원 및 복구 작업을 수행하기 전에 제한 사항을 알아야 합니다.

11.2.0.4에서 12.1.0.1까지의 Oracle 버전을 사용하는 경우 _renamedg_ 명령을 실행하면 복원 작업이 중단됩니다.  이 문제를 해결하려면 Oracle 패치 19544733을 적용하세요.

다음 복원 및 복구 작업은 지원되지 않습니다.

* 루트 컨테이너 데이터베이스(CDB)의 테이블스페이스 복원 및 복구
* 임시 테이블스페이스 및 PDB와 연관된 임시 테이블스페이스 복원
* 여러 PDB에서 동시에 테이블스페이스 복원 및 복구
* 로그 백업 복원
* 백업을 다른 위치로 복원
* Data Guard 대기 또는 Active Data Guard 대기 데이터베이스 이외의 모든 구성에서 REDO 로그 파일 복원
* SPFILE 및 비밀번호 파일 복원
* 동일한 호스트에서 기존 데이터베이스 이름을 사용하여 재생성된 데이터베이스에서 복원 작업을 수행하고, SnapCenter 에서 관리하며, 유효한 백업이 있는 경우, DBID가 다르더라도 복원 작업은 새로 생성된 데이터베이스 파일을 덮어씁니다.
+
다음 작업 중 하나를 수행하면 이를 방지할 수 있습니다.

+
** 데이터베이스가 다시 생성된 후 SnapCenter 리소스를 검색합니다.
** 다시 생성된 데이터베이스의 백업을 만듭니다.






== 테이블스페이스의 특정 시점 복구와 관련된 제한 사항

* SYSTEM, SYSAUX 및 UNDO 테이블스페이스의 PITR(Point-in-Time Recovery)이 지원되지 않습니다.
* 테이블스페이스의 PITR은 다른 유형의 복원과 함께 수행할 수 없습니다.
* 테이블스페이스 이름이 변경되고 이름이 변경되기 전 시점으로 복구하려는 경우 테이블스페이스의 이전 이름을 지정해야 합니다.
* 한 테이블스페이스의 테이블에 대한 제약 조건이 다른 테이블스페이스에 포함되어 있는 경우 두 테이블스페이스를 모두 복구해야 합니다.
* 테이블과 해당 인덱스가 서로 다른 테이블스페이스에 저장된 경우 PITR을 수행하기 전에 인덱스를 삭제해야 합니다.
* PITR을 사용하여 현재 기본 테이블스페이스를 복구할 수 없습니다.
* PITR은 다음 개체가 포함된 테이블스페이스를 복구하는 데 사용할 수 없습니다.
+
** 기본 객체(예: 구체화된 뷰)가 있는 객체 또는 포함된 객체(예: 분할된 테이블)가 모두 복구 세트에 없는 경우
+
또한, 파티션된 테이블의 파티션이 서로 다른 테이블스페이스에 저장되어 있는 경우 PITR을 수행하기 전에 테이블을 삭제하거나 PITR을 수행하기 전에 모든 파티션을 동일한 테이블스페이스로 이동해야 합니다.

** 세그먼트 실행 취소 또는 롤백
** 여러 수신자가 있는 Oracle 8 호환 고급 대기열
** SYS 사용자가 소유한 객체
+
이러한 유형의 객체의 예로는 PL/SQL, Java 클래스, 콜아웃 프로그램, 뷰, 동의어, 사용자, 권한, 차원, 디렉토리, 시퀀스 등이 있습니다.







== Oracle 데이터베이스 복원을 위한 소스 및 대상

기본 저장소나 보조 저장소의 백업 사본에서 Oracle 데이터베이스를 복원할 수 있습니다.  동일한 데이터베이스 인스턴스의 동일한 위치로만 데이터베이스를 복원할 수 있습니다.  하지만 RAC(Real Application Cluster) 설정에서는 데이터베이스를 다른 노드로 복원할 수 있습니다.



=== 복원 작업을 위한 소스

기본 저장소나 보조 저장소의 백업에서 데이터베이스를 복원할 수 있습니다.  다중 미러 구성에서 보조 저장소의 백업에서 복원하려는 경우 보조 저장소 미러를 소스로 선택할 수 있습니다.



=== 복원 작업의 대상지

동일한 데이터베이스 인스턴스의 동일한 위치로만 데이터베이스를 복원할 수 있습니다.

RAC 설정에서는 클러스터의 모든 노드에서 RAC 데이터베이스를 복원할 수 있습니다.
