---
permalink: protect-sce/concept_snapcenter_plug_in_for_exchange_server_overview.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for Exchange Server 
summary: Microsoft Exchange Server용 SnapCenter 플러그인은 Exchange 데이터베이스의 애플리케이션 인식 데이터 보호 관리를 지원하는 NetAppSnapCenter 소프트웨어의 호스트 측 구성 요소입니다.  Exchange용 플러그인은 SnapCenter 환경에서 Exchange 데이터베이스의 백업 및 복원을 자동화합니다. 
---
= Microsoft Exchange Server용 SnapCenter 플러그인 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Microsoft Exchange Server용 SnapCenter 플러그인은 Exchange 데이터베이스의 애플리케이션 인식 데이터 보호 관리를 지원하는 NetApp SnapCenter 소프트웨어의 호스트 측 구성 요소입니다.  Exchange용 플러그인은 SnapCenter 환경에서 Exchange 데이터베이스의 백업 및 복원을 자동화합니다.

Exchange용 플러그인을 설치하면 NetApp SnapMirror 기술과 함께 SnapCenter 사용하여 다른 볼륨에 백업 세트의 미러 사본을 만들고 NetApp SnapVault 기술을 사용하여 표준 준수 또는 보관 목적으로 디스크 간 백업 복제를 수행할 수 있습니다.

전체 Exchange 데이터베이스 대신 메일이나 사서함을 복원하고 복구하려는 경우 SMBR(Single Mailbox Recovery) 소프트웨어를 사용할 수 있습니다.  NetApp® Single Mailbox Recovery는 2023년 5월 12일에 제공이 종료되었습니다(EOA).  NetApp 2020년 6월 24일에 출시된 마케팅 부품 번호를 통해 사서함 용량, 유지 관리 및 지원을 구매한 고객을 지원 자격 기간 동안 계속 지원할 것입니다.

NetApp Single Mailbox Recovery는 Ontrack에서 제공하는 파트너 제품입니다.  Ontrack PowerControls는 NetApp Single Mailbox Recovery와 유사한 기능을 제공합니다.  고객은 Ontrack(licensingteam@ontrack.com)을 통해 새로운 Ontrack PowerControls 소프트웨어 라이선스와 Ontrack PowerControls 유지관리 및 지원 갱신을 구매하여 세부적인 사서함 복구를 할 수 있습니다.

Exchange용 플러그인은 SnapMirror Active Sync(처음에는 SnapMirror Business Continuity[SM-BC]로 출시)를 지원하여 사이트 전체에 장애가 발생하더라도 비즈니스 서비스가 계속 운영될 수 있도록 하며, 보조 복사본을 사용하여 애플리케이션이 투명하게 장애 조치되도록 지원합니다.  SnapMirror Active Sync를 사용하면 장애 조치를 트리거하는 데 수동 개입이나 추가 스크립팅이 필요하지 않습니다.

SnapMirror Active Sync의 비대칭, 장애 조치 또는 비이중 모드를 지원합니다.  이는 최적화된 경로가 기본 측 LUN 소유 노드에서만 생성되는 솔루션을 말합니다.  보조 클러스터 경로에서 발생하는 모든 I/O는 기본 클러스터로 프록시되어 처리됩니다.  동기 복제는 단방향, 즉 기본 복제에서 보조 복제로 진행됩니다.

* SnapCenter 환경에서 Microsoft Exchange Server 데이터베이스 및 DAG(데이터베이스 가용성 그룹)에 대한 애플리케이션 인식 백업 및 복원 작업을 자동화합니다.
* SnapCenter Plug-in for VMware vSphere 배포하고 SnapCenter 에 플러그인을 등록하면 RDM LUN에서 가상화된 Exchange 서버를 지원합니다.

