---
permalink: protect-sce/reference_prerequisites_to_add_hosts_and_install_snapcenter_plug_in_for_microsoft_exchange_server.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for Microsoft Exchange Server 
summary: 호스트를 추가하고 플러그인 패키지를 설치하기 전에 모든 요구 사항을 충족해야 합니다. 
---
= Microsoft Exchange Server용 SnapCenter 플러그인을 설치하고 호스트를 추가하기 위한 전제 조건
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
호스트를 추가하고 플러그인 패키지를 설치하기 전에 모든 요구 사항을 충족해야 합니다.

* iSCSI를 사용하는 경우 iSCSI 서비스가 실행 중이어야 합니다.
* 원격 호스트에 로컬 로그인 권한이 있는 로컬 관리자 권한이 있는 도메인 사용자가 있어야 합니다.
* 독립 실행형 및 데이터베이스 가용성 그룹 구성에는 Microsoft Exchange Server 2013, 2016 또는 2019를 사용해야 합니다.
* Windows 호스트에 플러그인을 설치할 때 기본 제공되지 않은 자격 증명을 지정하거나 사용자가 로컬 작업 그룹 사용자에 속하는 경우 호스트에서 UAC를 비활성화해야 합니다.
* SnapCenter 에서 클러스터 노드를 관리하는 경우 클러스터의 모든 노드에 대한 관리 권한이 있는 사용자가 있어야 합니다.
* Exchange Server에 대한 관리 권한이 있는 사용자가 있어야 합니다.
* Microsoft Exchange Server용 SnapManager 와 Windows용 SnapDrive 이미 설치되어 있는 경우 SnapCenter 사용하여 데이터를 성공적으로 보호하려면 동일한 Exchange Server에 Exchange용 플러그인을 설치하기 전에 SnapDrive for Windows에서 사용하는 VSS 하드웨어 공급자를 등록 취소해야 합니다.
* SnapManager for Microsoft Exchange Server와 Plug-in for Exchange가 동일한 서버에 설치된 경우 SnapManager for Microsoft Exchange Server에서 생성한 모든 일정을 Windows 스케줄러에서 일시 중단하거나 삭제해야 합니다.
* 호스트는 서버에서 정규화된 도메인 이름(FQDN)으로 확인 가능해야 합니다.  호스트 파일을 수정하여 확인할 수 있게 하고 호스트 파일에 짧은 이름과 FQDN이 모두 지정된 경우 SnapCenter 호스트 파일에 다음 형식으로 항목을 만듭니다. _<ip_address> <host_fqdn> <host_name>_.
* 다음 포트가 방화벽에서 차단되어 있지 않은지 확인하세요. 차단되어 있으면 호스트 추가 작업이 실패합니다.  이 문제를 해결하려면 동적 포트 범위를 구성해야 합니다. 자세한 내용은 다음을 참조하세요.  https://docs.microsoft.com/en-us/troubleshoot/windows-server/networking/configure-rpc-dynamic-port-allocation-with-firewalls["Microsoft 설명서"^] .
+
** Windows 2016 및 Exchange 2016의 포트 범위 50000~51000
** Windows 2012 R2 및 Exchange 2013의 경우 포트 범위 6000~6500
** Windows 2019의 포트 범위 49152 - 65536




[NOTE]
====
포트 범위를 식별하려면 다음 명령을 실행하세요.

* netsh int ipv4 show dynamicport tcp
* netsh int ipv4 show dynamicport udp
* netsh int ipv6 show dynamicport tcp
* netsh int ipv6 show dynamicport udp


====


== Windows용 SnapCenter 플러그인 패키지를 설치하기 위한 호스트 요구 사항

Windows용 SnapCenter 플러그인 패키지를 설치하기 전에 몇 가지 기본적인 호스트 시스템 공간 요구 사항과 크기 요구 사항을 숙지해야 합니다.

|===
| 목 | 요구 사항 


 a| 
운영 체제
 a| 
마이크로소프트 윈도우

지원되는 버전에 대한 최신 정보는 다음을 참조하세요. https://imt.netapp.com/imt/imt.jsp?components=134502;&solution=1258&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 도구"^] .



 a| 
호스트의 SnapCenter 플러그인을 위한 최소 RAM
 a| 
1GB



 a| 
호스트의 SnapCenter 플러그인에 대한 최소 설치 및 로그 공간
 a| 
5GB


NOTE: 충분한 디스크 공간을 할당하고 로그 폴더의 저장 공간 소비를 모니터링해야 합니다.  필요한 로그 공간은 보호해야 할 엔터티의 수와 데이터 보호 작업의 빈도에 따라 달라집니다.  디스크 공간이 충분하지 않으면 최근 실행된 작업에 대한 로그가 생성되지 않습니다.



 a| 
필수 소프트웨어 패키지
 a| 
* ASP.NET Core Runtime 8.0.12(및 이후 모든 8.0.x 패치) 호스팅 번들
* 파워셸 코어 7.4.2
* Java 11 Oracle Java 및 OpenJDK
+
Java 11 Oracle Java 및 OpenJDK는 SAP HANA, IBM Db2, PostgreSQL, MySQL, NetApp 지원 플러그인 및 Windows 호스트에 설치할 수 있는 기타 사용자 정의 애플리케이션에만 필요합니다.



지원되는 버전에 대한 최신 정보는 다음을 참조하세요. https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 도구"^] .

.NET 관련 문제 해결 정보는 다음을 참조하세요. https://kb.netapp.com/mgmt/SnapCenter/SnapCenter_upgrade_or_install_fails_with_This_KB_is_not_related_to_the_OS["인터넷 연결이 없는 레거시 시스템에서는 SnapCenter 업그레이드 또는 설치가 실패합니다."]

|===


== Exchange Server 권한이 필요합니다

SnapCenter Exchange Server 또는 DAG를 추가하고 호스트 또는 DAG에 Microsoft Exchange Server용 SnapCenter 플러그인을 설치하도록 하려면 최소한의 권한 및 사용 권한이 있는 사용자의 자격 증명으로 SnapCenter 구성해야 합니다.

로컬 관리자 권한이 있는 도메인 사용자가 있어야 하며, 원격 Exchange 호스트에 대한 로컬 로그인 권한과 DAG의 모든 노드에 대한 관리 권한이 있어야 합니다.  도메인 사용자에게는 다음과 같은 최소 권한이 필요합니다.

* Add-MailboxDatabaseCopy
* Dismount-데이터베이스
* Get-AdServerSettings
* Get-DatabaseAvailabilityGroup
* Get-ExchangeServer
* Get-MailboxDatabase
* Get-MailboxDatabaseCopyStatus
* Get-MailboxServer
* Get-MailboxStatistics
* Get-PublicFolderDatabase
* Move-ActiveMailboxDatabase
* Move-DatabasePath -ConfigurationOnly:$true
* 마운트-데이터베이스
* 새 사서함 데이터베이스
* 새로운 공개 폴더 데이터베이스
* Remove-MailboxDatabase
* Remove-MailboxDatabaseCopy
* Remove-PublicFolderDatabase
* 이력서-사서함 데이터베이스 복사
* 광고 서버 설정 설정
* Set-MailboxDatabase -allowfilerestore:$true
* Set-MailboxDatabaseCopy
* Set-PublicFolderDatabase
* 일시 중단-사서함 데이터베이스 복사
* 업데이트-사서함데이터베이스복사




== Windows용 SnapCenter 플러그인 패키지를 설치하기 위한 호스트 요구 사항

Windows용 SnapCenter 플러그인 패키지를 설치하기 전에 몇 가지 기본적인 호스트 시스템 공간 요구 사항과 크기 요구 사항을 숙지해야 합니다.

|===
| 목 | 요구 사항 


 a| 
운영 체제
 a| 
마이크로소프트 윈도우

지원되는 버전에 대한 최신 정보는 다음을 참조하세요. https://imt.netapp.com/imt/imt.jsp?components=134502;&solution=1258&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 도구"^] .



 a| 
호스트의 SnapCenter 플러그인을 위한 최소 RAM
 a| 
1GB



 a| 
호스트의 SnapCenter 플러그인에 대한 최소 설치 및 로그 공간
 a| 
5GB


NOTE: 충분한 디스크 공간을 할당하고 로그 폴더의 저장 공간 소비를 모니터링해야 합니다.  필요한 로그 공간은 보호해야 할 엔터티의 수와 데이터 보호 작업의 빈도에 따라 달라집니다.  디스크 공간이 충분하지 않으면 최근 실행된 작업에 대한 로그가 생성되지 않습니다.



 a| 
필수 소프트웨어 패키지
 a| 
* ASP.NET Core Runtime 8.0.12(및 이후 모든 8.0.x 패치) 호스팅 번들
* 파워셸 코어 7.4.2
* Java 11 Oracle Java 및 OpenJDK
+
Java 11 Oracle Java 및 OpenJDK는 SAP HANA, IBM Db2, PostgreSQL, MySQL, NetApp 지원 플러그인 및 Windows 호스트에 설치할 수 있는 기타 사용자 정의 애플리케이션에만 필요합니다.



지원되는 버전에 대한 최신 정보는 다음을 참조하세요. https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 도구"^] .

.NET 관련 문제 해결 정보는 다음을 참조하세요. https://kb.netapp.com/mgmt/SnapCenter/SnapCenter_upgrade_or_install_fails_with_This_KB_is_not_related_to_the_OS["인터넷 연결이 없는 레거시 시스템에서는 SnapCenter 업그레이드 또는 설치가 실패합니다."]

|===