---
permalink: protect-sce/task_reseed_a_passive_exchange_node_replica.html 
sidebar: sidebar 
keywords:  
summary: 예를 들어 복사본이 손상된 경우 복제본을 다시 시드해야 하는 경우 SnapCenter 의 다시 시드 기능을 사용하여 최신 백업으로 다시 시드할 수 있습니다. 
---
= 수동 Exchange 노드 복제본을 다시 시드합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
예를 들어 복사본이 손상된 경우 복제본을 다시 시드해야 하는 경우 SnapCenter 의 다시 시드 기능을 사용하여 최신 백업으로 다시 시드할 수 있습니다.

.시작하기 전에
다시 시딩하려는 데이터베이스의 백업을 만들어야 합니다.

+ 노드 간 지연을 방지하려면 재시드 작업을 수행하기 전에 새 백업을 만들거나 최신 백업이 있는 호스트를 선택할 수 있습니다.

.단계
. 왼쪽 탐색 창에서 *리소스*를 클릭한 다음 목록에서 *Microsoft Exchange Server 플러그인*을 선택합니다.
. 리소스 페이지에서 보기 목록에서 적절한 옵션을 선택하세요.
+
|===
| 옵션 | 설명 


 a| 
단일 데이터베이스를 다시 시드하려면
 a| 
보기 목록에서 *데이터베이스*를 선택합니다.



 a| 
DAG에서 데이터베이스를 다시 시드하려면
 a| 
보기 목록에서 *데이터베이스 가용성 그룹*을 선택합니다.

|===
. 다시 시드할 리소스를 선택하세요.
. 사본 관리 페이지에서 *다시 시드*를 클릭합니다.
. 다시 시드 마법사의 비정상 데이터베이스 복사본 목록에서 다시 시드하려는 복사본을 선택한 후 *다음*을 클릭합니다.
. 호스트 창에서 다시 시딩하려는 백업이 있는 호스트를 선택한 후 *다음*을 클릭합니다.
. 알림 페이지의 *이메일 환경 설정* 드롭다운 목록에서 이메일을 보낼 시나리오를 선택합니다.
+
또한 발신자와 수신자의 이메일 주소와 이메일 제목을 지정해야 합니다.

. 요약을 검토한 후 *마침*을 클릭하세요.
. 페이지 하단의 활동 패널을 확장하면 작업 상태를 볼 수 있습니다.
+

NOTE: 수동 데이터베이스 복사본이 NetApp 스토리지가 아닌 곳에 있는 경우 다시 시드 작업이 지원되지 않습니다.


