---
permalink: protect-sce/task_define_a_restore_strategy_for_exchange_databases.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: Exchange Server에 대한 복원 전략을 정의하면 데이터베이스를 성공적으로 복원할 수 있습니다. 
---
= Exchange 데이터베이스에 대한 복원 전략 정의
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Exchange Server에 대한 복원 전략을 정의하면 데이터베이스를 성공적으로 복원할 수 있습니다.



== Exchange Server에서 복원 작업을 위한 소스

기본 저장소의 백업 복사본에서 Exchange Server 데이터베이스를 복원할 수 있습니다.

기본 저장소에서만 데이터베이스를 복원할 수 있습니다.



== Exchange Server에서 지원되는 복원 작업 유형

SnapCenter 사용하면 Exchange 리소스에 대해 다양한 유형의 복원 작업을 수행할 수 있습니다.

* 최신 정보를 복원합니다
* 이전 시점으로 복원




=== 최신 상태로 복원

최신 복원 작업에서는 데이터베이스가 오류 발생 지점까지 복구됩니다.  SnapCenter 다음 순서를 수행하여 이를 달성합니다.

. 선택한 전체 데이터베이스 백업에서 데이터베이스를 복원합니다.
. 백업된 모든 트랜잭션 로그와 가장 최근 백업 이후 생성된 모든 새 로그를 적용합니다.
+
거래 로그가 앞으로 이동되어 선택한 데이터베이스에 적용됩니다.

+
복원이 완료되면 Exchange에서 새로운 로그 체인을 만듭니다.

+
|===


| *모범 사례:* 복원이 완료된 후에는 새로운 전체 백업과 로그 백업을 수행하는 것이 좋습니다. 
|===
+
최신 복원 작업에는 연속된 트랜잭션 로그 세트가 필요합니다.

+
최신 복원을 수행한 후에는 복원에 사용한 백업을 특정 시점 복원 작업에만 사용할 수 있습니다.

+
모든 백업에 대한 최신 복원 기능을 유지할 필요가 없는 경우 백업 정책을 통해 시스템의 트랜잭션 로그 백업 보존을 구성할 수 있습니다.





=== 이전 시점으로 복원

지정 시점 복원 작업에서는 데이터베이스가 과거의 특정 시점으로만 복원됩니다.  지정 시간 복원 작업은 다음과 같은 복원 상황에서 발생합니다.

* 데이터베이스는 백업된 트랜잭션 로그의 특정 시간으로 복원됩니다.
* 데이터베이스가 복원되고, 백업된 트랜잭션 로그의 하위 집합만 적용됩니다.

