---
permalink: protect-sce/task_install_the_snapcenter_plug_in_for_exchange_silently_from_the_command_line.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: SnapCenter 사용자 인터페이스 내에서 Exchange용 플러그인을 설치해야 합니다.  하지만 어떤 이유로 실행할 수 없다면 Windows 명령줄에서 자동 모드로 Exchange 플러그인 설치 프로그램을 자동으로 실행할 수 있습니다. 
---
= 명령줄에서 Exchange용 SnapCenter 플러그인을 자동으로 설치합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 사용자 인터페이스 내에서 Exchange용 플러그인을 설치해야 합니다.  하지만 어떤 이유로 실행할 수 없다면 Windows 명령줄에서 자동 모드로 Exchange 플러그인 설치 프로그램을 자동으로 실행할 수 있습니다.

.시작하기 전에
* Microsoft Exchange Server 리소스를 백업해야 합니다.
* SnapCenter 플러그인 패키지를 설치해야 합니다.
* Microsoft SQL Server용 SnapCenter 플러그인을 설치하기 전에 이전 릴리스를 삭제해야 합니다.
+
자세한 내용은 다음을 참조하세요.  https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_Install_a_SnapCenter_Plug-In_manually_and_directly_from_thePlug-In_Host["플러그인 호스트에서 SnapCenter 플러그인을 수동으로 직접 설치하는 방법"^] .



.단계
. 플러그인 호스트에 _C:\temp_ 폴더가 있는지, 로그인한 사용자가 해당 폴더에 대한 전체 액세스 권한이 있는지 확인합니다.
. _C:\ProgramData\ NetApp\ SnapCenter \Package_ Repository에서 Microsoft Windows용 SnapCenter 플러그인을 다운로드하세요.
+
이 경로는 SnapCenter 서버가 설치된 호스트에서 접근할 수 있습니다.

. 플러그인을 설치하려는 호스트에 설치 파일을 복사합니다.
. 로컬 호스트의 Windows 명령 프롬프트에서 플러그인 설치 파일을 저장한 디렉토리로 이동합니다.
. 플러그인을 설치하려면 다음 명령을 입력하세요.
+
_snapcenter_windows_host_plugin.exe"/silent /debuglog"<디버그_로그_경로>" /log"<로그_경로>" BI_SNAPCENTER_PORT=<번호> SUITE_INSTALLDIR="<설치_디렉토리_경로>" BI_SERVICEACCOUNT=<도메인\관리자> BI_SERVICEPWD=<비밀번호> ISFeatureInstall=HPPW,SCW,SCE_

+
예를 들어:

+
_C:\ProgramData\ NetApp\ SnapCenter\Package Repository\snapcenter_windows_host_plugin.exe"/silent /debuglog"C:\HPPW_SCSQL_Install.log" /log"C:\temp" BI_SNAPCENTER_PORT=8145 SUITE_INSTALLDIR="C:\Program Files\ NetApp\ SnapCenter" BI_SERVICEACCOUNT=도메인\관리자 BI_SERVICEPWD=암호 ISFeatureInstall=HPPW,SCW,SCE_

+

NOTE: Exchange 플러그인을 설치하는 동안 전달되는 모든 매개변수는 대소문자를 구분합니다.

+
변수에 다음 값을 입력하세요.

+
|===
| 변하기 쉬운 | 가치 


 a| 
_/debuglog"<디버그_로그_경로>_
 a| 
다음 예와 같이 제품군 설치 프로그램 로그 파일의 이름과 위치를 지정합니다.

_Setup.exe /debuglog"C:\PathToLog\setupexe.log_



 a| 
BI_SNAPCENTER_PORT
 a| 
SnapCenter SMCore와 통신하는 포트를 지정합니다.



 a| 
SUITE_INSTALLDIR
 a| 
호스트 플러그인 패키지 설치 디렉토리를 지정합니다.



 a| 
BI_SERVICEACCOUNT
 a| 
Microsoft Windows 웹 서비스 계정에 대한 SnapCenter 플러그인을 지정합니다.



 a| 
BI_SERVICEPWD
 a| 
Microsoft Windows 웹 서비스 계정용 SnapCenter 플러그인의 비밀번호를 지정합니다.



 a| 
ISFeature설치
 a| 
SnapCenter 가 원격 호스트에 배포할 솔루션을 지정합니다.

|===
. Windows 작업 스케줄러, 기본 설치 로그 파일 _C:\Installdebug.log_ 및 _C:\Temp_에 있는 추가 설치 파일을 모니터링합니다.
. _msiexe.exe_ 설치 프로그램이 오류 없이 소프트웨어를 설치하는지 확인하려면 _%temp%_ 디렉터리를 모니터링하세요.
+

NOTE: Exchange용 플러그인을 설치하면 플러그인이 SnapCenter 서버가 아닌 호스트에 등록됩니다.  SnapCenter GUI 또는 PowerShell cmdlet을 사용하여 호스트를 추가하여 SnapCenter 서버에 플러그인을 등록할 수 있습니다.  호스트가 추가되면 플러그인이 자동으로 검색됩니다.


