---
permalink: protect-sce/task_define_a_backup_strategy_for_exchange_server_resources.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: '백업 작업을 생성하기 전에 백업 전략을 정의하면 데이터베이스를 성공적으로 복원하는 데 필요한 백업이 있는지 확인하는 데 도움이 됩니다.  서비스 수준 계약(SLA), 복구 시간 목표(RTO), 복구 지점 목표(RPO)는 백업 전략을 크게 결정합니다.' 
---
= Exchange Server 리소스에 대한 백업 전략 정의
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
백업 작업을 생성하기 전에 백업 전략을 정의하면 데이터베이스를 성공적으로 복원하는 데 필요한 백업이 있는지 확인하는 데 도움이 됩니다.  백업 전략은 주로 서비스 수준 계약(SLA), 복구 시간 목표(RTO), 복구 지점 목표(RPO)에 따라 결정됩니다.

SLA는 기대되는 서비스 수준을 정의하고 서비스 가용성과 성능을 포함한 많은 서비스 관련 문제를 해결합니다.  RTO는 서비스가 중단된 후 비즈니스 프로세스를 복구해야 하는 시간입니다.  RPO는 장애 발생 후 정상적인 작업을 재개하기 위해 백업 저장소에서 복구해야 하는 파일의 수명에 대한 전략을 정의합니다.  SLA, RTO, RPO는 백업 전략에 기여합니다.



== Exchange 데이터베이스에 지원되는 백업 유형

SnapCenter 사용하여 Exchange 사서함을 백업하려면 데이터베이스 및 DAG(데이터베이스 가용성 그룹)와 같은 리소스 유형을 선택해야 합니다.  스냅샷 기술은 리소스가 있는 볼륨의 온라인, 읽기 전용 복사본을 만드는 데 활용됩니다.

|===
| 백업 유형 | 설명 


 a| 
전체 및 로그 백업
 a| 
잘린 로그를 포함하여 데이터베이스와 모든 트랜잭션 로그를 백업합니다.

전체 백업이 완료되면 Exchange Server는 이미 데이터베이스에 커밋된 트랜잭션 로그를 잘라냅니다.

일반적으로 이 옵션을 선택하는 것이 좋습니다.  하지만 백업 시간이 짧다면 전체 백업과 함께 트랜잭션 로그 백업을 실행하지 않도록 선택할 수 있습니다.



 a| 
전체 백업
 a| 
데이터베이스와 트랜잭션 로그를 백업합니다.

잘린 트랜잭션 로그는 백업되지 않습니다.



 a| 
로그 백업
 a| 
모든 거래 로그를 백업합니다.

이미 데이터베이스에 커밋된 잘린 로그는 백업되지 않습니다.  전체 데이터베이스 백업 사이에 자주 트랜잭션 로그 백업을 예약하면 세분화된 복구 지점을 선택할 수 있습니다.

|===


== 데이터베이스 플러그인에 대한 백업 일정

백업 빈도(일정 유형)는 정책에 지정되고, 백업 일정은 리소스 그룹 구성에 지정됩니다.  백업 빈도나 일정을 결정하는 가장 중요한 요소는 리소스의 변화율과 데이터의 중요도입니다.  자주 사용되는 리소스는 매시간 백업하고, 거의 사용되지 않는 리소스는 하루에 한 번 백업할 수도 있습니다.  기타 요소로는 조직에 대한 리소스의 중요성, 서비스 수준 계약(SLA), 복구 지점 목표(RPO) 등이 있습니다.

SLA는 기대되는 서비스 수준을 정의하고 서비스 가용성과 성능을 포함한 많은 서비스 관련 문제를 해결합니다.  RPO는 장애 발생 후 정상적인 작업을 재개하기 위해 백업 저장소에서 복구해야 하는 파일의 수명에 대한 전략을 정의합니다.  SLA와 RPO는 데이터 보호 전략에 기여합니다.

많이 사용되는 리소스의 경우에도 하루에 한두 번 이상 전체 백업을 실행할 필요는 없습니다.  예를 들어, 정기적인 트랜잭션 로그 백업을 통해 필요한 백업을 확보하는 데 충분할 수 있습니다.  데이터베이스를 더 자주 백업할수록 SnapCenter 복원 시 사용해야 하는 트랜잭션 로그가 줄어들어 복원 작업이 더 빨라질 수 있습니다.

백업 일정은 다음과 같이 두 부분으로 구성됩니다.

* 백업 주파수
+
일부 플러그인의 경우 _스케줄 유형_이라고 하는 백업 빈도(백업을 수행하는 빈도)는 정책 구성의 일부입니다.  정책의 백업 빈도를 시간별, 일별, 주별 또는 월별로 선택할 수 있습니다.  이러한 주파수를 선택하지 않으면 생성된 정책은 주문형 정책만입니다.  *설정* > *정책*을 클릭하면 정책에 액세스할 수 있습니다.

* 백업 일정
+
백업 일정(백업을 정확히 언제 수행해야 하는지)은 리소스 그룹 구성의 일부입니다.  예를 들어, 주간 백업에 대한 정책이 구성된 리소스 그룹이 있는 경우 매주 목요일 오후 10시에 백업하도록 일정을 구성할 수 있습니다.  *리소스* > *리소스 그룹*을 클릭하면 리소스 그룹 일정에 액세스할 수 있습니다.





== 데이터베이스에 필요한 백업 작업 수

필요한 백업 작업 수를 결정하는 요소에는 리소스 크기, 사용된 볼륨 수, 리소스 변경률, 서비스 수준 계약(SLA) 등이 있습니다.



== 백업 명명 규칙

기본 스냅샷 명명 규칙을 사용하거나 사용자 지정 명명 규칙을 사용할 수 있습니다.  기본 백업 명명 규칙은 스냅샷 이름에 타임스탬프를 추가하여 복사본이 생성된 시기를 식별하는 데 도움이 됩니다.

스냅샷은 다음과 같은 기본 명명 규칙을 사용합니다.

`resourcegroupname_hostname_timestamp`

다음 예와 같이 논리적으로 백업 리소스 그룹의 이름을 지정해야 합니다.

[listing]
----
dts1_mach1x88_03-12-2015_23.17.26
----
이 예에서 구문 요소는 다음과 같은 의미를 갖습니다.

* _dts1_은 리소스 그룹 이름입니다.
* _mach1x88_은 호스트 이름입니다.
* _03-12-2015_23.17.26_은 날짜와 타임스탬프입니다.


또는, *스냅샷 복사에 사용자 지정 이름 형식 사용*을 선택하여 리소스나 리소스 그룹을 보호하는 동안 스냅샷 이름 형식을 지정할 수 있습니다.  예를 들어, customtext_resourcegroup_policy_hostname 또는 resourcegroup_hostname입니다.  기본적으로 타임스탬프 접미사는 스냅샷 이름에 추가됩니다.



== 백업 보존 옵션

백업 사본을 보관할 일수를 선택하거나 보관할 백업 사본 수를 지정할 수 있으며, ONTAP 최대 255개 사본까지 보관할 수 있습니다.  예를 들어, 귀하의 조직에서는 10일 분의 백업 사본이나 130개의 백업 사본을 보관하도록 요구할 수 있습니다.

정책을 생성하는 동안 백업 유형과 일정 유형에 대한 보존 옵션을 지정할 수 있습니다.

SnapMirror 복제를 설정하면 보존 정책이 대상 볼륨에 미러링됩니다.

SnapCenter 일정 유형과 일치하는 보존 레이블이 있는 보관된 백업을 삭제합니다.  리소스 또는 리소스 그룹의 일정 유형이 변경된 경우 이전 일정 유형 레이블이 지정된 백업이 시스템에 남아 있을 수 있습니다.


NOTE: 백업 사본을 장기간 보관하려면 SnapVault 백업을 사용해야 합니다.



== Exchange Server의 소스 저장소 볼륨에서 트랜잭션 로그 백업을 보관하는 기간

Microsoft Exchange Server용 SnapCenter 플러그인은 최신 복원 작업을 수행하기 위해 트랜잭션 로그 백업이 필요하며, 이를 통해 두 개의 전체 백업 사이의 시간으로 데이터베이스를 복원합니다.

예를 들어, Plug-in for Exchange가 오전 8시에 전체 백업과 트랜잭션 로그 백업을 수행하고 오후 5시에 또 다른 전체 백업과 트랜잭션 로그 백업을 수행한 경우 최신 트랜잭션 로그 백업을 사용하여 오전 8시와 오후 5시 사이의 어느 시간으로든 데이터베이스를 복원할 수 있습니다. 트랜잭션 로그를 사용할 수 없는 경우 Plug-in for Exchange는 특정 시점 복원 작업만 수행할 수 있으며, 이 경우 Plug-in for Exchange가 전체 백업을 완료한 시점으로 데이터베이스를 복원합니다.

일반적으로 최신 복구 작업은 하루나 이틀 정도만 필요합니다.  기본적으로 SnapCenter 최소 2일간 보관합니다.
