---
permalink: protect-sce/task_add_hosts_and_install_plug_in_for_exchange.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for Microsoft Exchange Server, NET TCP 
summary: SnapCenterAdd Host 페이지를 사용하여 Windows 호스트를 추가할 수 있습니다.  Exchange용 플러그인은 지정된 호스트에 자동으로 설치됩니다.  플러그인을 설치하는 데 권장되는 방법입니다.  개별 호스트나 클러스터에 호스트를 추가하고 플러그인을 설치할 수 있습니다. 
---
= 호스트 추가 및 Exchange용 플러그인 설치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 호스트 추가 페이지를 사용하여 Windows 호스트를 추가할 수 있습니다.  Exchange용 플러그인은 지정된 호스트에 자동으로 설치됩니다.  플러그인을 설치하는 데 권장되는 방법입니다.  개별 호스트나 클러스터에 호스트를 추가하고 플러그인을 설치할 수 있습니다.

.시작하기 전에
* SnapCenter 서버 호스트의 운영 체제가 Windows 2019이고 플러그인 호스트의 운영 체제가 Windows 2022인 경우 다음을 수행해야 합니다.
+
** Windows Server 2019(OS 빌드 17763.5936) 이상으로 업그레이드하세요.
** Windows Server 2022(OS 빌드 20348.2402) 이상으로 업그레이드하세요.


* SnapCenter 관리자와 같이 플러그인 설치 및 제거 권한이 있는 역할에 할당된 사용자여야 합니다.
* Windows 호스트에 플러그인을 설치할 때 기본 제공되지 않은 자격 증명을 지정하거나 사용자가 로컬 작업 그룹 사용자에 속하는 경우 호스트에서 UAC를 비활성화해야 합니다.
* 메시지 큐잉 서비스가 실행 중이어야 합니다.
* 그룹 관리 서비스 계정(gMSA)을 사용하는 경우 관리자 권한으로 gMSA를 구성해야 합니다. 자세한 내용은 다음을 참조하세요.link:task_configure_gMSA_on_windows_server_2012_or_later.html["Windows Server 2016 이상에서 Microsoft Exchange Server에 대한 그룹 관리 서비스 계정 구성"^] .


.이 작업에 관하여
* SnapCenter 서버를 다른 SnapCenter 서버에 플러그인 호스트로 추가할 수 없습니다.
* 개별 호스트나 클러스터에 대해 호스트를 추가하고 플러그인 패키지를 설치할 수 있습니다.
* 교환 노드가 DAG의 일부인 경우 SnapCenter 서버에 노드를 하나만 추가할 수 없습니다.
* 클러스터(Exchange DAG)에 플러그인을 설치하는 경우 일부 노드에 NetApp LUN에 데이터베이스가 없더라도 클러스터의 모든 노드에 플러그인이 설치됩니다.


SnapCenter 4.6부터 SCE는 멀티테넌시를 지원하며 다음 방법을 사용하여 호스트를 추가할 수 있습니다.

|===
| 호스트 작업 추가 | 4.5 및 이전 버전 | 4.6 이상 


| 교차 도메인 또는 다른 도메인에 IP 없는 DAG 추가 | 지원되지 않음 | 지원됨 


| 동일 도메인 또는 교차 도메인에 있는 고유한 이름을 가진 여러 IP DAG를 추가합니다. | 지원됨 | 지원됨 


| 동일한 호스트 이름 및/또는 DB 이름을 갖는 여러 IP 또는 IP 없는 DAG를 크로스 도메인에 추가합니다. | 지원되지 않음 | 지원됨 


| 동일한 이름과 교차 도메인을 갖는 여러 개의 IP/IP 없는 DAG 추가 | 지원되지 않음 | 지원됨 


| 동일한 이름과 크로스 도메인을 가진 여러 독립형 호스트 추가 | 지원되지 않음 | 지원됨 
|===
Exchange용 플러그인은 Windows용 SnapCenter 플러그인 패키지에 따라 달라지며, 버전이 동일해야 합니다.  Exchange용 플러그인 설치 중에 Windows용 SnapCenter 플러그인 패키지가 기본적으로 선택되고 VSS 하드웨어 공급자와 함께 설치됩니다.

Microsoft Exchange Server용 SnapManager 와 Windows용 SnapDrive 이미 설치되어 있고 동일한 Exchange Server에 Exchange용 플러그인을 설치하려는 경우, Windows용 SnapDrive 에서 사용하는 VSS 하드웨어 공급자를 등록 취소해야 합니다. 이 공급자는 Exchange용 플러그인과 Windows용 SnapCenter 플러그인 패키지에 설치된 VSS 하드웨어 공급자와 호환되지 않기 때문입니다. 자세한 내용은 다음을 참조하세요.  https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_manually_register_the_Data_ONTAP_VSS_Hardware_Provider["Data ONTAP VSS 하드웨어 공급자를 수동으로 등록하는 방법"] .

.단계
. 왼쪽 탐색 창에서 *호스트*를 클릭합니다.
. 맨 위에 *관리되는 호스트*가 선택되어 있는지 확인하세요.
. *추가*를 클릭하세요.
. 호스트 페이지에서 다음을 수행합니다.
+
|===
| 이 분야에서는... | 이렇게 하세요... 


 a| 
호스트 유형
 a| 
호스트 유형으로 *Windows*를 선택합니다.

SnapCenter Server는 호스트를 추가한 다음 Windows용 플러그인과 Exchange용 플러그인이 아직 설치되어 있지 않으면 호스트에 이를 설치합니다.

Windows용 플러그인과 Exchange용 플러그인은 동일한 버전이어야 합니다.  이전에 다른 버전의 Windows용 플러그인이 설치된 경우 SnapCenter 설치의 일부로 해당 버전을 업데이트합니다.



 a| 
호스트 이름
 a| 
호스트의 정규화된 도메인 이름(FQDN) 또는 IP 주소를 입력하세요.

SnapCenter DNS의 적절한 구성에 달려 있습니다.  따라서 가장 좋은 방법은 정규화된 도메인 이름(FQDN)을 입력하는 것입니다.

신뢰할 수 없는 도메인 호스트의 경우 IP 주소는 FQDN으로 확인되는 경우에만 지원됩니다.

SnapCenter 사용하여 호스트를 추가하고 해당 호스트가 하위 도메인의 일부인 경우 FQDN을 제공해야 합니다.

다음 중 하나의 IP 주소나 FQDN을 입력할 수 있습니다.

** 독립형 호스트
** DAG 교환
+
Exchange DAG의 경우 다음을 수행할 수 있습니다.

+
*** DAG 이름, DAG IP 주소, 노드 이름 또는 노드 IP 주소를 제공하여 DAG를 추가합니다.
*** DAG 클러스터 노드 중 하나의 IP 주소나 FQDN을 제공하여 IP가 없는 DAG 클러스터를 추가합니다.
*** 동일한 도메인이나 다른 도메인에 있는 IP 없는 DAG를 추가합니다.  이름은 같지만 도메인이 다른 여러 개의 IP/IP 없는 DAG를 추가할 수도 있습니다.





NOTE: 독립 실행형 호스트 또는 Exchange DAG(크로스 도메인 또는 동일 도메인)의 경우 호스트나 DAG의 FQDN 또는 IP 주소를 제공하는 것이 좋습니다.



 a| 
신임장
 a| 
생성한 자격 증명 이름을 선택하거나 새 자격 증명을 생성하세요.

자격 증명에는 원격 호스트에 대한 관리 권한이 있어야 합니다.  자세한 내용은 자격 증명 생성에 대한 정보를 참조하세요.

지정한 자격 증명 이름 위에 커서를 놓으면 자격 증명에 대한 세부 정보를 볼 수 있습니다.


NOTE: 자격 증명 인증 모드는 호스트 추가 마법사에서 지정하는 호스트 유형에 따라 결정됩니다.

|===
. 설치할 플러그인 선택 섹션에서 설치할 플러그인을 선택합니다.
+
Exchange용 플러그인을 선택하면 Microsoft SQL Server용 SnapCenter 플러그인이 자동으로 선택 해제됩니다.  Microsoft에서는 Exchange에서 사용되는 메모리 양과 기타 리소스 사용량 때문에 SQL Server와 Exchange 서버를 동일한 시스템에 설치하지 않는 것이 좋습니다.

. (선택 사항) *추가 옵션*을 클릭합니다.
+
|===
| 이 분야에서는... | 이렇게 하세요... 


 a| 
포트
 a| 
기본 포트 번호를 유지하거나 포트 번호를 지정하세요.

기본 포트 번호는 8145입니다.  SnapCenter 서버가 사용자 지정 포트에 설치된 경우 해당 포트 번호가 기본 포트로 표시됩니다.


NOTE: 플러그인을 수동으로 설치하고 사용자 지정 포트를 지정한 경우 동일한 포트를 지정해야 합니다.  그렇지 않으면 작업이 실패합니다.



 a| 
설치 경로
 a| 
기본 경로는 다음과 같습니다. `C:\Program Files\NetApp\SnapCenter` .

선택적으로 경로를 사용자 정의할 수 있습니다.



 a| 
DAG에 모든 호스트 추가
 a| 
DAG를 추가할 때 이 확인란을 선택하세요.



 a| 
사전 설치 확인 건너뛰기
 a| 
플러그인을 수동으로 설치했고 호스트가 플러그인 설치 요구 사항을 충족하는지 확인하지 않으려면 이 확인란을 선택하세요.



 a| 
플러그인 서비스를 실행하려면 그룹 관리 서비스 계정(gMSA)을 사용하세요.
 a| 
플러그인 서비스를 실행하기 위해 그룹 관리 서비스 계정(gMSA)을 사용하려면 이 확인란을 선택하세요.

다음 형식으로 gMSA 이름을 제공하세요: _domainName\accountName$_.


NOTE: gMSA는 Windows용 SnapCenter 플러그인 서비스에 대한 로그온 서비스 계정으로만 사용됩니다.

|===
. *제출*을 클릭하세요.
+
"사전 검사 건너뛰기" 확인란을 선택하지 않은 경우, 호스트가 플러그인 설치 요구 사항을 충족하는지 확인하기 위해 유효성 검사를 실시합니다. 최소 요구 사항을 충족하지 못할 경우, 해당 오류 또는 경고 메시지가 표시됩니다.

+
오류가 디스크 공간이나 RAM과 관련된 경우 다음 위치에 있는 web.config 파일을 업데이트할 수 있습니다. `C:\Program Files\NetApp\SnapCenter` 기본값을 수정하는 WebApp입니다.  오류가 다른 매개변수와 관련된 경우 문제를 해결해야 합니다.

+

NOTE: HA 설정에서 web.config 파일을 업데이트하는 경우 두 노드에서 모두 파일을 업데이트해야 합니다.

. 설치 진행 상황을 모니터링합니다.




== NET TCP 통신을 위한 사용자 정의 포트 구성

기본적으로 SnapCenter 6.0 릴리스부터 Windows용 SnapCenter 플러그인은 NET TCP 통신에 포트 909를 사용합니다.  포트 909가 사용 중인 경우 NET TCP 통신을 위해 다른 포트를 구성할 수 있습니다.

.단계
. _C:\Program Files\ NetApp\ SnapCenter\ SnapCenter Plug-in for Microsoft Windows\vssproviders\navssprv.exe.config_에 있는 _NetTCPPort_ 키 값을 필요한 포트 번호로 수정합니다.
`<add key="NetTCPPort" value="new_port_number" />`
. _C:\Program Files\ NetApp\ SnapCenter\ SnapCenter Plug-in for Microsoft Windows\SnapDriveService.dll.config_에 있는 _NetTCPPort_ 키의 값을 필요한 포트 번호로 수정합니다.
`<add key="NetTCPPort" value="new_port_number" />`
. 아래 명령을 실행하여 _Data ONTAP VSS Hardware Provider_ 서비스의 등록을 취소합니다.
`"C:\Program Files\NetApp\SnapCenter\SnapCenter Plug-in for Microsoft Windows\navssprv.exe" -r service -u`
+
_services.msc_의 서비스 목록에 해당 서비스가 표시되지 않는지 확인하세요.

. 아래 명령을 실행하여 _Data ONTAP VSS 하드웨어 공급자_ 서비스를 등록합니다.
`"C:\Program Files\NetApp\SnapCenter\SnapCenter Plug-in for Microsoft Windows\vssproviders\navssprv.exe" -r service -a ".\LocalSystem"``
+
_services.msc_의 서비스 목록에 해당 서비스가 표시되는지 확인하세요.

. _Windows용 플러그인_ 서비스를 다시 시작합니다.

