---
permalink: protect-sce/task_create_backup_policies_for_exchange_server_databases.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: SnapCenter 사용하여 Microsoft Exchange Server 리소스를 백업하기 전에 Exchange 리소스 또는 리소스 그룹에 대한 백업 정책을 만들거나, 리소스 그룹을 만들거나 단일 리소스를 백업할 때 백업 정책을 만들 수 있습니다. 
---
= Exchange Server 데이터베이스에 대한 백업 정책 만들기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 사용하여 Microsoft Exchange Server 리소스를 백업하기 전에 Exchange 리소스 또는 리소스 그룹에 대한 백업 정책을 만들거나, 리소스 그룹을 만들거나 단일 리소스를 백업할 때 백업 정책을 만들 수 있습니다.

.시작하기 전에
* 데이터 보호 전략을 정의해야 합니다.
+
자세한 내용은 Exchange 데이터베이스에 대한 데이터 보호 전략 정의에 대한 정보를 참조하세요.

* SnapCenter 설치, 호스트 추가, 리소스 식별, 스토리지 시스템 연결 생성 등의 작업을 완료하여 데이터 보호를 준비했어야 합니다.
* Exchange Server 리소스를 새로 고침(검색)했어야 합니다.
* 스냅샷을 미러 또는 볼트에 복제하는 경우 SnapCenter 관리자가 소스 볼륨과 대상 볼륨 모두에 대한 스토리지 가상 머신(SVM)을 할당해야 합니다.
* PowerShell 스크립트를 prescripts 및 postscripts로 실행하려면 다음 값을 설정해야 합니다. `usePowershellProcessforScripts` 매개변수를 true로 설정 `web.config` 파일.
+
기본값은 false입니다.

* SnapMirror Active Sync의 특정 전제 조건과 제한 사항을 검토하세요. 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["SnapMirror Active Sync에 대한 개체 제한"] .


.이 작업에 관하여
* 백업 정책은 백업을 관리하고 보관하는 방법과 리소스 또는 리소스 그룹을 백업하는 빈도를 제어하는 일련의 규칙입니다.  또한 스크립트 설정을 지정할 수 있습니다.  정책에서 옵션을 지정하면 다른 리소스 그룹에 정책을 재사용할 때 시간을 절약할 수 있습니다.
* 전체 백업 보존은 주어진 정책에 따라 달라집니다.  전체 백업 보존 기간이 4인 정책 A를 사용하는 데이터베이스 또는 리소스는 전체 백업을 4개 보존하고, 보존 기간이 3인 동일한 데이터베이스 또는 리소스에 대한 정책 B에는 영향을 미치지 않습니다. 정책 B는 전체 백업을 3개 보존할 수 있습니다.
* 로그 백업 보존은 모든 정책에 적용되며, 데이터베이스나 리소스에 대한 모든 로그 백업에 적용됩니다.  따라서 정책 B를 사용하여 전체 백업을 수행하는 경우 로그 보존 설정은 동일한 데이터베이스 또는 리소스에서 정책 A가 생성한 로그 백업에 영향을 미칩니다.  마찬가지로, 정책 A에 대한 로그 보존 설정은 동일한 데이터베이스에서 정책 B가 생성한 로그 백업에 영향을 미칩니다.
* SCRIPTS_PATH는 플러그인 호스트의 SMCoreServiceHost.exe.Config 파일에 있는 PredefinedWindowsScriptsDirectory 키를 사용하여 정의됩니다.
+
필요한 경우 이 경로를 변경하고 SMcore 서비스를 다시 시작할 수 있습니다.  보안을 위해 기본 경로를 사용하는 것이 좋습니다.

+
키 값은 API를 통해 swagger에서 표시될 수 있습니다: API /4.7/configsettings

+
GET API를 사용하여 키 값을 표시할 수 있습니다.  SET API는 지원되지 않습니다.

+
|===


| *모범 사례:* 전체적으로 보존하려는 전체 및 로그 백업의 수에 따라 보조 보존 정책을 구성하는 것이 가장 좋습니다.  보조 보존 정책을 구성할 때 데이터베이스와 로그가 서로 다른 볼륨에 있는 경우 각 백업에 스냅샷이 3개 있을 수 있고, 데이터베이스와 로그가 동일한 볼륨에 있는 경우 각 백업에 스냅샷이 2개 있을 수 있다는 점을 명심하세요. 
|===
* SnapLock
+
** '특정 기간 동안 백업 사본을 보관합니다' 옵션을 선택한 경우 SnapLock 보관 기간은 언급된 보관 기간보다 짧거나 같아야 합니다.
+
스냅샷 잠금 기간을 지정하면 보존 기간이 만료될 때까지 스냅샷이 삭제되지 않습니다. 이를 통해 정책에 지정된 수보다 더 많은 수의 스냅샷을 보존할 수 있습니다.

+
ONTAP 9.12.1 이하 버전의 경우 SnapLock Vault 스냅샷에서 생성된 복제본은 SnapLock Vault 만료 시간을 상속받습니다. 스토리지 관리자는 SnapLock 만료 시간 이후에 복제본을 수동으로 정리해야 합니다.





.단계
. 왼쪽 탐색 창에서 *설정*을 클릭합니다.
. 설정 페이지에서 *정책*을 클릭합니다.
. *새로 만들기*를 클릭합니다.
. 이름 페이지에서 정책 이름과 세부 정보를 입력합니다.
. 백업 유형 및 복제 페이지에서 다음 단계를 수행합니다.
+
.. 백업 유형을 선택하세요:
+
|===
| 만약 당신이 원한다면... | 이렇게 하세요... 


 a| 
데이터베이스 파일과 필요한 트랜잭션 로그를 백업하세요.
 a| 
*전체 백업 및 로그 백업*을 선택하세요.

데이터베이스는 로그 잘라내기를 통해 백업되며, 잘린 로그를 포함한 모든 로그가 백업됩니다.


NOTE: 이는 권장되는 백업 유형입니다.



 a| 
데이터베이스 파일과 커밋되지 않은 트랜잭션 로그를 백업합니다.
 a| 
*전체 백업*을 선택하세요.

데이터베이스는 로그 잘림을 통해 백업되고, 잘린 로그는 백업되지 않습니다.



 a| 
모든 거래 로그를 백업하세요
 a| 
*로그 백업*을 선택하세요.

활성 파일 시스템의 모든 트랜잭션 로그가 백업되고 로그가 잘리지 않습니다.

라이브 로그와 동일한 디스크에 _scebackupinfo_ 디렉토리가 생성됩니다.  이 디렉토리에는 Exchange 데이터베이스의 증분 변경 사항에 대한 포인터가 포함되어 있으며 전체 로그 파일과 동일하지 않습니다.



 a| 
트랜잭션 로그 파일을 잘라내지 않고 모든 데이터베이스 파일과 트랜잭션 로그를 백업합니다.
 a| 
*백업 복사*를 선택하세요.

모든 데이터베이스와 모든 로그가 백업되며, 로그가 잘리지 않습니다.  일반적으로 이 백업 유형은 복제본을 다시 시드하거나 문제를 테스트 또는 진단하는 데 사용됩니다.

|===
+

NOTE: 최신(UTM) 보존 기간이 아닌 전체 백업 보존 기간을 기준으로 로그 백업에 필요한 공간을 정의해야 합니다.

+

NOTE: Exchange 볼륨(LUN)을 처리할 때 로그와 데이터베이스에 대해 별도의 볼트 정책을 만들고, 동일한 레이블을 사용하여 로그 정책의 유지(보존)를 각 레이블의 두 배로 설정합니다.  자세한 내용은 다음을 참조하세요. https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_for_Exchange_Backups_only_keep_half_the_Snapshots_on_the_Vault_destination_log_volume["Exchange 백업용 SnapCenter Vault 대상 로그 볼륨에 있는 스냅샷의 절반만 보관합니다."^]

.. 데이터베이스 가용성 그룹 설정 섹션에서 다음 작업을 선택합니다.
+
|===
| 이 분야에서는... | 이렇게 하세요... 


 a| 
활성 사본 백업
 a| 
선택한 데이터베이스의 활성 복사본만 백업하려면 이 옵션을 선택하세요.

DAG(데이터베이스 가용성 그룹)의 경우 이 옵션은 DAG에 있는 모든 데이터베이스의 활성 복사본만 백업합니다.

수동 사본은 백업되지 않습니다.



 a| 
백업 작업 생성 시 선택할 서버에 백업 사본을 저장합니다.
 a| 
선택한 서버의 데이터베이스 사본(활성 및 수동 모두)을 백업하려면 이 옵션을 선택하세요.

DAG의 경우 이 옵션은 선택한 서버의 모든 데이터베이스의 활성 및 수동 복사본을 모두 백업합니다.

|===
+

NOTE: 클러스터 구성에서 백업은 정책에 설정된 보존 설정에 따라 클러스터의 각 노드에 보존됩니다.  클러스터의 소유자 노드가 변경되면 이전 소유자 노드의 백업이 보존됩니다.  보존은 노드 수준에서만 적용됩니다.

.. 일정 빈도 섹션에서 다음 중 하나 이상의 빈도 유형을 선택합니다. *주문형*, *시간별*, *일별*, *주별*, *월별*.
+

NOTE: 리소스 그룹을 생성하는 동안 백업 작업에 대한 일정(시작 날짜, 종료 날짜)을 지정할 수 있습니다.  이를 통해 동일한 정책과 백업 빈도를 공유하는 리소스 그룹을 만들 수 있지만, 각 정책에 다른 백업 일정을 할당할 수 있습니다.

+

NOTE: 오전 2시로 예약한 경우, 일광 절약 시간제(DST) 기간에는 일정이 실행되지 않습니다.

.. 정책 라벨을 선택합니다.
+

NOTE: 원격 복제를 위해 기본 스냅샷에 SnapMirror 레이블을 할당하면 기본 스냅샷이 SnapCenter 에서 ONTAP 보조 시스템으로 스냅샷 복제 작업을 오프로드할 수 있습니다. 정책 페이지에서 SnapMirror 또는 SnapVault 옵션을 활성화하지 않고도 이 작업을 수행할 수 있습니다.

.. 보조 복제 옵션 선택 섹션에서 다음 보조 복제 옵션 중 하나 또는 둘 다를 선택합니다.
+
|===
| 이 분야에서는... | 이렇게 하세요... 


 a| 
로컬 스냅샷을 생성한 후 SnapMirror 업데이트
 a| 
백업 세트의 미러 복사본을 다른 볼륨(SnapMirror)에 보관하려면 이 옵션을 선택하세요.

2차 복제 중에 SnapLock 만료 시간은 기본 SnapLock 만료 시간을 로드합니다.

SnapMirror Active Sync의 경우 이 옵션을 활성화해야 합니다.


IMPORTANT: Exchange ONTAP 볼륨에 대해 SnapMirror 활성 동기화가 설정된 경우 기본 전용 정책을 사용할 수 없습니다.  SnapCenter 이를 허용하지 않습니다.  "미러" 옵션을 활성화해야 합니다.

토폴로지 페이지에서 *새로 고침* 버튼을 클릭하면 ONTAP 에서 검색된 보조 및 기본 SnapLock 만료 시간이 새로 고침됩니다.

보다 link:../protect-sce/task_view_exchange_backups_in_the_topology_page.html["토폴로지 페이지에서 Exchange 백업 보기"] .



 a| 
로컬 스냅샷을 생성한 후 SnapVault 업데이트
 a| 
디스크 간 백업 복제를 수행하려면 이 옵션을 선택하세요.



 a| 
오류 재시도 횟수
 a| 
프로세스가 중단되기 전에 발생해야 하는 복제 시도 횟수를 입력합니다.

|===
+

NOTE: 보조 저장소의 스냅샷 최대 한도에 도달하지 않도록 하려면 ONTAP 에서 보조 저장소 SnapMirror 보존 정책을 구성해야 합니다.



. 보존 페이지에서 보존 설정을 구성합니다.
+
표시되는 옵션은 이전에 선택한 백업 유형과 빈도 유형에 따라 달라집니다.

+

NOTE: 최대 보존 값은 1018입니다. 보존 기간이 기본 ONTAP 버전에서 지원하는 것보다 높은 값으로 설정된 경우 백업이 실패합니다.

+

IMPORTANT: SnapVault 복제를 활성화하려면 보존 횟수를 2 이상으로 설정해야 합니다.  보존 횟수를 1로 설정하면 새 스냅샷이 대상에 복제될 때까지 첫 번째 스냅샷이 SnapVault 관계에 대한 참조 스냅샷이 되기 때문에 보존 작업이 실패할 수 있습니다.

+
.. 로그 백업 보존 설정 섹션에서 다음 중 하나를 선택하세요.
+
|===
| 만약 당신이 원한다면... | 이렇게 하세요... 


 a| 
특정 수의 로그 백업만 보관
 a| 
*로그를 보관할 전체 백업 수*를 선택하고 최신 복원 기능을 원하는 전체 백업 수를 지정합니다.

최신(UTM) 보존은 전체 백업이나 로그 백업을 통해 생성된 로그 백업에 적용됩니다.  예를 들어, UTM 보존 설정이 마지막 5개 전체 백업의 로그 백업을 보존하도록 구성된 경우 마지막 5개 전체 백업의 로그 백업이 보존됩니다.

전체 백업과 로그 백업의 일부로 생성된 로그 폴더는 UTM의 일부로 자동으로 삭제됩니다.  로그 폴더를 수동으로 삭제할 수 없습니다.  예를 들어, 전체 또는 전체 및 로그 백업의 보존 설정이 1개월로 설정되고 UTM 보존 기간이 10일로 설정된 경우, 이러한 백업의 일부로 생성된 로그 폴더는 UTM에 따라 삭제됩니다.  결과적으로 10일 분량의 로그 폴더만 남게 되고 다른 모든 백업은 특정 시점 복원으로 표시됩니다.

최신 복원을 수행하지 않으려면 UTM 보존 값을 0으로 설정할 수 있습니다.  이를 통해 특정 시점의 복원 작업이 가능해집니다.

*모범 사례:* 전체 백업 보존 설정 섹션의 전체 스냅샷(전체 백업) 설정과 동일하게 설정하는 것이 가장 좋습니다.  이렇게 하면 전체 백업마다 로그 파일이 보존됩니다.



 a| 
백업 사본을 특정 일수 동안 보관합니다.
 a| 
*마지막으로 로그 백업 보관* 옵션을 선택하고 로그 백업 사본을 보관할 일 수를 지정합니다.

전체 백업의 일수만큼의 로그 백업이 보존됩니다.



 a| 
스냅샷 잠금 기간
 a| 
*스냅샷 복사 잠금 기간*을 선택하고 일, 월 또는 년을 선택합니다.

SnapLock 보존 기간은 100년 미만이어야 합니다.

|===
+
백업 유형으로 *로그 백업*을 선택한 경우, 로그 백업은 전체 백업에 대한 최신 보존 설정의 일부로 보존됩니다.

.. 전체 백업 보존 설정 섹션에서 주문형 백업의 경우 다음 중 하나를 선택한 다음, 전체 백업의 경우 하나를 선택합니다.
+
|===
| 이 분야에서는... | 이렇게 하세요... 


 a| 
특정 수의 스냅샷만 보관
 a| 
보관할 전체 백업의 수를 지정하려면 *보관할 총 스냅샷 사본* 옵션을 선택하고 보관할 스냅샷(전체 백업)의 수를 지정합니다.

전체 백업의 수가 지정된 수를 초과하는 경우, 지정된 수를 초과하는 전체 백업이 삭제되고, 가장 오래된 복사본이 먼저 삭제됩니다.



 a| 
특정 기간 동안 전체 백업을 보관합니다.
 a| 
*스냅샷 복사본 보관 기간* 옵션을 선택하고 스냅샷(전체 백업)을 보관할 일수를 지정합니다.



 a| 
기본 스냅샷 잠금 기간
 a| 
*기본 스냅샷 복사 잠금 기간*을 선택하고 일, 월 또는 년을 선택합니다.

SnapLock 보존 기간은 100년 미만이어야 합니다.



 a| 
2차 스냅샷 잠금 기간
 a| 
*보조 스냅샷 복사 잠금 기간*을 선택하고 일, 월 또는 년을 선택합니다.

|===
+
DAG 구성의 호스트에 로그 백업만 있고 전체 백업이 없는 데이터베이스가 있는 경우 로그 백업은 다음과 같은 방식으로 보관됩니다.

+
*** 기본적으로 SnapCenter DAG의 다른 모든 호스트에서 이 데이터베이스에 대한 가장 오래된 전체 백업을 찾고, 전체 백업 이전에 수행된 이 호스트의 모든 로그 백업을 삭제합니다.
*** DAG에 있는 호스트의 데이터베이스에 대해 로그 백업만 있는 경우 위의 기본 보존 동작을 재정의하려면 _C:\Program Files\ NetApp\ SnapCenter WebApp\web.config_ 파일에 *MaxLogBackupOnlyCountWithoutFullBackup* 키를 추가합니다.
+
 <add key="MaxLogBackupOnlyCountWithoutFullBackup" value="10">
+
이 예에서 값 10은 호스트에 최대 10개의 로그 백업을 보관한다는 것을 의미합니다.





. 스크립트 페이지에서 백업 작업 전이나 후에 실행해야 하는 프리스크립트나 포스트스크립트의 경로와 인수를 각각 입력합니다.
+
** 사전 스크립트 백업 인수에는 "`$Database`"와 "`$ServerInstance`"가 포함됩니다.
** Postscript 백업 인수에는 "`$Database`", "`$ServerInstance`", "`$BackupName`", "`$LogDirectory`", "`$LogSnapshot`"이 포함됩니다.
+
스크립트를 실행하여 SNMP 트랩을 업데이트하고, 알림을 자동화하고, 로그를 보내는 등의 작업을 수행할 수 있습니다.

+

NOTE: prescripts 또는 postscripts 경로에는 드라이브나 공유가 포함되어서는 안 됩니다.  경로는 SCRIPTS_PATH를 기준으로 해야 합니다.



. 요약을 검토한 후 *마침*을 클릭하세요.

