---
permalink: protect-scw/reference_storage_types_supported_by_snapcenter_plug_ins_for_microsoft_windows.html 
sidebar: sidebar 
keywords: Storage types 
summary: SnapCenter 물리적 머신과 가상 머신 모두에서 다양한 스토리지 유형을 지원합니다.  호스트에 패키지를 설치하기 전에 해당 스토리지 유형에 대한 지원이 제공되는지 확인해야 합니다. 
---
= Microsoft Windows용 SnapCenter 플러그인에서 지원하는 스토리지 유형
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 물리적 머신과 가상 머신 모두에서 다양한 스토리지 유형을 지원합니다.  호스트에 패키지를 설치하기 전에 해당 스토리지 유형에 대한 지원이 제공되는지 확인해야 합니다.

SnapCenter 프로비저닝 및 데이터 보호 지원은 Windows Server에서 제공됩니다.  지원되는 버전에 대한 최신 정보는 다음을 참조하세요.https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 도구"^] .

|===
| 기계 | 저장 유형 | 제공을 사용하여 | 지원 노트 


 a| 
물리적 서버
 a| 
FC 연결 LUN
 a| 
SnapCenter 그래픽 사용자 인터페이스(GUI) 또는 PowerShell cmdlet
 a| 



 a| 
물리적 서버
 a| 
iSCSI로 연결된 LUN
 a| 
SnapCenter GUI 또는 PowerShell cmdlet
 a| 



 a| 
물리적 서버
 a| 
SVM(스토리지 가상 머신)에 있는 SMB3(CIFS) 공유
 a| 
SnapCenter GUI 또는 PowerShell cmdlet
 a| 
프로비저닝만 지원합니다.



 a| 
VMware VM
 a| 
FC 또는 iSCSI HBA로 연결된 RDM LUN
 a| 
PowerShell cmdlet
 a| 



 a| 
VMware VM
 a| 
iSCSI 이니시에이터에 의해 게스트 시스템에 직접 연결된 iSCSI LUN
 a| 
SnapCenter GUI 또는 PowerShell cmdlet
 a| 



 a| 
VMware VM
 a| 
가상 머신 파일 시스템(VMFS) 또는 NFS 데이터 저장소
 a| 
VMware vSphere
 a| 



 a| 
VMware VM
 a| 
SVM에 있는 SMB3 공유에 연결된 게스트 시스템
 a| 
SnapCenter GUI 또는 PowerShell cmdlet
 a| 
프로비저닝만 지원합니다.



 a| 
VMware VM
 a| 
NFS와 SAN 모두에 있는 vVol 데이터 저장소
 a| 
VMware vSphere용 ONTAP 도구
 a| 



 a| 
Hyper-V VM
 a| 
가상 파이버 채널 스위치로 연결된 가상 FC(vFC) LUN
 a| 
SnapCenter GUI 또는 PowerShell cmdlet
 a| 
가상 파이버 채널 스위치로 연결된 가상 FC(vFC) LUN을 프로비저닝하려면 Hyper-V 관리자를 사용해야 합니다.


NOTE: NetApp 스토리지에 프로비저닝된 VHD(x)에 있는 Hyper-V 패스스루 디스크와 데이터베이스 백업은 지원되지 않습니다.



 a| 
Hyper-V VM
 a| 
iSCSI 이니시에이터에 의해 게스트 시스템에 직접 연결된 iSCSI LUN
 a| 
SnapCenter GUI 또는 PowerShell cmdlet
 a| 

NOTE: NetApp 스토리지에 프로비저닝된 VHD(x)에 있는 Hyper-V 패스스루 디스크와 데이터베이스 백업은 지원되지 않습니다.



 a| 
Hyper-V VM
 a| 
SVM에 있는 SMB3 공유에 연결된 게스트 시스템
 a| 
SnapCenter GUI 또는 PowerShell cmdlet
 a| 
프로비저닝만 지원합니다.


NOTE: NetApp 스토리지에 프로비저닝된 VHD(x)에 있는 Hyper-V 패스스루 디스크와 데이터베이스 백업은 지원되지 않습니다.

|===