---
permalink: protect-scw/task_define_a_backup_strategy_for_windows_file_systems.html 
sidebar: sidebar 
keywords: backup strategy 
summary: '백업을 만들기 전에 백업 전략을 정의하면 파일 시스템을 성공적으로 복원하거나 복제하는 데 필요한 백업을 얻을 수 있습니다.  백업 전략은 주로 서비스 수준 계약(SLA), 복구 시간 목표(RTO), 복구 지점 목표(RPO)에 따라 결정됩니다.' 
---
= Windows 파일 시스템에 대한 백업 전략 정의
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
백업을 만들기 전에 백업 전략을 정의하면 파일 시스템을 성공적으로 복원하거나 복제하는 데 필요한 백업을 얻을 수 있습니다.  백업 전략은 주로 서비스 수준 계약(SLA), 복구 시간 목표(RTO), 복구 지점 목표(RPO)에 따라 결정됩니다.

SLA는 기대되는 서비스 수준을 정의하고 서비스의 가용성과 성능을 포함한 많은 서비스 관련 문제를 해결합니다.  RTO는 서비스가 중단된 후 비즈니스 프로세스를 복구해야 하는 시간입니다.  RPO는 장애 발생 후 정상적인 작업을 재개하기 위해 백업 저장소에서 복구해야 하는 파일의 기간에 대한 전략을 정의합니다.  SLA, RTO, RPO는 데이터 보호 전략에 기여합니다.



== Windows 파일 시스템의 백업 일정

백업 빈도는 정책에 지정되고, 백업 일정은 리소스 그룹 구성에 지정됩니다.  백업 빈도나 일정을 결정하는 가장 중요한 요소는 리소스의 변화율과 데이터의 중요도입니다.  자주 사용되는 리소스는 매시간 백업하고, 거의 사용되지 않는 리소스는 하루에 한 번 백업할 수도 있습니다.  기타 요소로는 조직에 대한 리소스의 중요성, 서비스 수준 계약(SLA), 복구 지점 목표(RPO) 등이 있습니다.

SLA는 기대되는 서비스 수준을 정의하고 서비스 가용성과 성능을 포함한 많은 서비스 관련 문제를 해결합니다.  RPO는 장애 발생 후 정상적인 작업을 재개하기 위해 백업 저장소에서 복구해야 하는 파일의 수명에 대한 전략을 정의합니다.  SLA와 RPO는 데이터 보호 전략에 기여합니다.

많이 사용되는 리소스의 경우에도 하루에 한두 번 이상 전체 백업을 실행할 필요는 없습니다.

백업 일정은 다음과 같이 두 부분으로 구성됩니다.

* 백업 주파수
+
일부 플러그인의 경우 _스케줄 유형_이라고 하는 백업 빈도(백업을 수행하는 빈도)는 정책 구성의 일부입니다.  예를 들어, 백업 빈도를 매시간, 매일, 매주 또는 매월로 구성하거나, 정책을 주문형 정책으로만 만드는 *없음*을 지정할 수 있습니다.  *설정* > *정책*을 클릭하면 정책에 액세스할 수 있습니다.

* 백업 일정
+
백업 일정(백업을 정확히 언제 수행해야 하는지)은 리소스 그룹 구성의 일부입니다.  예를 들어, 주간 백업에 대한 정책이 구성된 리소스 그룹이 있는 경우 매주 목요일 오후 10시에 백업하도록 일정을 구성할 수 있습니다.  *리소스* > *리소스 그룹*을 클릭하면 리소스 그룹 일정에 액세스할 수 있습니다.





== Windows 파일 시스템에 필요한 백업 수

필요한 백업 수를 결정하는 요소에는 Windows 파일 시스템의 크기, 사용된 볼륨 수, 파일 시스템의 변경률, 서비스 수준 계약(SLA) 등이 있습니다.



== Windows 파일 시스템의 백업 명명 규칙

Windows 파일 시스템 백업은 기본 스냅샷 명명 규칙을 사용합니다.  기본 백업 명명 규칙은 스냅샷 이름에 타임스탬프를 추가하여 복사본이 생성된 시기를 식별하는 데 도움이 됩니다.

스냅샷은 다음 기본 명명 규칙을 사용합니다: resourcegroupname_hostname_timestamp

다음 예와 같이 논리적으로 백업 리소스 그룹의 이름을 지정해야 합니다.

[listing]
----
dts1_mach1x88_03-12-2015_23.17.26
----
이 예에서 구문 요소는 다음과 같은 의미를 갖습니다.

* `dts1`리소스 그룹 이름입니다.
* `mach1x88`호스트 이름입니다.
* `03-12-2016_23.17.26`날짜와 타임스탬프입니다.


백업을 생성할 때 백업을 식별하는 데 도움이 되는 설명 태그를 추가할 수도 있습니다.  반면, 사용자 지정 백업 명명 규칙을 사용하려면 백업 작업이 완료된 후 백업의 이름을 바꿔야 합니다.



== 백업 보존 옵션

백업 사본을 보관할 일수를 선택하거나 보관할 백업 사본 수를 지정할 수 있으며, ONTAP 최대 255개 사본까지 보관할 수 있습니다.  예를 들어, 귀하의 조직에서는 10일 분의 백업 사본이나 130개의 백업 사본을 보관하도록 요구할 수 있습니다.

정책을 생성하는 동안 백업 유형과 일정 유형에 대한 보존 옵션을 지정할 수 있습니다.

SnapMirror 복제를 설정하면 보존 정책이 대상 볼륨에 미러링됩니다.

SnapCenter 일정 유형과 일치하는 보존 레이블이 있는 보관된 백업을 삭제합니다.  리소스 또는 리소스 그룹의 일정 유형이 변경된 경우 이전 일정 유형 레이블이 지정된 백업이 시스템에 남아 있을 수 있습니다.


NOTE: 백업 사본을 장기간 보관하려면 SnapVault 백업을 사용해야 합니다.
