---
permalink: protect-scw/task_clone_from_a_windows_file_system_backup.html 
sidebar: sidebar 
keywords: clone 
summary: SnapCenter 사용하여 Windows 파일 시스템 백업을 복제할 수 있습니다.  실수로 삭제되거나 변경된 단일 파일의 사본이 필요한 경우 백업을 복제하여 복제본에서 해당 파일에 액세스할 수 있습니다. 
---
= Windows 파일 시스템 백업에서 복제
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 사용하여 Windows 파일 시스템 백업을 복제할 수 있습니다.  실수로 삭제되거나 변경된 단일 파일의 사본이 필요한 경우 백업을 복제하여 복제본에서 해당 파일에 액세스할 수 있습니다.

.시작하기 전에
* 호스트 추가, 리소스 식별, 스토리지 가상 머신(SVM) 연결 생성 등의 작업을 완료하여 데이터 보호를 준비했어야 합니다.
* 파일 시스템을 백업해야 합니다.
* 볼륨을 호스팅하는 집계가 스토리지 가상 머신(SVM)의 할당된 집계 목록에 있는지 확인해야 합니다.
* 리소스 그룹을 복제할 수 없습니다.  개별 파일 시스템 백업만 복제할 수 있습니다.
* 백업이 VMDK 디스크가 있는 가상 머신에 있는 경우 SnapCenter 백업을 물리적 서버로 복제할 수 없습니다.
* Windows 클러스터(예: 공유 LUN 또는 클러스터 공유 볼륨(CSV) LUN)를 복제하는 경우 복제본은 지정한 호스트에 전용 LUN으로 저장됩니다.
* 복제 작업의 경우 볼륨 마운트 지점의 루트 디렉토리는 공유 디렉토리가 될 수 없습니다.
* 집계의 홈 노드가 아닌 노드에는 복제본을 만들 수 없습니다.
* Windows 파일 시스템의 경우 반복되는 복제(복제 수명 주기) 작업을 예약할 수 없습니다. 백업은 수요에 따라서만 복제할 수 있습니다.
* 복제본이 포함된 LUN을 새 볼륨으로 이동하면 SnapCenter 더 이상 복제본을 지원할 수 없습니다.  예를 들어 SnapCenter 사용하여 해당 복제본을 삭제할 수 없습니다.
* 환경 간에 복제할 수 없습니다.  예를 들어, 실제 디스크에서 가상 디스크로 복제하거나 그 반대로 복제하는 경우입니다.


.이 작업에 관하여
* SCRIPTS_PATH는 플러그인 호스트의 SMCoreServiceHost.exe.Config 파일에 있는 PredefinedWindowsScriptsDirectory 키를 사용하여 정의됩니다.
+
필요한 경우 이 경로를 변경하고 SMcore 서비스를 다시 시작할 수 있습니다.  보안을 위해 기본 경로를 사용하는 것이 좋습니다.

+
키 값은 API를 통해 swagger에서 표시될 수 있습니다: API /4.7/configsettings

+
GET API를 사용하여 키 값을 표시할 수 있습니다.  SET API는 지원되지 않습니다.

* ONTAP 9.12.1 이하 버전의 경우 복원의 일부로 SnapLock Vault 스냅샷에서 생성된 복제본은 SnapLock Vault 만료 시간을 상속받습니다. 스토리지 관리자는 SnapLock 만료 시간 이후에 복제본을 수동으로 정리해야 합니다.


[role="tabbed-block"]
====
.SnapCenter UI
--
.단계
. 왼쪽 탐색 창에서 *리소스*를 클릭한 다음 목록에서 적절한 플러그인을 선택합니다.
. 리소스 페이지에서 목록에서 *파일 시스템*을 선택합니다.
. 호스트를 선택하세요.
+
리소스가 보호되면 토폴로지 보기가 자동으로 표시됩니다.

. 리소스 목록에서 복제하려는 백업을 선택한 다음 복제 아이콘을 클릭합니다.
. 옵션 페이지에서 다음을 수행합니다.
+
|===
| 이 분야에서는... | 이렇게 하세요... 


 a| 
복제 서버
 a| 
복제본을 생성할 호스트를 선택하세요.



 a| 
"`마운트 지점 자동 할당`" 또는 "`경로 아래에 볼륨 마운트 지점 자동 할당`"
 a| 
경로 아래에 마운트 지점이나 볼륨 마운트 지점을 자동으로 할당할지 여부를 선택합니다.

경로 아래의 볼륨 마운트 지점을 자동으로 할당: 경로 아래의 마운트 지점을 사용하면 마운트 지점이 생성될 특정 디렉토리를 제공할 수 있습니다.  이 옵션을 선택하기 전에 디렉토리가 비어 있는지 확인해야 합니다.  디렉토리에 백업이 있는 경우 마운트 작업 후 백업은 유효하지 않은 상태가 됩니다.



 a| 
보관 위치
 a| 
보조 백업을 복제하는 경우 보관 위치를 선택합니다.

|===
. 스크립트 페이지에서 실행하려는 사전 스크립트나 사후 스크립트를 지정합니다.
+

NOTE: prescripts 또는 postscripts 경로에는 드라이브나 공유가 포함되어서는 안 됩니다.  경로는 SCRIPTS_PATH를 기준으로 해야 합니다.

. 요약을 검토한 후 *마침*을 클릭하세요.
. *모니터* > *작업*을 클릭하여 작업 진행 상황을 모니터링하세요.


--
.PowerShell cmdlet
--
.단계
. Open-SmConnection cmdlet을 사용하여 지정된 사용자에 대한 SnapCenter 서버와의 연결 세션을 시작합니다.
+
[listing]
----
Open-SmConnection  -SMSbaseurl  https://snapctr.demo.netapp.com:8146
----
. Get-SmBackup 또는 Get-SmResourceGroup cmdlet을 사용하여 복제할 수 있는 백업을 나열합니다.
+
이 예제에서는 사용 가능한 모든 백업에 대한 정보를 표시합니다.

+
[listing]
----
C:\PS>PS C:\> Get-SmBackup

BackupId   BackupName                     BackupTime   BackupType
--------   ----------                     ----------   ----------
1          Payroll Dataset_vise-f6_08...  8/4/2015     Full Backup
                                          11:02:32 AM

2          Payroll Dataset_vise-f6_08...  8/4/2015
                                          11:23:17 AM
----
+
이 예제에서는 지정된 리소스 그룹, 해당 리소스 및 관련 정책에 대한 정보를 표시합니다.

+
[listing]
----
PS C:\> Get-SmResourceGroup -ListResources –ListPolicies

Description :
CreationTime : 8/4/2015 3:44:05 PM
ModificationTime : 8/4/2015 3:44:05 PM
EnableEmail : False
EmailSMTPServer :
EmailFrom :
EmailTo :
EmailSubject :
EnableSysLog : False
ProtectionGroupType : Backup
EnableAsupOnFailure : False
Policies : {FinancePolicy}
HostResourceMaping : {}
Configuration : SMCoreContracts.SmCloneConfiguration
LastBackupStatus :
VerificationServer :
EmailBody :
EmailNotificationPreference : Never
VerificationServerInfo : SMCoreContracts.SmVerificationServerInfo
SchedulerSQLInstance :
CustomText :
CustomSnapshotFormat :
SearchResources : False
ByPassCredential : False
IsCustomSnapshot :
MaintenanceStatus : Production
PluginProtectionGroupTypes : {SMSQL}
Name : Payrolldataset
Type : Group
Id : 1
Host :
UserName :
Passphrase :
Deleted : False
Auth : SMCoreContracts.SmAuth
IsClone : False
CloneLevel : 0
ApplySnapvaultUpdate : False
ApplyRetention : False
RetentionCount : 0
RetentionDays : 0
ApplySnapMirrorUpdate : False
SnapVaultLabel :
MirrorVaultUpdateRetryCount : 7
AppPolicies : {}
Description : FinancePolicy
PreScriptPath :
PreScriptArguments :
PostScriptPath :
PostScriptArguments :
ScriptTimeOut : 60000
DateModified : 8/4/2015 3:43:30 PM
DateCreated : 8/4/2015 3:43:30 PM
Schedule : SMCoreContracts.SmSchedule
PolicyType : Backup
PluginPolicyType : SMSQL
Name : FinancePolicy
Type :
Id : 1
Host :
UserName :
Passphrase :
Deleted : False
Auth : SMCoreContracts.SmAuth
IsClone : False
CloneLevel : 0
clab-a13-13.sddev.lab.netapp.com
DatabaseGUID :
SQLInstance : clab-a13-13
DbStatus : AutoClosed
DbAccess : eUndefined
IsSystemDb : False
IsSimpleRecoveryMode : False
IsSelectable : True
SqlDbFileGroups : {}
SqlDbLogFiles : {}
AppFileStorageGroups : {}
LogDirectory :
AgName :
Version :
VolumeGroupIndex : -1
IsSecondary : False
Name : TEST
Type : SQL Database
Id : clab-a13-13\TEST
Host : clab-a13-13.sddev.mycompany.com
UserName :
Passphrase :
Deleted : False
Auth : SMCoreContracts.SmAuth
IsClone : False
----
. New-SmClone cmdlet을 사용하여 기존 백업에서 복제 작업을 시작합니다.
+
이 예제에서는 모든 로그를 포함하는 지정된 백업에서 복제본을 만듭니다.

+
[listing]
----
PS C:\> New-SmClone
-BackupName payroll_dataset_vise-f3_08-05-2015_15.28.28.9774
-Resources @{"Host"="vise-f3.sddev.mycompany.com";
"Type"="SQL Database";"Names"="vise-f3\SQLExpress\payroll"}
-CloneToInstance vise-f3\sqlexpress -AutoAssignMountPoint
-Suffix _clonefrombackup
-LogRestoreType All -Policy clonefromprimary_ondemand

PS C:> New-SmBackup -ResourceGroupName PayrollDataset -Policy FinancePolicy
----
+
이 예제에서는 지정된 Microsoft SQL Server 인스턴스에 대한 복제본을 만듭니다.

+
[listing]
----
PS C:\> New-SmClone
-BackupName "BackupDS1_NY-VM-SC-SQL_12-08-2015_09.00.24.8367"
-Resources @{"host"="ny-vm-sc-sql";"Type"="SQL Database";
"Names"="ny-vm-sc-sql\AdventureWorks2012_data"}
-AppPluginCode SMSQL -CloneToInstance "ny-vm-sc-sql"
-Suffix _CLPOSH -AssignMountPointUnderPath "C:\SCMounts"
----
. Get-SmCloneReport cmdlet을 사용하여 복제 작업의 상태를 확인합니다.
+
이 예제에서는 지정된 작업 ID에 대한 복제 보고서를 표시합니다.

+
[listing]
----
PS C:\> Get-SmCloneReport -JobId 186

SmCloneId : 1
SmJobId : 186
StartDateTime : 8/3/2015 2:43:02 PM
EndDateTime : 8/3/2015 2:44:08 PM
Duration : 00:01:06.6760000
Status : Completed
ProtectionGroupName : Draper
SmProtectionGroupId : 4
PolicyName : OnDemand_Clone
SmPolicyId : 4
BackupPolicyName : OnDemand_Full_Log
SmBackupPolicyId : 1
CloneHostName : SCSPR0054212005.mycompany.com
CloneHostId : 4
CloneName : Draper__clone__08-03-2015_14.43.53
SourceResources : {Don, Betty, Bobby, Sally}
ClonedResources : {Don_DRAPER, Betty_DRAPER, Bobby_DRAPER,
                   Sally_DRAPER}
----


cmdlet과 함께 사용할 수 있는 매개변수와 해당 설명에 대한 정보는 _Get-Help command_name_을 실행하면 얻을 수 있습니다. 또는 다음을 참조할 수도 있습니다. https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter 소프트웨어 Cmdlet 참조 가이드"^] .

--
====