---
permalink: protect-scw/task_install_the_snapcenter_plug_in_for_windows_silently_from_the_command_line.html 
sidebar: sidebar 
keywords: install, snapcenter 
summary: SnapCenter GUI에서 원격으로 플러그인을 설치할 수 없는 경우 Windows 호스트에 로컬로 Microsoft Windows용 SnapCenter 플러그인을 설치할 수 있습니다.  Windows 명령줄에서 SnapCenter 플러그인을 Microsoft Windows 설치 프로그램으로 자동 모드로 실행할 수 있습니다. 
---
= 명령줄에서 Microsoft Windows용 SnapCenter 플러그인을 자동으로 설치합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter GUI에서 원격으로 플러그인을 설치할 수 없는 경우 Windows 호스트에 로컬로 Microsoft Windows용 SnapCenter 플러그인을 설치할 수 있습니다.  Windows 명령줄에서 SnapCenter 플러그인을 Microsoft Windows 설치 프로그램으로 자동 모드로 실행할 수 있습니다.

.시작하기 전에
* ASP.NET Core Runtime 8.0.12(및 이후의 모든 8.0.x 패치) 호스팅 번들을 설치해야 합니다.
* PowerShell 7.4.2 이상을 설치해야 합니다.
* 호스트의 로컬 관리자여야 합니다.


.단계
. 설치 위치에서 Microsoft Windows용 SnapCenter 플러그인을 다운로드하세요.
+
예를 들어, 기본 설치 경로는 C:\ProgramData\ NetApp\ SnapCenter\Package Repository입니다.

+
이 경로는 SnapCenter 서버가 설치된 호스트에서 접근할 수 있습니다.

. 플러그인을 설치하려는 호스트에 설치 파일을 복사합니다.
. 명령 프롬프트에서 설치 파일을 다운로드한 디렉토리로 이동합니다.
. 다음 명령을 입력하고 변수를 사용자의 데이터로 바꾸세요.
+
`"snapcenter_windows_host_plugin.exe"/silent / debuglog"" /log"" BI_SNAPCENTER_PORT= SUITE_INSTALLDIR="" BI_SERVICEACCOUNT= BI_SERVICEPWD= ISFeatureInstall=SCW`

+
예를 들어:

+
 `"C:\ProgramData\NetApp\SnapCenter\Package Repository \snapcenter_windows_host_plugin.exe"/silent /debuglog"C: \HPPW_SCW_Install.log" /log"C:\" BI_SNAPCENTER_PORT=8145 SUITE_INSTALLDIR="C: \Program Files\NetApp\SnapCenter" BI_SERVICEACCOUNT=domain\administrator BI_SERVICEPWD=password ISFeatureInstall=SCW`
+

NOTE: Windows용 플러그인을 설치하는 동안 전달되는 모든 매개변수는 대소문자를 구분합니다.

+
다음 변수의 값을 입력하세요.

+
|===
| 변하기 쉬운 | 가치 


 a| 
_/debuglog"<디버그_로그_경로>_
 a| 
다음 예와 같이 제품군 설치 프로그램 로그 파일의 이름과 위치를 지정합니다: Setup.exe /debuglog"C:\PathToLog\setupexe.log".



 a| 
BI_SNAPCENTER_PORT
 a| 
SnapCenter SMCore와 통신하는 포트를 지정합니다.



 a| 
SUITE_INSTALLDIR
 a| 
호스트 플러그인 패키지 설치 디렉토리를 지정합니다.



 a| 
BI_SERVICEACCOUNT
 a| 
Microsoft Windows 웹 서비스 계정에 대한 SnapCenter 플러그인을 지정합니다.



 a| 
BI_SERVICEPWD
 a| 
Microsoft Windows 웹 서비스 계정용 SnapCenter 플러그인의 비밀번호를 지정합니다.



 a| 
ISFeature설치
 a| 
SnapCenter 가 원격 호스트에 배포할 솔루션을 지정합니다.

|===
+
_debuglog_ 매개변수에는 SnapCenter 의 로그 파일 경로가 포함됩니다.  이 로그 파일에 쓰는 것은 문제 해결 정보를 얻는 가장 좋은 방법입니다. 이 파일에는 설치 과정에서 플러그인 필수 구성 요소를 확인하기 위해 수행한 검사 결과가 들어 있기 때문입니다.

+
필요한 경우 Windows 패키지용 SnapCenter 의 로그 파일에서 추가적인 문제 해결 정보를 찾을 수 있습니다.  패키지의 로그 파일은 _%Temp%_ 폴더(예: _C:\temp\_)에 가장 오래된 파일부터 나열됩니다.

+

NOTE: Windows용 플러그인을 설치하면 플러그인이 SnapCenter 서버가 아닌 호스트에 등록됩니다.  SnapCenter GUI 또는 PowerShell cmdlet을 사용하여 호스트를 추가하여 SnapCenter 서버에 플러그인을 등록할 수 있습니다.  호스트가 추가되면 플러그인이 자동으로 검색됩니다.


