---
permalink: protect-scw/task_create_backup_policies_for_windows_file_systems.html 
sidebar: sidebar 
keywords: backup policy 
summary: SnapCenter 사용하여 Windows 파일 시스템을 백업하기 전에 리소스에 대한 새 백업 정책을 만들거나, 리소스 그룹을 만들거나 리소스를 백업할 때 새 백업 정책을 만들 수 있습니다. 
---
= Windows 파일 시스템에 대한 백업 정책 만들기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 사용하여 Windows 파일 시스템을 백업하기 전에 리소스에 대한 새 백업 정책을 만들거나, 리소스 그룹을 만들거나 리소스를 백업할 때 새 백업 정책을 만들 수 있습니다.

.시작하기 전에
* 백업 전략을 정의했어야 합니다.link:task_define_a_backup_strategy_for_windows_file_systems.html["자세히 알아보기"^]
* 데이터 보호를 위해 준비를 하셔야 합니다.
+
데이터 보호를 준비하려면 SnapCenter 설치, 호스트 추가, 리소스 검색, 스토리지 가상 머신(SVM) 연결 생성 등의 작업을 완료해야 합니다.

* 스냅샷을 미러 또는 볼트 보조 스토리지에 복제하는 경우 SnapCenter 관리자가 소스 및 대상 볼륨 모두에 대한 SVM을 할당해야 합니다.
* PowerShell 스크립트를 prescripts 및 postscripts로 실행하려면 web.config 파일에서 usePowershellProcessforScripts 매개변수 값을 true로 설정해야 합니다.
+
기본값은 false입니다

* SnapMirror Active Sync의 특정 전제 조건과 제한 사항을 검토하세요. 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["SnapMirror Active Sync에 대한 개체 제한"] .


.이 작업에 관하여
* SCRIPTS_PATH는 플러그인 호스트의 SMCoreServiceHost.exe.Config 파일에 있는 PredefinedWindowsScriptsDirectory 키를 사용하여 정의됩니다.
+
필요한 경우 이 경로를 변경하고 SMcore 서비스를 다시 시작할 수 있습니다.  보안을 위해 기본 경로를 사용하는 것이 좋습니다.

+
키 값은 API를 통해 swagger에서 표시될 수 있습니다: API /4.7/configsettings

+
GET API를 사용하여 키 값을 표시할 수 있습니다.  SET API는 지원되지 않습니다.

* SnapLock
+
** '특정 기간 동안 백업 사본을 보관합니다' 옵션을 선택한 경우 SnapLock 보관 기간은 언급된 보관 기간보다 짧거나 같아야 합니다.
** 스냅샷 잠금 기간을 지정하면 보존 기간이 만료될 때까지 스냅샷이 삭제되지 않습니다. 이를 통해 정책에 지정된 수보다 더 많은 수의 스냅샷을 보존할 수 있습니다.
** ONTAP 9.12.1 이하 버전의 경우 복원의 일부로 SnapLock Vault 스냅샷에서 생성된 복제본은 SnapLock Vault 만료 시간을 상속받습니다. 스토리지 관리자는 SnapLock 만료 시간 이후에 복제본을 수동으로 정리해야 합니다.




.단계
. 왼쪽 탐색 창에서 *설정*을 선택합니다.
. 설정 페이지에서 *정책*을 선택합니다.
. *새로 만들기*를 선택하세요.
. 이름 페이지에서 정책 이름과 세부 정보를 입력합니다.
. 백업 및 복제 페이지에서 다음 작업을 수행합니다.
+
.. 백업 설정을 선택하세요.
+
|===
| 옵션 | 설명 


 a| 
파일 시스템 일관성 백업
 a| 
백업 작업이 시작되기 전에 SnapCenter 파일 시스템이 있는 디스크 드라이브를 정지시키고 백업 작업이 끝난 후 디스크 드라이브를 다시 시작하도록 하려면 이 옵션을 선택합니다.



 a| 
파일 시스템 충돌 시에도 일관된 백업
 a| 
SnapCenter 파일 시스템이 있는 디스크 드라이브를 정지시키지 않도록 하려면 이 옵션을 선택하세요.

|===
.. 일정 빈도(정책 유형이라고도 함)를 선택합니다.
+
정책은 백업 빈도만 지정합니다.  백업을 위한 구체적인 보호 일정은 리소스 그룹에서 정의됩니다.  따라서 두 개 이상의 리소스 그룹이 동일한 정책과 백업 빈도를 공유할 수 있지만 백업 일정은 서로 다를 수 있습니다.

+

NOTE: 오전 2시로 예약한 경우, 일광 절약 시간제(DST) 기간에는 일정이 실행되지 않습니다.

.. 정책 라벨을 선택하세요.
+
선택한 스냅샷 레이블에 따라 ONTAP 레이블과 일치하는 보조 스냅샷 보존 정책을 적용합니다.

+

NOTE: 로컬 스냅샷 복사본을 만든 후 SnapMirror 업데이트를 선택한 경우 선택적으로 보조 정책 레이블을 지정할 수 있습니다.  하지만 로컬 스냅샷 복사본을 만든 후 SnapVault 업데이트를 선택한 경우 보조 정책 레이블을 지정해야 합니다.



. 보조 복제 옵션 선택 섹션에서 다음 보조 복제 옵션 중 하나 또는 둘 다를 선택합니다.
+
|===
| 이 분야에서는... | 이렇게 하세요... 


 a| 
로컬 스냅샷 복사본을 만든 후 SnapMirror 업데이트
 a| 
다른 볼륨에 백업 세트의 미러 복사본을 생성하려면 이 옵션을 선택하세요(SnapMirror).

SnapSnapMirror Active Sync에서는 이 옵션을 활성화해야 합니다.

2차 복제 중에 SnapLock 만료 시간은 기본 SnapLock 만료 시간을 로드합니다.  토폴로지 페이지에서 *새로 고침* 버튼을 클릭하면 ONTAP 에서 검색된 보조 및 기본 SnapLock 만료 시간이 새로 고침됩니다.

보다 link:../protect-scw/task_view_related_backups_and_clones_in_the_topology_page.html["토폴로지 페이지에서 관련 백업 및 복제본 보기"] .



 a| 
스냅샷 복사본을 만든 후 SnapVault 업데이트
 a| 
디스크 간 백업 복제를 수행하려면 이 옵션을 선택하세요.

2차 복제 중에 SnapLock 만료 시간은 기본 SnapLock 만료 시간을 로드합니다.  토폴로지 페이지에서 새로 고침 버튼을 클릭하면 ONTAP 에서 검색된 보조 및 기본 SnapLock 만료 시간이 새로 고쳐집니다.

ONTAP 에서 SnapLock Vault로 알려진 보조 노드에만 SnapLock 구성된 경우 토폴로지 페이지에서 새로 고침 버튼을 클릭하면 ONTAP 에서 검색된 보조 노드의 잠금 기간이 새로 고쳐집니다.

SnapLock Vault에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/ontap/snaplock/commit-snapshot-copies-worm-concept.html["볼트 대상의 WORM에 스냅샷 복사본 커밋"]



 a| 
오류 재시도 횟수
 a| 
프로세스가 중단되기 전에 발생해야 하는 복제 시도 횟수를 입력합니다.

|===
+

NOTE: 보조 저장소의 스냅샷 최대 한도에 도달하지 않도록 하려면 ONTAP 에서 보조 저장소 SnapMirror 보존 정책을 구성해야 합니다.

. 보존 설정 페이지에서 주문형 백업과 선택한 각 일정 빈도에 대한 보존 설정을 지정합니다.
+
|===
| 옵션 | 설명 


 a| 
보관할 총 스냅샷 사본
 a| 
SnapCenter 가 자동으로 삭제하기 전에 저장하는 스냅샷 수를 지정하려면 이 옵션을 선택하세요.



 a| 
스냅샷 사본을 보관하세요
 a| 
SnapCenter 백업 사본을 삭제하기 전에 보관하는 일수를 지정하려면 이 옵션을 선택하세요.



 a| 
스냅샷 복사 잠금 기간
 a| 
스냅샷 잠금 기간을 선택하고 기간을 일, 월 또는 년으로 지정합니다.

SnapLock 보존 기간은 100년 미만이어야 합니다.

|===
+

IMPORTANT: 보존 횟수를 2 이상으로 설정해야 합니다.  보존 횟수의 최소값은 2입니다.

+

NOTE: 최대 보존 값은 1018입니다. 보존 기간이 ONTAP 버전에서 지원하는 것보다 높은 값으로 설정된 경우 백업이 실패합니다.

. 스크립트 페이지에서 SnapCenter 서버가 백업 작업 전이나 후에 실행할 프리스크립트 또는 포스트스크립트의 경로와 SnapCenter 스크립트가 실행될 때까지 기다리는 시간 제한을 입력합니다.
+
예를 들어, SNMP 트랩을 업데이트하고, 알림을 자동화하고, 로그를 보내는 스크립트를 실행할 수 있습니다.

+

NOTE: prescripts 또는 postscripts 경로에는 드라이브나 공유가 포함되어서는 안 됩니다.  경로는 SCRIPTS_PATH를 기준으로 해야 합니다.

. 요약을 검토한 후 *마침*을 클릭하세요.

