---
permalink: protect-hana/task_create_a_storage_system_connection_and_a_run_as_account_using_powershell_cmdlets_for_sap_hana_database.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SAP HANA Database 
summary: 'PowerShell cmdlet을 사용하여 SAP HANA 데이터베이스를 백업, 복원 또는 복제하려면 먼저 SVM(스토리지 가상 머신) 연결과 자격 증명을 만들어야 합니다.' 
---
= PowerShell cmdlet을 사용하여 SAP HANA 데이터베이스용 스토리지 시스템 연결 및 자격 증명 만들기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
PowerShell cmdlet을 사용하여 SAP HANA 데이터베이스를 백업, 복원 또는 복제하려면 먼저 SVM(스토리지 가상 머신) 연결과 자격 증명을 만들어야 합니다.

.시작하기 전에
* PowerShell cmdlet을 실행하려면 PowerShell 환경을 준비해야 합니다.
* 저장소 연결을 생성하려면 인프라 관리자 역할에 필요한 권한이 있어야 합니다.
* 플러그인 설치가 진행 중이 아닌지 확인해야 합니다.
+
스토리지 시스템 연결을 추가하는 동안에는 호스트 플러그인 설치가 진행 중이어서는 안 됩니다. 호스트 캐시가 업데이트되지 않고 SnapCenter GUI에 데이터베이스 상태가 "`백업에 사용할 수 없음`" 또는 "` NetApp 스토리지에 없음`"으로 표시될 수 있기 때문입니다.

* 저장 시스템 이름은 고유해야 합니다.
+
SnapCenter 서로 다른 클러스터에 동일한 이름을 가진 여러 스토리지 시스템을 지원하지 않습니다.  SnapCenter 에서 지원하는 각 스토리지 시스템은 고유한 이름과 고유한 데이터 LIF IP 주소를 가져야 합니다.



.단계
. Open-SmConnection cmdlet을 사용하여 PowerShell 연결 세션을 시작합니다.
+
[listing]
----
PS C:\> Open-SmStorageConnection
----
. Add-SmStorageConnection cmdlet을 사용하여 스토리지 시스템에 대한 새 연결을 만듭니다.
+
[listing]
----
PS C:\> Add-SmStorageConnection -StorageType DataOntap -Type DataOntap -OntapStorage ‘scsnfssvm’ -Protocol Https -Timeout 60
----
. Add-SmCredential cmdlet을 사용하여 새 자격 증명을 만듭니다.
+
이 예제에서는 Windows 자격 증명을 사용하여 FinanceAdmin이라는 새 자격 증명을 만드는 방법을 보여줍니다.

+
[listing]
----
PS C:> Add-SmCredential -Name FinanceAdmin -AuthMode Windows
-Credential sddev\administrator
----
. SnapCenter 서버에 SAP HANA 통신 호스트를 추가합니다.
+
[listing]
----
PS C:> Add-SmHost -HostName 10.232.204.61 -OSType Windows -RunAsName FinanceAdmin -PluginCode hana
----
. 호스트에 SAP HANA 데이터베이스용 패키지와 SnapCenter 플러그인을 설치합니다.
+
Linux의 경우:

+
[listing]
----
PS C:> Install-SmHostPackage -HostNames 10.232.204.61 -ApplicationCode hana
----
+
Windows의 경우:

+
[listing]
----
Install-SmHostPackage -HostNames 10.232.204.61 -ApplicationCode hana -FilesystemCode scw -RunAsName FinanceAdmin
----
. HDBSQL 클라이언트의 경로를 설정합니다.
+
Windows의 경우:

+
[listing]
----
PS C:> Set-SmConfigSettings -Plugin -HostName 10.232.204.61 -PluginCode hana -configSettings @{"HANA_HDBSQL_CMD" = "C:\Program Files\sap\hdbclient\hdbsql.exe"}
----
+
Linux의 경우:

+
[listing]
----
Set-SmConfigSettings -Plugin -HostName scs-hana.gdl.englab.netapp.com -PluginCode hana -configSettings @{"HANA_HDBSQL_CMD"="/usr/sap/hdbclient/hdbsql"}
----


cmdlet과 함께 사용할 수 있는 매개변수와 해당 설명에 대한 정보는 _Get-Help command_name_을 실행하면 얻을 수 있습니다. 또는 다음을 참조할 수도 있습니다. https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter 소프트웨어 Cmdlet 참조 가이드"^] .
