---
permalink: protect-hana/task_create_backup_policies_for_sap_hana_databases.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SAP HANA Database 
summary: SnapCenter 사용하여 SAP HANA 데이터베이스 리소스를 백업하기 전에 백업하려는 리소스 또는 리소스 그룹에 대한 백업 정책을 만들어야 합니다.  백업 정책은 백업을 관리, 일정을 정하고 보관하는 방법을 규정하는 일련의 규칙입니다. 
---
= SAP HANA 데이터베이스에 대한 백업 정책 만들기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 사용하여 SAP HANA 데이터베이스 리소스를 백업하기 전에 백업하려는 리소스 또는 리소스 그룹에 대한 백업 정책을 만들어야 합니다.  백업 정책은 백업을 관리, 일정을 정하고 보관하는 방법을 규정하는 일련의 규칙입니다.

.시작하기 전에
* 백업 전략을 정의했어야 합니다.
+
자세한 내용은 SAP HANA 데이터베이스에 대한 데이터 보호 전략 정의에 대한 정보를 참조하세요.

* SnapCenter 설치, 호스트 추가, 스토리지 시스템 연결 설정, 리소스 추가 등의 작업을 완료하여 데이터 보호를 준비했어야 합니다.
* 스냅샷을 미러 또는 볼트에 복제하는 경우 SnapCenter 관리자가 소스 및 대상 볼륨 모두에 대한 SVM을 할당해야 합니다.
+
또한 정책에서 복제, 스크립트 및 애플리케이션 설정을 지정할 수 있습니다.  이러한 옵션을 사용하면 다른 리소스 그룹에 대한 정책을 재사용할 때 시간을 절약할 수 있습니다.

* SnapMirror Active Sync의 특정 전제 조건과 제한 사항을 검토하세요.  자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["SnapMirror Active Sync에 대한 개체 제한"] .


.이 작업에 관하여
* SAP HANA 시스템 복제
+
** 기본 SAP HANA 시스템을 보호하고 모든 데이터 보호 작업을 수행할 수 있습니다.
** 보조 SAP HANA 시스템을 보호할 수는 있지만 백업을 생성할 수는 없습니다.
+
장애 조치 후에는 보조 SAP HANA 시스템이 기본 SAP HANA 시스템이 되어 모든 데이터 보호 작업을 수행할 수 있습니다.

+
SAP HANA 데이터 볼륨에 대한 백업을 생성할 수 없지만 SnapCenter 비데이터 볼륨(NDV)을 계속 보호합니다.



* SnapLock
+
** '특정 기간 동안 백업 사본을 보관합니다' 옵션을 선택한 경우 SnapLock 보관 기간은 언급된 보관 기간보다 짧거나 같아야 합니다.
** 스냅샷 잠금 기간을 지정하면 보존 기간이 만료될 때까지 스냅샷이 삭제되지 않습니다. 이를 통해 정책에 지정된 수보다 더 많은 수의 스냅샷을 보존할 수 있습니다.
** ONTAP 9.12.1 이하 버전의 경우 복원의 일부로 SnapLock Vault 스냅샷에서 생성된 복제본은 SnapLock Vault 만료 시간을 상속받습니다. 스토리지 관리자는 SnapLock 만료 시간 이후에 복제본을 수동으로 정리해야 합니다.




.단계
. 왼쪽 탐색 창에서 *설정*을 클릭합니다.
. 설정 페이지에서 *정책*을 클릭합니다.
. *새로 만들기*를 클릭합니다.
. 이름 페이지에서 정책 이름과 세부 정보를 입력합니다.
. 정책 유형 페이지에서 다음 단계를 수행합니다.
+
** 저장 유형을 선택하세요
** 백업 유형을 선택하세요:
+
|===
| 만약 당신이 원한다면... | 이렇게 하세요... 


 a| 
스냅샷 기술을 사용하여 백업을 만듭니다.
 a| 
*스냅샷 기반*을 선택하세요.



 a| 
데이터베이스의 무결성 검사를 수행합니다.
 a| 
*파일 기반 백업*을 선택하세요.  활성 테넌트만 백업됩니다.

|===


. 스냅샷 및 복제 페이지에서 다음 단계를 수행합니다.
+
** *주문형*, *시간별*, *일별*, *주별* 또는 *월별*을 선택하여 일정 유형을 지정합니다.
+

NOTE: 리소스 그룹을 생성하는 동안 백업 작업에 대한 일정(시작 날짜, 종료 날짜, 빈도)을 지정할 수 있습니다.  이를 통해 동일한 정책과 백업 빈도를 공유하는 리소스 그룹을 만들 수 있을 뿐만 아니라 각 정책에 다른 백업 일정을 할당할 수도 있습니다.

+

NOTE: 오전 2시로 예약한 경우, 일광 절약 시간제(DST) 기간에는 일정이 실행되지 않습니다.



. 스냅샷 및 복제 페이지에서 백업 유형 페이지에서 선택한 백업 유형과 일정 유형에 대한 보존 설정을 지정합니다.
+
|===
| 만약 당신이 원한다면... | 그 다음에... 


 a| 
특정 수의 스냅샷을 보관하세요
 a| 
*보관할 사본*을 선택한 다음 보관하려는 스냅샷 수를 지정합니다.

스냅샷 수가 지정된 수를 초과하면 가장 오래된 스냅샷이 먼저 삭제됩니다.


NOTE: 최대 보존 값은 1018입니다. 보존 기간이 ONTAP 버전에서 지원하는 것보다 높은 값으로 설정된 경우 백업이 실패합니다.


IMPORTANT: 스냅샷 복사 기반 백업의 경우 SnapVault 복제를 활성화하려면 보존 횟수를 2 이상으로 설정해야 합니다.  보존 횟수를 1로 설정하면 새 스냅샷이 대상에 복제될 때까지 첫 번째 스냅샷이 SnapVault 관계에 대한 참조 스냅샷이 되기 때문에 보존 작업이 실패할 수 있습니다.


NOTE: SAP HANA 시스템 복제의 경우, SAP HANA 시스템의 모든 리소스를 하나의 리소스 그룹에 추가하는 것이 좋습니다.  이렇게 하면 적절한 수의 백업이 보관됩니다.


NOTE: SAP HANA 시스템 복제의 경우, 생성된 총 스냅샷은 리소스 그룹에 대해 설정된 보존 기간과 동일합니다.  가장 오래된 스냅샷을 제거하는 것은 가장 오래된 스냅샷이 위치한 노드에 따라 결정됩니다.  예를 들어, SAP HANA 시스템 복제가 기본이고 SAP HANA 시스템 복제가 보조인 리소스 그룹의 경우 보존 기간이 7로 설정됩니다.  SAP HANA 시스템 복제 기본 및 SAP HANA 시스템 복제 보조를 모두 포함하여 한 번에 최대 7개의 스냅샷을 찍을 수 있습니다.



 a| 
스냅샷을 특정 일수 동안 보관하세요
 a| 
*사본 보관 기간*을 선택한 다음, 스냅샷을 삭제하기 전에 보관할 일수를 지정합니다.



 a| 
스냅샷 복사 잠금 기간
 a| 
*스냅샷 복사 잠금 기간*을 선택하고 일, 월 또는 년을 지정합니다.

SnapLock 보존 기간은 100년 미만이어야 합니다.

|===
. 스냅샷 라벨을 선택하세요.
+

NOTE: 원격 복제를 위해 기본 스냅샷에 SnapMirror 레이블을 할당하면 기본 스냅샷이 SnapCenter 에서 ONTAP 보조 시스템으로 스냅샷 복제 작업을 오프로드할 수 있습니다. 정책 페이지에서 SnapMirror 또는 SnapVault 옵션을 활성화하지 않고도 이 작업을 수행할 수 있습니다.

. 스냅샷 복사 기반 백업의 경우 보조 복제 옵션 선택 섹션에서 다음 보조 복제 옵션 중 하나 또는 둘 다를 선택합니다.
+
|===
| 이 분야에서는... | 이렇게 하세요... 


 a| 
*로컬 스냅샷 복사본을 만든 후 SnapMirror 업데이트*
 a| 
다른 볼륨에 백업 세트의 미러 복사본을 생성하려면 이 필드를 선택합니다(SnapMirror 복제).

SnapMirror Active Sync의 경우 이 옵션을 활성화해야 합니다.

ONTAP 의 보호 관계가 미러 및 볼트 유형이고 이 옵션만 선택하는 경우, 기본에서 생성된 스냅샷은 대상으로 전송되지 않지만 대상에는 나열됩니다.  대상에서 이 스냅샷을 선택하여 복원 작업을 수행하는 경우, 선택한 보관/미러링 백업에 대해 보조 위치를 사용할 수 없다는 오류 메시지가 표시됩니다.

2차 복제 중에 SnapLock 만료 시간은 기본 SnapLock 만료 시간을 로드합니다.

토폴로지 페이지에서 *새로 고침* 버튼을 클릭하면 ONTAP 에서 검색된 보조 및 기본 SnapLock 만료 시간이 새로 고침됩니다.

보다 link:../protect-hana/task_view_sap_hana_database_backups_and_clones_in_the_topology_page_sap_hana.html["토폴로지 페이지에서 SAP HANA 데이터베이스 백업 및 복제본 보기"] .



 a| 
*로컬 스냅샷 복사본을 만든 후 SnapVault 업데이트*
 a| 
디스크 간 백업 복제(SnapVault 백업)를 수행하려면 이 옵션을 선택하세요.

2차 복제 중에 SnapLock 만료 시간은 기본 SnapLock 만료 시간을 로드합니다.  토폴로지 페이지에서 *새로 고침* 버튼을 클릭하면 ONTAP 에서 검색된 보조 및 기본 SnapLock 만료 시간이 새로 고침됩니다.

ONTAP 에서 SnapLock Vault로 알려진 보조 노드에만 SnapLock 구성된 경우 토폴로지 페이지에서 *새로 고침* 버튼을 클릭하면 ONTAP 에서 검색된 보조 노드의 잠금 기간이 새로 고침됩니다.

SnapLock Vault에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/ontap/snaplock/commit-snapshot-copies-worm-concept.html["볼트 대상의 WORM에 스냅샷 복사본 커밋"]

보다 link:../protect-hana/task_view_sap_hana_database_backups_and_clones_in_the_topology_page_sap_hana.html["토폴로지 페이지에서 SAP HANA 데이터베이스 백업 및 복제본 보기"] .



 a| 
*오류 재시도 횟수*
 a| 
작업이 중지되기 전에 허용할 수 있는 최대 복제 시도 횟수를 입력하세요.

|===
+

NOTE: 보조 저장소의 스냅샷 최대 한도에 도달하지 않도록 하려면 ONTAP 에서 보조 저장소 SnapMirror 보존 정책을 구성해야 합니다.

. 요약을 검토한 후 *마침*을 클릭하세요.

