---
permalink: protect-hana/task_add_hosts_and_install_plug_in_packages_on_remote_hosts_sap_hana.html 
sidebar: sidebar 
keywords: credentials 
summary: SnapCenter 호스트 추가 페이지를 사용하여 호스트를 추가한 다음 플러그인 패키지를 설치해야 합니다.  플러그인은 원격 호스트에 자동으로 설치됩니다.  개별 호스트나 클러스터에 대해 호스트를 추가하고 플러그인 패키지를 설치할 수 있습니다. 
---
= 원격 호스트에 호스트를 추가하고 플러그인 패키지를 설치합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 호스트 추가 페이지를 사용하여 호스트를 추가한 다음 플러그인 패키지를 설치해야 합니다.  플러그인은 원격 호스트에 자동으로 설치됩니다.  개별 호스트나 클러스터에 대해 호스트를 추가하고 플러그인 패키지를 설치할 수 있습니다.

.시작하기 전에
* SnapCenter 서버 호스트의 운영 체제가 Windows 2019이고 플러그인 호스트의 운영 체제가 Windows 2022인 경우 다음을 수행해야 합니다.
+
** Windows Server 2019(OS 빌드 17763.5936) 이상으로 업그레이드하세요.
** Windows Server 2022(OS 빌드 20348.2402) 이상으로 업그레이드하세요.


* SnapCenter 관리자 역할과 같이 플러그인 설치 및 제거 권한이 있는 역할에 할당된 사용자여야 합니다.
* Windows 호스트에 플러그인을 설치할 때 기본 제공되지 않은 자격 증명을 지정하거나 사용자가 로컬 작업 그룹 사용자에 속하는 경우 호스트에서 UAC를 비활성화해야 합니다.
* 메시지 대기열 서비스가 실행 중인지 확인해야 합니다.
* 관리 문서에는 호스트 관리에 대한 정보가 포함되어 있습니다.
* 그룹 관리 서비스 계정(gMSA)을 사용하는 경우 관리자 권한으로 gMSA를 구성해야 합니다.
+
link:../protect-hana/task_configure_gMSA_on_windows_server_2012_or_later.html["SAP HANA를 위해 Windows Server 2016 이상에서 그룹 관리 서비스 계정 구성"^]



.이 작업에 관하여
* SnapCenter 서버를 다른 SnapCenter 서버에 플러그인 호스트로 추가할 수 없습니다.
* SAP HANA 시스템 복제가 기본 및 보조 시스템 모두에서 리소스를 검색하려면 root 또는 sudo 사용자를 사용하여 기본 및 보조 시스템을 모두 추가하는 것이 좋습니다.


.단계
. 왼쪽 탐색 창에서 *호스트*를 클릭합니다.
. 상단에 *관리되는 호스트* 탭이 선택되어 있는지 확인하세요.
. *추가*를 클릭하세요.
. 호스트 페이지에서 다음 작업을 수행합니다.
+
|===
| 이 분야에서는... | 이렇게 하세요... 


 a| 
호스트 유형
 a| 
호스트 유형을 선택하세요:

** Windows
** 리눅스
+

NOTE: SAP HANA용 플러그인은 HDBSQL 클라이언트 호스트에 설치되며, 이 호스트는 Windows 시스템이나 Linux 시스템에 있을 수 있습니다.





 a| 
호스트 이름
 a| 
통신 호스트 이름을 입력하세요.  호스트의 정규화된 도메인 이름(FQDN) 또는 IP 주소를 입력하세요.  SnapCenter DNS의 적절한 구성에 달려 있습니다.  따라서 FQDN을 입력하는 것이 가장 좋습니다.

이 호스트에서 HDBSQL 클라이언트와 HDBUserStore를 구성해야 합니다.



 a| 
신임장
 a| 
생성한 자격 증명 이름을 선택하거나 새 자격 증명을 생성하세요.  자격 증명에는 원격 호스트에 대한 관리 권한이 있어야 합니다.  자세한 내용은 자격 증명 생성에 대한 정보를 참조하세요.

제공한 자격 증명 이름 위에 커서를 놓으면 자격 증명에 대한 세부 정보를 볼 수 있습니다.


NOTE: 자격 증명 인증 모드는 호스트 추가 마법사에서 지정하는 호스트 유형에 따라 결정됩니다.

|===
. 설치할 플러그인 선택 섹션에서 설치할 플러그인을 선택합니다.
. (선택 사항) *추가 옵션*을 클릭합니다.
+
|===
| 이 분야에서는... | 이렇게 하세요... 


 a| 
포트
 a| 
기본 포트 번호를 유지하거나 포트 번호를 지정하세요.  기본 포트 번호는 8145입니다.  SnapCenter 서버가 사용자 지정 포트에 설치된 경우 해당 포트 번호가 기본 포트로 표시됩니다.


NOTE: 플러그인을 수동으로 설치하고 사용자 지정 포트를 지정한 경우 동일한 포트를 지정해야 합니다.  그렇지 않으면 작업이 실패합니다.



 a| 
설치 경로
 a| 
SAP HANA용 플러그인은 HDBSQL 클라이언트 호스트에 설치되며, 이 호스트는 Windows 시스템이나 Linux 시스템에 있을 수 있습니다.

** Windows용 SnapCenter 플러그인 패키지의 경우 기본 경로는 C:\Program Files\ NetApp\ SnapCenter 입니다.  선택적으로 경로를 사용자 정의할 수 있습니다.
** Linux용 SnapCenter 플러그인 패키지의 경우 기본 경로는 /opt/ NetApp/snapcenter입니다.  선택적으로 경로를 사용자 정의할 수 있습니다.




 a| 
사전 설치 확인 건너뛰기
 a| 
플러그인을 수동으로 설치했고 호스트가 플러그인 설치 요구 사항을 충족하는지 확인하지 않으려면 이 확인란을 선택하세요.



 a| 
플러그인 서비스를 실행하려면 그룹 관리 서비스 계정(gMSA)을 사용하세요.
 a| 
Windows 호스트의 경우 플러그인 서비스를 실행하기 위해 그룹 관리 서비스 계정(gMSA)을 사용하려면 이 확인란을 선택합니다.


NOTE: 다음 형식으로 gMSA 이름을 제공하세요: domainName\accountName$.


NOTE: gMSA는 Windows용 SnapCenter 플러그인 서비스에 대한 로그온 서비스 계정으로만 사용됩니다.

|===
. *제출*을 클릭하세요.
+
"사전 검사 건너뛰기" 확인란을 선택하지 않은 경우, 호스트가 플러그인 설치 요구 사항을 충족하는지 확인하기 위해 호스트의 유효성 검사가 수행됩니다. 디스크 공간, RAM, PowerShell 버전, .NET 버전, 위치(Windows 플러그인의 경우), Java 버전(Linux 플러그인의 경우)이 최소 요구 사항을 충족하는지 검증됩니다.  최소 요구 사항을 충족하지 못하면 해당 오류 또는 경고 메시지가 표시됩니다.

+
오류가 디스크 공간이나 RAM과 관련된 경우 C:\Program Files\ NetApp\ SnapCenter WebApp에 있는 web.config 파일을 업데이트하여 기본값을 수정할 수 있습니다.  오류가 다른 매개변수와 관련된 경우 문제를 해결해야 합니다.

+

NOTE: HA 설정에서 web.config 파일을 업데이트하는 경우 두 노드에서 모두 파일을 업데이트해야 합니다.

. 호스트 유형이 Linux인 경우 지문을 확인한 다음 *확인 및 제출*을 클릭합니다.
+
클러스터 설정에서는 클러스터의 각 노드의 지문을 확인해야 합니다.

+

NOTE: 동일한 호스트가 이전에 SnapCenter 에 추가되었고 지문이 확인된 경우에도 지문 확인은 필수입니다.

. 설치 진행 상황을 모니터링합니다.
+
설치 관련 로그 파일은 /custom_location/snapcenter/logs에 있습니다.


