---
permalink: protect-hana/task_prepare_multitenant_database_containers_for_data_protection.html 
sidebar: sidebar 
keywords: multitenant database containers 
summary: 'SnapCenter 에 직접 등록된 SAP HANA 호스트의 경우 SAP HANA 데이터베이스용 SnapCenter 플러그인을 설치하거나 업그레이드하면 호스트의 리소스가 자동으로 검색됩니다.  플러그인을 설치하거나 업그레이드한 후, 플러그인 호스트에 있는 모든 멀티테넌트 데이터베이스 컨테이너 \(MDC\) 리소스에 대해 다른 GUID 형식으로 또 다른 MDC 리소스가 자동으로 검색되어 SnapCenter 에 등록됩니다.  새로운 리소스는 "잠김" 상태가 됩니다.' 
---
= 데이터 보호를 위한 멀티테넌트 데이터베이스 컨테이너 준비
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 에 직접 등록된 SAP HANA 호스트의 경우 SAP HANA 데이터베이스용 SnapCenter 플러그인을 설치하거나 업그레이드하면 호스트의 리소스가 자동으로 검색됩니다.  플러그인을 설치하거나 업그레이드한 후, 플러그인 호스트에 있는 모든 멀티테넌트 데이터베이스 컨테이너(MDC) 리소스에 대해 다른 GUID 형식으로 또 다른 MDC 리소스가 자동으로 검색되어 SnapCenter 에 등록됩니다.  새로운 리소스는 "`잠김`" 상태가 됩니다.

.이 작업에 관하여
예를 들어 SnapCenter 4.2에서 E90 MDC 리소스가 플러그인 호스트에 위치하고 수동으로 등록된 경우 SnapCenter 4.3으로 업그레이드하면 다른 GUID를 가진 또 다른 E90 MDC 리소스가 검색되어 SnapCenter 에 등록됩니다.


NOTE: SnapCenter 4.2 및 이전 버전의 리소스와 관련된 백업은 보존 기간이 만료될 때까지 보관해야 합니다.  보존 기간이 만료된 후에는 이전 MDC 리소스를 삭제하고 자동으로 검색된 새 MDC 리소스를 계속 관리할 수 있습니다.

`Old MDC resource`SnapCenter 4.2 또는 이전 릴리스에서 수동으로 추가된 플러그인 호스트에 대한 MDC 리소스입니다.

SnapCenter 4.3에서 발견된 새로운 리소스를 데이터 보호 작업에 사용하려면 다음 단계를 수행하세요.

.단계
. 리소스 페이지에서 이전 SnapCenter 릴리스에 추가된 백업이 있는 이전 MDC 리소스를 선택하고 토폴로지 페이지에서 "유지 관리 모드"로 전환합니다.
+
리소스가 리소스 그룹의 일부인 경우 리소스 그룹을 "유지 관리 모드"로 전환합니다.

. SnapCenter 4.3으로 업그레이드한 후 발견된 새로운 MDC 리소스를 구성하려면 리소스 페이지에서 새 리소스를 선택합니다.
+
"`새로운 MDC 리소스`"는 SnapCenter 서버와 플러그인 호스트가 4.3으로 업그레이드된 후 발견된 새로 발견된 MDC 리소스입니다.  새로운 MDC 리소스는 주어진 호스트에 대해 기존 MDC 리소스와 동일한 SID를 가진 리소스로 식별할 수 있으며, 리소스 페이지에서 해당 리소스 옆에 빨간색 자물쇠 아이콘이 표시됩니다.

. SnapCenter 4.3으로 업그레이드한 후 발견된 새로운 MDC 리소스를 보호하려면 보호 정책, 일정 및 알림 설정을 선택합니다.
. 보존 설정에 따라 SnapCenter 4.2 또는 이전 릴리스에서 수행된 백업을 삭제합니다.
. 토폴로지 페이지에서 리소스 그룹을 삭제합니다.
. 리소스 페이지에서 이전 MDC 리소스를 삭제합니다.
+
예를 들어, 기본 스냅샷 보존 기간이 7일이고 보조 스냅샷 보존 기간이 45일인 경우, 45일이 끝나고 모든 백업이 삭제되면 리소스 그룹과 이전 MDC 리소스를 삭제해야 합니다.



.관련 정보
link:task_configure_hdb_user_store_key_and_hdbsql_os_user_for_the_sap_hana_database.html["SAP HANA 데이터베이스에 대한 HDB 사용자 저장소 키 및 HDBSQL OS 사용자 구성"]

link:task_view_sap_hana_database_backups_and_clones_in_the_topology_page_sap_hana.html["토폴로지 페이지에서 SAP HANA 데이터베이스 백업 및 복제본 보기"]
