---
sidebar: sidebar 
permalink: sc-automation/concept_input_variables_controlling_an_api_request.html 
keywords: http methods, request headers, request body, filtering objects, size, pagination 
summary: HTTP 요청에 설정된 매개변수와 변수를 통해 API 호출이 처리되는 방식을 제어할 수 있습니다. 
---
= API 요청을 제어하는 입력 변수
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
HTTP 요청에 설정된 매개변수와 변수를 통해 API 호출이 처리되는 방식을 제어할 수 있습니다.



== HTTP 메서드

SnapCenter REST API에서 지원하는 HTTP 메서드는 다음 표에 나와 있습니다.


NOTE: 각 REST 엔드포인트에서 모든 HTTP 메서드를 사용할 수 있는 것은 아닙니다.

|===
| HTTP 메서드 | 설명 


| 얻다 | 리소스 인스턴스 또는 컬렉션에서 개체 속성을 검색합니다. 


| 우편 | 제공된 입력을 기반으로 새로운 리소스 인스턴스를 생성합니다. 


| 삭제 | 기존 리소스 인스턴스를 삭제합니다. 


| 놓다 | 기존 리소스 인스턴스를 수정합니다. 
|===


== 요청 헤더

HTTP 요청에는 여러 개의 헤더를 포함해야 합니다.



=== 콘텐츠 유형

요청 본문에 JSON이 포함되어 있는 경우 이 헤더를 _application/json_으로 설정해야 합니다.



=== 수용하다

이 헤더는 _application/json_으로 설정되어야 합니다.



=== 권한 부여

기본 인증은 사용자 이름과 비밀번호를 base64 문자열로 인코딩하여 설정해야 합니다.



== 요청 본문

요청 본문의 내용은 특정 호출에 따라 다릅니다. HTTP 요청 본문은 다음 중 하나로 구성됩니다.

* 입력 변수가 있는 JSON 객체
* 비어 있는




== 객체 필터링

GET을 사용하는 API 호출을 실행할 때 반환되는 객체를 속성에 따라 제한하거나 필터링할 수 있습니다. 예를 들어, 일치시킬 정확한 값을 지정할 수 있습니다.

`<field>=<query value>`

정확한 일치 외에도 다양한 연산자를 사용하여 값 범위에 대한 객체 집합을 반환할 수 있습니다.  SnapCenter REST API는 아래 표에 표시된 필터링 연산자를 지원합니다.

|===
| 연산자 | 설명 


| = | 동일하다 


| < | 미만 


| > | 보다 크다 


| <= | 이하 


| >= | 이상 또는 같음 


| 업데이트 | 또는 


| ! | 같지 않다 


| * | 탐욕스러운 와일드카드 
|===
*null* 키워드나 부정 *!null*을 쿼리의 일부로 사용하면 특정 필드가 설정되었는지 여부에 따라 개체 컬렉션을 반환할 수도 있습니다.


NOTE: 설정되지 않은 필드는 일반적으로 일치하는 쿼리에서 제외됩니다.



== 특정 객체 필드 요청

기본적으로 GET을 사용하여 API 호출을 실행하면 객체를 고유하게 식별하는 속성만 반환됩니다. 이 최소 필드 집합은 각 객체의 키 역할을 하며 객체 유형에 따라 달라집니다. 다음을 사용하여 추가 개체 속성을 선택할 수 있습니다. `fields` 다음과 같은 방법으로 쿼리 매개변수를 사용합니다.



=== 공통 또는 표준 필드

가장 일반적으로 사용되는 객체 필드를 검색하려면 *fields=**를 지정합니다.  이러한 필드는 일반적으로 로컬 서버 메모리에 유지되거나 액세스하는 데 거의 처리가 필요하지 않습니다.  이는 URL 경로 키(UUID)와 함께 GET을 사용한 후 객체에 대해 반환되는 속성과 동일합니다.



=== 모든 분야

*fields=***를 지정하면 추가 서버 처리가 필요한 필드를 포함하여 모든 개체 필드를 검색합니다.



=== 사용자 정의 필드 선택

원하는 정확한 필드를 지정하려면 *fields=<field_name>*을 사용하세요. 여러 필드를 요청할 경우, 공백 없이 쉼표로 값을 구분해야 합니다.


IMPORTANT: 의 필요할 때만 공통 필드 세트나 모든 필드를 검색해야 합니다.  어떤 필드가 공통으로 분류되고 _fields=*_를 사용하여 반환되는지는 NetApp 에서 내부 성능 분석을 기반으로 결정합니다.  필드 분류는 향후 릴리스에서 변경될 수 있습니다.



== 출력 세트에서 객체 정렬

리소스 컬렉션의 레코드는 객체에 정의된 기본 순서대로 반환됩니다. 다음을 사용하여 순서를 변경할 수 있습니다. `order_by` 필드 이름과 정렬 방향을 포함하는 쿼리 매개변수는 다음과 같습니다.

`order_by=<field name> asc|desc`

예를 들어, 유형 필드를 내림차순으로 정렬한 다음 ID를 오름차순으로 정렬할 수 있습니다.

`order_by=type desc, id asc`

* 정렬 필드를 지정했지만 방향을 제공하지 않으면 값이 오름차순으로 정렬됩니다.
* 여러 개의 매개변수를 포함하는 경우 필드를 쉼표로 구분해야 합니다.




== 컬렉션에서 객체를 검색할 때의 페이지 매김

GET을 사용하여 동일한 유형의 객체 컬렉션에 액세스하기 위한 API 호출을 발행할 때 SnapCenter 두 가지 제약 조건에 따라 가능한 한 많은 객체를 반환하려고 시도합니다.  요청에 대한 추가 쿼리 매개변수를 사용하여 이러한 각 제약 조건을 제어할 수 있습니다.  특정 GET 요청에 대해 도달한 첫 번째 제약 조건은 요청을 종료하고 따라서 반환되는 레코드 수를 제한합니다.


NOTE: 모든 객체를 반복하기 전에 요청이 종료되면 응답에는 다음 레코드 배치를 검색하는 데 필요한 링크가 포함됩니다.



=== 객체 수 제한

기본적으로 SnapCenter GET 요청에 대해 최대 10,000개의 객체를 반환합니다.  _max_records_ 쿼리 매개변수를 사용하여 이 제한을 변경할 수 있습니다. 예를 들어:

`max_records=20`

실제로 반환되는 객체의 수는 관련 시간 제약과 시스템의 총 객체 수에 따라 적용되는 최대값보다 적을 수 있습니다.



=== 객체를 검색하는 데 사용되는 시간 제한

기본적으로 SnapCenter GET 요청에 허용된 시간 내에 가능한 한 많은 객체를 반환합니다.  기본 제한 시간은 15초입니다.  _return_timeout_ 쿼리 매개변수를 사용하여 이 제한을 변경할 수 있습니다. 예를 들어:

`return_timeout=5`

실제로 반환되는 객체의 수는 시스템의 객체 수와 관련된 제약 조건 및 객체 총 수에 따라 적용되는 최대값보다 적을 수 있습니다.



=== 결과 집합 좁히기

필요한 경우 이 두 매개변수를 추가 쿼리 매개변수와 결합하여 결과 집합을 좁힐 수 있습니다.  예를 들어, 다음은 지정된 시간 이후에 생성된 최대 10개의 EMS 이벤트를 반환합니다.

`time=> 2018-04-04T15:41:29.140265Z&max_records=10`

여러 개의 요청을 발행하여 객체를 탐색할 수 있습니다. 이후의 각 API 호출은 마지막 결과 집합의 최신 이벤트를 기반으로 새로운 시간 값을 사용해야 합니다.



== 크기 속성

일부 API 호출과 특정 쿼리 매개변수에 사용되는 입력 값은 숫자형입니다.  바이트 단위의 정수를 제공하는 대신 다음 표에 표시된 것처럼 접미사를 사용할 수도 있습니다.

|===
| 접미사 | 설명 


| KB | KB 킬로바이트(1024바이트) 또는 키비바이트 


| 엠비 | MB 메가바이트(KB x 1024바이트) 또는 메비바이트 


| 영국 | GB 기가바이트(MB x 1024바이트) 또는 기비바이트 


| 결핵 | TB 테라바이트(GB x 1024바이트) 또는 테비바이트 


| 피비 | PB 페타바이트(TB x 1024바이트) 또는 페비바이트 
|===