---
sidebar: sidebar 
permalink: sc-automation/concept_basic_operational_characteristics.html 
keywords: request and response, object identifiers, synchronous, asynchronous 
summary: REST는 공통된 기술과 모범 사례를 제공하지만, 각 API의 세부 사항은 설계 방식에 따라 달라질 수 있습니다. 
---
= 기본 작동 특성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
REST는 공통된 기술과 모범 사례를 제공하지만, 각 API의 세부 사항은 설계 방식에 따라 달라질 수 있습니다.



== 요청 및 응답 API 트랜잭션

모든 REST API 호출은 SnapCenter 서버 시스템에 대한 HTTP 요청으로 수행되며, 이를 통해 클라이언트에 대한 관련 응답이 생성됩니다.  이 요청과 응답 쌍은 API 트랜잭션으로 간주됩니다.

API를 사용하기 전에 요청을 제어하는 데 사용할 수 있는 입력 변수와 응답 출력의 내용을 잘 알고 있어야 합니다.



== CRUD 작업 지원

SnapCenter REST API를 통해 사용 가능한 각 리소스는 CRUD 모델을 기반으로 액세스됩니다.

* 만들다
* 읽다
* 업데이트
* 삭제


일부 리소스의 경우 작업의 하위 집합만 지원됩니다.



== 객체 식별자

각 리소스 인스턴스 또는 객체는 생성될 때 고유 식별자가 할당됩니다. 대부분의 경우 식별자는 128비트 UUID입니다.  이러한 식별자는 특정 SnapCenter 서버 내에서 전역적으로 고유합니다.

새로운 객체 인스턴스를 생성하는 API 호출을 발행한 후, 연관된 ID가 있는 URL이 HTTP 응답의 위치 헤더에 포함되어 호출자에게 반환됩니다. 식별자를 추출하여 리소스 인스턴스를 참조할 때 후속 호출에서 사용할 수 있습니다.


IMPORTANT: 객체 식별자의 내용과 내부 구조는 언제든지 변경될 수 있습니다. 연관된 객체를 참조할 때 해당 API 호출에서 필요에 따라서만 식별자를 사용해야 합니다.



== 객체 인스턴스 및 컬렉션

리소스 경로와 HTTP 메서드에 따라 API 호출은 특정 개체 인스턴스나 개체 컬렉션에 적용될 수 있습니다.



== 동기 및 비동기 작업

SnapCenter 클라이언트로부터 수신한 HTTP 요청을 동기적 또는 비동기적으로 수행합니다.



=== 동기 처리

SnapCenter 요청을 즉시 수행하고 성공하면 HTTP 상태 코드 200 또는 201로 응답합니다.

GET 메서드를 사용하는 모든 요청은 항상 동기적으로 수행됩니다.  또한 POST를 사용하는 요청은 2초 이내에 완료될 것으로 예상되는 경우 동기적으로 실행되도록 설계되었습니다.



=== 비동기 처리

비동기 요청이 유효한 경우 SnapCenter 요청을 처리하기 위한 백그라운드 작업과 작업을 고정하기 위한 작업 객체를 생성합니다.  HTTP 상태 코드 202는 작업 객체와 함께 호출자에게 반환됩니다.  성공 또는 실패를 확인하려면 작업 상태를 검색해야 합니다.

POST 및 DELETE 메서드를 사용하는 요청은 완료하는 데 2초 이상 걸릴 것으로 예상되는 경우 비동기적으로 실행되도록 설계되었습니다.



== 보안

REST API가 제공하는 보안은 주로 SnapCenter 에서 제공하는 기존 보안 기능을 기반으로 합니다.  API에서는 다음과 같은 보안을 사용합니다.



=== 전송 계층 보안

SnapCenter 서버와 클라이언트 간 네트워크를 통해 전송되는 모든 트래픽은 일반적으로 SnapCenter 구성 설정에 따라 TLS를 사용하여 암호화됩니다.



=== HTTP 인증

HTTP 수준에서는 API 트랜잭션에 기본 인증이 사용됩니다.  사용자 이름과 비밀번호를 base64 문자열로 담은 HTTP 헤더가 각 요청에 추가됩니다.
