---
sidebar: sidebar 
permalink: sc-automation/concept_rest_web_services_foundation.html 
keywords: uri endpoints, http messages, json format 
summary: REST는 분산 웹 애플리케이션을 만드는 스타일입니다. 웹 서비스 API 설계에 적용되면 서버 기반 리소스를 노출하고 상태를 관리하는 데 필요한 기술과 모범 사례를 확립합니다.  SnapCenter 관리하기 위한 유연한 기반을 제공하기 위해 주류 프로토콜과 표준을 사용합니다. 
---
= REST 웹 서비스 기반
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
REST(Representational State Transfer)는 분산 웹 애플리케이션을 구축하는 스타일입니다. 웹 서비스 API 설계에 적용되면 서버 기반 리소스를 노출하고 상태를 관리하는 데 필요한 기술과 모범 사례를 확립합니다. SnapCenter 관리하기 위한 유연한 기반을 제공하기 위해 주류 프로토콜과 표준을 사용합니다.



== 자원과 국가 대표

리소스는 웹 기반 시스템의 기본 구성 요소입니다. REST 웹 서비스 애플리케이션을 구축할 때 초기 설계 작업은 다음과 같습니다.



=== 시스템 또는 서버 기반 리소스 식별

모든 시스템은 리소스를 사용하고 유지관리합니다. 리소스는 파일, 비즈니스 트랜잭션, 프로세스 또는 관리 개체일 수 있습니다. REST 웹 서비스 기반 애플리케이션을 설계할 때 가장 먼저 해야 할 작업 중 하나는 리소스를 식별하는 것입니다.



=== 리소스 상태 및 관련 상태 작업의 정의

자원은 항상 유한한 수의 상태 중 하나에 머물러 있습니다.  상태와 상태 변경에 영향을 미치는 관련 작업은 명확하게 정의되어야 합니다.



== URI 엔드포인트

모든 REST 리소스는 명확하게 정의된 주소 지정 체계를 사용하여 정의하고 제공해야 합니다. 리소스가 위치하고 식별되는 엔드포인트는 URI(Uniform Resource Identifier)를 사용합니다.

URI는 네트워크의 각 리소스에 고유한 이름을 생성하는 일반적인 프레임워크를 제공합니다. URL(Uniform Resource Locator)은 웹 서비스에서 리소스를 식별하고 액세스하는 데 사용되는 URI 유형입니다. 리소스는 일반적으로 파일 디렉터리와 유사한 계층 구조로 노출됩니다.



== HTTP 메시지

HTTP(Hypertext Transfer Protocol)는 웹 서비스 클라이언트와 서버가 리소스에 대한 요청 및 응답 메시지를 교환하는 데 사용하는 프로토콜입니다.

웹 서비스 애플리케이션을 설계하는 과정에서 HTTP 메서드는 리소스와 해당 상태 관리 작업에 매핑됩니다. HTTP는 상태를 저장하지 않습니다.  따라서 관련된 요청과 응답 세트를 하나의 트랜잭션의 일부로 연관시키려면 요청 및 응답 데이터 흐름과 함께 전달되는 HTTP 헤더에 추가 정보를 포함해야 합니다.



== JSON 포맷팅

웹 서비스 클라이언트와 서버 간에 정보를 구성하고 전송하는 방법은 여러 가지가 있지만, 가장 인기 있는 옵션은 JSON(JavaScript Object Notation)입니다.

JSON은 간단한 데이터 구조를 일반 텍스트로 표현하는 업계 표준이며, 리소스를 설명하는 상태 정보를 전송하는 데 사용됩니다. SnapCenter REST API는 JSON을 사용하여 각 HTTP 요청 및 응답 본문에 포함된 데이터를 형식화합니다.
