---
permalink: protect-azure/add-hosts-install-plugin-for-sap-hana.html 
sidebar: sidebar 
keywords: add host, install, install plug-in, SAP HANA 
summary: 호스트를 추가한 다음 플러그인 패키지를 설치합니다. 
---
= 호스트를 추가하고 SAP HANA 데이터베이스용 SnapCenter 플러그인을 설치합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 호스트 추가 페이지를 사용하여 호스트를 추가한 다음 플러그인 패키지를 설치해야 합니다.  플러그인은 원격 호스트에 자동으로 설치됩니다.

.시작하기 전에
* SnapCenter 관리자 역할과 같이 플러그인 설치 및 제거 권한이 있는 역할에 할당된 사용자여야 합니다.
* Windows 호스트에 플러그인을 설치할 때 기본 제공되지 않은 자격 증명을 지정하거나 사용자가 로컬 작업 그룹 사용자에 속하는 경우 호스트에서 UAC를 비활성화해야 합니다.
* 중앙 호스트에 설치하는 경우 SAP HANA 클라이언트 소프트웨어가 해당 호스트에 설치되어 있는지 확인하고 SAP HANA 데이터베이스 호스트에서 필요한 포트를 열어 HDB SQL 쿼리를 원격으로 실행하세요.


.단계
. 왼쪽 탐색 창에서 *호스트*를 클릭합니다.
. *관리되는 호스트* 탭이 선택되어 있는지 확인하세요.
. *추가*를 클릭하세요.
. 호스트 페이지에서 다음 작업을 수행합니다.
+
.. 호스트 유형 필드에서 호스트 유형을 선택합니다.
.. 호스트 이름 필드에 호스트의 정규화된 도메인 이름(FQDN) 또는 IP 주소를 입력합니다.
.. 자격 증명 필드에 귀하가 만든 자격 증명을 입력합니다.


. 설치할 플러그인 선택 섹션에서 설치할 플러그인을 선택합니다.
. (선택 사항) *추가 옵션*을 클릭하고 세부 정보를 지정합니다.
. *제출*을 클릭하세요.
. 호스트 유형이 Linux인 경우 지문을 확인한 다음 *확인 및 제출*을 클릭합니다.
+
클러스터 설정에서는 클러스터의 각 노드의 지문을 확인해야 합니다.

. 설치 진행 상황을 모니터링합니다.

