---
permalink: protect-azure/create-azure-credential.html 
sidebar: sidebar 
keywords: snapcenter, azure, azure credential 
summary: SnapCenter 에서 Azure 자격 증명을 만들어 Azure NetApp 계정에 액세스합니다. 
---
= SnapCenter 에서 Azure 자격 증명 만들기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Azure NetApp 계정에 액세스하려면 SnapCenter 에서 Azure 자격 증명을 만들어야 합니다.

.시작하기 전에
* Azure에서 서비스 주체를 만들었는지 확인하세요.
* 서비스 주체와 연결된 테넌트 ID, 클라이언트 ID 및 비밀 키를 사용할 수 있는지 확인하세요.
+
** 테넌트 ID는 Azure Portal의 Entra ID 개요 페이지에서 찾을 수 있습니다.
** 클라이언트 ID는 엔터프라이즈 앱/서비스 주체의 애플리케이션 ID라고도 합니다.  이는 SnapCenter 의 서비스 주체 역할을 하도록 만든 엔터프라이즈 애플리케이션의 개요 페이지에 있는 Azure Portal에서 찾을 수 있습니다.
** 클라이언트 비밀 키는 비밀 값이라고도 합니다.  Azure Portal에서 Entra ID 아래의 *앱 등록*으로 이동하여 이 클라이언트 비밀번호를 만들 수 있습니다.  생성한 엔터프라이즈 앱을 선택한 후 *인증서 및 비밀번호*로 이동한 다음 *새 클라이언트 비밀번호*로 이동합니다.
+

NOTE: 비밀 값은 생성될 때만 접근할 수 있습니다.  나중에 접근할 수 없습니다.

** 서비스 주체에게 권한을 부여해야 합니다.  기여자 역할을 통해 서비스 주체는 Azure에서 필요한 작업을 수행할 수 있습니다.  이는 구독 페이지 내의 액세스 제어(IAM) 페이지에서 부여할 수 있습니다.




.단계
. 왼쪽 탐색 창에서 *설정*을 클릭합니다.
. 설정 페이지에서 *자격 증명*을 클릭합니다.
. *새로 만들기*를 클릭합니다.
. 자격 증명 페이지에서 자격 증명을 만드는 데 필요한 다음 정보를 지정하세요.
+
|===
| 이 분야에서는... | 이렇게 하세요... 


 a| 
자격 증명 이름
 a| 
자격 증명의 이름을 입력하세요.



 a| 
인증 모드
 a| 
드롭다운 목록에서 *Azure 자격 증명*을 선택합니다.



 a| 
세입자 ID
 a| 
세입자 ID를 입력하세요.



 a| 
클라이언트 ID
 a| 
클라이언트 ID를 입력하세요.



 a| 
클라이언트 비밀 키
 a| 
클라이언트 비밀 키를 입력하세요.

|===
. *확인*을 클릭합니다.

