---
permalink: protect-azure/install-snapcenter-azure-virtual-machine.html 
sidebar: sidebar 
keywords: snapcenter server, azure virtual machine, install 
summary: Azure Virtual Machine에 SnapCenter 다운로드하여 설치합니다. 
---
= Azure 가상 머신에 SnapCenter 설치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp 지원 사이트에서 SnapCenter software 다운로드하여 Azure 가상 머신에 소프트웨어를 설치할 수 있습니다.

.시작하기 전에
* Azure Windows 가상 머신이 SnapCenter 서버 설치에 필요한 요구 사항을 충족하는지 확인하세요. 자세한 내용은 다음을 참조하세요.link:../install/requirements-to-install-snapcenter-server.html["SnapCenter 서버 설치 요구 사항"] .
* Azure NetApp Files 처음 사용하고 기존 NetApp 계정이 없는 경우 SnapCenter 소프트웨어에 액세스할 수 있도록 등록했는지 확인하세요.  자세한 내용은 다음을 참조하세요.link:../install/register_enable_software_access.html["SnapCenter software 액세스하려면 등록하세요"] .


.단계
. SnapCenter 서버 설치 패키지를 다운로드하세요. https://mysupport.netapp.com/site/products/all/details/snapcenter/downloads-tab["NetApp 지원 사이트"] .
. 다운로드한 .exe 파일을 두 번 클릭하여 SnapCenter 서버 설치를 시작합니다.
+
설치를 시작하면 모든 사전 검사가 수행되고 최소 요구 사항을 충족하지 못하면 해당 오류 또는 경고 메시지가 표시됩니다.  경고 메시지를 무시하고 설치를 진행할 수 있습니다. 그러나 오류는 수정되어야 합니다.

. SnapCenter 서버 설치에 필요한 미리 채워진 값을 검토하고 필요한 경우 수정합니다.
+
MySQL 서버 저장소 데이터베이스에 대한 비밀번호를 지정할 필요는 없습니다.  SnapCenter 서버를 설치하는 동안 비밀번호가 자동으로 생성됩니다.

+

NOTE: 저장소 데이터베이스의 사용자 지정 경로에서는 특수 문자 "%"가 지원되지 않습니다.  경로에 "%"를 포함하면 설치가 실패합니다.

. *지금 설치*를 클릭하세요.
+
잘못된 값을 지정한 경우 해당 오류 메시지가 표시됩니다.  값을 다시 입력한 다음 설치를 시작하세요.

+

NOTE: *취소* 버튼을 클릭하면 실행 중인 단계가 완료되고, 이후 롤백 작업이 시작됩니다.  SnapCenter 서버가 호스트에서 완전히 제거됩니다.

+
하지만 "SnapCenter 서버 사이트 재시작" 또는 " SnapCenter 서버 시작 대기" 작업이 수행되는 동안 *취소*를 클릭하면 작업을 취소하지 않고 설치가 진행됩니다.





== 지원을 받으려면 제품을 등록하세요

NetApp 처음 사용하고 기존 NetApp 계정이 없는 경우 지원을 받으려면 제품을 등록해야 합니다.

.단계
. SnapCenter 설치한 후 *도움말 > 정보*로 이동합니다.
. _SnapCenter 정보_ 대화 상자에서 971로 시작하는 20자리 숫자인 SnapCenter 인스턴스를 기록해 둡니다.
. 딸깍 하는 소리 https://register.netapp.com[] .
. *저는 등록된 NetApp 고객이 아닙니다*를 클릭하세요.
. 등록하려면 세부 정보를 입력하세요.
. NetApp 참조 SN 필드를 비워 두세요.
. 제품 라인 드롭다운에서 * SnapCenter*를 선택합니다.
. 청구 제공자를 선택하세요.
. 20자리 SnapCenter 인스턴스 ID를 입력하세요.
. *제출*을 클릭하세요.

