---
permalink: protect-azure/protect-applications-azure-netapp-files.html 
sidebar: sidebar 
keywords: azure netapp files, ANF, back up, restore, clone, ANF backup, Azure Blob storage 
summary: Azure NetApp Files 에서 실행되는 애플리케이션을 백업, 복원 및 복제할 수 있습니다. 
---
= Azure NetApp Files 에서 실행되는 애플리케이션 보호
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter Azure NetApp Files 에 있는 Oracle, SQL, SAP HANA와 같은 애플리케이션을 보호하는 것을 지원합니다.  SnapCenter 6.0.1 릴리스부터 장기 복구, 보관 및 규정 준수를 위한 완전 관리형 백업 솔루션을 제공하여 Azure NetApp Files 의 데이터 보호 기능을 확장하는 Azure NetApp Files 백업 기능을 지원합니다.

Azure NetApp Files 는 장기 백업 보존에 비용이 많이 들 수 있는 프리미엄 스토리지 솔루션입니다.  비용을 최적화하려면 Azure NetApp Files 저장소에서 Azure 개체 저장소로 백업을 이동할 수 있습니다.  SnapCenter 6.0.1부터 Azure NetApp Files 에 있는 애플리케이션을 Azure Blob Storage(개체 저장소)로 백업하고 복제할 수 있습니다.  단기 복구를 위해 Azure NetApp Files 저장소에 볼륨 스냅샷 복사본을 보관하고, 장기 복구를 위해 Azure Blob Storage에 또 다른 복사본을 보관하여 두 개의 데이터 복사본을 유지할 수 있습니다.

Azure NetApp Files 백업이 포함된 정책이 활성화되고 리소스와 연결되면 SnapCenter 볼륨 스냅샷을 생성하고 Azure Blob Storage에 백업합니다.  SnapCenter 백업 볼트를 생성하고 볼륨에 대한 백업을 활성화합니다.  볼륨에 대한 백업을 활성화한 경우 SnapCenter 기존 볼트를 활용합니다.



== 제한 사항

* FAS, ASA 또는 AFF ONTAP 및 Amazon FSx for NetApp ONTAP 스토리지 시스템에 대한 개체 스토리지 기능은 지원되지 않습니다.
* Oracle 및 SAP HANA 마운트 및 카탈로그 워크플로는 개체 스토리지 백업에는 지원되지 않지만 스냅샷에는 지원됩니다.
* Oracle PDB 복제본은 개체 스토리지 백업에는 지원되지 않지만 스냅샷에는 지원됩니다.
* 개체 스토리지에서의 백업 검증, REST API 지원, 개체 스토리지에서의 복제 수명 주기 관리, 개체 스토리지 백업에 대한 보고 기능은 지원되지 않습니다.
* Azure Blob Storage의 백업에서 Azure NetApp Files 로 복원하는 기능은 지원되지 않습니다.  또는 복제 옵션을 사용할 수도 있습니다.
* 복제 분할은 지원되지 않습니다.

