---
permalink: tech-refresh/task_tech_refresh_plugin_host.html 
sidebar: sidebar 
keywords: tech refresh, plug-in host, supported plug-ins, prerequisites to refresh plug-in hosts, application hosts, limitations for tech refresh of plug-in hosts 
summary: 플러그인 호스트의 기술을 새로 고치려면 이전 호스트에서 새 호스트로 리소스를 이동합니다. 
---
= SnapCenter 플러그인 호스트의 기술 업데이트
:allow-uri-read: 


[role="lead"]
SnapCenter 플러그인 호스트를 새로 고쳐야 하는 경우 리소스를 이전 호스트에서 새 호스트로 이동해야 합니다.  새로운 호스트가 SnapCenter 에 추가되면 모든 리소스가 검색되지만 새로운 리소스로 처리됩니다.

.이 작업에 관하여
이전 호스트 이름과 새 호스트 이름을 입력으로 받고, 이름으로 리소스를 비교하고, 일치하는 리소스의 객체를 이전 호스트에서 새 호스트로 다시 연결하는 API나 cmdlet을 실행해야 합니다.  일치하는 리소스는 보호됨으로 표시됩니다.

* _IsDryRun_ 매개변수는 기본적으로 True로 설정되며 이는 이전 호스트와 새 호스트의 일치하는 리소스를 식별합니다.
+
일치하는 리소스를 확인한 후 _IsDryRun_ 매개변수를 False로 설정하여 일치하는 리소스의 객체를 이전 호스트에서 새 호스트로 다시 연결해야 합니다.

* _AutoMigrateManuallyAddedResources_ 매개변수는 기본적으로 True로 설정되어 있으며, 이를 통해 수동으로 추가된 리소스가 이전 호스트에서 새 호스트로 자동으로 복사됩니다.
+
_AutoMigrateManuallyAddedResources_ 매개변수는 Oracle 및 SAP HANA 리소스에만 적용할 수 있습니다.

* 이전 호스트와 새 호스트의 인스턴스 이름이 다른 경우 _SQLInstanceMapping_ 매개변수를 사용해야 합니다.  기본 인스턴스인 경우 인스턴스 이름으로 _default_instance_를 사용합니다.


다음 SnapCenter 플러그인에 대해 기술 업데이트가 지원됩니다.

* Microsoft SQL Server용 SnapCenter 플러그인
+
** SQL 데이터베이스가 인스턴스 수준에서 보호되고 호스트 기술 업데이트의 일부로 일부 리소스만 새 호스트로 이동된 경우 기존 인스턴스 수준 보호는 리소스 그룹 보호로 변환되고 두 호스트의 인스턴스가 리소스 그룹에 추가됩니다.
** SQL 호스트(예: host1)가 다른 호스트(예: host2)의 리소스에 대한 스케줄러 또는 검증 서버로 사용되는 경우, host1에서 기술 업데이트를 수행하는 동안 스케줄이나 검증 세부 정보는 마이그레이션되지 않고 host1에서 계속 실행됩니다.  수정해야 하는 경우 해당 호스트에서 수동으로 변경해야 합니다.
** SQL FCI(Failover Cluster Instances) 설정을 사용하는 경우 FCI 클러스터에 새 노드를 추가하고 SnapCenter 에서 플러그인 호스트를 새로 고쳐서 기술 업데이트를 수행할 수 있습니다.
** SQL 가용성 그룹(AG) 설정을 사용하는 경우 기술 업데이트가 필요하지 않습니다.  AG에 새로운 노드를 추가하고 SnapCenter 에서 호스트를 새로 고칠 수 있습니다.


* Windows용 SnapCenter 플러그인
* Oracle 데이터베이스용 SnapCenter 플러그인
+
Oracle Real Application Cluster(RAC) 설정을 사용하는 경우 RAC 클러스터에 새 노드를 추가하고 SnapCenter 에서 플러그인 호스트를 새로 고쳐서 기술 새로 고침을 수행할 수 있습니다.

* SAP HANA 데이터베이스용 SnapCenter 플러그인


지원되는 사용 사례는 다음과 같습니다.

* 한 호스트에서 다른 호스트로 리소스를 마이그레이션합니다.
* 여러 호스트에서 하나 이하의 호스트로 리소스를 마이그레이션합니다.
* 한 호스트에서 여러 호스트로 리소스를 마이그레이션합니다.


지원되는 시나리오는 다음과 같습니다.

* 새로운 호스트의 이름은 이전 호스트와 다릅니다.
* 기존 호스트의 이름이 변경되었습니다.


.시작하기 전에
이 워크플로는 SnapCenter 저장소의 데이터를 수정하므로 SnapCenter 저장소를 백업하는 것이 좋습니다.  데이터 문제가 발생할 경우 SnapCenter 저장소를 백업을 사용하여 이전 상태로 되돌릴 수 있습니다.

자세한 내용은 다음을 참조하세요.  https://docs.netapp.com/us-en/snapcenter/admin/concept_manage_the_snapcenter_server_repository.html#back-up-the-snapcenter-repository["SnapCenter 저장소 백업"] .

.단계
. 새로운 호스트를 배포하고 애플리케이션을 설치합니다.
. 이전 호스트의 일정을 중단합니다.
. 필요한 리소스를 이전 호스트에서 새 호스트로 이동합니다.
+
.. 동일한 저장소에서 새 호스트에 필요한 데이터베이스를 불러옵니다.
+
*** 저장소가 이전 호스트와 동일한 드라이브 또는 동일한 마운트 경로에 매핑되었는지 확인하세요.  저장소가 올바르게 매핑되지 않으면 이전 호스트에서 생성된 백업을 복원에 사용할 수 없습니다.
+

NOTE: 기본적으로 Windows는 사용 가능한 다음 드라이브를 자동으로 할당합니다.

*** 스토리지 DR이 활성화된 경우 해당 스토리지를 새 호스트에 마운트해야 합니다.


.. 애플리케이션 버전이 변경된 경우 호환성을 확인하세요.
.. Oracle 플러그인 호스트의 경우에만 Oracle과 해당 그룹 사용자의 UID와 GID가 이전 호스트와 동일한지 확인하세요.
+
자세한 내용은 다음을 참조하세요.

+
*** https://kb.netapp.com/mgmt/SnapCenter/How_to_perform_SQL_host_tech_refresh["이전 호스트에서 새 호스트로 SQL 데이터베이스를 마이그레이션하는 방법"]
*** https://kb.netapp.com/mgmt/SnapCenter/How_to_perform_Oracle_host_tech_refresh["Oracle 데이터베이스를 이전 호스트에서 새 호스트로 마이그레이션하는 방법"]
*** https://kb.netapp.com/mgmt/SnapCenter/How_to_perform_Hana_host_tech_refresh["새 호스트에 SAP HANA 데이터베이스를 가져오는 방법"]




. SnapCenter 에 새로운 호스트를 추가합니다.
. 모든 리소스가 검색되었는지 확인하세요.
. 호스트 새로 고침 API를 실행합니다. `/<snapcenter_version>/techrefresh/host` 또는 cmdlet: _Invoke-SmTechRefreshHost_.
+

NOTE: 기본적으로 드라이런이 활성화되어 있으며, 다시 연결할 일치하는 리소스가 식별됩니다.  API: '/jobs/{jobid}' 또는 cmdlet _Get-SmJobSummaryReport_를 실행하여 리소스를 확인할 수 있습니다.

+
여러 호스트에서 리소스를 마이그레이션한 경우 모든 호스트에 대해 API나 cmdlet을 실행해야 합니다.  새 호스트의 드라이브 또는 마운트 경로가 이전 호스트와 동일하지 않으면 다음 복원 작업이 실패합니다.

+
** SQL 내부 복원은 실패합니다.  하지만 RTAL 기능을 활용할 수 있습니다.
** Oracle 및 SAP HANA 데이터베이스 복원이 실패합니다.
+
여러 호스트로 마이그레이션하려면 모든 호스트에 대해 1단계부터 모든 단계를 수행해야 합니다.

+

NOTE: 동일한 호스트에서 API나 cmdlet을 여러 번 실행할 수 있으며, 새로운 리소스가 식별된 경우에만 다시 연결됩니다.



. (선택 사항) SnapCenter 에서 이전 호스트를 제거합니다.


.관련 정보
API에 대한 정보를 보려면 Swagger 페이지에 액세스해야 합니다.link:https://docs.netapp.com/us-en/snapcenter/sc-automation/task_how%20to_access_rest_apis_using_the_swagger_api_web_page.html["Swagger API 웹 페이지를 사용하여 REST API에 액세스하는 방법"] .

cmdlet과 함께 사용할 수 있는 매개변수와 해당 설명에 대한 정보는 _Get-Help command_name_을 실행하면 얻을 수 있습니다.  또는 다음을 참조할 수도 있습니다. https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter 소프트웨어 Cmdlet 참조 가이드"^] .
