---
permalink: tech-refresh/task_tech_refresh_storage_system.html 
sidebar: sidebar 
keywords: tech refresh, storage system, 
summary: 데이터를 기존 스토리지에서 새 스토리지로 옮기고, 새 스토리지를 해당 호스트에 마운트한 다음 데이터베이스를 구동하여 스토리지 시스템의 기술을 새로 고칩니다. 
---
= 저장 시스템의 기술 업데이트
:allow-uri-read: 


[role="lead"]
스토리지가 기술적으로 업데이트되면 데이터는 새로운 스토리지로 마이그레이션되고 애플리케이션 호스트는 새로운 스토리지에 마운트됩니다.  SnapCenter 백업 워크플로는 새 저장소를 식별하고 새 저장소가 SnapCenter 에 등록되면 스냅샷을 만듭니다.

저장소 새로 고침 후 생성된 새 백업에 대해 복원, 마운트 및 복제를 수행할 수 있습니다.  그러나 저장소 새로 고침 전에 생성된 백업에서 이러한 작업을 수행하면 실패하게 됩니다. 백업에 이전 저장소 세부 정보가 있기 때문입니다.  SnapCenter 의 이전 백업을 새 스토리지 세부 정보로 업데이트하려면 스토리지 기술 새로 고침 API 또는 cmdlet을 실행해야 합니다.

다음 SnapCenter 플러그인에 대해 기술 업데이트가 지원됩니다.

* Microsoft SQL Server용 SnapCenter 플러그인
* Windows용 SnapCenter 플러그인
* Oracle 데이터베이스용 SnapCenter 플러그인
* SAP HANA 데이터베이스용 SnapCenter 플러그인
* Microsoft Exchange Server용 SnapCenter 플러그인


지원되는 사용 사례는 다음과 같습니다.

* 기본 저장소 새로 고침
+
스토리지 기술 갱신은 기본 스토리지를 새 스토리지로 교체하는 데 지원됩니다.  기존의 보조 저장소를 기본 저장소로 변환할 수 없습니다.

* 보조 저장소 새로 고침




== 기본 저장소의 백업을 업데이트합니다.

저장소 기술이 업데이트되면 저장소 기술 업데이트 API 또는 cmdlet을 실행하여 SnapCenter 의 이전 백업을 새 저장소 세부 정보로 업데이트해야 합니다.

.시작하기 전에
이 워크플로는 SnapCenter 저장소의 데이터를 수정하므로 SnapCenter 저장소를 백업하는 것이 좋습니다.  데이터 문제가 발생할 경우 SnapCenter 저장소를 백업을 사용하여 이전 상태로 되돌릴 수 있습니다.

자세한 내용은 다음을 참조하세요.  https://docs.netapp.com/us-en/snapcenter/admin/concept_manage_the_snapcenter_server_repository.html#back-up-the-snapcenter-repository["SnapCenter 저장소 백업"] .

.단계
. 기존 저장소에서 새 저장소로 데이터를 마이그레이션합니다.
+
마이그레이션 방법에 대한 자세한 내용은 다음을 참조하세요.

+
** https://kb.netapp.com/mgmt/SnapCenter/How_to_perform_Storage_tech_refresh["데이터를 새 저장소로 마이그레이션하는 방법"]
** https://kb.netapp.com/onprem/ontap/dp/SnapMirror/How_can_I_copy_a_volume_and_preserve_all_of_the_Snapshot_copies["볼륨을 복사하고 모든 스냅샷 사본을 보존하려면 어떻게 해야 합니까?"]


. 호스트를 유지 관리 모드로 전환합니다.
. 각 호스트에 새로운 스토리지를 마운트하고 데이터베이스를 불러옵니다.
+
새로운 저장소는 이전과 같은 방식으로 호스트에 연결되어야 합니다.  예를 들어, SAN으로 연결된 경우 SAN으로 연결해야 합니다.

+
새로운 저장소는 기존 저장소와 동일한 드라이브나 경로에 마운트되어야 합니다.

. 모든 리소스가 제대로 작동하고 있는지 확인하세요.
. SnapCenter 에 새로운 저장소를 추가합니다.
+
SnapCenter 의 클러스터 전체에서 고유한 SVM 이름이 있는지 확인하세요.  새 스토리지에서 동일한 SVM 이름을 사용하고 스토리지 새로 고침을 실행하기 전에 SVM의 모든 볼륨을 마이그레이션할 수 있는 경우, 이전 클러스터에서 SVM을 삭제하고 SnapCenter 에서 이전 클러스터를 다시 검색하여 캐시에서 SVM을 제거하는 것이 좋습니다.

. 호스트를 프로덕션 모드로 전환합니다.
. SnapCenter 에서 스토리지가 마이그레이션된 리소스의 백업을 만듭니다.  SnapCenter 에서 최신 스토리지 공간을 식별하려면 새로운 백업이 필요하며, 이는 기존 백업의 메타데이터를 업데이트하는 데 사용됩니다.
+

NOTE: 새로운 LUN이 호스트에 연결될 때마다 새로운 일련 번호가 지정됩니다.  Windows 파일 시스템을 검색하는 동안 SnapCenter 모든 고유한 일련 번호를 새 리소스로 처리합니다.  스토리지 기술 새로 고침 중에 새 스토리지의 LUN이 동일한 드라이브 문자 또는 경로로 호스트에 연결되면 SnapCenter 에서 Windows 파일 시스템을 검색하여 동일한 드라이브 문자 또는 경로로 마운트된 경우에도 기존 리소스를 삭제된 것으로 표시하고 새 LUN을 새 리소스로 표시합니다.  리소스가 삭제됨으로 표시되면 SnapCenter 에서 스토리지 기술 새로 고침에 고려되지 않으며 이전 리소스의 모든 백업이 손실됩니다.  Windows 파일 시스템 리소스의 경우 저장소 새로 고침이 발생할 때마다 저장소 새로 고침 API 또는 cmdlet을 실행하기 전에 리소스 검색을 수행해서는 안 됩니다.

. 저장소 새로 고침 API를 실행합니다. `/<snapcenter_version>/techrefresh/primarystorage` 또는 cmdlet: _Invoke-SmTechRefreshPrimaryStorage_.
+

NOTE: 리소스가 복제가 활성화된 정책으로 구성된 경우, 저장소 새로 고침 후의 최신 백업에는 보조 저장소에 대한 세부 정보가 포함되어야 합니다.

+
.. SQL FCI(Failover Cluster Instances) 설정을 사용하는 경우 백업은 클러스터 수준에서 유지 관리됩니다.  스토리지 기술 업데이트에 대한 입력으로 클러스터 이름을 제공해야 합니다.
.. SQL 가용성 그룹(AG) 설정을 사용하는 경우 백업은 노드 수준에서 유지 관리됩니다.  스토리지 기술 업데이트에 대한 입력으로 노드 이름을 제공해야 합니다.
.. Oracle Real Application Clusters(RAC) 설정을 사용하는 경우 모든 노드에서 스토리지 기술 새로 고침을 수행할 수 있습니다.
+
_IsDryRun_ 속성은 기본적으로 True로 설정됩니다.  저장소가 새로 고쳐지는 리소스를 식별합니다.  API: '<snapcenter_version>/jobs/{jobid}' 또는 cmdlet _Get-SmJobSummaryReport_를 실행하여 리소스와 변경된 저장소 세부 정보를 볼 수 있습니다.



. 저장소 세부 정보를 확인한 후 _IsDryRun_ 속성을 False로 설정하고 저장소 새로 고침 API를 실행합니다. `/<snapcenter_version>/techrefresh/primarystorage` 또는 cmdlet: _Invoke-SmTechRefreshPrimaryStorage_.
+
이렇게 하면 이전 백업의 저장 세부 정보가 업데이트됩니다.

+
동일한 호스트에서 API나 cmdlet을 여러 번 실행할 수 있으며, 저장소가 새로 고쳐진 경우에만 이전 백업의 저장소 세부 정보가 업데이트됩니다.

+

NOTE: ONTAP 에서는 클론 계층을 마이그레이션할 수 없습니다.  마이그레이션되는 스토리지에 SnapCenter 에 복제 메타데이터가 있는 경우 복제된 리소스는 독립 리소스로 표시됩니다.  복제 메타데이터의 복제본은 재귀적으로 제거됩니다.

. (선택 사항) 모든 스냅샷이 이전 기본 저장소에서 새 기본 저장소로 이동되지 않은 경우 다음 API를 실행합니다. `/<snapcenter_version>/hosts/primarybackupsexistencecheck` 또는 cmdlet _Invoke-SmPrimaryBackupsExistenceCheck_.
+
이렇게 하면 새로운 기본 저장소에서 스냅샷 존재 여부 검사가 수행되고 해당 백업을 SnapCenter 에서 어떤 작업에도 사용할 수 없음으로 표시합니다.





== 보조 저장소의 백업을 업데이트합니다.

저장소 기술이 업데이트되면 저장소 기술 업데이트 API 또는 cmdlet을 실행하여 SnapCenter 의 이전 백업을 새 저장소 세부 정보로 업데이트해야 합니다.

.시작하기 전에
이 워크플로는 SnapCenter 저장소의 데이터를 수정하므로 SnapCenter 저장소를 백업하는 것이 좋습니다.  데이터 문제가 발생할 경우 SnapCenter 저장소를 백업을 사용하여 이전 상태로 되돌릴 수 있습니다.

자세한 내용은 다음을 참조하세요.  https://docs.netapp.com/us-en/snapcenter/admin/concept_manage_the_snapcenter_server_repository.html#back-up-the-snapcenter-repository["SnapCenter 저장소 백업"] .

.단계
. 기존 저장소에서 새 저장소로 데이터를 마이그레이션합니다.
+
마이그레이션 방법에 대한 자세한 내용은 다음을 참조하세요.

+
** https://kb.netapp.com/mgmt/SnapCenter/How_to_perform_Storage_tech_refresh["데이터를 새 저장소로 마이그레이션하는 방법"]
** https://kb.netapp.com/onprem/ontap/dp/SnapMirror/How_can_I_copy_a_volume_and_preserve_all_of_the_Snapshot_copies["볼륨을 복사하고 모든 스냅샷 사본을 보존하려면 어떻게 해야 합니까?"]


. 기본 저장소와 새로운 보조 저장소 사이에 SnapMirror 관계를 설정하고 관계 상태가 양호한지 확인합니다.
. SnapCenter 에서 스토리지가 마이그레이션된 리소스의 백업을 만듭니다.
+
SnapCenter 에서 최신 스토리지 공간을 식별하려면 새로운 백업이 필요하며, 이는 기존 백업의 메타데이터를 업데이트하는 데 사용됩니다.

+

IMPORTANT: 이 작업이 완료될 때까지 기다려야 합니다.  완료 전에 다음 단계로 진행하면 SnapCenter 이전 보조 스냅샷 메타데이터가 완전히 손실됩니다.

. 호스트의 모든 리소스에 대한 백업을 성공적으로 생성한 후 보조 스토리지 새로 고침 API를 실행합니다. `/<snapcenter_version>/techrefresh/secondarystorage` 또는 cmdlet: _Invoke-SmTechRefreshSecondaryStorage_.
+
이렇게 하면 지정된 호스트의 이전 백업에 대한 보조 저장소 세부 정보가 업데이트됩니다.

+
리소스 수준에서 이를 실행하려면 각 리소스에 대해 *새로 고침*을 클릭하여 보조 저장소 메타데이터를 업데이트합니다.

. 이전 백업을 성공적으로 업데이트한 후에는 기존 보조 저장소와 기본 저장소의 관계를 끊을 수 있습니다.

