---
permalink: admin/concept_overview_of_dashboard.html 
sidebar: sidebar 
keywords: dashboard 
summary: 'SnapCenter 왼쪽 탐색 창에서 대시보드를 통해 최근 작업 활동, 알림, 보호 요약, 스토리지 효율성 및 사용량, SnapCenter 작업 상태(백업, 복제, 복원), 독립 실행형 및 Windows 클러스터 호스트의 구성 상태, SnapCenter 에서 관리하는 스토리지 가상 머신(SVM) 수, 라이선스 용량 등 시스템 상태를 한눈에 볼 수 있습니다.' 
---
= 대시보드 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 왼쪽 탐색 창에서 대시보드를 통해 최근 작업 활동, 알림, 보호 요약, 스토리지 효율성 및 사용량, SnapCenter 작업 상태(백업, 복제, 복원), 독립 실행형 및 Windows 클러스터 호스트의 구성 상태, SnapCenter 에서 관리하는 스토리지 가상 머신(SVM) 수, 라이선스 용량 등 시스템 상태를 한눈에 볼 수 있습니다.

대시보드 보기에 표시되는 정보는 현재 SnapCenter 에 로그인한 사용자에게 할당된 역할에 따라 달라집니다.  사용자에게 해당 정보를 볼 권한이 없으면 일부 콘텐츠가 표시되지 않을 수 있습니다.

많은 경우, *i*에 마우스를 올리면 디스플레이에 대한 자세한 정보를 볼 수 있습니다.  어떤 경우에는 대시보드 표시의 정보가 SnapCenter GUI 페이지(리소스, 모니터, 보고서 등)의 자세한 소스 정보에 연결됩니다.



== 최근 직무 활동

최근 작업 활동 타일은 사용자가 액세스할 수 있는 모든 백업, 복원 및 복제 작업의 최신 작업 활동을 표시합니다.  이 디스플레이의 작업은 완료, 경고, 실패, 실행 중, 대기 중, 취소 중 하나의 상태를 갖습니다.

일자리 위에 마우스를 올리면 자세한 정보가 표시됩니다.  특정 작업 번호를 클릭하면 모니터 페이지로 이동하여 추가 작업 정보를 볼 수 있습니다.  여기에서 작업 세부 정보나 로그 정보를 얻고, 해당 작업에 대한 구체적인 보고서를 생성할 수 있습니다.

*모두 보기*를 클릭하면 모든 SnapCenter 작업의 기록을 볼 수 있습니다.



== 알림

알림 타일은 호스트와 SnapCenter 서버에 대한 최신의 해결되지 않은 중요 및 경고 알림을 표시합니다.

위험 및 경고 범주 알림의 총 개수가 화면 상단에 표시됩니다.  중요 또는 경고 총계를 클릭하면 알림 페이지에 특정 필터가 적용된 알림 페이지로 이동합니다.

특정 알림을 클릭하면 해당 알림에 대한 자세한 내용을 볼 수 있는 알림 페이지로 이동합니다.  화면 하단의 *모두 보기*를 클릭하면 모든 알림 목록이 있는 알림 페이지로 이동합니다.



== 최신 보호 요약

최신 보호 요약 타일은 사용자가 액세스할 수 있는 모든 엔터티의 보호 상태를 알려줍니다.  기본적으로 디스플레이는 모든 플러그인의 상태를 제공하도록 설정되어 있습니다.  스냅샷으로 기본 저장소에 백업된 리소스와 SnapMirror 및 SnapVault 기술을 사용하여 보조 저장소에 백업된 리소스에 대한 상태 정보가 제공됩니다.  보조 저장소에 대한 보호 상태 정보의 가용성은 선택한 플러그인 유형에 따라 달라집니다.


NOTE: 미러 볼트 보호 정책을 사용하는 경우 보호 요약에 대한 카운터는 SnapVault 차트가 아닌 SnapMirror 요약 차트에 표시됩니다.

개별 플러그인의 보호 상태는 드롭다운 메뉴에서 플러그인을 선택하여 확인할 수 있습니다.  도넛형 차트는 선택한 플러그인의 보호된 리소스 비율을 보여줍니다. 도넛형 조각을 클릭하면 *보고서* > *플러그인* 페이지로 이동하여 지정된 플러그인의 모든 기본 및 보조 스토리지 활동에 대한 상세 보고서를 제공합니다.


IMPORTANT: 보조 저장소에 대한 보고서는 SnapVault 에만 적용되며 SnapMirror 보고서는 지원되지 않습니다.


NOTE: SAP HANA는 스냅샷의 기본 및 보조 스토리지에 대한 보호 상태 정보를 제공합니다.  파일 기반 백업에는 기본 저장소 보호 상태만 사용할 수 있습니다.

|===
| 보호 상태 | 1차 저장소 | 2차 저장소 


 a| 
실패한
 a| 
리소스 그룹이 백업을 실행했지만 백업이 실패한 경우, 리소스 그룹에 속한 엔터티의 수입니다.
 a| 
보조 대상으로 전송하지 못한 백업이 있는 엔터티의 수입니다.



 a| 
성공적인
 a| 
리소스 그룹이 성공적으로 백업된 리소스 그룹의 엔터티 수입니다.
 a| 
백업이 보조 대상으로 성공적으로 전송된 엔터티의 수입니다.



 a| 
구성되지 않음
 a| 
리소스 그룹에 속하지 않고 백업되지 않은 엔터티의 수입니다.
 a| 
백업을 보조 대상으로 전송하도록 구성되지 않은 하나 이상의 리소스 그룹에 속하는 엔터티의 수입니다.



 a| 
시작되지 않음
 a| 
리소스 그룹에 속하지만 백업이 실행되지 않은 엔터티의 수입니다.
 a| 
해당 없음.

|===

NOTE: SnapCenter Server 4.2와 이전 버전의 플러그인(4.2 이전 버전)을 사용하여 백업을 생성하는 경우, *최신 보호 요약* 타일에는 이러한 백업의 SnapMirror 보호 상태가 표시되지 않습니다.



== 일자리

작업 타일은 사용자가 액세스할 수 있는 백업, 복원 및 복제 작업에 대한 요약을 제공합니다.  드롭다운 메뉴를 사용하여 보고서의 기간을 사용자 지정할 수 있습니다.  기간 옵션은 최근 24시간, 최근 7일, 최근 30일로 고정됩니다.  기본 보고서에는 지난 7일 동안 실행된 데이터 보호 작업이 표시됩니다.

백업, 복원 및 복제 작업 정보는 도넛 차트로 표시됩니다.  도넛 조각을 클릭하면 선택 항목에 작업 필터가 미리 적용된 모니터 페이지로 이동합니다.

|===
| 작업 상태 | 설명 


 a| 
실패한
 a| 
실패한 작업의 수.



 a| 
경고
 a| 
오류가 발생한 작업의 수입니다.



 a| 
성공적인
 a| 
성공적으로 완료된 작업의 수입니다.



 a| 
달리기
 a| 
현재 실행 중인 작업의 수입니다.

|===


== 스토리지

저장소 타일은 90일 동안 보호 작업에 사용된 기본 및 보조 저장소를 표시하고, 소비 추세를 그래픽으로 표현하며, 기본 저장소 절감액을 계산합니다.  저장 정보는 24시간마다 오전 12시에 업데이트됩니다.

SnapCenter 에서 사용 가능한 백업의 총 수와 이러한 백업이 차지하는 크기를 포함하는 하루 총 사용량이 화면 상단에 표시됩니다.  백업에는 여러 개의 스냅샷이 연관될 수 있으며 개수도 동일하게 반영됩니다.  이는 기본 및 보조 스냅샷 모두에 적용됩니다.  예를 들어, 10개의 백업을 생성했는데, 그 중 2개는 정책 기반 백업 보존으로 인해 삭제되었고 1개는 사용자가 명시적으로 삭제한 백업입니다.  따라서 7개의 백업이 차지하는 크기와 함께 7개의 백업 수가 표시됩니다.

기본 스토리지의 스토리지 절약 계수는 논리적 용량(복제본 및 스냅샷 절약과 소비된 스토리지)과 기본 스토리지의 물리적 용량의 비율입니다.  막대형 차트는 저장 공간 절약 효과를 보여줍니다.

선형 그래프는 90일 동안의 일별 1차 및 2차 저장소 소비량을 별도로 표시합니다.  차트 위에 마우스를 올리면 일별 자세한 결과가 표시됩니다.


NOTE: SnapCenter Server 4.2와 이전 버전의 플러그인(4.2 이전 버전)을 사용하여 백업을 생성하는 경우, *저장소* 타일에는 백업 수, 백업에 사용된 저장 공간, 스냅샷 절약량, 복제본 절약량 및 스냅샷 크기가 표시되지 않습니다.



== 구성

구성 타일은 SnapCenter 관리하고 사용자가 액세스할 수 있는 모든 활성 독립형 및 Windows 클러스터 호스트에 대한 통합 상태 정보를 제공합니다.  여기에는 해당 호스트와 관련된 플러그인 상태 정보가 포함됩니다.

호스트 옆에 있는 숫자를 클릭하면 호스트 페이지의 관리 호스트 섹션으로 이동합니다.  여기에서 선택한 호스트에 대한 자세한 정보를 얻을 수 있습니다.

또한 이 디스플레이는 SnapCenter 에서 관리하고 사용자가 액세스할 수 있는 Standalone ONTAP SVM과 Cluster ONTAP SVM의 합계를 보여줍니다.  SVM 옆에 있는 숫자를 클릭하면 스토리지 시스템 페이지로 이동합니다.  여기에서 선택한 SVM에 대한 자세한 정보를 얻을 수 있습니다.

호스트 구성 상태는 빨간색(중요), 노란색(경고), 녹색(활성)으로 표시되며 각 상태에 있는 호스트 수도 함께 표시됩니다.  각 상태에 대한 상태 메시지가 제공됩니다.

|===
| 구성 상태 | 설명 


 a| 
업그레이드 필수
 a| 
지원되지 않는 플러그인을 실행하고 업그레이드가 필요한 호스트의 수입니다.  지원되지 않는 플러그인은 이 버전의 SnapCenter 와 호환되지 않습니다.



 a| 
이주 필수
 a| 
지원되지 않는 플러그인을 실행 중이고 마이그레이션이 필요한 호스트의 수입니다.  지원되지 않는 플러그인은 이 버전의 SnapCenter 와 호환되지 않습니다.



 a| 
플러그인이 설치되지 않았습니다
 a| 
플러그인을 설치해야 하거나 플러그인 설치에 실패했지만 성공적으로 추가된 호스트 수입니다.



 a| 
정지된
 a| 
일정이 중단되어 유지 관리 중인 호스트 수입니다.



 a| 
멈췄다
 a| 
플러그인 서비스가 실행되지 않지만 작동 중인 호스트의 수입니다.



 a| 
호스트 다운
 a| 
다운되었거나 접속할 수 없는 호스트의 수입니다.



 a| 
업그레이드 가능(선택 사항)
 a| 
플러그인 패키지의 최신 버전을 업그레이드할 수 있는 호스트 수입니다.



 a| 
마이그레이션 가능(선택 사항)
 a| 
플러그인의 최신 버전을 마이그레이션할 수 있는 호스트 수입니다.



 a| 
로그 디렉토리 구성
 a| 
SCSQL이 트랜잭션 로그 백업을 수행하기 위해 로그 디렉토리를 구성해야 하는 호스트 수입니다.



 a| 
VMware 플러그인 구성
 a| 
SnapCenter Plug-in for VMware vSphere 추가해야 하는 호스트 수입니다.



 a| 
알려지지 않은
 a| 
등록되었지만 설치가 아직 시작되지 않은 호스트의 수입니다.



 a| 
달리기
 a| 
작동 중인 호스트 수와 플러그인이 실행 중인 호스트 수입니다.  그리고 SCSQL 플러그인의 경우, 로그 디렉토리와 하이퍼바이저가 구성됩니다.



 a| 
플러그인 설치/제거
 a| 
플러그인 설치 또는 제거가 진행 중인 호스트의 수입니다.

|===