---
permalink: admin/concept_manage_policies.html 
sidebar: sidebar 
keywords: Manage policies 
summary: 리소스 또는 리소스 그룹에서 정책을 분리하고, 수정, 삭제, 보기 및 복사할 수 있습니다. 
---
= 정책 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
리소스 또는 리소스 그룹에서 정책을 분리하고, 수정, 삭제, 보기 및 복사할 수 있습니다.



== 정책 수정

정책이 리소스 또는 리소스 그룹에 연결되어 있는 동안 복제 옵션, 스냅샷 보존 설정, 오류 재시도 횟수 또는 스크립트 정보를 수정할 수 있습니다.  정책을 분리한 후에만 일정 유형(빈도)을 수정할 수 있습니다.

*이 작업에 관하여*

정책에서 일정 유형을 수정하려면 추가 단계가 필요합니다. SnapCenter 서버는 정책이 리소스나 리소스 그룹에 연결될 때만 일정 유형을 등록하기 때문입니다.

|===
| 만약 당신이 원한다면... | 그 다음에... 


 a| 
추가 일정 유형 추가
 a| 
새로운 정책을 만들어 필요한 리소스나 리소스 그룹에 연결합니다.

예를 들어, 리소스 그룹 정책이 매시간 백업만 지정하고 매일 백업도 추가하려는 경우, 매일 일정 유형으로 정책을 만들어 리소스 그룹에 추가할 수 있습니다.  그러면 리소스 그룹에는 시간별 정책과 일별 정책이라는 두 가지 정책이 생깁니다.



 a| 
일정 유형 제거 또는 변경
 a| 
다음을 수행하세요.

. 해당 정책을 사용하는 모든 리소스와 리소스 그룹에서 정책을 분리합니다.
. 일정 유형을 수정합니다.
. 모든 리소스와 리소스 그룹에 정책을 다시 연결합니다.


예를 들어, 정책에서 매시간 백업을 지정하고 이를 매일 백업으로 변경하려는 경우 먼저 해당 정책을 분리해야 합니다.

|===
*단계*

. 왼쪽 탐색 창에서 *설정*을 클릭합니다.
. 설정 페이지에서 *정책*을 클릭합니다.
. 정책을 선택한 다음 *수정*을 클릭합니다.
. 정보를 수정한 후 *마침*을 클릭합니다.




== 정책 분리

더 이상 해당 정책으로 리소스의 데이터 보호를 관리하고 싶지 않으면 언제든지 리소스 또는 리소스 그룹에서 정책을 분리할 수 있습니다.  정책을 삭제하거나 일정 유형을 수정하려면 먼저 정책을 분리해야 합니다.

*단계*

. 왼쪽 탐색 창에서 *리소스*를 클릭한 다음 목록에서 적절한 플러그인을 선택합니다.
. 리소스 페이지에서 *보기* 목록에서 *리소스 그룹*을 선택합니다.
. 리소스 그룹을 선택한 다음 *리소스 그룹 수정*을 클릭합니다.
. 리소스 그룹 수정 마법사의 정책 페이지에서 드롭다운 목록에서 분리하려는 정책 옆에 있는 확인 표시를 지웁니다.
. 마법사의 나머지 부분에서 리소스 그룹에 대한 추가 수정 사항을 적용한 다음 *마침*을 클릭합니다.




== 정책 삭제

더 이상 정책이 필요하지 않은 경우 정책을 삭제하는 것이 좋습니다.

.시작하기 전에
정책이 리소스 또는 리소스 그룹과 연결되어 있는 경우 해당 정책을 리소스 또는 리소스 그룹에서 분리해야 합니다.

*단계*

. 왼쪽 탐색 창에서 *설정*을 클릭합니다.
. 설정 페이지에서 *정책*을 클릭합니다.
. 정책을 선택한 다음 *삭제*를 클릭합니다.
. *예*를 클릭하세요.

