---
permalink: admin/concept_manage_the_storage_system.html 
sidebar: sidebar 
keywords: Manage storage system 
summary: 스토리지 시스템을 추가한 후에는 스토리지 시스템 구성과 연결을 수정하거나 스토리지 시스템을 삭제할 수 있습니다. 
---
= 저장 시스템 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 시스템을 추가한 후에는 스토리지 시스템 구성과 연결을 수정하거나 스토리지 시스템을 삭제할 수 있습니다.



== 스토리지 시스템 구성 수정

사용자 이름, 비밀번호, 플랫폼, 포트, 프로토콜, 시간 초과 기간, 기본 IP 주소 또는 메시징 옵션을 변경하려는 경우 SnapCenter 사용하여 스토리지 시스템 구성을 수정할 수 있습니다.

*이 작업에 관하여*

개별 사용자 또는 그룹에 대한 저장소 연결을 수정할 수 있습니다.  동일한 스토리지 시스템에 대한 권한이 있는 하나 이상의 그룹에 속해 있는 경우 스토리지 연결 이름은 스토리지 시스템에 대한 권한이 있는 각 그룹마다 한 번씩, 스토리지 연결 목록에 여러 번 표시됩니다.

*단계*

. 왼쪽 탐색 창에서 *저장 시스템*을 클릭합니다.
. 스토리지 시스템 페이지의 *유형* 드롭다운에서 다음 작업 중 하나를 수행합니다.
+
|===
| 선택하다... | 단계... 


 a| 
ONTAP SVM
 a| 
추가된 모든 스토리지 가상 머신(SVM)을 보고, 필요한 SVM 구성을 수정합니다.

.. 저장소 연결 페이지에서 적절한 SVM 이름을 클릭합니다.
.. 다음 작업 중 하나를 수행합니다.
+
*** SVM이 어떤 클러스터에도 속하지 않은 경우 스토리지 시스템 수정 페이지에서 사용자 이름, 비밀번호, EMS 및 AutoSupport 설정, 플랫폼, 프로토콜, 포트, 시간 초과, 기본 IP 등의 구성을 수정합니다.
*** SVM이 클러스터의 일부인 경우 스토리지 시스템 수정 페이지에서 *SVM을 독립적으로 관리*를 선택하고 사용자 이름, 비밀번호, EMS 및 AutoSupport 설정, 플랫폼, 프로토콜, 포트, 시간 초과, 기본 IP 등의 구성을 수정합니다.
+
SVM을 독립적으로 관리하도록 수정한 후, 클러스터를 통해 관리하기로 결정한 경우 SVM을 삭제한 후 *재검색*을 클릭해야 합니다.  SVM이 ONTAP 클러스터에 추가됩니다.

+

NOTE: SnapCenter GUI에서 스토리지 시스템 비밀번호가 업데이트되면 해당 플러그인이나 서버 호스트의 SMCore 서비스를 다시 시작해야 합니다. 업데이트된 비밀번호가 SMCore에 반영되지 않아 백업 작업이 잘못된 자격 증명 오류로 실패하게 됩니다.







 a| 
ONTAP 클러스터
 a| 
추가된 모든 클러스터를 보고 필요한 클러스터 구성을 수정합니다.

.. 저장소 연결 페이지에서 클러스터 이름을 클릭합니다.
.. 스토리지 시스템 수정 페이지에서 사용자 이름 옆에 있는 편집 아이콘을 클릭하고 사용자 이름과 비밀번호를 수정합니다.
.. EMS 및 AutoSupport 설정을 선택하거나 선택 취소합니다.
.. *추가 옵션*을 클릭하고 플랫폼, 프로토콜, 포트, 시간 초과, 기본 IP 등의 다른 구성을 수정합니다.


|===
. *제출*을 클릭하세요.




== 저장 시스템 삭제

SnapCenter 사용하면 사용하지 않는 저장 시스템을 삭제할 수 있습니다.

*이 작업에 관하여*

개별 사용자 또는 그룹의 저장소 연결을 삭제할 수 있습니다.  동일한 스토리지 시스템에 대한 권한이 있는 하나 이상의 그룹에 속해 있는 경우 스토리지 시스템 이름은 스토리지 연결 목록에 여러 번 표시되며, 스토리지 시스템에 대한 권한이 있는 각 그룹마다 한 번씩 표시됩니다.


IMPORTANT: 스토리지 시스템을 삭제하면 해당 스토리지 시스템에서 수행 중인 모든 작업이 실패합니다.

*단계*

. 왼쪽 탐색 창에서 *저장 시스템*을 클릭합니다.
. 스토리지 시스템 페이지의 *유형* 드롭다운에서 * ONTAP SVM* 또는 * ONTAP 클러스터*를 선택합니다.
. 저장소 연결 페이지에서 SVM 옆에 있는 확인란을 선택하거나 삭제하려는 클러스터를 선택합니다.
+

NOTE: 클러스터의 일부인 SVM을 선택할 수 없습니다.

. *삭제*를 클릭하세요.
. 저장소 시스템 연결 설정 삭제 페이지에서 *확인*을 클릭합니다.
+

NOTE: ONTAP GUI를 사용하여 ONTAP 클러스터에서 SVM을 삭제한 경우 SnapCenter GUI에서 *재검색*을 클릭하여 SVM 목록을 업데이트합니다.





== REST API 지원

ONTAP 에 대한 모든 ASA, AFF 또는 FAS 시스템 연결은 기본적으로 ZAPI를 통해 이루어집니다.  REST API는 특정 ONTAP 버전에 대해 활성화될 수 있습니다.

SnapCenter ZAPI를 지원하지 않는 ASA r2 시스템에서 모든 작업을 수행하기 위해 REST API를 활용합니다.

다음 구성 파일에서 구성 키를 수정할 수 있습니다.

* 저장소 연결에 대한 휴식이 활성화되어 있습니까?
+
기본값은 false입니다.

* REST를 사용하는 MinOntapVersion
+
기본값은 9.13.1입니다.



.REST API를 통한 연결 활성화
. IsRestEnabledForStorageConnection을 true로 설정합니다.
. 서버와 Windows 플러그인 호스트 모두의 SMCoreServiceHost.dll.config와 SnapDriveService.dll.config에 키를 추가합니다.
+
_<키="IsRestEnabledForStorageConnection" 값="true" />_ 추가



.REST API를 통한 연결을 ONTAP 의 특정 버전으로 제한합니다.
. 구성 매개변수 MinOntapVersionToUseREST를 true로 설정합니다.
. 서버와 Windows 플러그인 호스트 모두의 SMCoreServiceHost.dll.config와 SnapDriveService.dll.config에 키를 추가합니다.
+
_<키="MinOntapVersionToUseREST" 값="9.13.1" />_ 추가

. 서버에서 SmCore 서비스를 다시 시작하고 플러그인 머신에서 플러그인과 SnapDrive 서비스를 다시 시작합니다.

