---
permalink: admin/concept_overview_of_snapcenter_reports.html 
sidebar: sidebar 
keywords: SnapCenter reports 
summary: SnapCenter 시스템 상태와 운영 성공 여부를 모니터링하고 관리할 수 있는 다양한 보고 옵션을 제공합니다. 
---
= SnapCenter 보고 기능 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 시스템 상태와 운영 성공 여부를 모니터링하고 관리할 수 있는 다양한 보고 옵션을 제공합니다.

|===
| 보고서 유형 | 설명 


 a| 
백업 보고서
 a| 
백업 보고서는 SnapCenter 환경의 백업 추세, 백업 성공률, 지정된 시간 동안 수행된 각 백업에 대한 일부 정보에 대한 전반적인 데이터를 제공합니다.  백업이 삭제되면 보고서에는 삭제된 백업에 대한 상태 정보가 표시되지 않습니다.  백업 세부 정보 보고서는 지정된 백업 작업에 대한 자세한 정보를 제공하고 성공적으로 백업된 리소스와 실패한 리소스를 나열합니다.



 a| 
복제 보고서
 a| 
클론 보고서는 SnapCenter 환경의 클론 추세, 클론 성공률, 지정된 시간 동안 수행된 각 클론 작업에 대한 일부 정보에 대한 전반적인 데이터를 제공합니다.  복제본이 삭제되면 보고서에는 삭제된 복제본에 대한 상태 정보가 표시되지 않습니다.  복제 세부 정보 보고서는 지정된 복제, 복제 호스트 및 복제 작업 상태에 대한 세부 정보를 제공합니다.  작업이 실패하면 복제 세부 정보 보고서에 실패에 대한 정보가 표시됩니다.



 a| 
보고서 복원
 a| 
복원 보고서는 복원 작업에 대한 전반적인 정보를 제공합니다.  복원 세부 정보 보고서는 호스트 이름, 백업 이름, 작업 시작 및 기간, 개별 작업의 상태를 포함하여 지정된 복원 작업에 대한 세부 정보를 제공합니다.  작업이 실패하면 복원 세부 정보 보고서에 실패에 대한 정보가 표시됩니다.



 a| 
보호 보고서
 a| 
이러한 보고서는 모든 SnapCenter 플러그인 인스턴스에서 관리하는 리소스에 대한 보호 세부 정보를 제공합니다.  이 보고서는 모든 플러그인 인스턴스에서 관리하는 리소스에 대한 보호 세부 정보를 제공합니다.  보고서가 생성될 때 백업되지 않은 리소스, 보호되지 않은 리소스, 백업 작업이 실패한 리소스 그룹의 리소스, SnapVault 상태 등에 대한 개요, 세부 정보를 볼 수 있습니다.



 a| 
예정된 보고서
 a| 
이러한 보고서는 매일, 매주 또는 매월 등 주기적으로 실행되도록 예약되어 있습니다.  보고서는 지정된 날짜와 시간에 자동으로 생성되며, 해당 보고서는 이메일을 통해 해당 담당자에게 전송됩니다.  일정을 활성화, 비활성화, 수정 또는 삭제할 수 있습니다.  활성화된 일정은 *지금 실행* 버튼을 클릭하여 필요에 따라 실행할 수 있습니다.  관리자는 모든 일정을 실행할 수 있지만, 생성된 보고서에는 일정을 만든 사용자가 제공한 권한에 따라 데이터가 포함됩니다.

관리자 외의 다른 사용자는 자신의 권한에 따라 일정을 보거나 수정할 수 있습니다. 역할 추가 페이지에서 이 역할의 모든 구성원이 다른 구성원의 객체를 볼 수 있음 옵션이 선택된 경우, 해당 역할의 다른 구성원이 보고 수정할 수 있습니다.

|===


== 액세스 보고서

SnapCenter 대시보드를 사용하면 시스템 상태를 빠르게 파악할 수 있습니다.  대시보드에서 더 자세한 내용을 확인할 수 있습니다.  혹은 자세한 보고서에 직접 접근할 수도 있습니다.

다음 방법 중 하나를 사용하여 보고서에 액세스할 수 있습니다.

* 왼쪽 탐색 창에서 *대시보드*를 클릭한 다음 *마지막 보호 요약* 원형 차트를 클릭하면 보고서 페이지에서 자세한 내용을 볼 수 있습니다.
* 왼쪽 탐색 창에서 *보고서*를 클릭합니다.




== 보고서 필터링

필요한 정보의 세부 수준과 기간 등에 따라 다양한 매개변수에 따라 보고서 데이터를 필터링할 수 있습니다.

*단계*

. 왼쪽 탐색 창에서 *보고서*를 클릭합니다.
. 매개변수 보기가 표시되지 않으면 보고서 도구 모음에서 *매개변수 영역 전환* 아이콘을 클릭합니다.
. 보고서를 실행할 시간 범위를 지정하세요.  + 종료 날짜를 생략하면 사용 가능한 모든 정보가 검색됩니다.
. 다음 기준에 따라 보고서 정보를 필터링합니다.
+
** 리소스 그룹
** 주인
** 정책
** 의지
** 상태
** 플러그인 이름


. *적용*을 클릭하세요.




== 보고서 내보내기 또는 인쇄

SnapCenter 보고서를 내보내면 다양한 대체 형식으로 보고서를 볼 수 있습니다.  보고서를 인쇄할 수도 있습니다.

*단계*

. 왼쪽 탐색 창에서 *보고서*를 클릭합니다.
. 보고서 도구 모음에서 다음 중 하나를 수행합니다.
+
** 인쇄 가능한 보고서를 미리 보려면 *인쇄 미리보기 전환* 아이콘을 클릭하세요.
** 보고서를 다른 형식으로 내보내려면 *내보내기* 아이콘 드롭다운 목록에서 형식을 선택하세요.


. 보고서를 인쇄하려면 *인쇄* 아이콘을 클릭하세요.
. 특정 보고서 요약을 보려면 보고서의 해당 섹션으로 스크롤하세요.




== 이메일 알림을 위한 SMTP 서버 설정

데이터 보호 작업 보고서를 자신 또는 다른 사람에게 보내는 데 사용할 SMTP 서버를 지정할 수 있습니다.  구성을 확인하기 위해 테스트 이메일을 보낼 수도 있습니다.  해당 설정은 이메일 알림을 구성하는 모든 SnapCenter 작업에 전역적으로 적용됩니다.

이 옵션은 모든 데이터 보호 작업 보고서를 보내기 위한 SMTP 서버를 구성합니다.  그러나 특정 리소스에 대한 정기적인 SnapCenter 데이터 보호 작업 업데이트를 자신이나 다른 사람에게 전송하여 해당 업데이트 상태를 모니터링하려는 경우, 리소스 그룹을 생성할 때 SnapCenter 보고서를 이메일로 전송하는 옵션을 구성할 수 있습니다.

*단계*

. 왼쪽 탐색 창에서 *설정*을 클릭합니다.
. 설정 페이지에서 *전역 설정*을 클릭합니다.
. SMTP 서버를 입력하고 *저장*을 클릭합니다.
. 테스트 이메일을 보내려면 이메일을 보낼 발신자 및 수신자 이메일 주소를 입력하고, 제목을 입력한 후 *보내기*를 클릭하세요.




== 이메일로 보고서를 보내는 옵션을 구성하세요

정기적인 SnapCenter 데이터 보호 작업 업데이트를 자신이나 다른 사람에게 전송하여 해당 업데이트 상태를 모니터링하려는 경우, 리소스 그룹을 생성할 때 SnapCenter 보고서를 이메일로 전송하는 옵션을 구성할 수 있습니다.

.시작하기 전에
설정 아래의 글로벌 설정 페이지에서 SMTP 서버를 구성했어야 합니다.

*단계*

. 왼쪽 탐색 창에서 *리소스*를 클릭한 다음 목록에서 적절한 플러그인을 선택합니다.
. 보고 싶은 리소스 유형을 선택하고 *새 리소스 그룹*을 클릭하거나, 기존 리소스 그룹을 선택하고 *수정*을 클릭하여 기존 리소스 그룹에 대한 이메일 보고서를 구성합니다.
. 새 리소스 그룹 마법사의 알림 패널에서 풀다운 메뉴에서 항상 보고서를 받을지, 실패 시 보고서를 받을지, 실패 또는 경고 시 보고서를 받을지 선택합니다.
. 이메일이 발송된 주소, 이메일이 발송된 주소, 이메일 제목을 입력하세요.

