---
permalink: admin/concept_monitor_jobs_schedules_events_and_logs.html 
sidebar: sidebar 
keywords: Monitor jobs, schedules, events, logs 
summary: 모니터 페이지에서 작업 진행 상황을 모니터링하고, 예약된 작업에 대한 정보를 얻고, 이벤트와 로그를 검토할 수 있습니다. 
---
= 작업, 일정, 이벤트 및 로그를 모니터링합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
모니터 페이지에서 작업 진행 상황을 모니터링하고, 예약된 작업에 대한 정보를 얻고, 이벤트와 로그를 검토할 수 있습니다.



== 작업 모니터링

SnapCenter 백업, 복제, 복원 및 검증 작업에 대한 정보를 볼 수 있습니다.  시작 및 종료 날짜, 작업 유형, 리소스 그룹, 정책 또는 SnapCenter 플러그인을 기준으로 이 보기를 필터링할 수 있습니다. 또한, 지정된 작업에 대한 추가 세부 정보와 로그 파일을 확인할 수도 있습니다.

SnapMirror 및 SnapVault 작업과 관련된 작업도 모니터링할 수 있습니다.


NOTE: SnapCenter 관리자 또는 다른 슈퍼 유저 역할이 할당되지 않은 한, 본인이 생성하고 본인과 관련된 작업만 모니터링할 수 있습니다.

작업 모니터링과 관련된 다음 작업을 수행할 수 있습니다.

* 백업, 복제, 복원 및 검증 작업을 모니터링합니다.
* 작업 세부 정보와 보고서를 확인하세요.
* 예약된 작업을 중지합니다.




=== 예약된 백업 작업 관리

SnapCenter 6.0.1 릴리스부터 새로운 매개변수 *JobConcurrencyThreshold*가 도입되어 주어진 시간에 실행될 수 있는 예약된 작업 수에 대한 임계값을 설정합니다.  이를 통해 시스템 하드웨어 구성에 따라 실행하려는 백업 수를 제어할 수 있습니다.

*JobConcurrencyThreshold*에 할당된 기본값은 0이며 비활성화되어 있습니다.  예약된 백업 창 동안 성능 저하가 관찰되면 값을 할당하여 활성화할 수 있습니다.


NOTE: *JobConcurrencyThreshold*를 활성화하여 동시 작업을 관리하는 경우 SnapCenter 백업 순서를 제어할 수 없으며 일정에 지정된 동시에 백업이 트리거되지 않을 수 있습니다.

.단계
. _C:\Program Files\ NetApp\ SnapCenter WebApp\ SnapManager.Web.UI.dll.config_에 있는 _JobConcurrencyThreshold_ 매개변수의 값을 설정합니다.
. IIS > 애플리케이션 풀 > SnapCenter > 다시 시작을 클릭하여 SnapCenter 애플리케이션 풀을 재활용합니다.
. IIS > 사이트 > SnapCenter > 다시 시작을 클릭하여 SnapCenter 웹 서비스를 다시 시작합니다.




=== 오래된 작업 관리

오래된 작업은 SnapCenter 의 중단이나 부적절한 작업 업데이트로 인해 생성됩니다.  SnapCenter 6.0.1 릴리스부터 72시간 이상 멈춰 있는 오래된 작업을 정리하기 위한 사전 정의된 일정이 도입되었습니다.  구성 가능한 매개변수 *CleanUpStaleJobsIntervalHours*를 편집하여 일정 빈도를 변경할 수 있습니다.

*모니터* > *일정* > *SnapCenter_StaleJobCleanUp*에서 일정을 실행하여 필요에 따라 정리를 트리거할 수 있습니다.

.단계
. _C:\Program Files\ NetApp\ SnapCenter WebApp\ SnapManager.Web.UI.dll.config_에 있는 _CleanUpStaleJobsIntervalHours_ 매개변수의 값을 설정합니다.
. IIS > 애플리케이션 풀 > SnapCenter > 다시 시작을 클릭하여 SnapCenter 애플리케이션 풀을 재활용합니다.
. IIS > 사이트 > SnapCenter > 다시 시작을 클릭하여 SnapCenter 웹 서비스를 다시 시작합니다.




== 일정을 모니터링하세요

작업이 시작되는 시점, 마지막 실행 시점, 다음에 실행되는 시점을 확인하려면 현재 일정을 확인하는 것이 좋습니다.  또한 작업이 실행되는 호스트와 작업의 리소스 그룹 및 정책 정보를 확인할 수도 있습니다.

*단계*

. 왼쪽 탐색 창에서 *모니터*를 클릭합니다.
. 모니터 페이지에서 *일정*을 클릭합니다.
. 리소스 그룹과 일정 유형을 선택하세요.
. 예정된 작업 목록을 확인하세요.




== 이벤트 모니터링

사용자가 리소스 그룹을 생성하거나 시스템이 예약된 백업을 생성하는 등의 활동을 시작할 때 등 시스템에서 SnapCenter 이벤트 목록을 볼 수 있습니다.  백업이나 복원 작업과 같은 작업이 현재 진행 중인지 확인하기 위해 이벤트를 보고 싶을 수도 있습니다.

*이 작업에 관하여*

모든 채용 정보는 이벤트 페이지에 표시됩니다.  예를 들어, 백업 작업이 시작되면 "`backup start`" 이벤트가 나타납니다.  백업이 완료되면 "`백업 완료`" 이벤트가 나타납니다.

*단계*

. 왼쪽 탐색 창에서 *모니터*를 클릭합니다.
. 모니터 페이지에서 *이벤트*를 클릭합니다.
. (선택 사항) 필터 상자에서 시작 또는 종료 날짜, 이벤트 범주(예: 백업, 리소스 그룹 또는 정책), 심각도 수준을 입력하고 *적용*을 클릭합니다.  또는 검색창에 문자를 입력하세요.
. 이벤트 목록을 확인하세요.




== 로그 모니터링

SnapCenter 서버 로그, SnapCenter 호스트 에이전트 로그, 플러그인 로그를 보고 다운로드할 수 있습니다.  문제 해결에 도움이 되도록 로그를 확인하는 것이 좋습니다.

*이 작업에 관하여*

로그를 필터링하여 특정 로그 심각도 수준만 표시할 수 있습니다.

* 디버그
* 정보
* 경고하다
* 오류
* 치명적인


또한 작업 수준 로그를 얻을 수도 있습니다. 예를 들어, 백업 작업 실패 이유를 해결하는 데 도움이 되는 로그입니다.  작업 수준 로그의 경우 *모니터* > *작업* 옵션을 사용하세요.

*단계*

. 왼쪽 탐색 창에서 *모니터*를 클릭합니다.
. 작업 페이지에서 작업을 선택하고 로그 다운로드를 클릭합니다.
+
다운로드한 압축 폴더에는 작업 로그와 일반 로그가 들어 있습니다.  압축된 폴더 이름에는 선택한 작업 ID와 작업 유형이 포함되어 있습니다.

. 모니터 페이지에서 *로그*를 클릭합니다.
. 로그 유형, 호스트, 인스턴스를 선택하세요.
+
로그 유형을 *플러그인*으로 선택하면 호스트 또는 SnapCenter 플러그인을 선택할 수 있습니다. 로그 유형이 *서버*인 경우에는 이 작업을 수행할 수 없습니다.

. 특정 소스, 메시지 또는 로그 수준별로 로그를 필터링하려면 열 제목 상단에 있는 필터 아이콘을 클릭합니다.
+
모든 로그를 표시하려면 *크거나 같음*을 선택하십시오. `Debug` 수준.

. *새로고침*을 클릭하세요.
. 로그 목록을 확인하세요.
. *다운로드*를 클릭하여 로그를 다운로드하세요.
+
다운로드한 압축 폴더에는 작업 로그와 일반 로그가 들어 있습니다.  압축된 폴더 이름에는 선택한 작업 ID와 작업 유형이 포함되어 있습니다.



최적의 성능을 위해 대규모 구성에서는 PowerShell cmdlet을 사용하여 SnapCenter 의 로그 설정을 최소 수준으로 설정해야 합니다.

`Set-SmLogSettings -LogLevel All -MaxFileSize 10MB -MaxSizeRollBackups 10 -JobLogsMaxFileSize 10MB -Server`


NOTE: 장애 조치 작업이 완료된 후 상태 또는 구성 정보에 액세스하려면 cmdlet을 실행하세요. `Get-SmRepositoryConfig` .



== SnapCenter 에서 작업 및 로그 제거

SnapCenter 에서 백업, 복원, 복제 및 검증 작업과 로그를 제거할 수 있습니다.  SnapCenter 사용자가 삭제하지 않는 한 성공한 작업 로그와 실패한 작업 로그를 무기한 저장합니다.  저장 공간을 보충하려면 제거하는 것이 좋습니다.

*이 작업에 관하여*

현재 운영 중인 일자리가 없어야 합니다.  작업 ID를 제공하여 특정 작업을 제거할 수도 있고, 지정된 기간 내에 작업을 제거할 수도 있습니다.

작업을 제거하기 위해 호스트를 유지 관리 모드로 전환할 필요는 없습니다.

*단계*

. PowerShell을 실행합니다.
. 명령 프롬프트에서 다음을 입력합니다. `Open-SMConnection`
. 명령 프롬프트에서 다음을 입력합니다. `Remove-SmJobs`
. 왼쪽 탐색 창에서 *모니터*를 클릭합니다.
. 모니터 페이지에서 *작업*을 클릭합니다.
. 작업 페이지에서 작업 상태를 검토하세요.


.관련 정보
cmdlet과 함께 사용할 수 있는 매개변수와 해당 설명에 대한 정보는 _Get-Help command_name_을 실행하면 얻을 수 있습니다. 또는 다음을 참조할 수도 있습니다. https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter 소프트웨어 Cmdlet 참조 가이드"^] .
