---
permalink: admin/concept_manage_ems_data_collection.html 
sidebar: sidebar 
keywords: EMS data collection 
summary: 'PowerShell cmdlet을 사용하여 이벤트 관리 시스템(EMS) 데이터 수집을 예약하고 관리할 수 있습니다.  EMS 데이터 수집에는 SnapCenter 서버, 설치된 SnapCenter 플러그인 패키지, 호스트 및 이와 유사한 정보에 대한 세부 정보를 수집한 다음 이를 지정된 ONTAP 스토리지 가상 머신(SVM)으로 보내는 작업이 포함됩니다.' 
---
= EMS 데이터 수집 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
PowerShell cmdlet을 사용하여 이벤트 관리 시스템(EMS) 데이터 수집을 예약하고 관리할 수 있습니다.  EMS 데이터 수집에는 SnapCenter 서버, 설치된 SnapCenter 플러그인 패키지, 호스트 및 이와 유사한 정보에 대한 세부 정보를 수집한 다음 이를 지정된 ONTAP 스토리지 가상 머신(SVM)으로 전송하는 작업이 포함됩니다.


NOTE: 데이터 수집 작업이 진행 중일 때는 시스템 CPU 사용률이 높습니다.  작업이 진행되는 동안에는 데이터 크기에 관계없이 CPU 사용률이 높게 유지됩니다.



== EMS 데이터 수집 중지

EMS 데이터 수집은 기본적으로 활성화되어 있으며 설치일로부터 7일마다 실행됩니다.  PowerShell cmdlet _Disable-SmDataCollectionEMS_를 사용하면 언제든지 데이터 수집을 비활성화할 수 있습니다.

.단계
. PowerShell 명령줄에서 _Open-SmConnection_을 입력하여 SnapCenter 와 세션을 설정합니다.
. _Disable-SmDataCollectionEms_를 입력하여 EMS 데이터 수집을 비활성화합니다.




== EMS 데이터 수집 시작

EMS 데이터 수집은 기본적으로 활성화되어 있으며 설치 날짜로부터 7일마다 실행되도록 예약되어 있습니다.  비활성화한 경우 _Enable-SmDataCollectionEMS_ cmdlet을 사용하여 EMS 데이터 수집을 다시 시작할 수 있습니다.

NetApp ONTAP 이벤트 generate-autosupport-log 권한이 SVM(스토리지 가상 머신) 사용자에게 부여되었습니다.

.단계
. PowerShell 명령줄에서 _Open-SmConnection_을 입력하여 SnapCenter 와 세션을 설정합니다.
. _Enable-SmDataCollectionEMS_를 입력하여 EMS 데이터 수집을 활성화합니다.




== EMS 데이터 수집 일정 및 대상 SVM 변경

PowerShell cmdlet을 사용하여 EMS 데이터 수집 일정이나 대상 스토리지 가상 머신(SVM)을 변경할 수 있습니다.

.단계
. PowerShell 명령줄에서 SnapCenter 와 세션을 설정하려면 _Open-SmConnection_ cmdlet을 입력합니다.
. EMS 데이터 수집 대상을 변경하려면 _Set-SmDataCollectionEmsTarget_ cmdlet을 입력합니다.
. EMS 데이터 수집 일정을 변경하려면 _Set-SmDataCollectionEmsSchedule_ cmdlet을 입력합니다.




== EMS 데이터 수집 상태 모니터링

여러 PowerShell cmdlet을 사용하여 EMS 데이터 수집 상태를 모니터링할 수 있습니다.  일정, 스토리지 가상 머신(SVM) 대상 및 상태에 대한 정보를 얻을 수 있습니다.

.단계
. PowerShell 명령줄에서 _Open-SmConnection_을 입력하여 SnapCenter 와 세션을 설정합니다.
. _Get-SmDataCollectionEmsSchedule_을 입력하여 EMS 데이터 수집 일정에 대한 정보를 검색합니다.
. _Get-SmDataCollectionEmsStatus_를 입력하여 EMS 데이터 수집 상태에 대한 정보를 검색합니다.
. _Get-SmDataCollectionEmsTarget_을 입력하여 EMS 데이터 수집 대상에 대한 정보를 검색합니다.


.관련 정보
cmdlet과 함께 사용할 수 있는 매개변수와 해당 설명에 대한 정보는 _Get-Help command_name_을 실행하면 얻을 수 있습니다. 또는 다음을 참조할 수도 있습니다. https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter 소프트웨어 Cmdlet 참조 가이드"^] .
