---
permalink: admin/task_manage_resource_groups.html 
sidebar: sidebar 
keywords: Manage resource groups 
summary: 리소스 그룹에서 다양한 작업을 수행할 수 있습니다. 
---
= 리소스 그룹 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
리소스 그룹에서 다양한 작업을 수행할 수 있습니다.

리소스 그룹과 관련된 다음 작업을 수행할 수 있습니다.

* 리소스 그룹을 선택하고 *리소스 그룹 수정*을 클릭하여 리소스 그룹을 수정하면 리소스 그룹을 만들 때 제공한 정보를 편집할 수 있습니다.
+

NOTE: 리소스 그룹을 수정하는 동안 일정을 변경할 수 있습니다.  하지만 일정 유형을 변경하려면 정책을 수정해야 합니다.

+

NOTE: 리소스 그룹에서 리소스를 제거하는 경우 리소스 그룹에 현재 연결된 정책에 정의된 백업 보존 설정은 제거된 리소스에 계속 적용됩니다.

* 리소스 그룹의 백업을 만듭니다.
* 백업의 복제본을 만듭니다.
+
기존 SQL, Oracle, Windows 파일 시스템, 사용자 정의 애플리케이션, SAP HANA 데이터베이스 리소스 또는 리소스 그룹의 백업에서 복제할 수 있습니다.

* 리소스 그룹의 복제본을 만듭니다.
+
이 작업은 SQL 리소스 그룹(데이터베이스만 포함)에 대해서만 지원됩니다.  리소스 그룹 복제 일정(복제 수명 주기)을 구성할 수 있습니다.

* 리소스 그룹에서 예약된 작업이 시작되지 않도록 합니다.
* 리소스 그룹을 삭제합니다.




== 리소스 그룹에서 작업 중지 및 재개

리소스 그룹에서 예약된 작업이 시작되지 않도록 일시적으로 비활성화할 수 있습니다.  나중에 원할 때 해당 작업을 활성화할 수 있습니다.

*단계*

. 왼쪽 탐색 창에서 *리소스*를 클릭한 다음 목록에서 적절한 플러그인을 선택합니다.
. 리소스 페이지에서 *보기* 목록에서 *리소스 그룹*을 선택합니다.
. 리소스 그룹을 선택하고 *유지 관리*를 클릭합니다.
. *확인*을 클릭합니다.


유지 관리 모드로 전환한 리소스 그룹에서 작업을 재개하려면 리소스 그룹을 선택하고 *프로덕션*을 클릭하세요.



== 리소스 그룹 삭제

리소스 그룹의 리소스를 더 이상 보호할 필요가 없으면 리소스 그룹을 삭제할 수 있습니다.  SnapCenter 에서 플러그인을 제거하기 전에 리소스 그룹이 삭제되었는지 확인해야 합니다.

*이 작업에 관하여*

리소스 그룹의 모든 리소스에 대해 생성된 모든 복제본을 수동으로 삭제해야 합니다.  선택적으로 리소스 그룹과 연관된 모든 백업, 메타데이터, 정책 및 스냅샷을 강제로 삭제할 수 있습니다.

*단계*

. 왼쪽 탐색 창에서 *리소스*를 클릭한 다음 목록에서 적절한 플러그인을 선택합니다.
. 리소스 페이지에서 *보기* 목록에서 *리소스 그룹*을 선택합니다.
. 리소스 그룹을 선택한 다음 *삭제*를 클릭합니다.
. 선택 사항: 리소스 그룹과 연관된 모든 백업, 메타데이터, 정책 및 스냅샷을 제거하려면 *이 리소스 그룹과 연관된 백업 삭제 및 정책 분리* 확인란을 선택합니다.
. *확인*을 클릭합니다.

