---
permalink: admin/task_manage_rbac.html 
sidebar: sidebar 
keywords: modify RBAC, role, users, groups 
summary: SnapCenter 사용하면 역할, 사용자, 그룹을 수정할 수 있습니다. 
---
= RBAC 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 사용하면 역할, 사용자, 그룹을 수정할 수 있습니다.



== 역할 수정

SnapCenter 역할을 수정하여 사용자 또는 그룹을 제거하고 해당 역할과 관련된 권한을 변경할 수 있습니다.  전체 역할에서 사용되는 권한을 변경하거나 제거하려는 경우 역할을 수정하는 것이 특히 유용합니다.

.시작하기 전에
"SnapCenterAdmin" 역할로 로그인해야 합니다.


NOTE: SnapCenterAdmin 역할에 대한 권한은 수정하거나 제거할 수 없습니다.

*단계*

. 왼쪽 탐색 창에서 *설정*을 클릭합니다.
. 설정 페이지에서 *역할*을 클릭합니다.
. 역할 이름 필드에서 수정하려는 역할을 클릭합니다.
. *이 역할의 모든 구성원은 다른 구성원의 개체를 볼 수 있음*을 선택하면 해당 역할의 다른 구성원이 리소스 목록을 새로 고친 후 볼륨 및 호스트와 같은 리소스를 볼 수 있습니다.
+
이 역할의 멤버가 다른 멤버에게 할당된 개체를 보지 못하도록 하려면 이 옵션의 선택을 해제합니다.

+

NOTE: 이 옵션을 활성화하면 사용자가 개체나 리소스를 만든 사용자와 동일한 역할에 속해 있는 경우 개체나 리소스에 대한 액세스 권한을 사용자에게 할당할 필요가 없습니다.

. 역할 세부 정보 페이지에서 필요에 따라 권한을 변경하거나 멤버 할당을 해제합니다.
. *제출*을 클릭하세요.




== 사용자 및 그룹 수정

SnapCenter 사용자 또는 그룹을 수정하여 해당 역할과 자산을 변경할 수 있습니다.

.시작하기 전에
SnapCenter 관리자로 로그인해야 합니다.

*단계*

. 왼쪽 탐색 창에서 *설정*을 클릭합니다.
. 설정 페이지에서 *사용자 및 액세스*를 클릭합니다.
. 사용자 또는 그룹 이름 목록에서 수정하려는 사용자 또는 그룹을 클릭합니다.
. 사용자 또는 그룹 세부 정보 페이지에서 역할과 자산을 변경합니다.
. *제출*을 클릭하세요.

