---
permalink: protect-postgresql/configure-CA-certificate-for-postgresql-on-Linux-host.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: Linux 호스트에서 SnapCenter PostgreSQL 플러그인 서비스에 대한 CA 인증서 구성 
---
= Linux 호스트에서 SnapCenter PostgreSQL 플러그인 서비스에 대한 CA 인증서 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
플러그인 키스토어와 인증서의 비밀번호를 관리하고, CA 인증서를 구성하고, 플러그인 신뢰 저장소에 루트 또는 중간 인증서를 구성하고, SnapCenter 플러그인 서비스를 사용하여 플러그인 신뢰 저장소에 CA 서명 키 쌍을 구성하여 설치된 디지털 인증서를 활성화해야 합니다.

플러그인은 _/opt/ NetApp/snapcenter/scc/etc_에 위치한 'keystore.jks' 파일을 신뢰 저장소와 키 저장소로 사용합니다.



== 사용 중인 CA 서명 키 쌍의 플러그인 키 저장소 및 별칭에 대한 비밀번호 관리

.단계
. 플러그인 에이전트 속성 파일에서 플러그인 키스토어 기본 비밀번호를 검색할 수 있습니다.
+
이는 'KEYSTORE_PASS' 키에 해당하는 값입니다.

. 키스토어 비밀번호를 변경하세요:
+
 keytool -storepasswd -keystore keystore.jks
. 키 저장소에 있는 개인 키 항목의 모든 별칭에 대한 비밀번호를 키 저장소에 사용된 비밀번호와 동일하게 변경합니다.
+
 keytool -keypasswd -alias "alias_name_in_cert" -keystore keystore.jks
+
_agent.properties_ 파일의 KEYSTORE_PASS 키에 대해서도 동일하게 업데이트합니다.

. 비밀번호를 변경한 후 서비스를 다시 시작하세요.



NOTE: 플러그인 키스토어의 비밀번호와 개인 키의 모든 관련 별칭 비밀번호는 동일해야 합니다.



== 플러그인 신뢰 저장소에 루트 또는 중간 인증서 구성

플러그인 trust-store에 개인 키 없이 루트 또는 중간 인증서를 구성해야 합니다.

.단계
. 플러그인 키 저장소가 있는 폴더로 이동합니다: /opt/ NetApp/snapcenter/scc/etc.
. 'keystore.jks' 파일을 찾으세요.
. 키 저장소에 추가된 인증서를 나열합니다.
+
`keytool -list -v -keystore keystore.jks`

. 루트 또는 중간 인증서를 추가합니다.
+
 keytool -import -trustcacerts -alias myRootCA -file /root/USERTrustRSA_Root.cer -keystore keystore.jks
. 플러그인 신뢰 저장소에 루트 또는 중간 인증서를 구성한 후 서비스를 다시 시작합니다.



NOTE: 루트 CA 인증서를 추가한 다음 중간 CA 인증서를 추가해야 합니다.



== 플러그인 신뢰 저장소에 CA 서명 키 쌍 구성

CA 서명 키 쌍을 플러그인 신뢰 저장소에 구성해야 합니다.

.단계
. 플러그인 키스토어 /opt/ NetApp/snapcenter/scc/etc가 포함된 폴더로 이동합니다.
. 'keystore.jks' 파일을 찾으세요.
. 키 저장소에 추가된 인증서를 나열합니다.
+
`keytool -list -v -keystore keystore.jks`

. 개인 키와 공개 키를 모두 포함하는 CA 인증서를 추가합니다.
+
`keytool -importkeystore -srckeystore /root/snapcenter.ssl.test.netapp.com.pfx -srcstoretype pkcs12 -destkeystore keystore.jks -deststoretype JKS`

. 키스토어에 추가된 인증서를 나열합니다.
+
`keytool -list -v -keystore keystore.jks`

. 키 저장소에 추가된 새 CA 인증서에 해당하는 별칭이 키 저장소에 포함되어 있는지 확인합니다.
. CA 인증서에 추가된 개인 키 비밀번호를 키 저장소 비밀번호로 변경합니다.
+
기본 플러그인 키 저장소 비밀번호는 agent.properties 파일의 KEYSTORE_PASS 키 값입니다.

+
 keytool -keypasswd -alias "alias_name_in_CA_cert" -keystore keystore.jks
. CA 인증서의 별칭 이름이 길고 공백이나 특수 문자("*",",")가 포함된 경우 별칭 이름을 간단한 이름으로 변경합니다.
+
 keytool -changealias -alias "long_alias_name" -destalias "simple_alias" -keystore keystore.jks
. agent.properties 파일에서 CA 인증서의 별칭 이름을 구성합니다.
+
이 값을 SCC_CERTIFICATE_ALIAS 키에 대해 업데이트합니다.

. CA 서명 키 쌍을 플러그인 신뢰 저장소로 구성한 후 서비스를 다시 시작합니다.




== 플러그인에 대한 인증서 해지 목록(CRL) 구성

.이 작업에 관하여
* SnapCenter 플러그인은 미리 구성된 디렉토리에서 CRL 파일을 검색합니다.
* SnapCenter 플러그인의 CRL 파일에 대한 기본 디렉토리는 'opt/ NetApp/snapcenter/scc/etc/crl'입니다.


.단계
. agent.properties 파일에서 기본 디렉토리를 CRL_PATH 키에 맞춰 수정하고 업데이트할 수 있습니다.
+
이 디렉토리에 두 개 이상의 CRL 파일을 넣을 수 있습니다.  수신 인증서는 각 CRL에 대해 검증됩니다.


