---
permalink: protect-postgresql/set-up-credentials-for-snapcenter-plug-in-for-postgresql.html 
sidebar: sidebar 
keywords: credentials, SnapCenter Plug-in for postgresql 
summary: SnapCenter 자격 증명을 사용하여 SnapCenter 작업을 위해 사용자를 인증합니다.  SnapCenter 플러그인을 설치하기 위한 자격 증명과 클러스터 또는 Windows 파일 시스템에서 데이터 보호 작업을 수행하기 위한 추가 자격 증명을 만들어야 합니다. 
---
= PostgreSQL용 SnapCenter 플러그인에 대한 자격 증명 설정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 자격 증명을 사용하여 SnapCenter 작업을 위해 사용자를 인증합니다.  SnapCenter 플러그인을 설치하기 위한 자격 증명과 클러스터 또는 Windows 파일 시스템에서 데이터 보호 작업을 수행하기 위한 추가 자격 증명을 만들어야 합니다.

.이 작업에 관하여
* 리눅스 호스트
+
Linux 호스트에 플러그인을 설치하려면 자격 증명을 설정해야 합니다.

+
플러그인 프로세스를 설치하고 시작하려면 루트 사용자 또는 sudo 권한이 있는 루트가 아닌 사용자의 자격 증명을 설정해야 합니다.

+
|===


| *모범 사례:* 호스트를 배포하고 플러그인을 설치한 후에도 Linux에 대한 자격 증명을 생성할 수 있지만, 가장 좋은 방법은 호스트를 배포하고 플러그인을 설치하기 전에 SVM을 추가한 후에 자격 증명을 생성하는 것입니다. 
|===
* Windows 호스트
+
플러그인을 설치하기 전에 Windows 자격 증명을 설정해야 합니다.

+
원격 호스트의 관리자 권한을 포함하여 관리자 권한으로 자격 증명을 설정해야 합니다.



개별 리소스 그룹에 대한 자격 증명을 설정하고 사용자 이름에 전체 관리자 권한이 없는 경우 최소한 리소스 그룹 및 백업 권한을 사용자 이름에 할당해야 합니다.

.단계
. 왼쪽 탐색 창에서 *설정*을 클릭합니다.
. 설정 페이지에서 *자격 증명*을 클릭합니다.
. *새로 만들기*를 클릭합니다.
. 자격 증명 페이지에서 자격 증명을 구성하는 데 필요한 정보를 지정합니다.
+
|===
| 이 분야에서는... | 이렇게 하세요... 


 a| 
자격 증명 이름
 a| 
자격 증명의 이름을 입력하세요.



 a| 
사용자 이름
 a| 
인증에 사용할 사용자 이름과 비밀번호를 입력하세요.

** 도메인 관리자 또는 관리자 그룹의 모든 구성원
+
SnapCenter 플러그인을 설치할 시스템의 도메인 관리자 또는 관리자 그룹 구성원을 지정하세요. 사용자 이름 필드에 사용할 수 있는 형식은 다음과 같습니다.

+
*** _NetBIOS\사용자 이름_
*** _도메인 FQDN\사용자 이름_


** 로컬 관리자(작업 그룹에만 해당)
+
작업 그룹에 속한 시스템의 경우, SnapCenter 플러그인을 설치할 시스템에 기본 제공되는 로컬 관리자를 지정하십시오. 사용자 계정에 승격된 권한이 있거나 호스트 시스템에서 사용자 액세스 제어 기능이 비활성화된 경우, 로컬 관리자 그룹에 속하는 로컬 사용자 계정을 지정할 수 있습니다.  사용자 이름 필드의 유효한 형식은 다음과 같습니다. _UserName_

+
비밀번호에 큰따옴표(")나 백틱(`)을 사용하지 마세요.  비밀번호에 '<' 기호와 '!)' 기호를 함께 사용하면 안 됩니다.  예를 들어, lessthan<!10, lessthan10<!, backtick`12.





 a| 
비밀번호
 a| 
인증에 사용되는 비밀번호를 입력하세요.



 a| 
인증 모드
 a| 
사용할 인증 모드를 선택하세요.



 a| 
sudo 권한을 사용하세요
 a| 
루트가 아닌 사용자에 대한 자격 증명을 생성하는 경우 *sudo 권한 사용* 확인란을 선택합니다.


NOTE: Linux 사용자에게만 적용됩니다.

|===
. *확인*을 클릭합니다.


자격 증명 설정을 마친 후 사용자 및 액세스 페이지에서 사용자 또는 사용자 그룹에 자격 증명 유지 관리를 할당할 수 있습니다.
