---
permalink: install/concept_create_and_manage_smb_shares.html 
sidebar: sidebar 
keywords: SMB shares 
summary: '스토리지 가상 머신(SVM)에서 SMB3 공유를 구성하려면 SnapCenter 사용자 인터페이스나 PowerShell cmdlet을 사용할 수 있습니다.' 
---
= SMB 공유 생성 및 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 가상 머신(SVM)에서 SMB3 공유를 구성하려면 SnapCenter 사용자 인터페이스나 PowerShell cmdlet을 사용할 수 있습니다.

|===


| *모범 사례:* SnapCenter 에서 제공하는 템플릿을 활용하여 공유 구성을 자동화할 수 있으므로 cmdlet을 사용하는 것이 좋습니다. 
|===
템플릿은 볼륨 및 공유 구성에 대한 모범 사례를 캡슐화합니다.  Windows용 SnapCenter 플러그인 패키지의 설치 폴더의 Templates 폴더에서 템플릿을 찾을 수 있습니다.


TIP: 편안하다면 제공된 모델을 따라 나만의 템플릿을 만들 수 있습니다.  사용자 지정 템플릿을 만들기 전에 cmdlet 설명서의 매개변수를 검토해야 합니다.



== SMB 공유 만들기

SnapCenter 공유 페이지를 사용하여 스토리지 가상 머신(SVM)에 SMB3 공유를 만들 수 있습니다.

SnapCenter 사용하여 SMB 공유의 데이터베이스를 백업할 수 없습니다.  SMB 지원은 프로비저닝에만 국한됩니다.

*단계*

. 왼쪽 탐색 창에서 *호스트*를 클릭합니다.
. 호스트 페이지에서 *공유*를 클릭합니다.
. *스토리지 가상 머신* 드롭다운 목록에서 SVM을 선택합니다.
. *새로 만들기*를 클릭합니다.
+
새 공유 대화 상자가 열립니다.

. 새 공유 대화 상자에서 공유를 정의합니다.
+
|===
| 이 분야에서는... | 이렇게 하세요... 


 a| 
설명
 a| 
공유에 대한 설명 텍스트를 입력하세요.



 a| 
공유 이름
 a| 
공유 이름을 입력합니다(예: test_share).

공유에 입력한 이름은 볼륨 이름으로도 사용됩니다.

공유 이름:

** UTF-8 문자열이어야 합니다.
** 다음 문자를 포함할 수 없습니다: 0x00~0x1F(둘 다 포함)의 제어 문자, 0x22(큰따옴표) 및 특수 문자 `\ / [ ] : (vertical bar) < > + = ; , ?`




 a| 
경로 공유
 a| 
** 필드를 클릭하여 새 파일 시스템 경로를 입력합니다(예: /).
** 기존 파일 시스템 경로 목록에서 선택하려면 필드를 두 번 클릭합니다.


|===
. 입력한 내용이 마음에 들면 *확인*을 클릭하세요.
+
SnapCenter SVM에 SMB 공유를 생성합니다.





== SMB 공유 삭제

더 이상 필요하지 않은 SMB 공유를 삭제할 수 있습니다.

*단계*

. 왼쪽 탐색 창에서 *호스트*를 클릭합니다.
. 호스트 페이지에서 *공유*를 클릭합니다.
. 공유 페이지에서 *저장소 가상 머신* 필드를 클릭하여 사용 가능한 저장 가상 머신(SVM) 목록이 있는 드롭다운을 표시한 다음, 삭제하려는 공유의 SVM을 선택합니다.
. SVM의 공유 목록에서 삭제하려는 공유를 선택하고 *삭제*를 클릭합니다.
. 공유 삭제 대화 상자에서 *확인*을 클릭합니다.
+
SnapCenter SVM에서 SMB 공유를 삭제합니다.


