---
permalink: install/concept_configure_snapcenter_servers_for_high_availabiity_using_f5.html 
sidebar: sidebar 
keywords: F5, netwoek load balancer, NLB, high availability, elastic load balancing, ELB, Azure load balancing, Amazon Web Services, AWS 
summary: F5, 네트워크 부하 분산 또는 Amazon Web Services를 사용하여 SnapCenter 에서 고가용성을 구성합니다. 
---
= 고가용성을 위한 SnapCenter 서버 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Windows 또는 Linux에서 실행되는 SnapCenter 에서 고가용성(HA)을 지원하려면 F5 로드 밸런서를 설치할 수 있습니다.  F5를 사용하면 SnapCenter 서버가 동일한 위치에 있는 최대 두 개의 호스트에서 액티브-패시브 구성을 지원할 수 있습니다.  SnapCenter 에서 F5 로드 밸런서를 사용하려면 SnapCenter 서버를 구성하고 F5 로드 밸런서를 구성해야 합니다.

SnapCenter 고가용성을 설정하기 위해 네트워크 부하 분산(NLB)을 구성할 수도 있습니다.  고가용성을 위해서는 SnapCenter 설치 외부에서 NLB를 수동으로 구성해야 합니다.

클라우드 환경의 경우 Amazon Web Services(AWS) Elastic Load Balancing(ELB) 및 Azure Load Balancer를 사용하여 고가용성을 구성할 수 있습니다.

[role="tabbed-block"]
====
.F5를 사용하여 고가용성 구성
--
F5 로드 밸런서를 사용하여 고가용성을 위해 SnapCenter 서버를 구성하는 방법에 대한 지침은 다음을 참조하세요. https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_configure_SnapCenter_Servers_for_high_availability_using_F5_Load_Balancer["F5 로드 밸런서를 사용하여 고가용성을 위해 SnapCenter 서버를 구성하는 방법"^] .

F5 클러스터를 추가하고 제거하기 위해 다음 cmdlet을 사용하려면 SnapCenter 서버에서 로컬 관리자 그룹의 구성원이어야 합니다(SnapCenterAdmin 역할이 할당되어야 함).

* Add-SmServerCluster
* Add-SmServer
* Remove-SmServerCluster
+
자세한 내용은 다음을 참조하세요.  https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter 소프트웨어 Cmdlet 참조 가이드"^] .



추가 정보

* 고가용성을 위해 SnapCenter 설치하고 구성한 후 SnapCenter 바탕 화면 바로 가기를 편집하여 F5 클러스터 IP를 가리키도록 합니다.
* SnapCenter 서버 간에 장애 조치가 발생하고 기존 SnapCenter 세션이 있는 경우 브라우저를 닫고 SnapCenter 에 다시 로그인해야 합니다.
* 로드 밸런서 설정(NLB 또는 F5)에서 NLB 또는 F5 호스트에 의해 부분적으로 해결된 호스트를 추가하고 SnapCenter 호스트가 이 호스트에 연결할 수 없는 경우 SnapCenter 호스트 페이지는 호스트의 다운 상태와 실행 상태 사이를 자주 전환합니다.  이 문제를 해결하려면 두 SnapCenter 호스트가 모두 NLB 또는 F5 호스트에서 호스트를 확인할 수 있는지 확인해야 합니다.
* MFA 설정을 위한 SnapCenter 명령은 모든 호스트에서 실행해야 합니다.  신뢰 당사자 구성은 F5 클러스터 세부 정보를 사용하여 AD FS(Active Directory Federation Services) 서버에서 수행해야 합니다.  MFA가 활성화되면 호스트 수준 SnapCenter UI 액세스가 차단됩니다.
* 장애 조치 중에 감사 로그 설정은 두 번째 호스트에 반영되지 않습니다.  따라서 F5 수동 호스트가 활성화되면 감사 로그 설정을 수동으로 반복해야 합니다.


--
.NLB(네트워크 부하 분산)를 사용하여 고가용성 구성
--
SnapCenter 고가용성을 설정하기 위해 네트워크 부하 분산(NLB)을 구성할 수 있습니다.  고가용성을 위해서는 SnapCenter 설치 외부에서 NLB를 수동으로 구성해야 합니다.

SnapCenter 사용하여 NLB(네트워크 부하 분산)를 구성하는 방법에 대한 정보는 다음을 참조하세요. https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_configure_NLB_and_ARR_with_SnapCenter["SnapCenter 로 NLB를 구성하는 방법"^] .

--
.AWS Elastic Load Balancing(ELB)을 사용하여 고가용성 구성
--
Amazon Web Services(AWS)에서 두 개의 SnapCenter 서버를 별도의 가용성 영역(AZ)에 설정하고 자동 장애 조치를 구성하여 고가용성 SnapCenter 환경을 구성할 수 있습니다.  아키텍처에는 가상 사설 IP 주소, 라우팅 테이블, 활성 및 대기 MySQL 데이터베이스 간의 동기화가 포함됩니다.

.단계
. AWS에서 가상 사설 오버레이 IP를 구성합니다. 자세한 내용은 다음을 참조하세요. https://docs.aws.amazon.com/vpc/latest/userguide/replace-local-route-target.html["가상 사설 오버레이 IP 구성"^] .
. Windows 호스트 준비
+
.. IPv6보다 IPv4를 우선시하도록 강제합니다.
+
*** 위치: HKLM\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters
*** 키: DisabledComponents
*** 유형: REG_DWORD
*** 값: 0x20


.. 완전히 정규화된 도메인 이름이 DNS 또는 로컬 호스트 구성을 통해 IPv4 주소로 확인될 수 있는지 확인하세요.
.. 시스템 프록시가 구성되어 있지 않은지 확인하세요.
.. Active Directory가 없는 설정을 사용하고 서버가 하나의 도메인에 속하지 않는 경우 두 Windows Server에서 관리자 암호가 동일한지 확인하세요.
.. 두 Windows 서버에 가상 IP를 추가합니다.


. SnapCenter 클러스터를 생성합니다.
+
.. PowerShell을 시작하고 SnapCenter 에 연결합니다.
`Open-SmConnection`
.. 클러스터를 생성합니다.
`Add-SmServerCluster -ClusterName <cluster_name> -ClusterIP <cluster_ip> -PrimarySCServerIP <primary_ip> -Verbose -Credential administrator`
.. 보조 서버를 추가합니다.
`Add-SmServer -ServerName <server_name> -ServerIP <server_ip> -CleanUpSecondaryServer -Verbose -Credential administrator`
.. 고가용성에 대한 세부 정보를 얻으세요.
`Get-SmServerConfig`


. AWS CloudWatch에서 모니터링하여 가상 사설 IP 엔드포인트를 사용할 수 없게 될 경우 라우팅 테이블을 조정하는 Lamda 함수를 생성합니다. 자세한 내용은 다음을 참조하세요. https://docs.aws.amazon.com/lambda/latest/dg/getting-started.html#getting-started-create-function["람다 함수 만들기"^] .
. CloudWatch에서 모니터를 생성하여 SnapCenter 엔드포인트의 가용성을 모니터링합니다.  엔드포인트에 도달할 수 없는 경우 람다 함수를 트리거하도록 알람이 구성됩니다.  Lambda 함수는 라우팅 테이블을 조정하여 트래픽을 활성 SnapCenter 서버로 리디렉션합니다. 자세한 내용은 다음을 참조하세요. https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Canaries_Create.html["합성 카나리아 만들기"^] .
. CloudWatch 모니터링의 대안으로 단계 함수를 사용하여 워크플로를 구현하면 장애 조치 시간을 단축할 수 있습니다.  워크플로에는 SnapCenter URL을 테스트하는 Lambda 프로브 함수, 실패 횟수를 저장하는 DynamoDB 테이블, Step 함수 자체가 포함됩니다.
+
.. SnapCenter URL을 조사하려면 람다 함수를 사용합니다. 자세한 내용은 다음을 참조하세요. https://docs.aws.amazon.com/lambda/latest/dg/getting-started.html["람다 함수 생성"^] .
.. 두 Step Function 반복 사이의 실패 횟수를 저장하기 위해 DynamoDB 테이블을 만듭니다. 자세한 내용은 다음을 참조하세요. https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStartedDynamoDB.html["DynamoDB 테이블 시작하기"^] .
.. 계단 함수를 만듭니다. 자세한 내용은 다음을 참조하세요. https://docs.aws.amazon.com/step-functions/["Step Function 문서"^] .
.. 단일 단계를 테스트합니다.
.. 전체 기능을 테스트합니다.
.. IAM 역할을 생성하고 Lambda 함수를 실행할 수 있는 권한을 조정합니다.
.. Step Function을 트리거하기 위한 일정을 만듭니다. 자세한 내용은 다음을 참조하세요. https://docs.aws.amazon.com/step-functions/latest/dg/using-eventbridge-scheduler.html["Amazon EventBridge Scheduler를 사용하여 Step Functions 시작하기"^] .




--
.Azure 부하 분산 장치를 사용하여 고가용성 구성
--
Azure 부하 분산 장치를 사용하여 고가용성 SnapCenter 환경을 구성할 수 있습니다.

.단계
. Azure Portal을 사용하여 확장 집합에서 가상 머신을 만듭니다.  Azure 가상 머신 확장 집합을 사용하면 부하 분산된 가상 머신 그룹을 만들고 관리할 수 있습니다.  가상 머신 인스턴스의 수는 수요나 정의된 일정에 따라 자동으로 늘어나거나 줄어들 수 있습니다. 자세한 내용은 다음을 참조하세요. https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/flexible-virtual-machine-scale-sets-portal["Azure Portal을 사용하여 확장 집합에서 가상 머신 만들기"^] .
. 가상 머신을 구성한 후 VM 세트의 각 가상 머신에 로그인하고 두 노드 모두에 SnapCenter Server를 설치합니다.
. 호스트 1에 클러스터를 생성합니다.
`Add-SmServerCluster -ClusterName <cluster_name> -ClusterIP <specify the load balancer front end virtual ip> -PrimarySCServerIP <ip address> -Verbose -Credential <credentials>`
. 보조 서버를 추가합니다.
`Add-SmServer -ServerName <name of node2> -ServerIP <ip address of node2> -Verbose -Credential <credentials>`
. 고가용성 세부 정보를 얻으세요.
`Get-SmServerConfig`
. 필요한 경우 보조 호스트를 다시 빌드합니다.
`Set-SmRepositoryConfig -RebuildSlave -Verbose`
. 두 번째 호스트로 장애 조치합니다.
`Set-SmRepositoryConfig ActiveMaster <name of node2> -Verbose`


--
== 고가용성을 위해 NLB에서 F5로 전환

SnapCenter HA 구성을 네트워크 부하 분산(NLB)에서 F5 부하 분산 장치를 사용하도록 변경할 수 있습니다.

*단계*

. F5를 사용하여 고가용성을 위해 SnapCenter 서버를 구성합니다. https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_configure_SnapCenter_Servers_for_high_availability_using_F5_Load_Balancer["자세히 알아보기"^] .
. SnapCenter 서버 호스트에서 PowerShell을 실행합니다.
. Open-SmConnection cmdlet을 사용하여 세션을 시작한 다음 자격 증명을 입력합니다.
. Update-SmServerCluster cmdlet을 사용하여 SnapCenter 서버가 F5 클러스터 IP 주소를 가리키도록 업데이트합니다.
+
cmdlet과 함께 사용할 수 있는 매개변수와 해당 설명에 대한 정보는 _Get-Help command_name_을 실행하면 얻을 수 있습니다. 또는 다음을 참조할 수도 있습니다. https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter 소프트웨어 Cmdlet 참조 가이드"^] .



====