---
permalink: install/configure_two_way_ssl_linux.html 
sidebar: sidebar 
keywords: security,two-way ssl,configure two-way ssl, linux host 
summary: Linux 호스트의 SnapCenter Server와 플러그인 간의 상호 통신을 보호하려면 양방향 SSL 통신을 구성해야 합니다. 
---
= Linux 호스트에서 양방향 SSL 통신 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Linux 호스트의 SnapCenter Server와 플러그인 간의 상호 통신을 보호하려면 양방향 SSL 통신을 구성해야 합니다.

.시작하기 전에
* Linux 호스트에 대한 CA 인증서를 구성했어야 합니다.
* 모든 플러그인 호스트와 SnapCenter 서버에서 양방향 SSL 통신을 활성화해야 합니다.


.단계
. *certificate.pem*을 _/etc/pki/ca-trust/source/anchors/_에 복사합니다.
. Linux 호스트의 신뢰 목록에 인증서를 추가합니다.
+
** `cp root-ca.pem /etc/pki/ca-trust/source/anchors/`
** `cp certificate.pem /etc/pki/ca-trust/source/anchors/`
** `update-ca-trust extract`


. 인증서가 신뢰 목록에 추가되었는지 확인하세요.
`trust list | grep "<CN of your certificate>"`
. SnapCenter *nginx* 파일에서 *ssl_certificate* 및 *ssl_certificate_key*를 업데이트하고 다시 시작합니다.
+
** `vim /etc/nginx/conf.d/snapcenter.conf`
** `systemctl restart nginx`


. SnapCenter 서버 GUI 링크를 새로 고칩니다.
. * SnapManager.Web.UI.dll.config*(_ /<설치 경로>/ NetApp/snapcenter/SnapManagerWeb_에 위치) 및 *SMCoreServiceHost.dll.config*(_ /<설치 경로>/ NetApp/snapcenter/SMCore_에 위치)에서 다음 키의 값을 업데이트합니다.
+
** <key="SERVICE_CERTIFICATE_PATH" value="<인증서.pfx 경로>" />를 추가합니다.
** <키 추가="서비스 인증서 비밀번호" 값="<비밀번호>"/>


. 다음 서비스를 다시 시작합니다.
+
** `systemctl restart smcore.service`
** `systemctl restart snapmanagerweb.service`


. 인증서가 SnapManager 웹 포트에 연결되어 있는지 확인하세요.
`openssl s_client -connect localhost:8146 -brief`
. 인증서가 smcore 포트에 연결되어 있는지 확인하세요.
`openssl s_client -connect localhost:8145 -brief`
. SPL 키스토어와 별칭에 대한 비밀번호를 관리합니다.
+
.. SPL 속성 파일의 *SPL_KEYSTORE_PASS* 키에 할당된 SPL 키 저장소 기본 비밀번호를 검색합니다.
.. 키스토어 비밀번호를 변경합니다.
`keytool -storepasswd -keystore keystore.jks`
.. 개인 키 항목의 모든 별칭에 대한 비밀번호를 변경합니다.
`keytool -keypasswd -alias "<alias_name>" -keystore keystore.jks`
.. _spl.properties_의 *SPL_KEYSTORE_PASS* 키에 대해 동일한 비밀번호를 업데이트합니다.
.. 서비스를 다시 시작합니다.


. 플러그인 Linux 호스트에서 SPL 플러그인의 키 저장소에 루트 및 중간 인증서를 추가합니다.
+
** `keytool -import -trustcacerts -alias <any preferred alias name> -file <path of root-ca.pem> -keystore <path of keystore.jks mentioned in spl.properties file>`
** `keytool -importkeystore -srckeystore <path of certificate.pfx> -srcstoretype pkcs12 -destkeystore <path of keystore.jks mentioned in spl.properties file> -deststoretype JKS`
+
... keystore.jks의 항목을 확인하세요.
`keytool -list -v -keystore <path to keystore.jks>`
... 필요한 경우 별칭의 이름을 바꾸세요.
`keytool -changealias -alias "old-alias" -destalias "new-alias" -keypass keypass -keystore </path/to/keystore> -storepass storepas`




. _spl.properties_ 파일에 있는 *SPL_CERTIFICATE_ALIAS* 값을 _keystore.jks_에 저장된 *certificate.pfx* 별칭으로 업데이트하고 SPL 서비스를 다시 시작합니다. `systemctl restart spl`
. 인증서가 smcore 포트에 연결되어 있는지 확인하세요.
`openssl s_client -connect localhost:8145 -brief`

