---
permalink: install/configure_mfa_using_powershell_sccli_restapi.html 
sidebar: sidebar 
keywords: mfa, authentication, multifactor authentication 
summary: Rest API, PowerShell 및 SCCLI 인터페이스를 사용하여 MFA를 구성할 수 있습니다. 
---
= PowerShell, SCCLI 및 REST API를 사용하여 SnapCenter 서버에서 MFA 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
PowerShell, SCCLI 및 REST API를 사용하여 SnapCenter 서버에서 MFA를 구성할 수 있습니다.



== SnapCenter MFA CLI 인증

PowerShell과 SCCLI에서 기존 cmdlet(Open-SmConnection)은 사용자를 인증하기 위해 전달자 토큰을 사용하기 위해 "AccessToken"이라는 필드가 하나 더 확장되었습니다.

`Open-SmConnection -Credential <PSCredential> [-SMSbaseUrl <String>] [-Port <String>] [-RoleName <String>] [ -AccessToken <string>]`

위의 cmdlet을 실행한 후 해당 사용자가 추가 SnapCenter cmdlet을 실행할 수 있는 세션이 생성됩니다.



== SnapCenter MFA REST API 인증

REST API 클라이언트(Postman이나 Swagger 등)에서 _Authorization=Bearer <액세스 토큰>_ 형식의 베어러 토큰을 사용하고 헤더에 사용자 RoleName을 언급하면 ​​SnapCenter 에서 성공적인 응답을 받을 수 있습니다.



== MFA Rest API 워크플로

MFA가 AD FS로 구성된 경우 Rest API를 통해 SnapCenter 애플리케이션에 액세스하려면 액세스(베어러) 토큰을 사용하여 인증해야 합니다.

*이 작업에 관하여*

* Postman, Swagger UI 또는 FireCamp와 같은 REST 클라이언트를 사용할 수 있습니다.
* 액세스 토큰을 받아서 이후 요청(SnapCenter Rest API)을 인증하여 모든 작업을 수행합니다.


*단계*

*AD FS MFA를 통해 인증하려면*

. 액세스 토큰을 가져오기 위해 AD FS 엔드포인트를 호출하도록 REST 클라이언트를 구성합니다.
+
애플리케이션에 대한 액세스 토큰을 받기 위해 버튼을 누르면 AD FS SSO 페이지로 리디렉션되며, 이 페이지에서 AD 자격 증명을 제공하고 MFA로 인증해야 합니다. 1.  AD FS SSO 페이지에서 사용자 이름 텍스트 상자에 사용자 이름이나 이메일을 입력합니다.

+
+ 사용자 이름은 user@domain 또는 domain\user 형식이어야 합니다.

. 비밀번호 텍스트 상자에 비밀번호를 입력하세요.
. *로그인*을 클릭하세요.
. *로그인 옵션* 섹션에서 인증 옵션을 선택하고 인증합니다(구성에 따라 다름).
+
** 푸시: 휴대폰으로 전송되는 푸시 알림을 승인합니다.
** QR 코드: AUTH Point 모바일 앱을 사용하여 QR 코드를 스캔한 다음 앱에 표시된 확인 코드를 입력하세요.
** 일회용 비밀번호: 토큰의 일회용 비밀번호를 입력하세요.


. 인증에 성공하면 액세스 토큰, ID 토큰, 새로 고침 토큰이 포함된 팝업이 열립니다.
+
액세스 토큰을 복사하여 SnapCenter Rest API에서 사용하여 작업을 수행합니다.

. Rest API에서는 헤더 섹션에 액세스 토큰과 역할 이름을 전달해야 합니다.
. SnapCenter AD FS에서 이 액세스 토큰의 유효성을 검사합니다.
+
유효한 토큰이면 SnapCenter 이를 디코딩하여 사용자 이름을 가져옵니다.

. SnapCenter 사용자 이름과 역할 이름을 사용하여 API 실행을 위해 사용자를 인증합니다.
+
인증에 성공하면 SnapCenter 결과를 반환하고, 그렇지 않으면 오류 메시지가 표시됩니다.





== Rest API, CLI 및 GUI에 대한 SnapCenter MFA 기능 활성화 또는 비활성화

*GUI*

*단계*

. SnapCenter 관리자로 SnapCenter 서버에 로그인합니다.
. *설정* > *전역 설정* > *다중 인증(MFA) 설정*을 클릭합니다.
. MFA 로그인을 활성화하거나 비활성화하려면 인터페이스(GUI/RST API/CLI)를 선택하세요.


*PowerShell 인터페이스*

*단계*

. GUI, Rest API, PowerShell 및 SCCLI에 대해 MFA를 활성화하려면 PowerShell 또는 CLI 명령을 실행합니다.
+
`Set-SmMultiFactorAuthentication -IsGuiMFAEnabled -IsRestApiMFAEnabled`
`-IsCliMFAEnabled -Path`

+
경로 매개 변수는 AD FS MFA 메타데이터 xml 파일의 위치를 지정합니다.

+
지정된 AD FS 메타데이터 파일 경로로 구성된 SnapCenter GUI, Rest API, PowerShell 및 SCCLI에 대해 MFA를 활성화합니다.

. 다음을 사용하여 MFA 구성 상태 및 설정을 확인하세요. `Get-SmMultiFactorAuthentication` cmdlet.


*SCCLI 인터페이스*

*단계*

. `# sccli Set-SmMultiFactorAuthentication -IsGuiMFAEnabled true -IsRESTAPIMFAEnabled true -IsCliMFAEnabled true  -Path "C:\ADFS_metadata\abc.xml"`
. `# sccli Get-SmMultiFactorAuthentication`


*REST API*

. GUI, REST API, PowerShell 및 SCCLI에 대한 MFA를 활성화하기 위해 다음 게시물 API를 실행합니다.
+
|===


| 매개변수 | 가치 


 a| 
요청된 URL
 a| 
/api/4.9/설정/다중 인증



 a| 
HTTP 메서드
 a| 
우편



 a| 
요청 본문
 a| 
{ "IsGuiMFAEnabled": 거짓, "IsRestApiMFAEnabled": 참, "IsCliMFAEnabled": 거짓, "ADFSConfigFilePath": "C:\\ADFS_metadata\\abc.xml" }



 a| 
대응 기관
 a| 
{ "MFAConfiguration": { "IsGuiMFAEnabled": 거짓, "ADFSConfigFilePath": "C:\\ADFS_metadata\\abc.xml", "SCConfigFilePath": 널, "IsRestApiMFAEnabled": 참, "IsCliMFAEnabled": 거짓, "ADFSHostName": "win-adfs-sc49.winscedom2.com" } }

|===
. 다음 API를 사용하여 MFA 구성 상태와 설정을 확인하세요.
+
|===


| 매개변수 | 가치 


 a| 
요청된 URL
 a| 
/api/4.9/설정/다중 인증



 a| 
HTTP 메서드
 a| 
얻다



 a| 
대응 기관
 a| 
{ "MFAConfiguration": { "IsGuiMFAEnabled": 거짓, "ADFSConfigFilePath": "C:\\ADFS_metadata\\abc.xml", "SCConfigFilePath": 널, "IsRestApiMFAEnabled": 참, "IsCliMFAEnabled": 거짓, "ADFSHostName": "win-adfs-sc49.winscedom2.com" } }

|===

