---
permalink: install/install_snapcenter_server_linux.html 
sidebar: sidebar 
keywords: install, snapcenter software, install, linux host 
summary: Linux 호스트에 SnapCenter 서버를 설치할 수 있습니다. 
---
= Linux 호스트에 SnapCenter 서버 설치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter Server 설치 프로그램 실행 파일을 실행하여 SnapCenter Server를 설치할 수 있습니다.

.시작하기 전에
* SnapCenter 설치할 권한이 없는 루트가 아닌 사용자를 사용하여 SnapCenter 서버를 설치하려는 경우 NetApp 지원 사이트에서 sudoers 체크섬 파일을 받으세요.  Linux 버전에 따라 적절한 체크섬 파일을 사용해야 합니다.
* SUSE Linux에서 sudo 패키지를 사용할 수 없는 경우 인증 실패를 방지하기 위해 sudo 패키지를 설치하세요.
* SUSE Linux의 경우 설치 실패를 방지하려면 호스트 이름을 구성하세요.
* 명령을 실행하여 보안 Linux 상태를 확인하세요. `sestatus` .  _SELinux 상태_가 "활성화"이고 _현재 모드_가 "강제"인 경우 다음을 수행합니다.
+
** 다음 명령을 실행합니다: `sudo semanage port -a -t http_port_t -p tcp <WEBAPP_EXTERNAL_PORT_>`
+
_WEBAPP_EXTERNAL_PORT_의 기본값은 8146입니다.

** 방화벽이 포트를 차단하는 경우 다음을 실행하세요. `sudo firewall-cmd --add-port <WEBAPP_EXTERNAL_PORT_>/tcp`
+
_WEBAPP_EXTERNAL_PORT_의 기본값은 8146입니다.

** 읽기 및 쓰기 권한이 있는 디렉토리에서 다음 명령을 실행하세요.
+
*** `sudo ausearch -c 'nginx' --raw | audit2allow -M my-nginx`
+
명령이 "할 일 없음"을 반환하는 경우 SnapCenter Server를 설치한 후 명령을 다시 실행합니다.

*** 명령이 _my-nginx.pp_를 생성하는 경우, 명령을 실행하여 정책 패키지를 활성화합니다. `sudo semodule -i my-nginx.pp`


** MySQL PID 디렉토리에 사용되는 경로는 _/var/opt/mysqld_입니다.  MySQL 설치에 대한 권한을 설정하려면 다음 명령을 실행하세요.
+
*** `mkdir /var/opt/mysqld`
*** `sudo semanage fcontext -a -t mysqld_var_run_t "/var/opt/mysqld(/.*)?"`
*** `sudo restorecon -Rv /var/opt/mysqld`


** MySQL 데이터 디렉토리에 사용된 경로는 _/INSTALL_DIR/ NetApp/snapcenter/SnapManagerWeb/Repository/MySQL/_입니다.  MySQL 데이터 디렉토리에 대한 권한을 설정하려면 다음 명령을 실행하세요.
+
*** `mkdir -p /INSTALL_DIR/NetApp/snapcenter/SnapManagerWeb/Repository/MySQL`
*** `sudo semanage fcontext -a -t mysqld_db_t "/INSTALL_DIR/NetApp/snapcenter/SnapManagerWeb/Repository/MySQL(/.*)?"`
*** `sudo restorecon -Rv /INSTALL_DIR/NetApp/snapcenter/SnapManagerWeb/Repository/MySQL`






.이 작업에 관하여
* SnapCenter Server가 Linux 호스트에 설치되면 MySQL, RabbitMq, Errlang과 같은 타사 서비스가 설치됩니다.  이러한 프로그램을 제거해서는 안 됩니다.
* Linux 호스트에 설치된 SnapCenter 서버는 다음을 지원하지 않습니다.
+
** 고가용성
** Windows 플러그인
** Active Directory(로컬 사용자만 지원, 루트 및 자격 증명이 있는 비 루트 사용자 모두)
** SnapCenter 에 로그인하기 위한 키 기반 인증


* .NET 런타임을 설치하는 동안 _libicu_ 라이브러리의 종속성을 해결하지 못하는 경우 다음 명령을 실행하여 _libicu_를 설치하세요. `yum install -y libicu`
* _Perl_을 사용할 수 없어 SnapCenter Server 설치에 실패하는 경우, 다음 명령을 실행하여 _Perl_을 설치하세요. `yum install -y perl`


.단계
. 다음을 다운로드하세요 https://mysupport.netapp.com/site/products/all/details/snapcenter/downloads-tab["NetApp 지원 사이트"^] _/홈 디렉토리_로.
+
** SnapCenter 서버 설치 패키지 - *snapcenter-linux-server-(el8/el9/sles15).bin*
** 공개 키 파일 - *snapcenter_public_key.pub*
** 해당 서명 파일 - *snapcenter-linux-server-(el8/el9/sles15).bin.sig*


. 서명 파일을 검증합니다.
`$openssl dgst -sha256 -verify snapcenter_public_key.pub -signature <path to signature file> <path to bin file>`
. 루트가 아닌 사용자로 설치하는 경우, .bin 설치 프로그램과 함께 제공되는 *snapcenter_server_checksum_(el8/el9/sles15).txt*에 지정된 visudo 콘텐츠를 추가합니다.
. .bin 설치 프로그램에 실행 권한을 할당합니다.
`chmod +x snapcenter-linux-server-(el8/el9/sles15).bin`
. SnapCenter Server를 설치하려면 다음 작업 중 하나를 수행하세요.
+
|===
| 공연을 하고 싶다면... | 이렇게 하세요... 


 a| 
대화형 설치
 a| 
`./snapcenter-linux-server-(el8/el9/sles15).bin`

다음 세부 정보를 입력하라는 메시지가 표시됩니다.

** Linux 호스트 외부에서 SnapCenter 서버에 액세스하는 데 사용되는 웹앱 외부 포트입니다.  기본값은 8146입니다.
** SnapCenter Server를 설치할 SnapCenter Server 사용자입니다.
** 패키지가 설치될 설치 디렉토리입니다.




 a| 
비대화형 설치
 a| 
`sudo ./snapcenter-linux-server-(el8/el9/sles15).bin -i silent -DWEBAPP_EXTERNAL_PORT=<port> -DWEBAPP_INTERNAL_PORT=<port> -DSMCORE_PORT=<port> -DSCHEDULER_PORT=<port>  -DSNAPCENTER_SERVER_USER=<user> -DUSER_INSTALL_DIR=<dir> -DINSTALL_LOG_NAME=<filename>`

예: sudo ./snapcenter_linux_server.bin -i silent -DWEBAPP_EXTERNAL_PORT=8146 -DSNAPCENTER_SERVER_USER=root -DUSER_INSTALL_DIR=/opt -DINSTALL_LOG_NAME=InstallerLog.log

로그는 _/var/opt/snapcenter/logs_에 저장됩니다.

SnapCenter Server를 설치하기 위해 전달해야 하는 매개변수:

** DWEBAPP_EXTERNAL_PORT: Linux 호스트 외부에서 SnapCenter 서버에 액세스하는 데 사용되는 웹앱 외부 포트입니다.  기본값은 8146입니다.
** DWEBAPP_INTERNAL_PORT: Linux 호스트 내에서 SnapCenter 서버에 액세스하는 데 사용되는 웹앱 내부 포트입니다.  기본값은 8147입니다.
** DSMCORE_PORT: smcore 서비스가 실행되는 SMCORE 포트입니다.  기본값은 8145입니다.
** DSCHEDULER_PORT: 스케줄러 서비스가 실행되는 스케줄러 포트입니다.  기본값은 8154입니다.
** DSNAPCENTER_SERVER_USER: SnapCenter Server를 설치할 SnapCenter Server 사용자입니다.  _DSNAPCENTER_SERVER_USER_의 경우 기본값은 설치 프로그램을 실행하는 사용자입니다.
** DUSER_INSTALL_DIR: 패키지가 설치될 설치 디렉토리입니다.  _DUSER_INSTALL_DIR_의 경우 기본 설치 디렉토리는 _/opt_입니다.
** DINSTALL_LOG_NAME: 설치 로그가 저장될 로그 파일 이름입니다.  이것은 선택적인 매개변수이며, 지정하면 콘솔에 로그가 표시되지 않습니다. 이 매개변수를 지정하지 않으면 로그가 콘솔에 표시되고 기본 로그 파일에도 저장됩니다.
** DSELINUX: _SELinux 상태_가 "활성화됨"이고, _현재 모드_가 "강제 실행"이며, 시작하기 전 섹션에 언급된 명령을 실행한 경우 이 매개변수를 지정하고 값을 1로 할당해야 합니다.  기본값은 0입니다.
** DUPGRADE: 기본값은 0입니다.  SnapCenter 서버를 업그레이드하려면 이 매개변수와 값을 0이 아닌 정수로 지정하세요.


|===


.다음은 무엇인가요?
* _SELinux 상태_가 "활성화"이고 _현재 모드_가 "강제"인 경우 *nginx* 서비스가 시작되지 않습니다.  다음 명령을 실행해야 합니다.
+
.. 홈 디렉토리로 이동합니다.
.. 다음 명령을 실행합니다: `journalctl -x|grep nginx` .
.. Webapp 내부 포트(8147)에서 수신이 허용되지 않으면 다음 명령을 실행하세요.
+
*** `ausearch -c 'nginx' --raw | audit2allow -M my-nginx`
*** `semodule -i my-nginx.pp`


.. 달리다 `setsebool -P httpd_can_network_connect on`






== 설치 중 Linux 호스트에서 활성화된 기능

SnapCenter 서버는 호스트 시스템의 문제 해결 및 유지 관리에 도움이 되는 아래 소프트웨어 패키지를 설치합니다.

* 래빗엠큐
* 얼랑

