---
permalink: install/task_reclaim_space_on_the_storage_system.html 
sidebar: sidebar 
keywords: space, storage system, reclaim 
summary: NTFS는 파일이 삭제되거나 수정될 때 LUN의 사용 가능한 공간을 추적하지만, 스토리지 시스템에 새로운 정보를 보고하지 않습니다.  Windows 호스트용 플러그인에서 공간 회수 PowerShell cmdlet을 실행하면 새로 해제된 블록이 저장소에서 사용 가능한 것으로 표시됩니다. 
---
= 저장 시스템에서 공간 확보
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NTFS는 파일이 삭제되거나 수정될 때 LUN의 사용 가능한 공간을 추적하지만, 스토리지 시스템에 새로운 정보를 보고하지 않습니다.  Windows 호스트용 플러그인에서 공간 회수 PowerShell cmdlet을 실행하면 새로 해제된 블록이 저장소에서 사용 가능한 것으로 표시됩니다.

원격 플러그인 호스트에서 cmdlet을 실행하는 경우 SnapCenterOpen-SMConnection cmdlet을 실행하여 SnapCenter 서버에 대한 연결을 열어야 합니다.

.시작하기 전에
* 복원 작업을 수행하기 전에 공간 회수 프로세스가 완료되었는지 확인해야 합니다.
* LUN이 Windows Server 장애 조치(failover) 클러스터의 호스트에서 공유되는 경우 클러스터 그룹을 소유한 호스트에서 공간 회수를 수행해야 합니다.
* 최적의 저장 성능을 위해서는 가능한 한 자주 공간 회수를 수행해야 합니다.
+
전체 NTFS 파일 시스템이 검사되었는지 확인해야 합니다.



*이 작업에 관하여*

* 공간 회수는 시간이 많이 걸리고 CPU를 많이 사용하므로 일반적으로 스토리지 시스템과 Windows 호스트 사용량이 낮을 때 작업을 실행하는 것이 가장 좋습니다.
* 공간 회수는 사용 가능한 공간을 거의 모두 회수하지만 100% 회수하지는 못합니다.
* 공간 회수를 수행하는 동안 디스크 조각 모음을 동시에 실행하면 안 됩니다.
+
그렇게 하면 회수 과정이 느려질 수 있습니다.



*단계*

애플리케이션 서버 PowerShell 명령 프롬프트에서 다음 명령을 입력합니다.

`Invoke-SdHostVolumeSpaceReclaim -Path drive_path`

drive_path는 LUN에 매핑된 드라이브 경로입니다.
