---
permalink: install/task_enable_two_way_ssl.html 
sidebar: sidebar 
keywords: security,disable two-way SSL,enable two-way SSL, windows host 
summary: PowerShell 명령을 사용하여 Windows 호스트의 SnapCenter 서버와 플러그인 간의 상호 통신을 보호하기 위해 양방향 SSL 통신을 활성화할 수 있습니다. 
---
= Windows 호스트에서 양방향 SSL 통신 활성화
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
PowerShell 명령을 사용하여 Windows 호스트의 SnapCenter 서버와 플러그인 간의 상호 통신을 보호하기 위해 양방향 SSL 통신을 활성화할 수 있습니다.

*시작하기 전에*

먼저 모든 플러그인과 SMCore 에이전트에 대한 명령을 실행한 다음 서버에 대한 명령을 실행합니다.

*단계*

. 양방향 SSL 통신을 활성화하려면 플러그인, 서버 및 양방향 SSL 통신이 필요한 각 에이전트에 대해 SnapCenter 서버에서 다음 명령을 실행합니다.
+
`> Set-SmConfigSettings -Agent -configSettings @{"EnableTwoWaySSL"="true"} -HostName <Plugin_HostName>`

+
`> Set-SmConfigSettings -Agent -configSettings @{"EnableTwoWaySSL"="true"} -HostName localhost`

+
`> Set-SmConfigSettings -Server -configSettings @{"EnableTwoWaySSL"="true"}`

. 다음 명령을 사용하여 IIS SnapCenter 애플리케이션 풀 재활용 작업을 수행합니다.
`> Restart-WebAppPool -Name "SnapCenter"`
. Windows 플러그인의 경우 다음 PowerShell 명령을 실행하여 SMCore 서비스를 다시 시작합니다.
+
`> Restart-Service -Name SnapManagerCoreService`





== 양방향 SSL 통신 비활성화

PowerShell 명령을 사용하여 양방향 SSL 통신을 비활성화할 수 있습니다.

*이 작업에 관하여*

* 먼저 모든 플러그인과 SMCore 에이전트에 대한 명령을 실행한 다음 서버에 대한 명령을 실행합니다.
* 양방향 SSL 통신을 비활성화하면 CA 인증서와 해당 구성은 제거되지 않습니다.
* SnapCenter Server에 새로운 호스트를 추가하려면 모든 플러그인 호스트에 대해 양방향 SSL을 비활성화해야 합니다.
* NLB와 F5는 지원되지 않습니다.


*단계*

. 양방향 SSL 통신을 비활성화하려면 모든 플러그인 호스트와 SnapCenter 호스트에 대해 SnapCenter 서버에서 다음 명령을 실행합니다.
+
`> Set-SmConfigSettings -Agent -configSettings @{"EnableTwoWaySSL"="false"} -HostName <Agent_HostName>`

+
`> Set-SmConfigSettings -Agent -configSettings @{"EnableTwoWaySSL"="false"} -HostName localhost`

+
`> Set-SmConfigSettings -Server -configSettings @{"EnableTwoWaySSL"="false"}`

. 다음 명령을 사용하여 IIS SnapCenter 애플리케이션 풀 재활용 작업을 수행합니다.
`> Restart-WebAppPool -Name "SnapCenter"`
. Windows 플러그인의 경우 다음 PowerShell 명령을 실행하여 SMCore 서비스를 다시 시작합니다.
+
`> Restart-Service -Name SnapManagerCoreService`


