---
permalink: install/task_add_storage_systems.html 
sidebar: sidebar 
keywords: add, storage system, SVM, ASA r2 systems 
summary: SnapCenter 데이터 보호 및 프로비저닝 작업을 수행할 수 있도록 ONTAP 스토리지에 액세스할 수 있는 스토리지 시스템을 설정해야 합니다.  단독 SVM을 추가하거나 여러 SVM으로 구성된 클러스터를 추가할 수 있습니다. 
---
= 스토리지 시스템 추가
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter ONTAP 스토리지, ASA r2 시스템 또는 Amazon FSx for NetApp ONTAP 에 액세스하여 데이터 보호 및 프로비저닝 작업을 수행할 수 있도록 스토리지 시스템을 설정해야 합니다.

독립형 SVM을 추가하거나 여러 SVM으로 구성된 클러스터를 추가할 수 있습니다.  Amazon FSx for NetApp ONTAP 사용하는 경우 fsxadmin 계정을 사용하여 여러 SVM으로 구성된 FSx 관리 LIF를 추가하거나 SnapCenter 에 FSx SVM을 추가할 수 있습니다.

.시작하기 전에
* 저장소 연결을 생성하려면 인프라 관리자 역할에 필요한 권한이 있어야 합니다.
* 플러그인 설치가 진행 중이 아닌지 확인해야 합니다.
+
스토리지 시스템 연결을 추가하는 동안에는 호스트 플러그인 설치가 진행 중이어서는 안 됩니다. 호스트 캐시가 업데이트되지 않고 SnapCenter GUI에 데이터베이스 상태가 "`백업에 사용할 수 없음`" 또는 "` NetApp 스토리지에 없음`"으로 표시될 수 있기 때문입니다.

* 저장 시스템 이름은 고유해야 합니다.
+
SnapCenter 서로 다른 클러스터에 동일한 이름을 가진 여러 스토리지 시스템을 지원하지 않습니다.  SnapCenter 에서 지원하는 각 스토리지 시스템은 고유한 이름과 고유한 데이터 LIF IP 주소를 가져야 합니다.



*이 작업에 관하여*

* 스토리지 시스템을 구성할 때 EMS(이벤트 관리 시스템) 및 AutoSupport 기능도 활성화할 수 있습니다.  AutoSupport 도구는 시스템 상태에 대한 데이터를 수집하여 NetApp 기술 지원팀에 자동으로 전송하여 시스템 문제를 해결할 수 있도록 합니다.
+
이러한 기능을 활성화하면 리소스가 보호되거나, 복원 또는 복제 작업이 성공적으로 완료되거나, 작업이 실패할 때 SnapCenter AutoSupport 정보를 스토리지 시스템에 보내고 EMS 메시지를 스토리지 시스템 syslog에 보냅니다.

* SnapMirror 대상이나 SnapVault 대상으로 스냅샷을 복제하려는 경우 대상 SVM이나 클러스터와 소스 SVM이나 클러스터에 대한 스토리지 시스템 연결을 설정해야 합니다.



NOTE: 저장 시스템 비밀번호를 변경하면 예약된 작업, 주문형 백업 및 복원 작업이 실패할 수 있습니다.  스토리지 시스템 비밀번호를 변경한 후 스토리지 탭에서 *수정*을 클릭하면 비밀번호를 업데이트할 수 있습니다.

*단계*

. 왼쪽 탐색 창에서 *저장 시스템*을 클릭합니다.
. 스토리지 시스템 페이지에서 *새로 만들기*를 클릭합니다.
. 스토리지 시스템 추가 페이지에서 다음 정보를 제공합니다.
+
|===
| 이 분야에서는... | 이렇게 하세요... 


 a| 
저장 시스템
 a| 
저장 시스템 이름이나 IP 주소를 입력하세요.


NOTE: 도메인 이름을 제외한 스토리지 시스템 이름은 15자 이하여야 하며, 이름을 확인할 수 있어야 합니다.  이름이 15자 이상인 스토리지 시스템 연결을 만들려면 Add-SmStorageConnectionPowerShell cmdlet을 사용할 수 있습니다.


NOTE: MetroCluster 구성(MCC)을 사용하는 스토리지 시스템의 경우 중단 없는 작업을 위해 로컬 클러스터와 피어 클러스터를 모두 등록하는 것이 좋습니다.

SnapCenter 서로 다른 클러스터에서 동일한 이름을 가진 여러 SVM을 지원하지 않습니다.  SnapCenter 에서 지원하는 각 SVM에는 고유한 이름이 있어야 합니다.


NOTE: SnapCenter 에 스토리지 연결을 추가한 후에는 ONTAP 사용하여 SVM이나 클러스터의 이름을 바꾸면 안 됩니다.


NOTE: SVM이 짧은 이름이나 FQDN으로 추가된 경우 SnapCenter 와 플러그인 호스트 모두에서 확인할 수 있어야 합니다.



 a| 
사용자 이름/비밀번호
 a| 
스토리지 시스템에 액세스하는 데 필요한 권한이 있는 스토리지 사용자의 자격 증명을 입력하세요.



 a| 
이벤트 관리 시스템(EMS) 및 AutoSupport 설정
 a| 
스토리지 시스템 syslog에 EMS 메시지를 보내거나 적용된 보호, 완료된 복원 작업 또는 실패한 작업에 대해 스토리지 시스템에 AutoSupport 메시지를 보내려면 해당 확인란을 선택합니다.

*실패한 작업에 대한 AutoSupport 알림을 스토리지 시스템에 보내기* 확인란을 선택하면 AutoSupport 알림을 활성화하려면 EMS 메시징이 필요하므로 * SnapCenter 서버 이벤트를 syslog에 기록* 확인란도 선택됩니다.

|===
. 플랫폼, 프로토콜, 포트 및 시간 초과에 할당된 기본값을 수정하려면 *추가 옵션*을 클릭하세요.
+
.. 플랫폼에서 드롭다운 목록에서 옵션 중 하나를 선택합니다.
+
SVM이 백업 관계의 보조 스토리지 시스템인 경우 *보조* 확인란을 선택합니다.  *보조* 옵션을 선택하면 SnapCenter 즉시 라이선스 확인을 수행하지 않습니다.

+
SnapCenter 에 SVM을 추가한 경우 사용자는 드롭다운에서 플랫폼 유형을 수동으로 선택해야 합니다.

.. 프로토콜에서 SVM 또는 클러스터 설정 중에 구성된 프로토콜(일반적으로 HTTPS)을 선택합니다.
.. 스토리지 시스템이 허용하는 포트를 입력하세요.
+
일반적으로 기본 포트 443이 작동합니다.

.. 통신 시도가 중단되기 전까지 걸리는 시간을 초 단위로 입력하세요.
+
기본값은 60초입니다.

.. SVM에 여러 관리 인터페이스가 있는 경우 *기본 IP* 확인란을 선택한 다음 SVM 연결에 대한 기본 IP 주소를 입력합니다.
.. *저장*을 클릭하세요.


. *제출*을 클릭하세요.


*결과*

스토리지 시스템 페이지의 *유형* 드롭다운에서 다음 작업 중 하나를 수행합니다.

* 추가된 모든 SVM을 보려면 * ONTAP SVM*을 선택하세요.
+
FSx SVM을 추가한 경우 FSx SVM이 여기에 나열됩니다.

* 추가된 모든 클러스터를 보려면 * ONTAP 클러스터*를 선택하세요.
+
fsxadmin을 사용하여 FSx 클러스터를 추가한 경우 FSx 클러스터가 여기에 나열됩니다.

+
클러스터 이름을 클릭하면 클러스터에 속한 모든 SVM이 스토리지 가상 머신 섹션에 표시됩니다.

+
ONTAP GUI를 사용하여 ONTAP 클러스터에 새로운 SVM을 추가한 경우 *재검색*을 클릭하여 새로 추가된 SVM을 확인합니다.



*끝난 후*

클러스터 관리자는 SnapCenter 액세스할 수 있는 모든 스토리지 시스템에서 이메일 알림을 보내려면 스토리지 시스템 명령줄에서 다음 명령을 실행하여 각 스토리지 시스템 노드에서 AutoSupport 활성화해야 합니다.

`autosupport trigger modify -node nodename -autosupport-message client.app.info -to enable -noteto enable`


NOTE: SVM(Storage Virtual Machine) 관리자는 AutoSupport 에 액세스할 수 없습니다.
