---
permalink: install/task_log_in_to_snapcenter.html 
sidebar: sidebar 
keywords: log in, logging, SnapCenter UI, modify timeout, GUI session timeout, disbale SSL 3.0, SSL 3.0, security 
summary: 'SnapCenter 역할 기반 액세스 제어(RBAC)를 지원합니다.  SnapCenter 관리자는 SnapCenter RBAC를 통해 작업 그룹이나 Active Directory의 사용자, 또는 Active Directory의 그룹에 역할과 리소스를 할당합니다.  이제 RBAC 사용자는 할당된 역할로 SnapCenter 에 로그인할 수 있습니다.' 
---
= RBAC 인증을 사용하여 SnapCenter 에 로그인합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 역할 기반 액세스 제어(RBAC)를 지원합니다.  SnapCenter 관리자는 SnapCenter RBAC를 통해 작업 그룹이나 Active Directory의 사용자, 또는 Active Directory의 그룹에 역할과 리소스를 할당합니다.  이제 RBAC 사용자는 할당된 역할로 SnapCenter 에 로그인할 수 있습니다.

.시작하기 전에
* Windows Server Manager에서 Windows Process Activation Service(WAS)를 활성화해야 합니다.
* SnapCenter 서버에 로그인하기 위해 Internet Explorer를 브라우저로 사용하려면 Internet Explorer의 보호 모드가 비활성화되어 있는지 확인해야 합니다.
* SnapCenter 서버가 Linux 호스트에 설치된 경우 SnapCenter 서버를 설치하는 데 사용된 사용자 계정을 사용하여 로그인해야 합니다.


*이 작업에 관하여*

SnapCenter 서버 설치 마법사는 설치하는 동안 바로 가기를 만들어 SnapCenter 설치된 호스트의 바탕 화면과 시작 메뉴에 놓습니다.  또한, 설치가 끝나면 설치 마법사가 설치 중에 제공한 정보를 기반으로 SnapCenter URL을 표시합니다. 원격 시스템에서 로그인하려는 경우 이 URL을 복사할 수 있습니다.


IMPORTANT: 웹 브라우저에 여러 개의 탭이 열려 있는 경우 SnapCenter 브라우저 탭만 닫아도 SnapCenter 에서 로그아웃되지 않습니다.  SnapCenter 와의 연결을 종료하려면 *로그아웃* 버튼을 클릭하거나 웹 브라우저 전체를 닫아 SnapCenter 에서 로그아웃해야 합니다.

|===


| *모범 사례:* 보안상의 이유로 브라우저에서 SnapCenter 비밀번호를 저장하지 않도록 설정하는 것이 좋습니다. 
|===
기본 GUI URL은 SnapCenter 서버가 설치된 서버의 기본 포트 8146(_\https://server:8146_)에 대한 보안 연결입니다.  SnapCenter 설치 중에 다른 서버 포트를 제공한 경우 해당 포트가 대신 사용됩니다.

고가용성(HA) 배포의 경우 가상 클러스터 IP _\https://Virtual_Cluster_IP_or_FQDN:8146_을 사용하여 SnapCenter 액세스해야 합니다.  Internet Explorer(IE)에서 _\https://Virtual_Cluster_IP_or_FQDN:8146_으로 이동할 때 SnapCenter UI가 보이지 않으면 각 플러그인 호스트의 IE에서 가상 클러스터 IP 주소 또는 FQDN을 신뢰할 수 있는 사이트로 추가하거나 각 플러그인 호스트에서 IE 강화 보안을 비활성화해야 합니다. 자세한 내용은 다음을 참조하세요.  https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/Unable_to_access_cluster_IP_address_from_outside_network["외부 네트워크에서 클러스터 IP 주소에 액세스할 수 없습니다."^] .

SnapCenter GUI를 사용하는 것 외에도 PowerShell cmdlet을 사용하여 구성, 백업 및 복원 작업을 수행하는 스크립트를 만들 수 있습니다.  일부 cmdlet은 SnapCenter 출시될 때마다 변경되었을 수 있습니다.  그만큼 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter 소프트웨어 Cmdlet 참조 가이드"^] 자세한 내용을 알고 있습니다.


NOTE: 처음으로 SnapCenter 에 로그인하는 경우 설치 과정에서 제공한 자격 증명을 사용하여 로그인해야 합니다.

*단계*

. 로컬 호스트 데스크톱에 있는 바로가기에서 SnapCenter 실행하거나, 설치가 끝날 때 제공된 URL에서 실행하거나, SnapCenter 관리자가 제공한 URL에서 실행하세요.
. 사용자 자격 증명을 입력하세요.
+
|===
| 다음을 지정하려면... | 다음 형식 중 하나를 사용하세요. 


 a| 
도메인 관리자
 a| 
** NetBIOS\사용자 이름
** 사용자 이름@UPN 접미사
+
예를 들어, \username@netapp.com

** 도메인 FQDN\사용자 이름




 a| 
지역 관리자
 a| 
사용자 이름

|===
. 두 개 이상의 역할이 할당된 경우 역할 상자에서 이 로그인 세션에 사용할 역할을 선택합니다.
+
SnapCenter 에 로그인하면 현재 사용자와 관련 역할이 오른쪽 상단에 표시됩니다.



*결과*

대시보드 페이지가 표시됩니다.

사이트에 접속할 수 없다는 오류로 로깅이 실패하는 경우 SSL 인증서를 SnapCenter 에 매핑해야 합니다. https://kb.netapp.com/?title=Advice_and_Troubleshooting%2FData_Protection_and_Security%2FSnapCenter%2FSnapCenter_will_not_open_with_error_%2522This_site_can%2527t_be_reached%2522["자세히 알아보기"^]

*끝난 후*

RBAC 사용자로 SnapCenter 서버에 처음 로그인한 후 리소스 목록을 새로 고칩니다.

SnapCenter 지원해야 할 신뢰할 수 없는 Active Directory 도메인이 있는 경우, 신뢰할 수 없는 도메인의 사용자 역할을 구성하기 전에 SnapCenter 에 해당 도메인을 등록해야 합니다. link:../install/task_register_untrusted_active_directory_domains.html["자세히 알아보기"^] .

Linux 호스트에서 실행되는 SnapCenter 에 플러그인 호스트를 추가하려면 _/opt/ NetApp/snapcenter/SnapManagerWeb/Repository_ 위치에서 체크섬 파일을 가져와야 합니다.

6.0 릴리스부터 SnapCenter PowerShell 바로 가기가 바탕 화면에 생성됩니다.  바로가기를 사용하여 SnapCenter PowerShell cmdlet에 직접 액세스할 수 있습니다.



== 다중 인증 요소(MFA)를 사용하여 SnapCenter 에 로그인하세요

SnapCenter Server는 Active Directory의 일부인 도메인 계정에 대한 MFA를 지원합니다.

.시작하기 전에
MFA를 활성화했어야 합니다.  MFA를 활성화하는 방법에 대한 자세한 내용은 다음을 참조하세요.link:../install/enable_multifactor_authentication.html["다중 요소 인증 활성화"]

*이 작업에 관하여*

* FQDN만 지원됩니다.
* 작업 그룹 및 크로스 도메인 사용자는 MFA를 사용하여 로그인할 수 없습니다.


*단계*

. 로컬 호스트 데스크톱에 있는 바로가기에서 SnapCenter 실행하거나, 설치가 끝날 때 제공된 URL에서 실행하거나, SnapCenter 관리자가 제공한 URL에서 실행하세요.
. AD FS 로그인 페이지에서 사용자 이름과 비밀번호를 입력합니다.
+
AD FS 페이지에 사용자 이름 또는 비밀번호가 올바르지 않다는 오류 메시지가 표시되면 다음 사항을 확인해야 합니다.

+
** 사용자 이름이나 비밀번호가 유효한지 여부
+
사용자 계정은 Active Directory(AD)에 있어야 합니다.

** AD에 설정된 허용된 최대 시도 횟수를 초과했는지 여부
** AD와 AD FS가 작동 중인지 여부






== SnapCenter 기본 GUI 세션 시간 초과 수정

SnapCenter GUI 세션 시간 초과 기간을 기본 시간 초과 기간인 20분보다 짧게 또는 길게 수정할 수 있습니다.

보안 기능으로, SnapCenter 기본적으로 15분 동안 활동이 없으면 5분 후에 GUI 세션에서 로그아웃된다는 경고를 표시합니다.  기본적으로 SnapCenter 20분 동안 아무런 활동이 없으면 GUI 세션에서 로그아웃되며, 다시 로그인해야 합니다.

*단계*

. 왼쪽 탐색 창에서 *설정* > *전역 설정*을 클릭합니다.
. 글로벌 설정 페이지에서 *구성 설정*을 클릭합니다.
. 세션 시간 초과 필드에 새 세션 시간 초과를 분 단위로 입력한 다음 *저장*을 클릭합니다.




== SSL 3.0을 비활성화하여 SnapCenter 웹 서버를 보호하세요.

보안을 위해 SnapCenter 웹 서버에서 SSL(Secure Socket Layer) 3.0 프로토콜이 활성화된 경우 Microsoft IIS에서 해당 프로토콜을 비활성화해야 합니다.

SSL 3.0 프로토콜에는 공격자가 연결 실패를 유발하거나 중간자 공격을 수행하여 웹사이트와 방문자 간의 암호화 트래픽을 관찰하는 데 사용할 수 있는 결함이 있습니다.

*단계*

. SnapCenter 웹 서버 호스트에서 레지스트리 편집기를 시작하려면 *시작* > *실행*을 클릭한 다음 regedit를 입력합니다.
. 레지스트리 편집기에서 HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\으로 이동합니다.
+
** 서버 키가 이미 존재하는 경우:
+
... 활성화된 DWORD를 선택한 다음 *편집* > *수정*을 클릭합니다.
... 값을 0으로 변경한 다음 *확인*을 클릭합니다.


** 서버 키가 존재하지 않는 경우:
+
... *편집* > *새로 만들기* > *키*를 클릭한 다음 키 이름을 Server로 지정합니다.
... 새로운 서버 키를 선택한 후 *편집* > *새로 만들기* > *DWORD*를 클릭합니다.
... 새 DWORD 이름을 Enabled로 지정한 다음 값으로 0을 입력합니다.




. 레지스트리 편집기를 닫습니다.

