---
permalink: install/task_configure_audit_log_settings.html 
sidebar: sidebar 
keywords: audit, log, configure 
summary: 소프트웨어 플랫폼과 해당 플랫폼에서 실행되는 모든 소프트웨어의 보안 이벤트를 기록하도록 구성할 수 있습니다. 
---
= 감사 로그 설정 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 서버의 모든 활동에 대해 감사 로그가 생성됩니다.  기본적으로 감사 로그는 기본 설치 위치인 _C:\Program Files\ NetApp\ SnapCenter WebApp\audit\_에 보관됩니다.

감사 로그는 각 감사 이벤트에 대해 디지털 서명된 다이제스트를 생성하여 보안을 유지함으로써 무단 수정으로부터 보호됩니다.  생성된 다이제스트는 별도의 감사 체크섬 파일에 유지 관리되며, 콘텐츠의 무결성을 보장하기 위해 주기적인 무결성 검사를 거칩니다.

"SnapCenterAdmin" 역할로 로그인했어야 합니다.

.이 작업에 관하여
* 알림은 다음과 같은 시나리오에서 전송됩니다.
+
** 감사 로그 무결성 검사 일정 또는 Syslog 서버가 활성화 또는 비활성화되었습니다.
** 감사 로그 무결성 검사, 감사 로그 또는 Syslog 서버 로그 실패
** 디스크 공간 부족


* 무결성 검사에 실패한 경우에만 이메일이 전송됩니다.
* 감사 로그 디렉토리와 감사 체크섬 로그 디렉토리 경로를 함께 수정해야 합니다.  그 중 하나만 수정할 수는 없습니다.
* 감사 로그 디렉토리와 감사 체크섬 로그 디렉토리 경로가 수정되면 이전 위치에 있는 감사 로그에 대한 무결성 검사를 수행할 수 없습니다.
* 감사 로그 디렉토리와 감사 체크섬 로그 디렉토리 경로는 SnapCenter Server의 로컬 드라이브에 있어야 합니다.
+
공유 또는 네트워크 마운트 드라이브는 지원되지 않습니다.

* Syslog 서버 설정에서 UDP 프로토콜을 사용하는 경우 포트가 다운되거나 사용할 수 없어 발생하는 오류는 SnapCenter 에서 오류나 알림으로 캡처될 수 없습니다.
* Set-SmAuditSettings 및 Get-SmAuditSettings 명령을 사용하여 감사 로그를 구성할 수 있습니다.
+
cmdlet과 함께 사용할 수 있는 매개변수와 해당 설명에 대한 정보는 Get-Help command_name을 실행하여 얻을 수 있습니다.  또는 다음을 참조할 수도 있습니다. https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter 소프트웨어 Cmdlet 참조 가이드"^] .



.단계
. *설정* 페이지에서 *설정* > *전역 설정* > *감사 로그 설정*으로 이동합니다.
. 감사 로그 섹션에 세부 정보를 입력합니다.
. *감사 로그 디렉토리* 및 *감사 체크섬 로그 디렉토리*를 입력합니다.
+
.. 최대 파일 크기를 입력하세요
.. 최대 로그 파일 입력
.. 알림을 보내려면 디스크 공간 사용량의 백분율을 입력하세요.


. (선택 사항) *UTC 시간 기록*을 활성화합니다.
. (선택 사항) *감사 로그 무결성 검사 일정*을 활성화하고 주문형 무결성 검사를 위해 *무결성 검사 시작*을 클릭합니다.
+
*Start-SmAuditIntegrityCheck* 명령을 실행하여 주문형 무결성 검사를 시작할 수도 있습니다.

. (선택 사항) 원격 Syslog 서버로 감사 로그 전달을 활성화하고 Syslog 서버 세부 정보를 입력합니다.
+
TLS 1.2 프로토콜의 경우 Syslog 서버에서 '신뢰할 수 있는 루트'로 인증서를 가져와야 합니다.

+
.. Syslog 서버 호스트 입력
.. Syslog 서버 포트를 입력하세요
.. Syslog 서버 프로토콜 입력
.. RFC 형식 입력


. *저장*을 클릭하세요.
. *모니터* > *작업*을 클릭하면 감사 무결성 검사와 디스크 공간 검사를 볼 수 있습니다.

