---
permalink: install/task_create_and_manage_disks.html 
sidebar: sidebar 
keywords: disks, create, manage, clustered disks, view 
summary: Windows 호스트는 스토리지 시스템의 LUN을 가상 디스크로 인식합니다.  SnapCenter 사용하여 FC 연결 또는 iSCSI 연결 LUN을 만들고 구성할 수 있습니다. 
---
= 디스크 생성 및 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Windows 호스트는 스토리지 시스템의 LUN을 가상 디스크로 인식합니다.  SnapCenter 사용하여 FC 연결 또는 iSCSI 연결 LUN을 만들고 구성할 수 있습니다.

* SnapCenter 기본 디스크만 지원합니다.  동적 디스크는 지원되지 않습니다.
* GPT의 경우 데이터 파티션은 하나만 허용되고, MBR의 경우 NTFS 또는 CSVFS로 포맷된 볼륨 하나와 마운트 경로가 하나인 기본 파티션 하나만 허용됩니다.
* 지원되는 파티션 스타일: GPT, MBR; VMware UEFI VM에서는 iSCSI 디스크만 지원됩니다.



NOTE: SnapCenter 디스크 이름 변경을 지원하지 않습니다.  SnapCenter 에서 관리하는 디스크의 이름이 변경되면 SnapCenter 작업이 성공하지 못합니다.



== 호스트의 디스크 보기

SnapCenter 사용하여 관리하는 각 Windows 호스트의 디스크를 볼 수 있습니다.

*단계*

. 왼쪽 탐색 창에서 *호스트*를 클릭합니다.
. 호스트 페이지에서 *디스크*를 클릭합니다.
. *호스트* 드롭다운 목록에서 호스트를 선택하세요.
+
디스크가 나열됩니다.





== 클러스터된 디스크 보기

SnapCenter 로 관리하는 클러스터에서 클러스터된 디스크를 볼 수 있습니다.  클러스터된 디스크는 호스트 드롭다운에서 클러스터를 선택할 때만 표시됩니다.

*단계*

. 왼쪽 탐색 창에서 *호스트*를 클릭합니다.
. 호스트 페이지에서 *디스크*를 클릭합니다.
. *호스트* 드롭다운 목록에서 클러스터를 선택합니다.
+
디스크가 나열됩니다.





== iSCSI 세션을 설정합니다

iSCSI를 사용하여 LUN에 연결하는 경우 통신을 활성화하려면 LUN을 생성하기 전에 iSCSI 세션을 설정해야 합니다.

*시작하기 전에*

* 스토리지 시스템 노드를 iSCSI 대상으로 정의해야 합니다.
* 스토리지 시스템에서 iSCSI 서비스를 시작했어야 합니다. http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/home.html["자세히 알아보기"^]


*이 작업에 관하여*

iSCSI 세션은 동일한 IP 버전 간에만 설정할 수 있습니다. 즉, IPv6에서 IPv6로, IPv4에서 IPv4로 설정할 수 있습니다.

iSCSI 세션 관리와 호스트와 대상 간의 통신에는 링크 로컬 IPv6 주소를 사용할 수 있지만, 이는 둘 다 동일한 서브넷에 있는 경우에만 가능합니다.

iSCSI 이니시에이터의 이름을 변경하면 iSCSI 대상에 대한 액세스가 영향을 받습니다.  이름을 변경한 후에는 개시자가 액세스하는 대상을 다시 구성하여 새 이름을 인식할 수 있도록 해야 할 수도 있습니다.  iSCSI 이니시에이터의 이름을 변경한 후에는 호스트를 다시 시작해야 합니다.

호스트에 iSCSI 인터페이스가 두 개 이상 있는 경우 첫 번째 인터페이스의 IP 주소를 사용하여 SnapCenter 에 iSCSI 세션을 설정하면 다른 IP 주소를 사용하여 다른 인터페이스에서 iSCSI 세션을 설정할 수 없습니다.

*단계*

. 왼쪽 탐색 창에서 *호스트*를 클릭합니다.
. 호스트 페이지에서 *iSCSI 세션*을 클릭합니다.
. *스토리지 가상 머신* 드롭다운 목록에서 iSCSI 대상에 대한 스토리지 가상 머신(SVM)을 선택합니다.
. *호스트* 드롭다운 목록에서 세션의 호스트를 선택합니다.
. *세션 설정*을 클릭하세요.
+
세션 설정 마법사가 표시됩니다.

. 세션 설정 마법사에서 대상을 식별합니다.
+
|===
| 이 분야에서는... | 입력하다... 


 a| 
대상 노드 이름
 a| 
iSCSI 대상의 노드 이름

기존 대상 노드 이름이 있는 경우 해당 이름은 읽기 전용 형식으로 표시됩니다.



 a| 
대상 포털 주소
 a| 
대상 네트워크 포털의 IP 주소



 a| 
대상 포털 포트
 a| 
대상 네트워크 포털의 TCP 포트



 a| 
개시자 포털 주소
 a| 
개시자 네트워크 포털의 IP 주소

|===
. 입력한 내용이 마음에 들면 *연결*을 클릭하세요.
+
SnapCenter iSCSI 세션을 설정합니다.

. 각 대상에 대한 세션을 설정하려면 이 절차를 반복합니다.




== FC 연결 또는 iSCSI 연결 LUN 또는 디스크 생성

Windows 호스트는 스토리지 시스템의 LUN을 가상 디스크로 인식합니다.  SnapCenter 사용하여 FC 연결 또는 iSCSI 연결 LUN을 만들고 구성할 수 있습니다.

SnapCenter 외부에서 디스크를 만들고 포맷하려면 NTFS 및 CSVFS 파일 시스템만 지원됩니다.

.시작하기 전에
* 스토리지 시스템에서 LUN에 대한 볼륨을 생성했어야 합니다.
+
볼륨은 LUN만 보관해야 하며, SnapCenter 로 생성된 LUN만 보관해야 합니다.

+

NOTE: 클론이 이미 분할되지 않은 한 SnapCenter 에서 생성된 클론 볼륨에 LUN을 생성할 수 없습니다.

* 스토리지 시스템에서 FC 또는 iSCSI 서비스를 시작했어야 합니다.
* iSCSI를 사용하는 경우 스토리지 시스템과 iSCSI 세션을 설정해야 합니다.
* Windows용 SnapCenter 플러그인 패키지는 디스크를 생성하는 호스트에만 설치해야 합니다.


*이 작업에 관하여*

* LUN이 Windows Server 장애 조치(failover) 클러스터의 호스트에서 공유되지 않는 한 LUN을 두 개 이상의 호스트에 연결할 수 없습니다.
* CSV(클러스터 공유 볼륨)를 사용하는 Windows Server 장애 조치(failover) 클러스터의 호스트에서 LUN을 공유하는 경우, 클러스터 그룹을 소유한 호스트에 디스크를 만들어야 합니다.


*단계*

. 왼쪽 탐색 창에서 *호스트*를 클릭합니다.
. 호스트 페이지에서 *디스크*를 클릭합니다.
. *호스트* 드롭다운 목록에서 호스트를 선택하세요.
. *새로 만들기*를 클릭합니다.
+
디스크 생성 마법사가 열립니다.

. LUN 이름 페이지에서 LUN을 식별합니다.
+
|===
| 이 분야에서는... | 이렇게 하세요... 


 a| 
저장 시스템
 a| 
LUN에 대한 SVM을 선택합니다.



 a| 
LUN 경로
 a| 
*찾아보기*를 클릭하여 LUN이 포함된 폴더의 전체 경로를 선택합니다.



 a| 
LUN 이름
 a| 
LUN의 이름을 입력하세요.



 a| 
클러스터 크기
 a| 
클러스터의 LUN 블록 할당 크기를 선택합니다.

클러스터 크기는 운영 체제와 애플리케이션에 따라 달라집니다.



 a| 
LUN 레이블
 a| 
선택적으로 LUN에 대한 설명 텍스트를 입력합니다.

|===
. 디스크 유형 페이지에서 디스크 유형을 선택합니다.
+
|===
| 선택하다... | 만약에... 


 a| 
전용 디스크
 a| 
LUN은 하나의 호스트에서만 액세스할 수 있습니다.

*리소스 그룹* 필드를 무시하세요.



 a| 
공유 디스크
 a| 
LUN은 Windows Server 장애 조치 클러스터의 호스트에서 공유됩니다.

*리소스 그룹* 필드에 클러스터 리소스 그룹의 이름을 입력합니다.  장애 조치 클러스터의 한 호스트에만 디스크를 생성해야 합니다.



 a| 
클러스터 공유 볼륨(CSV)
 a| 
LUN은 CSV를 사용하는 Windows Server 장애 조치 클러스터의 호스트에서 공유됩니다.

*리소스 그룹* 필드에 클러스터 리소스 그룹의 이름을 입력합니다.  디스크를 생성하는 호스트가 클러스터 그룹의 소유자인지 확인하세요.

|===
. 드라이브 속성 페이지에서 드라이브 속성을 지정합니다.
+
|===
| 재산 | 설명 


 a| 
마운트 지점 자동 할당
 a| 
SnapCenter 시스템 드라이브를 기반으로 볼륨 마운트 지점을 자동으로 할당합니다.

예를 들어, 시스템 드라이브가 C:인 경우 자동 할당은 C: 드라이브 아래에 볼륨 마운트 지점(C:\scmnpt\)을 생성합니다.  공유 디스크에는 자동 할당이 지원되지 않습니다.



 a| 
드라이브 문자 할당
 a| 
인접한 드롭다운 목록에서 선택한 드라이브에 디스크를 마운트합니다.



 a| 
볼륨 마운트 지점 사용
 a| 
인접 필드에 지정한 드라이브 경로에 디스크를 마운트합니다.

볼륨 마운트 지점의 루트는 디스크를 생성하는 호스트가 소유해야 합니다.



 a| 
드라이브 문자 또는 볼륨 마운트 지점을 할당하지 마십시오.
 a| 
Windows에서 디스크를 수동으로 마운트하려면 이 옵션을 선택하세요.



 a| 
LUN 크기
 a| 
LUN 크기를 지정하세요. 최소 150MB.

옆의 드롭다운 목록에서 MB, GB 또는 TB를 선택하세요.



 a| 
이 LUN을 호스팅하는 볼륨에 씬 프로비저닝을 사용합니다.
 a| 
LUN을 씬 프로비저닝합니다.

씬 프로비저닝은 한 번에 필요한 만큼의 저장 공간만 할당하므로 LUN이 사용 가능한 최대 용량까지 효율적으로 확장될 수 있습니다.

필요한 모든 LUN 스토리지를 수용할 수 있을 만큼 볼륨에 충분한 공간이 있는지 확인하세요.



 a| 
파티션 유형을 선택하세요
 a| 
GUID 파티션 테이블의 경우 GPT 파티션을 선택하고, 마스터 부트 레코드의 경우 MBR 파티션을 선택합니다.

MBR 파티션은 Windows Server 장애 조치(failover) 클러스터에서 정렬 오류 문제를 일으킬 수 있습니다.


NOTE: 통합 확장 가능 펌웨어 인터페이스(UEFI) 파티션 디스크는 지원되지 않습니다.

|===
. LUN 매핑 페이지에서 호스트의 iSCSI 또는 FC 이니시에이터를 선택합니다.
+
|===
| 이 분야에서는... | 이렇게 하세요... 


 a| 
주인
 a| 
클러스터 그룹 이름을 두 번 클릭하여 클러스터에 속한 호스트를 보여주는 드롭다운 목록을 표시한 다음, 개시자에 대한 호스트를 선택합니다.

이 필드는 LUN이 Windows Server 장애 조치 클러스터의 호스트에서 공유되는 경우에만 표시됩니다.



 a| 
호스트 개시자를 선택하세요
 a| 
*Fibre Channel* 또는 *iSCSI*를 선택한 다음 호스트에서 이니시에이터를 선택합니다.

MPIO(멀티패스 I/O)를 사용하는 FC를 사용하는 경우 여러 개의 FC 이니시에이터를 선택할 수 있습니다.

|===
. 그룹 유형 페이지에서 기존 igroup을 LUN에 매핑할지 아니면 새 igroup을 만들지 지정합니다.
+
|===
| 선택하다... | 만약에... 


 a| 
선택한 개시자에 대한 새 igroup 만들기
 a| 
선택한 개시자에 대한 새로운 igroup을 생성하려고 합니다.



 a| 
기존 igroup을 선택하거나 선택한 개시자에 대한 새 igroup을 지정합니다.
 a| 
선택한 개시자에 대해 기존 igroup을 지정하거나 지정한 이름으로 새 igroup을 만들려고 합니다.

*igroup 이름* 필드에 igroup 이름을 입력하세요.  기존 igroup 이름의 처음 몇 글자를 입력하면 필드가 자동 완성됩니다.

|===
. 요약 페이지에서 선택 사항을 검토한 다음 *마침*을 클릭합니다.
+
SnapCenter LUN을 생성하고 호스트의 지정된 드라이브 또는 드라이브 경로에 연결합니다.





== 디스크 크기 조정

저장 시스템의 변경 요구에 따라 디스크 크기를 늘리거나 줄일 수 있습니다.

*이 작업에 관하여*

* 씬 프로비저닝된 LUN의 경우 ONTAP LUN 지오메트리 크기는 최대 크기로 표시됩니다.
* 두꺼운 프로비저닝된 LUN의 경우 확장 가능한 크기(볼륨에서 사용 가능한 크기)는 최대 크기로 표시됩니다.
* MBR 스타일 파티션이 있는 LUN의 크기 제한은 2TB입니다.
* GPT 스타일 파티션이 있는 LUN의 스토리지 시스템 크기 제한은 16TB입니다.
* LUN 크기를 조정하기 전에 스냅샷을 만드는 것이 좋습니다.
* LUN 크기가 조정되기 전에 만든 스냅샷에서 LUN을 복원해야 하는 경우 SnapCenter 스냅샷 크기에 맞춰 LUN 크기를 자동으로 조정합니다.
+
복원 작업 후, 크기가 조정된 후 LUN에 추가된 데이터는 크기가 조정된 후 만들어진 스냅샷에서 복원되어야 합니다.



*단계*

. 왼쪽 탐색 창에서 *호스트*를 클릭합니다.
. 호스트 페이지에서 *디스크*를 클릭합니다.
. 호스트 드롭다운 목록에서 호스트를 선택합니다.
+
디스크가 나열됩니다.

. 크기를 조정하려는 디스크를 선택한 다음 *크기 조정*을 클릭합니다.
. 디스크 크기 조정 대화 상자에서 슬라이더 도구를 사용하여 디스크의 새 크기를 지정하거나 크기 필드에 새 크기를 입력합니다.
+

NOTE: 크기를 수동으로 입력하는 경우, 축소 또는 확장 버튼이 적절하게 활성화되기 전에 크기 필드 외부를 클릭해야 합니다.  또한, 측정 단위를 지정하려면 MB, GB 또는 TB를 클릭해야 합니다.

. 입력한 내용이 마음에 들면 필요에 따라 *축소* 또는 *확장*을 클릭하세요.
+
SnapCenter 디스크 크기를 조정합니다.





== 디스크 연결

디스크 연결 마법사를 사용하여 기존 LUN을 호스트에 연결하거나 연결이 끊어진 LUN을 다시 연결할 수 있습니다.

.시작하기 전에
* 스토리지 시스템에서 FC 또는 iSCSI 서비스를 시작했어야 합니다.
* iSCSI를 사용하는 경우 스토리지 시스템과 iSCSI 세션을 설정해야 합니다.
* LUN이 Windows Server 장애 조치(failover) 클러스터의 호스트에서 공유되지 않는 한 LUN을 두 개 이상의 호스트에 연결할 수 없습니다.
* LUN이 CSV(클러스터 공유 볼륨)를 사용하는 Windows Server 장애 조치(failover) 클러스터의 호스트에서 공유되는 경우, 클러스터 그룹을 소유한 호스트의 디스크를 연결해야 합니다.
* Windows용 플러그인은 디스크를 연결하는 호스트에만 설치하면 됩니다.


*단계*

. 왼쪽 탐색 창에서 *호스트*를 클릭합니다.
. 호스트 페이지에서 *디스크*를 클릭합니다.
. *호스트* 드롭다운 목록에서 호스트를 선택하세요.
. *연결*을 클릭하세요.
+
디스크 연결 마법사가 열립니다.

. LUN 이름 페이지에서 연결할 LUN을 식별합니다.
+
|===
| 이 분야에서는... | 이렇게 하세요... 


 a| 
저장 시스템
 a| 
LUN에 대한 SVM을 선택합니다.



 a| 
LUN 경로
 a| 
*찾아보기*를 클릭하여 LUN이 포함된 볼륨의 전체 경로를 선택합니다.



 a| 
LUN 이름
 a| 
LUN의 이름을 입력하세요.



 a| 
클러스터 크기
 a| 
클러스터의 LUN 블록 할당 크기를 선택합니다.

클러스터 크기는 운영 체제와 애플리케이션에 따라 달라집니다.



 a| 
LUN 레이블
 a| 
선택적으로 LUN에 대한 설명 텍스트를 입력합니다.

|===
. 디스크 유형 페이지에서 디스크 유형을 선택합니다.
+
|===
| 선택하다... | 만약에... 


 a| 
전용 디스크
 a| 
LUN은 하나의 호스트에서만 액세스할 수 있습니다.



 a| 
공유 디스크
 a| 
LUN은 Windows Server 장애 조치 클러스터의 호스트에서 공유됩니다.

장애 조치 클러스터에서 하나의 호스트에만 디스크를 연결하면 됩니다.



 a| 
클러스터 공유 볼륨(CSV)
 a| 
LUN은 CSV를 사용하는 Windows Server 장애 조치 클러스터의 호스트에서 공유됩니다.

디스크에 연결하는 호스트가 클러스터 그룹의 소유자인지 확인하세요.

|===
. 드라이브 속성 페이지에서 드라이브 속성을 지정합니다.
+
|===
| 재산 | 설명 


 a| 
자동 할당
 a| 
SnapCenter 시스템 드라이브를 기반으로 볼륨 마운트 지점을 자동으로 할당하도록 합니다.

예를 들어, 시스템 드라이브가 C:인 경우 자동 할당 속성은 C: 드라이브 아래에 볼륨 마운트 지점(C:\scmnpt\)을 만듭니다.  공유 디스크에서는 자동 할당 속성이 지원되지 않습니다.



 a| 
드라이브 문자 할당
 a| 
옆의 드롭다운 목록에서 선택한 드라이브에 디스크를 마운트합니다.



 a| 
볼륨 마운트 지점 사용
 a| 
인접한 필드에 지정한 드라이브 경로에 디스크를 마운트합니다.

볼륨 마운트 지점의 루트는 디스크를 생성하는 호스트가 소유해야 합니다.



 a| 
드라이브 문자 또는 볼륨 마운트 지점을 할당하지 마십시오.
 a| 
Windows에서 디스크를 수동으로 마운트하려면 이 옵션을 선택하세요.

|===
. LUN 매핑 페이지에서 호스트의 iSCSI 또는 FC 이니시에이터를 선택합니다.
+
|===
| 이 분야에서는... | 이렇게 하세요... 


 a| 
주인
 a| 
클러스터 그룹 이름을 두 번 클릭하면 클러스터에 속한 호스트를 보여주는 드롭다운 목록이 표시되고, 그런 다음 개시자에 대한 호스트를 선택합니다.

이 필드는 LUN이 Windows Server 장애 조치 클러스터의 호스트에서 공유되는 경우에만 표시됩니다.



 a| 
호스트 개시자를 선택하세요
 a| 
*Fibre Channel* 또는 *iSCSI*를 선택한 다음 호스트에서 이니시에이터를 선택합니다.

MPIO와 함께 FC를 사용하는 경우 여러 개의 FC 이니시에이터를 선택할 수 있습니다.

|===
. 그룹 유형 페이지에서 기존 igroup을 LUN에 매핑할지 아니면 새 igroup을 만들지 지정합니다.
+
|===
| 선택하다... | 만약에... 


 a| 
선택한 개시자에 대한 새 igroup 만들기
 a| 
선택한 개시자에 대한 새로운 igroup을 생성하려고 합니다.



 a| 
기존 igroup을 선택하거나 선택한 개시자에 대한 새 igroup을 지정합니다.
 a| 
선택한 개시자에 대해 기존 igroup을 지정하거나 지정한 이름으로 새 igroup을 만들려고 합니다.

*igroup 이름* 필드에 igroup 이름을 입력하세요.  기존 igroup 이름의 처음 몇 글자를 입력하면 필드가 자동으로 완성됩니다.

|===
. 요약 페이지에서 선택 사항을 검토하고 *마침*을 클릭합니다.
+
SnapCenter LUN을 호스트의 지정된 드라이브 또는 드라이브 경로에 연결합니다.





== 디스크 연결 해제

LUN의 내용에 영향을 미치지 않고 호스트에서 LUN을 분리할 수 있습니다. 단, 한 가지 예외가 있습니다. 복제본이 분할되기 전에 복제본의 연결을 끊으면 복제본의 내용이 손실됩니다.

.시작하기 전에
* LUN이 어떤 애플리케이션에서도 사용되고 있지 않은지 확인하세요.
* LUN이 모니터링 소프트웨어로 모니터링되고 있지 않은지 확인하세요.
* LUN이 공유된 경우 LUN에서 클러스터 리소스 종속성을 제거하고 클러스터의 모든 노드가 전원이 켜져 있고 제대로 작동하며 SnapCenter 에서 사용할 수 있는지 확인하세요.


*이 작업에 관하여*

SnapCenter 에서 생성한 FlexClone 볼륨에서 LUN의 연결을 끊고 해당 볼륨의 다른 LUN이 연결되어 있지 않으면 SnapCenter 해당 볼륨을 삭제합니다.  LUN 연결을 끊기 전에 SnapCenter FlexClone 볼륨이 삭제될 수 있다는 경고 메시지를 표시합니다.

FlexClone 볼륨이 자동으로 삭제되는 것을 방지하려면 마지막 LUN의 연결을 끊기 전에 볼륨의 이름을 바꿔야 합니다.  볼륨의 이름을 바꿀 때는 이름의 마지막 문자뿐만 아니라 여러 문자를 변경해야 합니다.

*단계*

. 왼쪽 탐색 창에서 *호스트*를 클릭합니다.
. 호스트 페이지에서 *디스크*를 클릭합니다.
. *호스트* 드롭다운 목록에서 호스트를 선택하세요.
+
디스크가 나열됩니다.

. 연결을 끊을 디스크를 선택한 다음 *연결 끊기*를 클릭합니다.
. 디스크 연결 끊기 대화 상자에서 *확인*을 클릭합니다.
+
SnapCenter 가 디스크 연결을 끊습니다.





== 디스크 삭제

더 이상 필요하지 않은 디스크는 삭제할 수 있습니다.  디스크를 삭제한 후에는 삭제를 취소할 수 없습니다.

*단계*

. 왼쪽 탐색 창에서 *호스트*를 클릭합니다.
. 호스트 페이지에서 *디스크*를 클릭합니다.
. *호스트* 드롭다운 목록에서 호스트를 선택하세요.
+
디스크가 나열됩니다.

. 삭제할 디스크를 선택한 다음 *삭제*를 클릭합니다.
. 디스크 삭제 대화 상자에서 *확인*을 클릭합니다.
+
SnapCenter 디스크를 삭제합니다.


