---
permalink: protect-db2/create-backup-policies-for-ibm-db2.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for IBM Db2 
summary: SnapCenter 사용하여 IBM Db2 데이터베이스 리소스를 백업하기 전에 백업하려는 리소스 또는 리소스 그룹에 대한 백업 정책을 만들어야 합니다.  백업 정책은 백업을 관리, 일정을 정하고 보관하는 방법을 규정하는 일련의 규칙입니다. 
---
= IBM Db2에 대한 백업 정책 만들기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 사용하여 IBM Db2 리소스를 백업하기 전에 백업하려는 리소스 또는 리소스 그룹에 대한 백업 정책을 만들어야 합니다.  백업 정책은 백업을 관리, 일정을 정하고 보관하는 방법을 규정하는 일련의 규칙입니다.

.시작하기 전에
* 백업 전략을 정의했어야 합니다.
+
자세한 내용은 IBM Db2 데이터베이스에 대한 데이터 보호 전략 정의에 대한 정보를 참조하세요.

* SnapCenter 설치, 호스트 추가, 스토리지 시스템 연결 설정, 리소스 추가 등의 작업을 완료하여 데이터 보호를 준비했어야 합니다.
* 스냅샷을 미러 또는 볼트에 복제하는 경우 SnapCenter 관리자가 소스 및 대상 볼륨 모두에 대한 SVM을 할당해야 합니다.
+
또한 정책에서 복제, 스크립트 및 애플리케이션 설정을 지정할 수 있습니다.  이러한 옵션을 사용하면 다른 리소스 그룹에 대한 정책을 재사용할 때 시간을 절약할 수 있습니다.



.이 작업에 관하여
* SnapLock
+
** '특정 기간 동안 백업 사본을 보관합니다' 옵션을 선택한 경우 SnapLock 보관 기간은 언급된 보관 기간보다 짧거나 같아야 합니다.
** 스냅샷 잠금 기간을 지정하면 보존 기간이 만료될 때까지 스냅샷이 삭제되지 않습니다.  이로 인해 정책에 지정된 수보다 더 많은 수의 스냅샷을 보관하게 될 수 있습니다.
** ONTAP 9.12.1 이하 버전의 경우 복원의 일부로 SnapLock Vault 스냅샷에서 생성된 복제본은 SnapLock Vault 만료 시간을 상속받습니다. 스토리지 관리자는 SnapLock 만료 시간 이후에 복제본을 수동으로 정리해야 합니다.




.단계
. 왼쪽 탐색 창에서 *설정*을 클릭합니다.
. 설정 페이지에서 *정책*을 클릭합니다.
. *새로 만들기*를 클릭합니다.
. 이름 페이지에서 정책 이름과 세부 정보를 입력합니다.
. 정책 유형 페이지에서 다음을 수행합니다.
+
.. 저장 유형을 선택하세요.
.. *사용자 정의 백업 설정* 섹션에서 플러그인에 키-값 형식으로 전달해야 하는 특정 백업 설정을 제공합니다.
+
플러그인에 전달할 여러 개의 키-값을 제공할 수 있습니다.



. 스냅샷 및 복제 페이지에서 다음 작업을 수행합니다.
+
.. *주문형*, *매시간*, *매일*, *매주*, *매월* 중에서 선택하여 일정 빈도를 지정하세요.
+

NOTE: 리소스 그룹을 생성하는 동안 백업 작업에 대한 일정(시작 날짜, 종료 날짜, 빈도)을 지정할 수 있습니다.  이를 통해 동일한 정책과 백업 빈도를 공유하는 리소스 그룹을 만들 수 있을 뿐만 아니라 각 정책에 다른 백업 일정을 할당할 수도 있습니다.

+

NOTE: 오전 2시로 예약한 경우, 일광 절약 시간제(DST) 기간에는 일정이 실행되지 않습니다.

.. 스냅샷 설정 섹션에서 다음 작업을 수행합니다.
+
|===
| 만약 당신이 원한다면... | 그 다음에... 


 a| 
특정 수의 스냅샷을 보관하세요
 a| 
*보관할 사본*을 선택한 다음 보관하려는 스냅샷 수를 지정합니다.

스냅샷 수가 지정된 수를 초과하면 스냅샷이 삭제되고 가장 오래된 사본이 먼저 삭제됩니다.



 a| 
스냅샷을 특정 일수 동안 보관하세요
 a| 
*사본 보관 기간*을 선택한 다음, 스냅샷을 삭제하기 전에 보관할 일수를 지정합니다.



 a| 
스냅샷 복사 잠금 기간
 a| 
*스냅샷 복사 잠금 기간*을 선택하고 일, 월 또는 년을 지정합니다.

스냅락 보관 기간은 100년 미만이어야 합니다.

|===
+

IMPORTANT: 스냅샷 복사 기반 백업의 경우 SnapVault 복제를 활성화하려면 보존 횟수를 2 이상으로 설정해야 합니다.  보존 횟수를 1로 설정하면 새 스냅샷이 대상에 복제될 때까지 첫 번째 스냅샷이 SnapVault 관계에 대한 참조 스냅샷이기 때문에 보존 작업이 실패할 수 있습니다.

.. 정책 라벨을 지정합니다.
+
원격 복제를 위해 기본 스냅샷에 SnapMirror 레이블을 할당하면 기본 스냅샷이 SnapCenter 에서 ONTAP 보조 시스템으로 스냅샷 복제 작업을 오프로드할 수 있습니다. 정책 페이지에서 SnapMirror 또는 SnapVault 옵션을 활성화하지 않고도 이 작업을 수행할 수 있습니다.



. 보조 복제 옵션 선택 섹션에서 다음 보조 복제 옵션 중 하나 또는 둘 다를 선택합니다.
+
|===
| 이 분야에서는... | 이렇게 하세요... 


 a| 
로컬 스냅샷 복사본을 만든 후 SnapMirror 업데이트
 a| 
다른 볼륨에 백업 세트의 미러 복사본을 생성하려면 이 필드를 선택합니다(SnapMirror 복제).

SnapMirror Active Sync의 경우 이 옵션을 활성화해야 합니다.



 a| 
로컬 스냅샷 복사본을 만든 후 SnapVault 업데이트
 a| 
디스크 간 백업 복제(SnapVault 백업)를 수행하려면 이 옵션을 선택하세요.



 a| 
오류 재시도 횟수
 a| 
작업이 중지되기 전에 허용할 수 있는 최대 복제 시도 횟수를 입력하세요.

|===
+

NOTE: 보조 저장소의 스냅샷 최대 한도에 도달하지 않도록 하려면 ONTAP 에서 보조 저장소 SnapMirror 보존 정책을 구성해야 합니다.

. 요약을 검토한 후 *마침*을 클릭하세요.

