---
permalink: protect-nsp/prerequisites_for_using_netapp_supported_plugins.html 
sidebar: sidebar 
keywords: Credentials 
summary: SnapCenter NetApp 지원 플러그인을 사용하기 전에 SnapCenter 관리자가 SnapCenter 서버를 설치하고 구성하고 필수 작업을 수행해야 합니다. 
---
= NetApp 지원 플러그인을 사용하기 위한 전제 조건
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter NetApp 지원 플러그인을 사용하기 전에 SnapCenter 관리자가 SnapCenter 서버를 설치하고 구성하고 필수 작업을 수행해야 합니다.

* SnapCenter 서버를 설치하고 구성합니다.
* SnapCenter 서버에 로그인합니다.
* 해당되는 경우 스토리지 시스템 연결을 추가하고 자격 증명을 생성하여 SnapCenter 환경을 구성합니다.
* 호스트를 추가하고 플러그인을 설치하여 업로드합니다.
* 해당되는 경우 플러그인 호스트에 Java 11을 설치합니다.
* 여러 데이터 경로(LIF) 또는 dNFS 구성이 있는 경우 데이터베이스 호스트에서 SnapCenter CLI를 사용하여 다음을 수행할 수 있습니다.
+
** 기본적으로 데이터베이스 호스트의 모든 IP 주소는 복제된 볼륨의 스토리지 가상 머신(SVM)에 있는 NFS 스토리지 내보내기 정책에 추가됩니다.  특정 IP 주소를 사용하거나 IP 주소의 하위 집합으로 제한하려면 Set-PreferredHostIPsInStorageExportPolicy CLI를 실행하세요.
** SVM에 여러 개의 데이터 경로(LIF)가 있는 경우 SnapCenter NFS 복제 볼륨을 마운트하기 위해 적절한 데이터 경로(LIF)를 선택합니다. 하지만 특정 데이터 경로(LIF)를 지정하려면 Set-SvmPreferredDataPath CLI를 실행해야 합니다. 명령과 함께 사용할 수 있는 매개변수와 해당 설명에 대한 정보는 _Get-Help command_name_을 실행하면 얻을 수 있습니다. 또는 다음을 참조할 수도 있습니다. https://library.netapp.com/ecm/ecm_download_file/ECMLP3337666["SnapCenter 소프트웨어 명령 참조 가이드"^] .


* 백업 복제가 필요한 경우 SnapMirror 와 SnapVault 설정하세요.
* 호스트의 다른 애플리케이션이 포트 9090을 사용하지 않는지 확인하세요.
+
포트 9090은 SnapCenter 에 필요한 다른 포트 외에도 NetApp 지원 플러그인에서 사용하도록 예약해야 합니다.


