---
permalink: protect-nsp/prerequisites_to_adding_hosts_and_installing_netapp_supported_plugins.html 
sidebar: sidebar 
keywords: credentials 
summary: 호스트를 추가하고 플러그인 패키지를 설치하기 전에 모든 요구 사항을 충족해야 합니다.  NetApp 에서 지원하는 플러그인은 Windows, Linux 또는 AIX 환경에서 모두 사용할 수 있습니다. 
---
= Windows, Linux 또는 AIX용 호스트 추가 및 플러그인 패키지 설치를 위한 전제 조건
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
호스트를 추가하고 플러그인 패키지를 설치하기 전에 모든 요구 사항을 충족해야 합니다.  NetApp 지원 플러그인은 Windows, Linux 및 AIX 환경에서 지원됩니다.


NOTE: AIX에서는 스토리지와 Oracle 애플리케이션이 지원됩니다.

* Linux, Windows 또는 AIX 호스트에 Java 11을 설치했어야 합니다.
+

NOTE: IBM Java는 Windows 및 Linux 호스트에서 지원되지 않습니다.

* Windows 호스트에 플러그인을 설치할 때 기본 제공되지 않은 자격 증명을 지정하거나 사용자가 로컬 작업 그룹 사용자에 속하는 경우 호스트에서 UAC를 비활성화해야 합니다.
* MongoDB, ORASCPM, Oracle Applications, SAP ASE, SAP MaxDB 및 Storage 플러그인과 같은 NetApp 지원 플러그인은 호스트 추가 작업이 수행되는 클라이언트 호스트에서 사용할 수 있어야 합니다.




== 일반적인

iSCSI를 사용하는 경우 iSCSI 서비스가 실행 중이어야 합니다.



== Windows 호스트

* 원격 호스트에 로컬 로그인 권한이 있는 로컬 관리자 권한이 있는 도메인 사용자가 있어야 합니다.
* SnapCenter 에서 클러스터 노드를 관리하는 경우 클러스터의 모든 노드에 대한 관리 권한이 있는 사용자가 있어야 합니다.
* Microsoft Windows용 SnapCenter 플러그인을 수동으로 선택해야 합니다.
+
http://www.java.com/en/download/manual.jsp["Windows용 JAVA 다운로드"]





== Linux 및 AIX 호스트


NOTE: AIX에서는 스토리지와 Oracle 애플리케이션이 지원됩니다.

* 루트 또는 루트가 아닌 사용자에 대해 비밀번호 기반 SSH 연결을 활성화해야 합니다.
* Linux 호스트에 Java 11을 설치했어야 합니다.
+
SnapCenter 서버 호스트로 Windows Server 2019 또는 Windows Server 2016을 사용하는 경우 Java 11을 설치해야 합니다.  상호 운용성 매트릭스 도구(IMT)에는 요구 사항에 대한 최신 정보가 포함되어 있습니다.

+
http://www.java.com/en/download/manual.jsp["Linux용 JAVA 다운로드"]

+
https://developer.ibm.com/languages/java/semeru-runtimes/downloads/?license=IBM["AIX용 JAVA 다운로드"]

+
https://imt.netapp.com/matrix/imt.jsp?components=117018;&solution=1259&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 도구"]

* 루트가 아닌 사용자에게 여러 경로에 대한 액세스 권한을 제공하려면 sudo 권한을 구성해야 합니다.  visudo Linux 유틸리티를 사용하여 /etc/sudoers 파일에 다음 줄을 추가합니다.
+

NOTE: Sudo 버전 1.8.7 이상을 사용하고 있는지 확인하세요.

+
[listing, subs="+quotes"]
----
Cmnd_Alias HPPLCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/snapcenter_linux_host_plugin.bin, /opt/NetApp/snapcenter/spl/installation/plugins/uninstall, /opt/NetApp/snapcenter/spl/bin/spl, /opt/NetApp/snapcenter/scc/bin/scc
Cmnd_Alias PRECHECKCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/Linux_Prechecks.sh
Cmnd_Alias CONFIGCHECKCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/plugins/scu/scucore/configurationcheck/Config_Check.sh
Cmnd_Alias SCCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/bin/sc_command_executor
Cmnd_Alias SCCCMDEXECUTOR =checksum_value== /opt/NetApp/snapcenter/scc/bin/sccCommandExecutor
_LINUX_USER_ ALL=(ALL) NOPASSWD:SETENV: HPPLCMD, PRECHECKCMD, CONFIGCHECKCMD, SCCCMDEXECUTOR, SCCMD
Defaults: _LINUX_USER_ env_keep += "IATEMPDIR"
Defaults: _LINUX_USER_ env_keep += "JAVA_HOME"
Defaults: _LINUX_USER_ !visiblepw
Defaults: _LINUX_USER_ !requiretty
----
+
_LINUX_USER_는 사용자가 생성한 루트가 아닌 사용자의 이름입니다.

+
_checksum_value_는 *sc_unix_plugins_checksum.txt* 파일에서 얻을 수 있습니다. 이 파일의 위치는 다음과 같습니다.

+
** SnapCenter Server가 Windows 호스트에 설치된 경우 _C:\ProgramData\ NetApp\ SnapCenter \Package Repository\sc_unix_plugins_checksum.txt_.
** SnapCenter 서버가 Linux 호스트에 설치되어 있는 경우 _/opt/ NetApp /snapcenter/SnapManagerWeb/Repository/sc_unix_plugins_checksum.txt_.
+

IMPORTANT: 이 예제는 귀하만의 데이터를 생성하기 위한 참고자료로만 사용해야 합니다.







== AIX 호스트 요구 사항

AIX용 SnapCenter 플러그인 패키지를 설치하기 전에 호스트가 요구 사항을 충족하는지 확인해야 합니다.


NOTE: AIX에서는 스토리지와 Oracle 애플리케이션이 지원됩니다.


NOTE: AIX용 SnapCenter 플러그인 패키지의 일부인 UNIX용 SnapCenter 플러그인은 동시 볼륨 그룹을 지원하지 않습니다.

|===
| 목 | 요구 사항 


 a| 
운영 체제
 a| 
AIX 7.1 이상



 a| 
호스트의 SnapCenter 플러그인을 위한 최소 RAM
 a| 
4GB



 a| 
호스트의 SnapCenter 플러그인에 대한 최소 설치 및 로그 공간
 a| 
2GB


NOTE: 충분한 디스크 공간을 할당하고 로그 폴더의 저장 공간 소비를 모니터링해야 합니다.  필요한 로그 공간은 보호해야 할 엔터티의 수와 데이터 보호 작업의 빈도에 따라 달라집니다.  디스크 공간이 충분하지 않으면 최근 실행된 작업에 대한 로그가 생성되지 않습니다.



 a| 
필수 소프트웨어 패키지
 a| 
자바 11 IBM 자바

JAVA를 최신 버전으로 업그레이드한 경우 /var/opt/snapcenter/spl/etc/spl.properties에 있는 JAVA_HOME 옵션이 올바른 JAVA 버전과 올바른 경로로 설정되어 있는지 확인해야 합니다.

|===
지원되는 버전에 대한 최신 정보는 다음을 참조하세요. https://imt.netapp.com/matrix/imt.jsp?components=121073;&solution=1257&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 도구"^] .



=== AIX 호스트에 대한 루트가 아닌 사용자에 대한 sudo 권한 구성

SnapCenter 4.4 이상에서는 루트가 아닌 사용자도 AIX용 SnapCenter 플러그인 패키지를 설치하고 플러그인 프로세스를 시작할 수 있습니다.  플러그인 프로세스는 루트가 아닌 사용자로 실행됩니다.  루트가 아닌 사용자에게 여러 경로에 대한 액세스 권한을 제공하려면 sudo 권한을 구성해야 합니다.

*필요한 것*

* Sudo 버전 1.8.7 이상.
* _/etc/ssh/sshd_config_ 파일을 편집하여 메시지 인증 코드 알고리즘(MAC hmac-sha2-256 및 MAC hmac-sha2-512)을 구성합니다.
+
구성 파일을 업데이트한 후 sshd 서비스를 다시 시작합니다.

+
예:

+
[listing]
----
#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::
#Legacy changes
#KexAlgorithms diffie-hellman-group1-sha1
#Ciphers aes128-cbc
#The default requires explicit activation of protocol
Protocol 2
HostKey/etc/ssh/ssh_host_rsa_key
MACs hmac-sha2-256
----


*이 작업에 관하여*

루트가 아닌 사용자에게 다음 경로에 대한 액세스를 제공하려면 sudo 권한을 구성해야 합니다.

* /home/_AIX_USER_/.sc_netapp/snapcenter_aix_host_plugin.bsx
* /custom_location/ NetApp/snapcenter/spl/설치/플러그인/제거
* /custom_location/ NetApp/snapcenter/spl/bin/spl


*단계*

. AIX용 SnapCenter 플러그인 패키지를 설치하려는 AIX 호스트에 로그인합니다.
. visudo Linux 유틸리티를 사용하여 /etc/sudoers 파일에 다음 줄을 추가합니다.
+
[listing, subs="+quotes"]
----
Cmnd_Alias HPPACMD = sha224:checksum_value== /home/_AIX_USER_/.sc_netapp/snapcenter_aix_host_plugin.bsx,
/opt/NetApp/snapcenter/spl/installation/plugins/uninstall, /opt/NetApp/snapcenter/spl/bin/spl
Cmnd_Alias PRECHECKCMD = sha224:checksum_value== /home/_AIX_USER_/.sc_netapp/AIX_Prechecks.sh
Cmnd_Alias CONFIGCHECKCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/plugins/scu/scucore/configurationcheck/Config_Check.sh
Cmnd_Alias SCCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/bin/sc_command_executor
_AIX_USER_ ALL=(ALL) NOPASSWD:SETENV: HPPACMD, PRECHECKCMD, CONFIGCHECKCMD, SCCMD
Defaults: _LINUX_USER_ env_keep += "IATEMPDIR"
Defaults: _LINUX_USER_ env_keep += "JAVA_HOME"
Defaults: _AIX_USER_ !visiblepw
Defaults: _AIX_USER_ !requiretty
----
+

NOTE: RAC 설정을 사용하는 경우 허용되는 다른 명령과 함께 다음을 /etc/sudoers 파일에 추가해야 합니다. '/<crs_home>/bin/olsnodes'



_crs_home_의 값은 _/etc/oracle/olr.loc_ 파일에서 얻을 수 있습니다.

_AIX_USER_는 사용자가 생성한 루트가 아닌 사용자의 이름입니다.

_checksum_value_는 *sc_unix_plugins_checksum.txt* 파일에서 얻을 수 있습니다. 이 파일의 위치는 다음과 같습니다.

* SnapCenter Server가 Windows 호스트에 설치된 경우 _C:\ProgramData\ NetApp\ SnapCenter \Package Repository\sc_unix_plugins_checksum.txt_.
* SnapCenter 서버가 Linux 호스트에 설치되어 있는 경우 _/opt/ NetApp /snapcenter/SnapManagerWeb/Repository/sc_unix_plugins_checksum.txt_.



IMPORTANT: 이 예제는 귀하만의 데이터를 생성하기 위한 참고자료로만 사용해야 합니다.
