---
permalink: protect-nsp/what_you_can_do_with_the_netapp_supported_plugins.html 
sidebar: sidebar 
keywords: NetApp supported plug-ins 
summary: 데이터 보호 작업에 NetApp 지원 플러그인을 사용할 수 있습니다. 
---
= NetApp 지원 플러그인으로 할 수 있는 작업
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MongoDB, ORASCPM, Oracle Applications, SAP ASE, SAP MaxDB 및 Storage 플러그인과 같은 NetApp 지원 플러그인을 데이터 보호 작업에 사용할 수 있습니다.

* 데이터베이스, 인스턴스, 문서 또는 테이블스페이스와 같은 리소스를 추가합니다.
* 백업을 만듭니다.
* 백업에서 복원합니다.
* 백업을 복제합니다.
* 백업 작업을 예약합니다.
* 백업, 복원 및 복제 작업을 모니터링합니다.
* 백업, 복원 및 복제 작업에 대한 보고서를 확인합니다.


데이터 보호 작업에 NetApp 지원 플러그인을 사용할 수 있습니다.

* ONTAP 클러스터 전반의 스토리지 볼륨에 대한 일관성 그룹 스냅샷을 만듭니다.
* 내장된 사전 및 사후 스크립팅 프레임워크를 사용하여 사용자 정의 애플리케이션 백업
+
ONTAP 볼륨, LUN 또는 Qtree를 백업할 수 있습니다.

* SnapCenter 정책을 사용하여 기존 복제 관계( SnapVault/ SnapMirror /통합 복제)를 활용하여 기본에서 촬영한 스냅샷을 ONTAP 보조로 업데이트합니다.
+
ONTAP 기본 및 보조는 ONTAP FAS, AFF, ASA, ONTAP Select 또는 Cloud Volumes ONTAP 될 수 있습니다.

* ONTAP 볼륨, LUN 또는 파일을 모두 복구합니다.
+
제품에는 탐색이나 인덱싱 기능이 내장되어 있지 않으므로 해당 파일 경로를 수동으로 제공해야 합니다.

+
Qtree 또는 디렉토리 복원은 지원되지 않지만 백업 범위가 Qtree 수준에서 정의된 경우에만 Qtree를 복제하고 내보낼 수 있습니다.


