---
permalink: get-started/concept_resources_resource_groups_and_policies.html 
sidebar: sidebar 
keywords: resource, resource group, policy 
summary: SnapCenter 사용하기 전에 수행하려는 백업, 복제 및 복원 작업과 관련된 기본 개념을 이해하는 것이 좋습니다. 
---
= 데이터 보호의 핵심 개념
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 사용하기 전에 백업, 복제, 복원에 대한 핵심 개념을 이해하세요.



== 리소스

리소스에는 SnapCenter 로 백업되거나 복제된 데이터베이스, Windows 파일 시스템 또는 파일 공유가 포함됩니다.  환경에 따라 리소스는 데이터베이스 인스턴스, SQL Server 가용성 그룹, Oracle 데이터베이스, RAC 데이터베이스 또는 사용자 지정 애플리케이션 그룹일 수도 있습니다.



== 리소스 그룹

리소스 그룹은 호스트나 클러스터에 있는 리소스의 모음으로, 잠재적으로 여러 호스트와 클러스터에 속합니다.  리소스 그룹에서 수행되는 작업은 지정된 일정에 따라 모든 리소스에 적용됩니다.  개별 리소스나 그룹에 대해 주문형 또는 예약된 백업을 수행할 수 있습니다.


NOTE: 공유 리소스 그룹의 한 호스트가 유지 관리 모드로 전환되면 해당 그룹에 대해 예약된 모든 작업이 모든 호스트에서 중단됩니다.

특정 리소스를 백업하려면 관련 플러그인을 사용하세요. 데이터베이스용 데이터베이스 플러그인, 파일 시스템용 파일 시스템 플러그인, VM 및 데이터 저장소용 SnapCenter Plug-in for VMware vSphere 사용하세요.



== 정책

정책은 데이터 보호 작업의 백업 빈도, 사본 보존, 복제, 스크립트 및 기타 특성을 지정합니다.

리소스 그룹을 생성하거나 주문형 백업을 수행할 때 하나 이상의 정책을 선택할 수 있습니다.

리소스 그룹은 보호해야 할 내용과 보호해야 할 날짜와 시간을 정의합니다.  정책은 보호가 어떻게 수행될 것인지 설명합니다.  예를 들어, 호스트의 모든 데이터베이스나 파일 시스템을 백업해야 하는 경우, 호스트의 모든 데이터베이스나 파일 시스템을 포함하는 리소스 그룹을 생성할 수 있습니다.  그러면 리소스 그룹에 일일 정책과 시간당 정책이라는 두 가지 정책을 첨부할 수 있습니다.

리소스 그룹을 만들고 정책을 첨부할 때 매일 전체 백업을 수행하도록 구성하고 매시간 로그 백업을 위한 일정을 별도로 지정할 수 있습니다.

사용자 정의 사전 규정 및 사후 규정은 데이터 보호 작업에 사용될 수 있습니다.  이러한 스크립트를 사용하면 데이터 보호 작업 전이나 후에 자동화를 수행할 수 있습니다.  예를 들어, 스크립트는 데이터 보호 작업 실패나 경고를 자동으로 알릴 수 있습니다.  이러한 스크립트를 작성하는 데 필요한 요구 사항을 이해하는 것은 사전 스크립트와 사후 스크립트를 설정하는 데 중요합니다.



== 전치사와 후치사의 사용

사용자 정의 사전 스크립트와 사후 스크립트를 사용하면 작업 전이나 후에 데이터 보호 작업을 자동화할 수 있습니다.  예를 들어, 작업 실패나 경고를 알려주는 스크립트를 추가할 수 있습니다.  스크립트를 설정하기 전에 해당 스크립트에 대한 요구 사항을 이해했는지 확인하세요.



=== 지원되는 스크립트 유형

Windows에서는 다음과 같은 유형의 스크립트가 지원됩니다.

* 배치 파일
* PowerShell 스크립트
* Perl 스크립트


UNIX에서는 다음과 같은 유형의 스크립트가 지원됩니다.

* Perl 스크립트
* 파이썬 스크립트
* 쉘 스크립트
+

NOTE: 기본 bash 셸과 함께 sh-shell, k-shell, c-shell과 같은 다른 셸도 지원됩니다.





=== 스크립트 경로

비가상화 및 가상화 스토리지 시스템 모두에서 SnapCenter 작업의 일부로 실행되는 모든 사전 스크립트와 사후 스크립트는 플러그인 호스트에서 실행됩니다.

* Windows 스크립트는 플러그인 호스트에 위치해야 합니다.



NOTE: prescripts 또는 postscripts 경로에는 드라이브나 공유가 포함되어서는 안 됩니다.  경로는 SCRIPTS_PATH를 기준으로 해야 합니다.

* UNIX 스크립트는 플러그인 호스트에 위치해야 합니다.



NOTE: 스크립트 경로는 실행 시점에 검증됩니다.



=== 스크립트를 지정할 위치

스크립트는 백업 정책에 지정됩니다.  백업 작업이 시작되면 정책은 스크립트를 백업되는 리소스와 자동으로 연결합니다.  백업 정책을 생성할 때 prescript 및 postscript 인수를 지정할 수 있습니다.


NOTE: 여러 스크립트를 지정할 수 없습니다.



=== 스크립트 시간 초과

기본적으로 시간 제한은 60초로 설정됩니다.  시간 초과 값을 수정할 수 있습니다.



=== 스크립트 출력

Windows 프리스크립트와 포스트스크립트 출력 파일의 기본 디렉토리는 Windows\System32입니다.

UNIX 스크립트와 포스트스크립트에 대한 기본 위치는 없습니다.  원하는 위치로 출력 파일을 리디렉션할 수 있습니다.
