---
permalink: uninstall/task_uninstall_plug_ins_from_a_host_using_the_snapcenter_gui.html 
sidebar: sidebar 
keywords: uninstall, gui 
summary: 더 이상 개별 플러그인이나 플러그인 패키지가 필요하지 않다고 판단되면 SnapCenter 인터페이스를 사용하여 제거할 수 있습니다. 
---
= SnapCenter GUI를 사용하여 플러그인 제거
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
더 이상 개별 플러그인이나 플러그인 패키지가 필요하지 않다고 판단되면 SnapCenter 인터페이스를 사용하여 제거할 수 있습니다.

.시작하기 전에
* 제거하려는 플러그인 패키지의 리소스 그룹을 제거해야 합니다.
* 제거하려는 플러그인 패키지의 리소스 그룹과 연관된 정책을 분리해야 합니다.


.이 작업에 관하여
개별 플러그인을 제거할 수 있습니다. 예를 들어, 호스트의 리소스가 부족하여 Microsoft SQL Server용 SnapCenter 플러그인을 더 강력한 호스트로 옮기고 싶을 때 해당 플러그인을 제거해야 할 수 있습니다.  플러그인 패키지 전체를 제거할 수도 있습니다.  예를 들어, Oracle Database용 SnapCenter 플러그인과 UNIX용 SnapCenter 플러그인이 포함된 Linux용 SnapCenter 플러그인 패키지를 제거해야 할 수도 있습니다.

* 호스트를 제거하면 모든 플러그인도 제거됩니다.
+
SnapCenter 에서 호스트를 제거하면 SnapCenter 호스트를 제거하기 전에 호스트의 모든 플러그인 패키지를 제거합니다.

* SnapCenter GUI는 한 번에 하나의 호스트에서 플러그인을 제거합니다.
+
SnapCenter GUI를 사용하면 한 번에 하나의 호스트에서만 플러그인을 제거할 수 있습니다.  하지만 여러 개의 설치 제거 작업을 동시에 실행할 수도 있습니다.

+
_Uninstall-SmHostPackage_ cmdlet과 필요한 매개변수를 사용하여 여러 호스트에서 플러그인을 제거할 수도 있습니다.  cmdlet과 함께 사용할 수 있는 매개변수와 해당 설명에 대한 정보는 _Get-Help command_name_을 실행하면 얻을 수 있습니다. 또는 다음을 참조할 수도 있습니다. https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter 소프트웨어 Cmdlet 참조 가이드"^] .




IMPORTANT: SnapCenter 서버가 설치된 호스트에서 Windows용 SnapCenter 플러그인 패키지를 제거하면 SnapCenter 서버 설치가 손상됩니다.  SnapCenter 서버가 더 이상 필요하지 않다고 확신하기 전까지는 Windows용 SnapCenter 플러그인 패키지를 제거하지 마세요.

.단계
. 왼쪽 탐색 창에서 *호스트*를 클릭합니다.
. 호스트 페이지에서 *관리되는 호스트*를 클릭합니다.
. 관리 호스트 페이지에서 플러그인이나 플러그인 패키지를 제거할 호스트를 선택합니다.
. 제거하려는 플러그인 옆의 *제거* > *제출*을 클릭합니다.


.당신이 완료한 후
해당 호스트에 플러그인을 다시 설치하기 전에 5분 정도 기다려야 합니다.  이 기간은 SnapCenter GUI가 관리 호스트의 상태를 새로 고치는 데 충분합니다.  플러그인을 바로 다시 설치하면 설치에 실패합니다.

Linux용 SnapCenter 플러그인 패키지를 제거하는 경우, 제거 관련 로그 파일은 _/custom_location/snapcenter/log_에서 사용할 수 있습니다.
