---
permalink: uninstall/task_remove_a_host.html 
sidebar: sidebar 
keywords: uninstall, remove, remove host 
summary: SnapCenter 서버가 호스트를 제거할 때는 먼저 SnapCenter 리소스 페이지에 나열된 해당 호스트에 대한 백업, 복제, 복제 작업, 리소스 그룹 및 리소스를 제거한 다음 호스트에서 플러그인 패키지를 제거합니다. 
---
= 호스트 제거
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 서버가 호스트를 제거할 때는 먼저 SnapCenter 리소스 페이지에 나열된 해당 호스트에 대한 백업, 복제, 복제 작업, 리소스 그룹 및 리소스를 제거한 다음 호스트에서 플러그인 패키지를 제거합니다.

.이 작업에 관하여
* 호스트를 삭제하면 해당 호스트와 연결된 백업, 복제본 및 리소스 그룹도 삭제됩니다.
* 리소스 그룹을 제거하면 연관된 모든 일정도 제거됩니다.
* 호스트에 다른 호스트와 공유되는 리소스 그룹이 있고 해당 호스트를 삭제하면 해당 리소스 그룹도 삭제됩니다.
* 사용이 중단되었거나 접근할 수 없는 플러그인 호스트를 제거하려면 _Remove-SmHost_ cmdlet을 사용해야 합니다.
+
cmdlet과 함께 사용할 수 있는 매개변수와 해당 설명에 대한 정보는 _Get-Help command_name_을 실행하면 얻을 수 있습니다.  또는 다음을 참조할 수도 있습니다. https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter 소프트웨어 Cmdlet 참조 가이드"^]

* 호스트를 제거하는 데 필요한 시간은 백업 수와 보존 설정에 따라 달라집니다.  이는 각 컨트롤러에서 스냅샷이 삭제되고 메타데이터가 정리되기 때문입니다.


.단계
. 왼쪽 탐색 창에서 *호스트*를 클릭합니다.
. *호스트* 페이지에서 *관리되는 호스트*를 클릭합니다.
. 제거할 호스트를 선택한 다음 *제거*를 클릭합니다.
. Oracle RAC 클러스터의 경우 클러스터의 모든 호스트에서 SnapCenter software 제거하려면 *클러스터의 모든 호스트 포함*을 선택합니다.
+
클러스터의 노드 하나를 제거하면 모든 노드를 하나씩 제거할 수도 있습니다.

. *확인*을 클릭합니다.
+

NOTE: 클러스터에서 호스트 플러그인을 제거했다가 다시 설치하면 클러스터 리소스가 자동으로 검색되지 않습니다.  클러스터 호스트 이름을 선택한 다음 *리소스 새로 고침*을 클릭하면 클러스터 리소스를 자동으로 검색합니다.


