---
permalink: protect-mysql/snapcenter-plug-in-for-mysql-features.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for MySQL 
summary: SnapCenter 플러그인 애플리케이션과 스토리지 시스템의 NetApp 기술과 통합됩니다.  MySQL 데이터베이스 플러그인을 사용하려면 SnapCenter 그래픽 사용자 인터페이스를 사용합니다. 
---
= MySQL용 SnapCenter 플러그인 기능
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 플러그인 애플리케이션과 스토리지 시스템의 NetApp 기술과 통합됩니다.  MySQL 데이터베이스 플러그인을 사용하려면 SnapCenter 그래픽 사용자 인터페이스를 사용합니다.

* *통합된 그래픽 사용자 인터페이스*
+
SnapCenter 인터페이스는 플러그인과 환경 전반에 걸쳐 표준화와 일관성을 제공합니다.  SnapCenter 인터페이스를 사용하면 플러그인 전반에 걸쳐 일관된 백업, 복원 및 복제 작업을 완료하고, 중앙 집중식 보고를 사용하고, 한눈에 볼 수 있는 대시보드 보기를 사용하고, 역할 기반 액세스 제어(RBAC)를 설정하고, 모든 플러그인에서 작업을 모니터링할 수 있습니다.

* *자동화된 중앙 관리*
+
백업 작업을 예약하고, 정책 기반 백업 보존을 구성하고, 복원 작업을 수행할 수 있습니다.  SnapCenter 구성하여 이메일 알림을 보내 환경을 사전에 모니터링할 수도 있습니다.

* *비중단 NetApp 스냅샷 복사 기술*
+
SnapCenter MySQL 데이터베이스 플러그인과 함께 NetApp 스냅샷 기술을 사용하여 리소스를 백업합니다.



MySQL 플러그인을 사용하면 다음과 같은 이점도 있습니다.

* 백업, 복원 및 복제 워크플로 지원
* RBAC 지원 보안 및 중앙 집중식 역할 위임
+
또한, 권한이 있는 SnapCenter 사용자에게 애플리케이션 수준 권한이 부여되도록 자격 증명을 설정할 수도 있습니다.

* NetApp FlexClone 기술을 사용하여 테스트 또는 데이터 추출을 위한 리소스의 공간 효율적 및 특정 시점 복사본 생성
+
복제본을 생성하려는 스토리지 시스템에 FlexClone 라이선스가 필요합니다.

* 백업 생성의 일부로 ONTAP 의 일관성 그룹(CG) 스냅샷 기능에 대한 지원.
* 여러 리소스 호스트에서 동시에 여러 백업을 실행할 수 있는 기능
+
단일 작업에서 단일 호스트의 리소스가 동일한 볼륨을 공유하는 경우 스냅샷이 통합됩니다.

* 외부 명령을 사용하여 스냅샷을 생성하는 기능.
* XFS 파일 시스템에서 Linux LVM을 지원합니다.

